### PR TITLE
[shared_preferences] Federate mobile implementations

### PR DESCRIPTION
**Pull request by stuartmorgan**
Fully federates the plugin by moving the existing mobile implementations to their own packages, per planned repo structure.

Temporarily marks `shared_preferences` as unpublishable to allow the implementations to be moved, rather than copied and deleted, in order to better preserve git history. A follow-up PR will restore it to publishable form.

Part of https://github.com/flutter/flutter/issues/68498

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I tried re-enabling the Android integration tests in FTL (https://github.com/flutter/flutter/issues/86749) but couldn't get it to run successfully in FTL; probably I was missing some basic step. But I have verified the integration tests locally, for both the app-facing and platform implementation packages.

**Comment by stuartmorgan** [comment]
> I tried re-enabling the Android integration tests in FTL ([flutter/flutter#86749](https://github.com/flutter/flutter/issues/86749)) but couldn't get it to run successfully in FTL; probably I was missing some basic step. But I have verified the integration tests locally, for both the app-facing and platform implementation packages.

I think I know what I did wrong; trying again...

**Comment by stuartmorgan** [comment]
> > I tried re-enabling the Android integration tests in FTL ([flutter/flutter#86749](https://github.com/flutter/flutter/issues/86749)) but couldn't get it to run successfully in FTL; probably I was missing some basic step. But I have verified the integration tests locally, for both the app-facing and platform implementation packages.
> 
> I think I know what I did wrong; trying again...

Nope, it's still failing with no results (crashing on launch maybe?), and I'm not sure why. Reverting back to the version that doesn't try to re-enable them.

**Comment by stuartmorgan** [comment]
> Nope, it's still failing with no results (crashing on launch maybe?), and I'm not sure why. Reverting back to the version that doesn't try to re-enable them.

@blasten found the piece I was missing in https://github.com/flutter/plugins/pull/4514, which I stole, so this now enables integration tests for both app-facing and android packages on Android.

**Review by bparrishMines — APPROVED** [review]
LGTM

**Pull request merged**
