### PR TITLE
[HX] Let ImagePicker get out of the way when used with AlarmManager

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
@cyanglaz if you're looking for ImagePicker fixes still, this would be a good one for you to take over. I'm not sure the fix is right. It made some tests fail. Might need to update the tests or update the code. The idea here is to make sure that ImagePicker doesn't throw when you're using AlarmManager.

**Comment by cyanglaz** [comment]
@Hixie Should we merge this one?

**Comment by Hixie** [comment]
Probably needs a test, but LGTM if there's no way to test it at the moment, since this blocks people from using the plugin.

**Comment by Hixie** [comment]
(I believe this landed in a separate PR)

**Pull request closed without merging**
