### PR TITLE
 [image_picker] Migrate Image_picker_platform interface to Null Safety

### PR DESCRIPTION
**Pull request by Sameerkash**
Migrate Image_picker_platform interface to Null Safety 

Related to #75162

All existing tests are passing 

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: refactoring with no logical change

**Comment by Sameerkash** [comment]
@stuartmorgan  Any hints on the failing checks? is it the CI config?

**Comment by cyanglaz** [comment]
@Sameerkash Thank you for the PR! This is being done in https://github.com/flutter/plugins/pull/3492 and we are almost landing the PR. I'm going to close this one :)

**Comment by cyanglaz** [comment]
@Sameerkash If you'd like to work on the migration for the image_picker plugin after #3492, I'll be super happy to review it! :)

**Comment by stuartmorgan** [comment]
@Sameerkash Apologies for the duplicated work here; I tried to capture in-progress work when filing all of the bugs, but missed #3492 when filing that issue.

**Comment by Sameerkash** [comment]
> @Sameerkash If you'd like to work on the migration for the image_picker plugin after #3492, I'll be super happy to review it! :) 

Yes. I would like to @cyanglaz 
I'll start asap. Should be up in a day.

**Comment by Sameerkash** [comment]
> @Sameerkash Apologies for the duplicated work here; I tried to capture in-progress work when filing all of the bugs, but missed #3492 when filing that issue.

It's okay!

**Comment by cyanglaz** [comment]
> Yes. I would like to @cyanglaz
> I'll start asap. Should be up in a day.

Please tag me on the PR! I'll be happy to review it!

**Pull request closed without merging**
