### PR TITLE
[camera]refactor FLTCam outside of CameraPlugin

### PR DESCRIPTION
**Pull request by hellohuanlin**
This PR moves `FLTCam` (and its companion classes) to a separate file, and updates the unit tests to remove dummy FLTCam interface. 

Note that this `FLTCam` class is **huge**, so I'd prefer to scope this PR to just moving the code. But it's worth pointing out that `FLTCam` has multiple style issues not addressed by this PR, for example, missing comments on each properties and methods, missing most unit tests, etc. 

This PR should conclude the "Breakup CameraPlugin.m" subtask in https://github.com/flutter/flutter/issues/96429

No version change: just moving code to separate files. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
> Note that this `FLTCam` class is **huge**, so I'd prefer to scope this PR to just moving the code. But it's worth pointing out that `FLTCam` has multiple style issues not addressed by this PR, for example, missing comments on each properties and methods, missing most unit tests, etc. 

👍  LGTM

**Comment by jmagman** [comment]
> trigger No version change validation

@hellohuanlin can you file an issue for the `publishable` not passing on re-run even when the description is updated?

**Comment by hellohuanlin** [comment]
> @hellohuanlin can you file an issue for the `publishable` not passing on re-run even when the description is updated?

I filed this a while ago https://github.com/flutter/flutter/issues/95594

**Comment by jmagman** [comment]
> I filed this a while ago [flutter/flutter#95594](https://github.com/flutter/flutter/issues/95594)

Ah thanks I couldn't find it.

**Pull request merged**
