### PR TITLE
[local_auth]

### PR DESCRIPTION
**Pull request by PiyushMishra318**
## Description
Editted the AlertDialog for those people who don't want a dialog on the screen for fingerprint scanning.

## Related Issues
- https://github.com/flutter/flutter/issues/30601

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by priezz** [comment]
@PiyushMishra318, could you please synchronize your PR with the upstream and make this change optional? I would love to have it merged!

**Comment by vanlooverenkoen** [comment]
Could you fix your merge conflicts?

**Comment by priezz** [comment]
> Could you fix your merge conflicts?

I have looked in the code and realized that it is impossible to fix the conflicts, because library now uses the new Android classes for auth. So I have published the package https://pub.dev/packages/flutter_local_auth_invisible, which has the invisible fingerprint auth on Android (base on the most recent `local_auth` version, which relied on older classes) and up to date code for iOS.

**Comment by stuartmorgan** [comment]
We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

Closing based on the discussion above, since the PR is no longer applicable to the current version of the plugin, but thanks for the contribution!

**Pull request closed without merging**
