### PR TITLE
Add plugin tools as a git submodule and depend on it directly

### PR DESCRIPTION
**Pull request by blasten**
This is the first step toward moving the plugin tools over to this repo. 

For the time being, this will allow you to change the plugin tools, and test the changes directly without the need to publish to the tool to pub.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
What's the reason for using a submodule instead of actually moving the code into this repo? (I ask because my previous experience with submodules was that they really didn't work very well, and it was easy to get a tree into a state where it was hard to understand what was happening and how to fix it; that was a number of years ago though, so maybe tooling has improved.)

**Comment by blasten** [comment]
@stuartmorgan yes. The GitHub UI tells you exactly which commit the submodule points to. This is mostly a temporary state before I move the code and archive that repo.  I'd like to ensure I capture everything else that might be needed as a result.

**Comment by blasten** [comment]
https://github.com/flutter/plugins/tree/5bb6ce7fc6ebdd1f2a033704f3a0013e27032bad/script as an example

**Review by stuartmorgan — APPROVED** [review]
My issues were actually with the `git` tool itself, not GitHub. But since this is temporary, and should be easy to reverse if we find any really sharp edges with gitmodules, LGTM.

**Pull request merged**
