### PR TITLE
[camera] Fixes crash with using inner camera on some Android devices.

### PR DESCRIPTION
**Pull request by najeira**
Fixes NullPointerException when using inner camera on Android Pixel 3 XL.

* https://github.com/flutter/flutter/issues/73922

Crashes in 0.6.4+3 and later versions. 

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
  - This is crash on actual devices, I did not add tests.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

## Details

NullPointerException on the following line in `Camera.getRegionBoundaries`:

```java
// Get the current distortion correction mode
Integer distortionCorrectionMode =
    captureRequestBuilder.get(CaptureRequest.DISTORTION_CORRECTION_MODE);
```

Does not crash with the outer camera. Probably to return under the previous conditions `supportsDistortionCorrection`.

```java
// No distortion correction support
if (android.os.Build.VERSION.SDK_INT < VERSION_CODES.P || !supportsDistortionCorrection()) {
  return cameraManager
      .getCameraCharacteristics(cameraDevice.getId())
      .get(CameraCharacteristics.SENSOR_INFO_PIXEL_ARRAY_SIZE);
}
```

captureRequestBuilder is created in the middle of `startPreview`'s processing.
For this reason, the position where the cameraRegions are created has been moved.

I think this is related to https://github.com/flutter/plugins/pull/3346

### CODE REVIEW

**Comment by najeira** [comment]
@BeMacized Could you review this change is good? I'm not very confident about this.

**Review by BeMacized — APPROVED** [review]
@najeira Thanks for the PR! Although I cannot reproduce your issue, this indeed looks like a more reliable point to initialise CameraRegions. 

Would you be able to update the version number in the pubspec and changelog files to resolve the conflicts with master?

Otherwise, LGTM!

**Review by mvanbeusekom — APPROVED** [review]
LGTM

@najeira thank you for submitting this pull request, if you could resolve the conflicts I will make sure this gets merged.

**Comment by mvanbeusekom** [comment]
Thank you for the quick follow up @najeira. Once the tree goes green, this PR will be merged.

**Pull request merged**
