### PR TITLE
Update all targetSdkVersions

### PR DESCRIPTION
**Pull request by stuartmorgan**
Fixes compilation failures in unit tests on master.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@blasten @camsim99 Unit test compilation is failing on master now, so I replaced all remaining references to non-31 compilation SDK versions. Was there a reason these were omitted in the previous PR?

**Review by blasten — APPROVED** [review]

**Comment by stuartmorgan** [comment]
Hm, apparently this isn't enough (I just did this as a search-replace thinking it would be an easy background fix while doing something else; I hadn't tested locally).

Any idea why we're still not using 31 here?
```

* What went wrong:
Execution failed for task ':shared_preferences_android:checkDebugUnitTestAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.window:window-java:1.0.0-beta03.
        AAR metadata file: /root/.gradle/caches/transforms-2/files-2.1/059568fb0a4bbd01a41155e23c4829f8/jetified-window-java-1.0.0-beta03/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-29).
        Dependency: androidx.window:window:1.0.0-beta03.
        AAR metadata file: /root/.gradle/caches/transforms-2/files-2.1/7cb51982015a848e795df4bee3b8a487/jetified-window-1.0.0-beta03/META-INF/com/android/build/gradle/aar-metadata.properties.
```

**Comment by camsim99** [comment]
> @blasten @camsim99 Unit test compilation is failing on master now, so I replaced all remaining references to non-31 compilation SDK versions. Was there a reason these were omitted in the previous PR?

If you're referring to bumping the compilation SDK versions of the plugins themselves vs test example apps, this was omitted in the previous PR for clarity.

**Comment by stuartmorgan** [comment]
Also, I don't remember what the fix is for:
```
D8: Cannot fit requested classes in a single dex file (# methods: 75754 > 65536)
```
which changing to 31 created for at least one plugin.

**Comment by stuartmorgan** [comment]
> > @blasten @camsim99 Unit test compilation is failing on master now, so I replaced all remaining references to non-31 compilation SDK versions. Was there a reason these were omitted in the previous PR?
> 
> If you're referring to bumping the compilation SDK versions of the plugins themselves vs test example apps, this was omitted in the previous PR for clarity.

Yep, that's what I meant. But I'm not sure I actually fixed anything here, so maybe I misdiagnosed the remaining problem. We'll need to figure out ASAP why re-landing [the engine change](https://github.com/flutter/engine/pull/29585) still broke us even after your PR.

**Comment by blasten** [comment]
I'll take a look shortly

**Comment by camsim99** [comment]
> Hm, apparently this isn't enough (I just did this as a search-replace thinking it would be an easy background fix while doing something else; I hadn't tested locally).
> 
> Any idea why we're still not using 31 here?
> 
> ```
> 
> * What went wrong:
> Execution failed for task ':shared_preferences_android:checkDebugUnitTestAarMetadata'.
> > Multiple task action failures occurred:
>    > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
>       > The minCompileSdk (31) specified in a
>         dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
>         is greater than this module's compileSdkVersion (android-29).
>         Dependency: androidx.window:window-java:1.0.0-beta03.
>         AAR metadata file: /root/.gradle/caches/transforms-2/files-2.1/059568fb0a4bbd01a41155e23c4829f8/jetified-window-java-1.0.0-beta03/META-INF/com/android/build/gradle/aar-metadata.properties.
>    > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
>       > The minCompileSdk (31) specified in a
>         dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
>         is greater than this module's compileSdkVersion (android-29).
>         Dependency: androidx.window:window:1.0.0-beta03.
>         AAR metadata file: /root/.gradle/caches/transforms-2/files-2.1/7cb51982015a848e795df4bee3b8a487/jetified-window-1.0.0-beta03/META-INF/com/android/build/gradle/aar-metadata.properties.
> ```
> 
> I changed all of the `compileSdkVersion`s:
> 
> ```
> $ git grep compileSdkVersion packages | grep -v CHANGELOG | grep -v 31
> $
> ```

It seems like I forgot to bump the compilation SDK version of shared_preferences_android example app in my PR; you did it here. Any chance this needs to be merged into the master branch before bumping the compilation SDK version of shared_preferences_android?

**Comment by stuartmorgan** [comment]
> It seems like I forgot to bump the compilation SDK version of shared_preferences_android example app in my PR; you did it here.

I split this out from shared_preferences while your PR was in progress, and forgot to account for it; I should have either done it in that PR or mentioned it in your PR.

> Any chance this needs to be merged into the master branch before bumping the compilation SDK version of shared_preferences_android?

That shouldn't be the case, since it's a path-based dependency. But now I'm not finding this in the test results so I'm wondering if I was looking at the wrong results set and this one is fixed by my PR. I'll do a more thorough sweep of what's failing here.

**Comment by stuartmorgan** [comment]
> But now I'm not finding this in the test results so I'm wondering if I was looking at the wrong results set and this one is fixed by my PR. I'll do a more thorough sweep of what's failing here.

Nevermind, I see what's happening. This is indeed a publishing issue as you suggested, because the failure is in IAP; the IAP example uses shared_preferences. This won't go green in presubmit, but will be okay post-submit once I (manually) publish)

Okay, the failures are:
- android_alarm_manager integration tests failing due to dex size.
  - As I said above, I forget how to fix this although I know I've done it once; IIRC it's some gradle tweaks? If it's non-trivial we could just disable these tests as this plugin is very nearly EoL and it's extremely unlikely we'll change it in the next month.
- iap_android unit tests:
  - The issue described above
- local_auth unit tests:
  - The same thing, just with flutter_plugin_android_lifecycle
- quick_actions
  - Another dex issue; we need to fix this one
- video_player unit tests:
  - Another publish-based problem, but with path_provider_android

**Comment by stuartmorgan** [comment]
I'm going to split out the ones that need to be published into a separate PR. That should be able to pass presubmit, and we can get it landed and then manually publish those while we figure out the dex issues for this PR.

**Comment by stuartmorgan** [comment]
Posted https://github.com/flutter/plugins/pull/4535 for the subset.

Longer term, we should probably figure out if we can change the way our unit tests build somehow so that transitive dependencies of the example apps (which aren't actually involved in the unit test on Android AFAIK?) can't cause this kind of build failure...

**Comment by blasten** [comment]
* To fix multidex issues
https://developer.android.com/studio/build/multidex

**Comment by stuartmorgan** [comment]
> * To fix multidex issues
>   https://developer.android.com/studio/build/multidex

Thanks! I've pushed a version of the PR that updates the min deployment SDK version for the examples apps of the plugins that had issues, but it's not clear to me if that is all it needs, or we need to actually enable multidex in the plugin itself (which we definitely wouldn't want to do by changing the deployment SDK version).

**Comment by blasten** [comment]
You can also use the `--multidex` flag, but it requires to use `flutter build`. Is there any reason why to call Gradle directly?

**Comment by blasten** [comment]
Merging to fix the tree

**Pull request merged**
