### PR TITLE
[video_player]add http headers option when loading network data source

### PR DESCRIPTION
**Pull request by rcunning**
I added optional request headers to VideoPlayerController.network contructor for video_player plugin. I did not see an obvious place to create a test for these changes, but happy to do so if you would like. I did manually test these changes on iOS and Android emulator.

### CODE REVIEW

**Comment by rcunning** [comment]
I signed it!

**Comment by cbenhagen** [comment]
Hi, thank you for trying to finally fix https://github.com/flutter/flutter/issues/16466. There is already a very similar PR open here https://github.com/flutter/plugins/pull/897.

The problem seems to be the usage of `AVURLAssetHTTPHeaderFieldsKey`. I can't tell if the usage of this private API would really get an app rejected. Can you try to get more information on this?

**Comment by JohnGalt1717** [comment]
We've had no issues with getting apps through the store with the AVURLAssetHTTPHeaderFieldsKey and I've found no one that has...

**Comment by ezamagni** [comment]
I **really** need this feature for my project. Unfortunately this PR seems abandoned. Any chance in getting it resumed?

**Comment by rcunning** [comment]
> I **really** need this feature for my project. Unfortunately this PR seems abandoned. Any chance in getting it resumed?

See comments in feature request https://github.com/flutter/flutter/issues/16466 and a similar pr https://github.com/flutter/plugins/pull/897

If I were you and you really need it, fork the repo, apply one of the prs (will have to update a little I am sure), and move on. You will have to merge in changes from the main repo though whenever you want the latest (see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork).

**Comment by troyanskiy** [comment]
Can someone resolve the conflicts and merge it. That is very useful feature!
Thank you!

**Review by nomadcore — APPROVED** [review]

**Comment by stuartmorgan** [comment]
Closing, as there is already https://github.com/flutter/plugins/pull/897 which addresses the same issue; let's consolidate discussion there.

**Pull request closed without merging**
