### PR TITLE
Add README instructions for enablePendingPurchases

### PR DESCRIPTION
**Pull request by matthew-carroll**
Add README instructions for enablePendingPurchases.

If a developer attempts to access this plugin on Android without invoking `enablePendingPurchases`, an exception is thrown.

Related StackOverflow post:
https://stackoverflow.com/questions/60046903/flutter-in-app-purchase-enablependingpurchases-enablependingpurchases-must

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@cyanglaz is there a reason that we would change the version number or the change log for a documentation correction?

**Comment by cyanglaz** [comment]
I believe the README is only updated on pub when a new version is published

**Comment by matthew-carroll** [comment]
Alright @cyanglaz I went ahead and bumped the version and updated the change log.

**Comment by matthew-carroll** [comment]
Actually, hold up, I need to resolve a conflict.

**Comment by matthew-carroll** [comment]
Now it's updated.

**Pull request merged**
