### PR TITLE
[ci] Add 'main' builders in bringup mode

### PR DESCRIPTION
**Pull request by stuartmorgan**
Creates `main` versions of the existing `master` CI builders, as the
first half of switching LUCI tests over to the `main` branch.

Part of https://github.com/flutter/flutter/issues/90476

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I'll wait on landing this until we actually have the branch mirroring, but I was updating the tool and though I'd go ahead and prep this at the same time.

**Comment by CaseyHillers** [comment]
\cc @godofredoc whose leading the migrations.

I think instead of adding new builders, we would want to convert the existing ones to main once we have mirroring set up.

**Comment by stuartmorgan** [comment]
How would we validate that there aren't problems (e.g., repo tooling bugs) with running on `main` without doing a two-phase conversion where we bring up bots using `main`, ensure they work, then eliminate the `master` versions?

**Comment by CaseyHillers** [comment]
Since the mirrors are pretty close to instant, the way we validate these tooling issues is by doing scheduled outages where we rename master to master_archived for short periods of time. In practice, the parallel runs catch very few issues compared to the outage approach.

**Comment by godofredoc** [comment]
> he way we validate these tooling issues is by doing scheduled outages where we rename master to master_archived for short periods of time. In practice, the parallel runs catch very few issues compared to the outage approach.

@stuartmorgan do the luci builders generate artifacts that can clash when using the same commit and builders coming from two different branches?

**Comment by stuartmorgan** [comment]
> @stuartmorgan do the luci builders generate artifacts that can clash when using the same commit and builders coming from two different branches?

No, our LUCI builders do not generate artifacts. (Nor do our Cirrus builders, actually; the closest thing we have to artifacts is the GitHub Action auto-publisher; we can do that one as a single switch)

**Comment by godofredoc** [comment]
> lly; the closest thing we have to artifacts is the GitHub Action auto-publisher; we can do that one as a single switch)

If that is the case we can enable parallel builders. The only reason we are doing a one time swap in the engine is because they are generating artifacts that get duplicated when running parallel builds.

**Review by CaseyHillers — APPROVED** [review]
flutter-lgtm

**Pull request merged**
