### PR TITLE
[in_app_purchase] Expose the NSLocale object

### PR DESCRIPTION
**Pull request by BeMacized**
This PR exposes the majority of the NSLocale object via the SKProductWrapper.

The values for `NSLocaleExemplarCharacterSet` and `NSLocaleCalendar` have been omitted, as they appear to be significantly more complex. 

Related issues: 
- flutter/flutter#26610

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by mvanbeusekom — APPROVED** [review]
LGTM!

**Comment by stuartmorgan** [comment]
Was there further discussion somewhere beyond what's in the issue? The issue suggested waiting and seeing if anyone actually needed this information before deciding to expose it, and I don't see anything there to suggest people have requested other information or provided use cases related to other fields, so it's not obvious why this is being done.

**Comment by mvanbeusekom** [comment]
> Was there further discussion somewhere beyond what's in the issue? The issue suggested waiting and seeing if anyone actually needed this information before deciding to expose it, and I don't see anything there to suggest people have requested other information or provided use cases related to other fields, so it's not obvious why this is being done.

Hi @stuartmorgan, this issue was on the list of "planned" items discussed offline between product managers. Since it was on the list treated as one of the issues agreed to be resolved. If you prefer we can rollback the changes and wait for more feedback on the issue.

**Comment by stuartmorgan** [comment]
Yes, let's revert this; adding a lot of API surface to maintain without any known clients doesn't seem like a good tradeoff.

**Pull request merged**
