### PR TITLE
Remove iOS stubs

### PR DESCRIPTION
**Pull request by stuartmorgan**
Plugins that don't actually support iOS are no longer required to have
an iOS stub to prevent build failures. This removes all iOS stubs from
plugins that don't support iOS, and changes the fallback behavior for
the repo tooling to treat a missing flag as Android-only.

Partially fixes https://github.com/flutter/flutter/issues/58285

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Turns out this is blocked by https://github.com/flutter/plugin_tools/pull/102/files#diff-7a0a4bb084bbea210ea6f06f08df00fd93af181200e48ba2acff4c7a1d87d077R182. We need to either do the breaking change, or figure out a more targeted legacy filter than assuming any platform with either iOS or Android supports both.

**Comment by stuartmorgan** [comment]
@cyanglaz I think this is ready for review; most is rubber-stamp, but I made slight changes to drive_examples_command.dart and .cirrus.yml to unblock the removal that should be reviewed.

(@blasten I think this is an example of a change where I'd feel more comfortable having unit tests, re recent conversation.)

**Comment by blasten** [comment]
I see. In the past, there was a time when the script were misconfigured, and tests were skipped as a result. Unfortunately, the issue wasn't in the tool, but in the scripts. or even in the .cirrus file.  I think with GitHub actions it's very clear what tests ran because it shows the check, so instead of `
build-ipas+drive-examples CHANNEL:beta PLUGIN_SHARDING:--shardIndex 0 --shardCount 4`  there is a `plugin-foo/driver test (iOS)`. 

Hopefully we  can clean this up entirely. :)

**Review by cyanglaz — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
(I'm not going to republish anything for this change; it shouldn't really affect any plugin users.)

**Pull request merged**
