### PR TITLE
[video_player] add allowBackgroundPlayback option platform interface changes

### PR DESCRIPTION
**Pull request by IlyaMax**
Part of this pr https://github.com/flutter/plugins/pull/4324

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by IlyaMax** [comment]
@stuartmorgan this part is ready for review

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
Actually, sorry, this should have a simple test.

Historically we do test coverage in the platform interface packages via the method channel implementation, but since we're no longer using the method channel in this package and don't plan to update it I think it would be good to do simple tests for the type classes.

Could you add a new unit test file for `VideoPlayerOptions` with some very simple tests (defaults to false, passing true works)? That gives us coverage here, and a foundation for any logic that might be added in the future (e.g., if we implement `==` for this at some point).

**Review by gaaclarke — APPROVED** [review]

**Review by stuartmorgan — APPROVED** [review]

**Comment by stuartmorgan** [comment]
@godofredoc Do you have any idea how this landed without any of the presubmit Cirrus tests having actually run?

**Comment by godofredoc** [comment]
> @godofredoc Do you have any idea how this landed without any of the presubmit Cirrus tests having actually run?

The autosubmit bot does not check explicitly for tests it just assumes the relevant checks are there and validate they all passed.

**Comment by stuartmorgan** [comment]
So does that mean none of the Cirrus tests was even queued within the hour between posting and landing? That seems like a really bad failure case.

**Pull request merged**
