### PR TITLE
[url_launcher] Fix breaking change version conflict

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
cc @Hixie @stuartmorgan I explained [here](https://github.com/flutter/plugins/pull/3954#issuecomment-852856099) why ~a breaking change was handled inproperly and this is why~ we need to specify the dependency that is at least `2.0.3`.

Before that version, the method head of `pushRouteNameToFramework` was different, which means that `^2.0.0` for the platform interface is a lie - any version before `2.0.3` is incompatible.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
The fix here is correct (there's an alternate option of making this actually backward compatible down to 2.0.0 again by changing the function variable type, but getting more people onto `url_launcher_platform_interface` 2.0.3 is a better outcome since 2.0.0-2 don't work correctly with master), but the description in the PR and the CHANGELOG are not, per https://github.com/flutter/plugins/pull/3954#issuecomment-853037801, unless I've missed something.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan So you think this PR would be fine to merge if the CHANGELOG was amended. If so, what would you include in the changelog / how would you phrase it?

**Review by stuartmorgan — APPROVED** [review]
I've rewritten the changelog; LGTM with that. Thanks for finding this!

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan Thanks a lot ❤️

**Pull request merged**
