### PR TITLE
[webview_flutter] fixing crash select tag

### PR DESCRIPTION
**Pull request by ametsuramet**
flutter/flutter#25767

### CODE REVIEW

**Comment by mklim** [comment]
Thanks again for the contribution. It looks like this PR has been sitting for a little while since the last round of feedback, do you still have time to work on it?

**Comment by tlueder** [comment]
Hi @mklim , this PR fixes the issue that an app is crashing as soon as you click on a select box on a web page. 

I've setup a minimal project to demo this crash.

https://github.com/tlueder/flutter_show_webview_crash

As soon as you click on the select box the app crashes with:

W/System.err( 6524): java.lang.ClassCastException: $Proxy0 cannot be cast to android.view.WindowManagerImpl
W/System.err( 6524):    at android.view.Window.setWindowManager(Window.java:778)
W/System.err( 6524):    at android.view.Window.setWindowManager(Window.java:760)
W/System.err( 6524):    at android.app.Dialog.<init>(Dialog.java:207)
W/System.err( 6524):    at android.app.AlertDialog.<init>(AlertDialog.java:204)
W/System.err( 6524):    at android.app.AlertDialog$Builder.create(AlertDialog.java:1105)
W/System.err( 6524):    at JB.<init>(PG:6)
W/System.err( 6524):    at org.chromium.content.browser.input.SelectPopup.show(PG:41)
W/System.err( 6524):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 6524):    at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err( 6524):    at android.os.Looper.loop(Looper.java:174)
W/System.err( 6524):    at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err( 6524):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 6524):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 6524):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
F/chromium( 6524): [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
F/libc    ( 6524): Fatal signal 5 (SIGTRAP), code 128 (SI_KERNEL), fault addr 0x0 in tid 6524 (w_webview_crash), pid 6524 (w_webview_crash)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.191030.002/5978551:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-01-07 11:33:30+0800
pid: 6524, tid: 6524, name: w_webview_crash  >>> de.nets.flutter_show_webview_crash <<<
uid: 10133
signal 5 (SIGTRAP), code 128 (SI_KERNEL), fault addr 0x0
Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
'
    eax 00000000  ebx cae07864  ecx e9d7f700  edx 00000400
    edi e6227980  esi ff9179c0
    ebp e9d7f700  esp ff917550  eip c83eec30
backtrace:
      #00 pc 01cfdc30  /system/product/app/TrichromeLibrary/TrichromeLibrary.apk!libmonochrome.so (offset 0x66c000) (BuildId: ffe50d4377c82928759c1f40f1b35ba9f411454a)
Lost connection to device. 

Hope this helps.

**Comment by tlueder** [comment]
This PR is related to this issue:

https://github.com/flutter/flutter/issues/25767

**Comment by yazinsai** [comment]
+1 this issue has been open for over a year: https://github.com/flutter/flutter/issues/34248

**Comment by cyanglaz** [comment]
The issue seems to be fixed in various PRs opened by @amirh 
The fix should be available on master. I'm closing this PR now. @ametsuramet if you found this issue not fixed, please feel empowered to tag me and reopen the PR

**Comment by yazinsai** [comment]
Latest version of `webview_flutter 0.3.22` still crashes when selecting a dropdown. Was this fix pushed to flutter itself, or the package? If flutter, which version resolves this issue

**Comment by tlueder** [comment]
Hi @cyanglaz , I believe this is a mixup with another issue.
https://github.com/flutter/flutter/issues/54164
which was fixed by @amirh in PR
https://github.com/flutter/plugins/pull/2663

As far as I know there was no patch to flutter or the engine to fix this.

This issue is still alive.
I've created a sample app to show this in action
https://github.com/tlueder/flutter_show_webview_crash

For this issue we have multiple PRs
https://github.com/flutter/plugins/pull/2535
https://github.com/flutter/plugins/pull/2330
https://github.com/flutter/plugins/pull/2081
https://github.com/flutter/plugins/pull/2071
https://github.com/flutter/plugins/pull/1861

Please correct me when i'm wrong and missed something.

Thanks

**Comment by cyanglaz** [comment]
@tlueder was there an issue created for this crash?

**Comment by tlueder** [comment]
@cyanglaz  This PR and all the other I linked are related to this issue:

https://github.com/flutter/flutter/issues/25767

**Comment by cyanglaz** [comment]
I'm going to close the PR because the CLA is not signed. Feel free to ping me when the CLA is signed and I'll re-open the PR. Or you can open a new PR after signing the CLA.

**Pull request closed without merging**
