### PR TITLE
[android_intent] Allows to specify an explicit type (a MIME type) of the intent data

### PR DESCRIPTION
**Pull request by JamalBelilet**
Allows to specify an explicit type (a MIME type) of the intent data. By setting this attribute, the system will show a the set of apps able to handle that type.

### CODE REVIEW

**Comment by sjmcdowall** [comment]
FWIW -- Been looking for this feature for quite a while, thanks for adding it!

**Comment by wuyugege** [comment]
how to specify an explicit type (a MIME type) of the intent data?,i use the android_intent: ^0.3.0+2，this version doesn't support to specify an explicit type。 @JamalBelilet

**Comment by JamalBelilet** [comment]
> how to specify an explicit type (a MIME type) of the intent data?,i use the android_intent: ^0.3.0+2，this version doesn't support to specify an explicit type。 @JamalBelilet

You can specify an explicit MIME type using the 'type' property of AndroidIntent's constructor, this is not merged yet so you need to clone this pull request instead of the base code.

carbon

**Comment by wuyugege** [comment]
thanks ,is there a plan to merge this   functionality？ @JamalBelilet

**Comment by JamalBelilet** [comment]
@wuyugege, I don’t know, I needed this feature for a project, so I share it in case someone’ll need it

**Comment by stuartmorgan** [comment]
Thanks for the submission! However, we’re currently not accepting non-critical PRs for this plugin, as we hope that in time we’re able to transition users to the corresponding plugin in [the Flutter Community Plus Plugins repository](https://plus.fluttercommunity.dev/). We encourage you to submit your PR there.

(We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.)

**Pull request closed without merging**
