### PR TITLE
[in_app_purchase] Add macOS support

### PR DESCRIPTION
**Pull request by alihassan143**
macos os support added also the example app also added

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Thanks for the submission! Since this currently doesn't pass any of the CI tests, and the checklist is missing critical elements like tests, I'm going to mark this as a draft. Please also read https://github.com/flutter/flutter/issues/84391#issuecomment-970474366 as it looks like you are duplicating code, which isn't an approach we would land.

Once this PR is complete, please mark it as ready for review and we'll take a look. Thanks!

**Comment by stuartmorgan** [comment]
This still has a number of high-level issues that need to be addressed before we can even start reviewing this:
- As mentioned above:
  > Please also read https://github.com/flutter/flutter/issues/84391#issuecomment-970474366 as it looks like you are duplicating code, which isn't an approach we would land.

  This doesn't appear to have been resolved; the diff is showing duplication of all of the files. They need to be symlinked from a shared location.
- The plugin does not build. See failures in `macos-build_all_plugins` and `macos-platform_tests`. It needs to build and pass tests.
- You have a lot of unrelated changes. You've made pubspec changes to packages with no changes, for reasons that aren't clear, and add a lot of files to the iOS and Android examples. All the changes that aren't related to this PR need to be reverted.
- You need to follow the process described [here](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins) so that CI can build the changes. You should also not be disabling publishing of `in_app_purchase`; there's no step in this process that would require that, and it disables important checks.

Some other issues as well:
- > - [x] I read and followed the [relevant style guides](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style) and ran [the auto-formatter](https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code). (Unlike the flutter/flutter repo, the flutter/plugins repo does use dart format.)

  This doesn't appear to have been run; see failures in the `format` task. The license check there is also failing; you'll need to add the license to all new files.
- > - [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates).
  > - [x] I updated CHANGELOG.md to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style).

  You've checked these boxes, but haven't actually done the steps. As I said in your previous PR, please don't check boxes when you haven't done the steps. We have this checklist for a reason; these steps are part of our development process.

**Comment by alihassan143** [comment]
thank you for clearing the confusion i will change the things and resend for review again

**Comment by stuartmorgan** [comment]
I'm not sure where you are seeing that error, but the errors in CI are from the build not being set up correctly in the first place. For instance:

> Errno::ENOENT - No such file or directory @ rb_check_realpath_internal - /private/var/folders/2f/dq81klt17l3g6yg3_nf0t2gh0000gn/T/cirrus-ci-build/packages/in_app_purchase/in_app_purchase_storekit/example/macos/Flutter/ephemeral/.symlinks/plugins/in_app_purchase_storekit/macos/Classes/FIAObjectTranslator.h

**Comment by alihassan143** [comment]
@stuartmorgan  i tried the ci test for ios also but they showing the same error also

**Comment by stuartmorgan** [comment]
> @stuartmorgan can you try to run again the ci test i am getting this error for ios also in native tests

I'm not sure what you are asking for here; CI tests are run automatically every time you push changes. Please link to the specific line in the Cirrus logs that you are referring to, because I've looked at the logs and don't see the errors you are describing.

**Comment by alihassan143** [comment]
@stuartmorgan    For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.3

      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
    [!] CocoaPods could not find compatible versions for pod "in_app_purchase_storekit":
      In Podfile:
        in_app_purchase_storekit (from `Flutter/ephemeral/.symlinks/plugins/in_app_purchase_storekit/macos`)

    Specs satisfying the `in_app_purchase_storekit (from `Flutter/ephemeral/.symlinks/plugins/in_app_purchase_storekit/macos`)` dependency were found, but they required a higher minimum deployment target.
    can you help how to resolve this error we need macos 10.15 for most of the in app purchase apis

**Comment by alihassan143** [comment]
> That error is completely different than the error you quoted earlier and said that you were seeing in the CI. It's very hard to help when you are providing conflicting information.
> 
> You can resolve that error by changing the minimum deployment target of the targets in the Runner project and the Podfile.

sorry i was wrong the error is showing only in local tests i don't know why

**Comment by stuartmorgan** [comment]
I see; that error is specific to `build_all_plugins`. Please understand that I have a lot of other demands on my time, including many other PRs to review, so the amount of time that I can devote to reviewing this PR is limited. When I ask for a link to the specific error line (and provide instructions for doing so), please actually do that instead of just quoting part of an error and expecting me to sift through the many CI failures this PR currently has every time in order to find the one you are talking about.

`build_all_plugins` uses a generated app, so will require some tooling adjustments to handle this correctly. Once you have fixed all of the other failures I can address `build_all_plugins`.

**Comment by alihassan143** [comment]
@stuartmorgan  
[darwin-lint_podspecs](https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6684439956) getting error in drain lints can you help me to fix this(
https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6684439956)
#format error I tried the commands provided in the documentations that format the code but getting the same issue (https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6684439927)
macOS build failed  pod is not installing (https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6684439966)
kindly help me is these error i am not getting any solution how to solve them

macOS tests did not even starting because of some cocopods issue(

https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6684439946)

macOS test for stable (
https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6684439932)
Publishable issue(
https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6684439933)
macOS build failed   for all plugin(
https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6684439951)

Submit queue issue (
https://api.github.com/repos/flutter/plugins/check-suites/6737496588/check-runs)

**Comment by alihassan143** [comment]
@stuartmorgan i ran the unit tests and all unit tests are passing

**Comment by alihassan143** [comment]
> @alihassan143 I can help answer specific questions, but I can't investigate and fix every issue from scratch; this is a low-priority feature, so the amount of time we can spend on a PR for it is, as I said above, limited.
> 
> As a starting point for your investigation: you appear to have used [absoluted paths](https://github.com/flutter/plugins/pull/5854/files#diff-abd53263f9c0e7e07f78cdeab484389ec65637d8c31ea2dbfe1a5da2683cca73) for your symlinks, which means this PR won't work on any machine except yours.

oh i see thanks i will add path that is accessible by every machine

**Comment by alihassan143** [comment]
@stuartmorgan  getting error in ci Select a development team in the Signing & Capabilities editor for build 
https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6750599811

**Comment by stuartmorgan** [comment]
> @stuartmorgan getting error in ci Select a development team in the Signing & Capabilities editor for build https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6750599811

The line right before that says:
> error: Signing for "Runner" requires a development team.

Our CI isn't set up to sign applications. Why have you enabled signing?

Also, note that the plugin package itself still doesn't even build, which seems like a more fundamental issue:
https://cirrus-ci.com/task/6046547497451520?logs=build#L64

**Comment by alihassan143** [comment]
i didn't enable the signing option it setup to none like other

**Comment by alihassan143** [comment]
> > @stuartmorgan getting error in ci Select a development team in the Signing & Capabilities editor for build https://github.com/flutter/plugins/pull/5854/checks?check_run_id=6750599811
> 
> The line right before that says:
> 
> > error: Signing for "Runner" requires a development team.
> 
> Our CI isn't set up to sign applications. Why have you enabled signing?
> 
> Also, note that the implementation package itself still doesn't even build, which seems like a more fundamental issue: https://cirrus-ci.com/task/6046547497451520?logs=build#L64

when i am trying this code in real device and real project it working fine without any errors

**Comment by alihassan143** [comment]
@stuartmorgan  this feature to enable in app purchase for macos is very important i don't know why flutter team is not woking on it please  if you help me to find some issue that will enable pr to be merged

**Comment by stuartmorgan** [comment]
> i didn't enable the signing option it setup to none like other

Every other example application in our repository builds successfully, so something about the signing setup of the one you've added is different. I suggest comparing settings with another, working example project.

> when i am trying this code in real device and real project it working fine without any errors

I'm not sure what you mean by "real device", but the example application in the implementation package is a real project, and it doesn't compile.

Working in customized local testing on your machine is a good start, but a PR needs to work everywhere--especially our CI.

> i don't know why flutter team is not woking on it

Because there is significant amount of higher-priority work at the moment.

> please if you help me to find some issue that will enable pr to be merged

I have pointed out a number of issues; fully debugging and resolving all of the issues, however, is beyond the scope of how much time we can devote to this right now.

**Comment by stuartmorgan** [comment]
A build timeout almost always means that `pub get` resolution is failing; there's an issue with `pub get` when running in CI where it times out instead of failing with output. I see you've done something strange with git references (instead of following our contributing guide's instructions for how to do multi-package changes). It's very likely that the problem is that you've made package resolution impossible with how you made that change.

**Comment by stuartmorgan** [comment]
https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins has the instructions for the process I was referring to in my last comment. You should follow the instructions in step 1 instead of using git references in pubspecs.

**Comment by Hixie** [comment]
@alihassan143 Thanks for your contribution! Can you post an update describing the state of this PR and the related PRs? I'm just trying to understand the state of our review queue. Thanks!

**Comment by alihassan143** [comment]
@Hixie  @IVLIVS-III  make changes in his pr that needed to be added now his pr is in final reviews my pr contains some error so i am closing this pr

**Pull request closed without merging**
