### PR TITLE
[ci] Removes unnecessary overrides.

### PR DESCRIPTION
**Pull request by pq**
Fix some diagnostics that will be reported by a pending update to the linter.

See: https://dart-review.googlesource.com/c/sdk/+/264961

### CODE REVIEW

**Comment by pq** [comment]
It looks like this requires a "no changelog change required" override...  I think that should be safe in this case?

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by pq** [comment]
(Confirmed w/ @goderbauer that no changelog updates are needed since this is sample code.)

**Comment by pq** [comment]
@stuartmorgan (or anyone): I'd love an assist landing this one. It's blocking a roll of the linter in the Dart SDK.

**Comment by ditman** [comment]
It seems that this is failing because something new is incoming that is changing some API that is being mocked:

```
+2
 -1
: 
loading test/make_deps_path_based_command_test.dart
[E]
Failed to load "test/make_deps_path_based_command_test.dart":
  test/common/package_command_test.mocks.dart:114:33: Error: The method 'MockGitDir.runCommand' has fewer named arguments than those of overridden method 'GitDir.runCommand'.
    _i6.Future<_i4.ProcessResult> runCommand(Iterable<String>? args,
                                  ^
  /root/.pub-cache/hosted/pub.dev/git-2.2.0/lib/src/git_dir.dart:254:25: Context: This is the overridden method ('runCommand').
    Future<ProcessResult> runCommand(
                          ^
  test/common/package_command_test.mocks.dart:114:33: Error: The method 'MockGitDir.runCommand' doesn't have the named parameter 'echoOutput' of overridden method 'GitDir.runCommand'.
    _i6.Future<_i4.ProcessResult> runCommand(Iterable<String>? args,
                                  ^
  /root/.pub-cache/hosted/pub.dev/git-2.2.0/lib/src/git_dir.dart:254:25: Context: This is the overridden method ('runCommand').
    Future<ProcessResult> runCommand(
                          ^
To run this test again:
 /sdks/flutter/bin/cache/dart-sdk/bin/dart test test/make_deps_path_based_command_test.dart -p vm --plain-name 'loading test/make_deps_path_based_command_test.dart'
```

The solution is probably to update the Mockito mocks in this package:

* https://github.com/flutter/plugins/tree/main/script/tool

(Giving this a quick shot)

**Comment by ditman** [comment]
(Does not reproduce @ Framework • revision 19871b15cd (2 weeks ago)), jumping to TOT.

**Comment by ditman** [comment]
Needs the `override: no changelog needed` because this is tripping in unrelated packages:

```
[0:01] Running for video_player_android...
  No version change.
  Found NEXT; validating next version in the CHANGELOG.
No CHANGELOG change found. If this PR needs an exemption from the standard policy of listing all changes in the CHANGELOG, comment in the PR to explain why the PR is exempt, and add (or ask your reviewer to add) the "override: no changelog needed" label. Otherwise, please add a NEXT entry in the CHANGELOG as described in the contributing guide.
[0:01] Running for video_player_avfoundation...
  No version change.
  Found NEXT; validating next version in the CHANGELOG.
No CHANGELOG change found. If this PR needs an exemption from the standard policy of listing all changes in the CHANGELOG, comment in the PR to explain why the PR is exempt, and add (or ask your reviewer to add) the "override: no changelog needed" label. Otherwise, please add a NEXT entry in the CHANGELOG as described in the contributing guide.
```

**Review by ditman — APPROVED** [review]
LGTM!

**Comment by pq** [comment]
Thanks a million @ditman!

**Comment by stuartmorgan** [comment]
> I think the tool is tripping because we're updating source within the `example`, and that is deemed to need to be published in pub.dev (however those files outside main.dart are not).

The tool knows what parts of example are published, which is why it didn't request a version change. The CHANGELOG flag is consistent with our policy:
>> This policy exists because some changes (e.g., updates to examples) that do not need to be published may still be of interest to clients of a package.

Overriding in this case would have been fine since the details of the change aren't likely to be very interesting, but we err on the side of failing and requiring human judgement.

**Comment by stuartmorgan** [comment]
> /cc @stuartmorgan how can we get out of this pickle? What's the most correct escape hatch for this tools check? Maybe pinning `package:git` to `>= 2.0.0 <2.1.0` until our legacy analysis rolls forward enough? (I'm going to test this but _not autosubmit_ the package until Stuart has time to see it)

This seems like a reasonable option. Thanks for the investigation and fix!

**Comment by pq** [comment]
Thanks for all your help!

**Comment by ditman** [comment]
Thanks for keeping the repo tidy and checks passing! @pq 🙏

**Pull request merged**
