### PR TITLE
[firebase_auth] Add updatePhoneNumber function

### PR DESCRIPTION
**Pull request by zerefati**
Add updatePhoneNumber function.

### CODE REVIEW

**Comment by zerefati** [comment]
I signed it!

**Comment by kroikie** [comment]
@zerefati Thanks for the contribution, we would need to have the Android and iOS implementation of this before we can merge, any chance you can add that?

**Comment by collinjackson** [comment]
@zerefati - friendly ping, please let us know if you want to finish or abandon this PR

**Comment by zerefati** [comment]
Yes sure, I will update it soon.

**Comment by zerefati** [comment]
Yes sure, I will update it soon.

**Comment by GianlucaCesari** [comment]
Is this going to be in the next package release?

**Comment by collinjackson** [comment]
I am hoping to land and publish it soon, but it needs a unit test still. If anyone wants to write that one, it will help me merge the PR faster.

**Comment by GianlucaCesari** [comment]
How can I help? I've never done unit test but if you link me a guide or an example I can try, I really need this  :)

**Comment by GianlucaCesari** [comment]
I'm ok with my commits being contributed to this project.

**Comment by collinjackson** [comment]
This change LGTM, just waiting for the tests to pass.

**Comment by GianlucaCesari** [comment]
Hey guys, what's missing to approve this PR?

**Pull request merged**
