### PR TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

### PR DESCRIPTION
**Pull request by jiangqingbo**
E/flutter (  946): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter (  946): 
E/flutter (  946): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter (  946): 
E/flutter (  946): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/package_info)

### CODE REVIEW

**Comment by jiangqingbo** [comment]
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

how resolve it ? ?

**Comment by dnfield** [comment]
I suspect you opened this by mistake.

If you have found a bug with flutter please file an issue.

You may want to check the documentation about adding the shared preferences plugin for your platform.

**Comment by Hu-Wentao** [comment]
> MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
> 
> how resolve it ? ?

What platform are you running on?
`package_info` only support `ANDROID` `IOS` and `MACOS`

**Comment by luokunman** [comment]
> > MissingPluginException（在通道 plugins.flutter.io/shared_preferences 上找不到方法 getAll 的实现）
> > 怎么解决呢？?
> 
> 你在什么平台上运行？
> `package_info`只支持`ANDROID` `IOS`和`MACOS`

I still haven't solved it for android. have you a solution?

**Comment by dvorapa** [comment]
Same issue here, current Flutter stable and current shared preferences plugin.

**Comment by bxxasn** [comment]
in android system
flutter version:2.5.3 have the error
flutter verison:2.3.2 not have the error

**Comment by bxxasn** [comment]
> how resolve it ? ?
======================================================================
in android system
flutter version:2.5.3 have the error
flutter verison:2.3.2 not have the error
----------------
but only run flutter not have the error
just flutter in androidModule get the  error

import:
shared_preferences: ^2.0.7
device_info: ^2.0.2
path_provider: ^2.0.2

**Pull request closed without merging**
