### PR TITLE
[video_player android/ios/web/platform_interface] Reusable video controller

### PR DESCRIPTION
**Pull request by sanekyy**
## Description

Make video player be reusable for various data sources.

This PR includes chages for 3 plugins: `video_player_platrofm_interface`, `video_player` and `video_player_web`.

**Existing behavior:**
 If someone shows widget with video and then want to shows another video in this widget, he should create new`VideoPlayerController` instance which will create new texture and new video player on platform side.

**New behavior:** 
If someone shows widget with video and then want to shows another video in this widget, he can call `videoPlayerController.setDataSource()` and reuse existing `VideoPlayerController` with it's platform  texture and video player instances.

**Motivating:**
Creation of new `VideoPlayerController` leads to creation new texture and new video player on platform side witch takes some time to create and initialize. Also usually number of video player instances which can exist at the same time is limited by platform ( around 4 on Android, for example ).

Disposing of texture and video player on platform side takes some time.

I faced with freezing UI while animating widgets and disposing controller in the middle of animation. After spending some time debugging, I found, that this freeze was caused by disposing video player on platform side ( Android in my case ) on main thread which took ~40ms.
I also made measurements:
+ Creation of new video player took ~5ms on platform side.
+ Set new data source to existing video player took same ~5ms on platform side.

**Addition:**

I have read https://flutter.dev/go/federated-plugins and understood what I did.
I make breaking changes in `video_player_platrofm_interface` to implement this feature.
I implemented support for this changes in `video_player` and `video_player_web` plugins.
I fixed all tests in all plugins to support new API.
I supported this changes on all platforms ( Android, iOS, web )

I updated versions of `video_player`, `video_player_web`  and `video_player_platrofm_interface` and also update `video_player_platrofm_interface` dependency version in `video_player` and `video_player_web`.
This leads to crash of CI checks pipeline for this PR because new version of `video_player_platrofm_interface` doesn't exist in pub. 
If you want, I can temporarily change it and refer to  `video_player_platrofm_interface` as path to my fork as here:
```
video_player_platform_interface:
    git:
      url: git://github.com/sanekyy/plugins.git
      ref: reusable_video_controller
      path: packages/video_player/video_player_platform_interface

```
to show green lights on CI checks

Also I am ready to apply your suggestions for this PR to improve it. Maybe you can suggest better API or logic chain or naming of some things.

Hope on productive collaboration on this PR.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by otopba** [comment]
@googlebot I consent.

**Comment by sanekyy** [comment]
analyze and format tasks failed with 
```breaking change detected.
Breaking changes to platform interfaces are strongly discouraged.```

![image](https://user-images.githubusercontent.com/18647037/78062703-bf99b900-7397-11ea-8b0f-254025fda01b.png)

![image](https://user-images.githubusercontent.com/18647037/78077929-f086e780-73b1-11ea-8578-1526a4fa4194.png)

**Comment by otopba** [comment]
@googlebot I consent

**Comment by raymondlee00** [comment]
Are there any updates on this?

**Comment by ldelafuente** [comment]
Hi @sanekyy! Do you think you can migrate this fork to Pigeon to merge it with master?

**Comment by ldelafuente** [comment]
Hi @sanekyy! Do you think you can migrate this fork or **reusable_video_controller_with_caching** (which would be incredible) to Pigeon to merge it with master?

**Comment by sanekyy** [comment]
Hello @ldelafuente 
Yes, I plan to do it ASAP.

**Comment by ldelafuente** [comment]
Maybe @recastrodiaz and @gaaclarke can help migrate it to Pigeon

**Comment by sanekyy** [comment]
I'll be really glad

**Comment by recastrodiaz** [comment]
@sanekyy @ldelafuente  I can help port this to pigeon if necessary (it should be easy as Pigeon does make our lives easier). However, I would need to know what the flutter team thinks first about the PR. Is this the only changed required for this PR to be merged to master?

**Comment by sanekyy** [comment]
Hi @recastrodiaz
Same question for Fluter team

**Comment by gaaclarke** [comment]
Hi, I gave this a look.  I think you should rework it so that it isn't a breaking change.  You can still keep the old constructors but add `setDataSource` and add an empty one constructor you think you need it.  The existing constructors can just use your `setDataSource` under the covers.

For migrating to Pigeon, I think the easiest thing will be for you would be to check out the master branch of video_player and plug your changes into that codebase.  It should be pretty straightforward.

I'm not sure what caused this PR to stall out.  mklim is no longer on this team and there was probably hesitation to accept breaking changes.  I think you can get what you want without making this a breaking change though.

Ping @amirh again when it is ready to review, hopefully it will go smoother this time around.  You can try pinging me again if this gets lost.  Also, you know about the discord server right?  There is a channel `hackers-ecosystem` if you want to make sure you are on the right path.

**Comment by ldelafuente** [comment]
> Hi, I gave this a look. I think you should rework it so that it isn't a breaking change. You can still keep the old constructors but add `setDataSource` and add an empty one constructor you think you need it. The existing constructors can just use your `setDataSource` under the covers.
> 
> For migrating to Pigeon, I think the easiest thing will be for you would be to check out the master branch of video_player and plug your changes into that codebase. It should be pretty straightforward.
> 
> I'm not sure what caused this PR to stall out. mklim is no longer on this team and there was probably hesitation to accept breaking changes. I think you can get what you want without making this a breaking change though.
> 
> Ping @amirh again when it is ready to review, hopefully it will go smoother this time around. You can try pinging me again if this gets lost. Also, you know about the discord server right? There is a channel `hackers-ecosystem` if you want to make sure you are on the right path.

I already migrated a big part of this PR to Pigeon. From my understanding and experience using this plugin, @sanekyy's implementation makes it more clean and easy to instantiate the controller and to programatically update the source. Even though these are breaking changes we should favor this new implementation.

**Comment by ldelafuente** [comment]
> Hi, I gave this a look. I think you should rework it so that it isn't a breaking change. You can still keep the old constructors but add `setDataSource` and add an empty one constructor you think you need it. The existing constructors can just use your `setDataSource` under the covers.
> 
> For migrating to Pigeon, I think the easiest thing will be for you would be to check out the master branch of video_player and plug your changes into that codebase. It should be pretty straightforward.
> 
> I'm not sure what caused this PR to stall out. mklim is no longer on this team and there was probably hesitation to accept breaking changes. I think you can get what you want without making this a breaking change though.
> 
> Ping @amirh again when it is ready to review, hopefully it will go smoother this time around. You can try pinging me again if this gets lost. Also, you know about the discord server right? There is a channel `hackers-ecosystem` if you want to make sure you are on the right path.

@gaaclarke I already migrated a big part of this PR to Pigeon. From my understanding and experience using this plugin, @sanekyy's implementation makes it more clean and easy to instantiate the controller and to programatically update the source. Even though these are breaking changes we should favor this new implementation.

**Comment by gaaclarke** [comment]
> @sanekyy's implementation makes it more clean and easy to instantiate the controller and to programatically update the source.

Do you really have to break the old code path to add the new clean and easy path?

If you think so, you are still probably better off splitting your work into 2 PR's in this case, one that adds the functionality you want and one that refactors the API to be cleaner.  There doesn't seem to be any reason adding this functionality necessitates a breaking change from what I see.

FWIW I think you are going to have a hard time getting any breaking change approved for the sake of cleanliness or ease of use.  The cost to users is just too high for something that's hard to objectify.

**Comment by ldelafuente** [comment]
> > @sanekyy's implementation makes it more clean and easy to instantiate the controller and to programatically update the source.
> 
> Do you really have to break the old code path to add the new clean and easy path?
> 
> If you think so, you are still probably better off splitting your work into 2 PR's in this case, one that adds the functionality you want and one that refactors the API to be cleaner. There doesn't seem to be any reason adding this functionality necessitates a breaking change from what I see.
> 
> FWIW I think you are going to have a hard time getting any breaking change approved for the sake of cleanliness or ease of use. The cost to users is just too high for something that's hard to objectify.

@gaaclarke I strongly disagree with your point. Is not only about having a more easy to understand implementation but also more efficient. As of today, video_player instantiates a player on the platform side increasing the amount of memory by a lot and even though we properly dispose the controller after being used a few times, the app crashes because different devices only support a few number of players being instantiated. We have tried for months by using the official implementation of the plugin but is far for being optimal.
Just like other parts of the framework introduce breaking changes, this shouldn't be a reason to not approve changes on this plugin.

**Comment by sanekyy** [comment]
Hello @gaaclarke.

Can I mark old methods and constructors as deprecated with adding new API?

**Comment by gaaclarke** [comment]
> Hello @gaaclarke.
> 
> Can I mark old methods and constructors as deprecated with adding new API?

I don't really have the authority to make that call.  We really need a decision from @amirh and the ecosystem team.  When this is in a state that is landable I would expect that he would present that to the team to discuss if we want to move forward.  You can try reaching out to them on discord if you want some feedback before that work is done.

If I were you I would present the PR with the following:
1) All CI checks are green
1) No breaking changes
1) Add deprecation tags to the old constructors.  It's better to start from there for discussion sake.

**Comment by aytunch** [comment]
@gaaclarke Did you have some time to review the changes @sanekyy did as you have requestes.
I think, with or without breaking changes, this PR should be merged and is needed asap.
For the time being it is impossible to make a production ready app with a video feed feature in Flutter. Optimizing resources will be beneficial to everyone

**Comment by cyanglaz** [comment]
I'm going to close the PR because the CLA is not signed. Feel free to ping me when the CLA is signed and I'll re-open the PR. Or you can open a new PR after signing the CLA.

**Comment by lukepighetti** [comment]
@cyanglaz I can't see the current status of the CLA bot, but this PR has been carted around GitHub in three different permutations, and https://github.com/flutter/plugins/pull/2130 contains the CLA that this bot might be looking for.

**Comment by amalnaami** [comment]
video_player ^2.1.10 which depends on video_player_platform_interface ^4.1.0, video_player_platform_interface from hosted is required.

I try to implement it on my code and get like this, How I can solve this problem ??

**Comment by aytunch** [comment]
@sanekyy @cyanglaz This PR reduces the Jank substantially if the app is a social app with a video app. Reusing native paltform resources for different videos is a must for video_player

**Comment by LeGoffMael** [comment]
> @sanekyy @cyanglaz This PR reduces the Jank substantially if the app is a social app with a video app. Reusing native paltform resources for different videos is a must for video_player

Like @aytunch said this is a must feature for video_player. I am really willing forward to see this PR being merged.

**Pull request closed without merging**
