### PR TITLE
[video_player] Support for simultaneous playback of audio sources on iOS

### PR DESCRIPTION
**Pull request by mitghi**
This PR adds support for  simultaneous playback of audio sources such as background music
along with video and other sources in iOS.

The _mixWithOthers_ option works as expected, as long as the video player is the **single**
audio source within the app. Therefore, the _mixWithOthers_ option alone, does not 
provide the flexibility of using the video player along with background music and other
audio sources within the app ( e.g. muted video + text-to-speech + background music ).

The proposed solution is to pass another argument to **VideoPlayerOptions** to setup ambient mode:
```dart
VideoPlayerOptions(mixWithOthers: true, ambient: true)
```

_Ambient_ mode allows mixing of audio sources within app with background sources.

This PR fixes issue [#94328](https://github.com/flutter/flutter/issues/94328).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Thanks for the contribution! This will need native unit tests testing the actual change in functionality; currently the only test coverage is that the option is passed through the method channel, not that it's used correctly.

Also, you've indicated that you've signed the CLA, but the check indicates that neither of the email addresses associated with the commits have CLA entries, so that will need to be resolved before we could review this.

**Comment by mitghi** [comment]
@stuartmorgan Thank you for the feedback. I will write the platform test cases and resubmit the PR. I have corrected the email address as well, but should resubmit the PR. Previously, the wrong email address was associated with git.

I have a question, this PR changes the platform interface slightly in order to add additional argument to _VideoPlayerOptions_. Should the changes to platform interface be separately submitted first? Because otherwise the video_player depend on a version of video_player_platform_interface that does not exist in repo.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins

**Comment by stuartmorgan** [comment]
> but should resubmit the PR

You're welcome to do a new PR if you want to, but you could also just `amend` the commits locally to have the right email address, and then force-push to this PR.

**Pull request closed without merging**
