### PR TITLE
Remove unused `test` dependencies add missing environment constraints

### PR DESCRIPTION
**Pull request by cyanglaz**
## Description

The `test` dependency seems to cause CI to hang, and we are not using them mostly in this repo so we can remove those and make the tree green. This PR only unblocks the tree, it didn't fix the root cause of the issue. See discussion in the issue for details. 

This PR also adds env constraints for some example apps who are missing env constraints. 

## Related Issues

https://github.com/flutter/flutter/issues/69439

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by amirh** [comment]
This seems to overlap with https://github.com/flutter/plugins/pull/3240, which is ok if we want to fix the tree at once though I see that not all the packages where the example apps get sdk constraints in https://github.com/flutter/plugins/pull/3240 are getting them in this PR...

**Comment by cyanglaz** [comment]
I'm going to see if this fixes the hang issue for the plugins in this PR, if so, i'll merge #3240 into this.

**Comment by cyanglaz** [comment]
Looks like the timeout is fixed by this. Merged 3240 and re-running CI.

**Comment by cyanglaz** [comment]
CC @zanderso For the 3240 merging.

**Comment by cyanglaz** [comment]
Also merged https://github.com/flutter/plugins/pull/3219 so we can remove the `test` dependency in video_player as well.

**Review by amirh — APPROVED** [review]
LGTM

**Comment by zanderso** [comment]
@dnfield @jonahwilliams

**Comment by dnfield** [comment]
If this passes CI and gets the tree open I'm fine with that. We really should figure out what's going on with vm_service that's causing things to hang sometimes.

**Comment by dnfield** [comment]
Failure is due to https://github.com/flutter/plugin_tools/pull/119

**Pull request merged**
