### PR TITLE
[video_player] Add ability to customize the SSL context for HTTPS connections

### PR DESCRIPTION
**Pull request by mrnicegaius**
This pull request adds the ability to customize the verification of HTTPS certificates in a similar way to the method used by the `SecurityContext` class when using `HttpClient`. Note this is my first pull request, so be kind :-).

*List which issues are fixed by this PR. You must list at least one issue.*

This provides a method for fixing (flutter/flutter#75995)[https://github.com/flutter/flutter/issues/75995]. That particular issue is about self-signed certificates, but this change allows particular certificates to be selected.

Currently this is only supported under Android, as I do not have any iOS devices.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [ ] I signed the [CLA].
  * Is this a deal breaker? I dont have a gmail account associated with my github user account. And dont really want to associate the two. However this seems the only way to sign the CLA? 
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
  *  Is this PR exempt from version changes? When i was developing i had to change the yaml files to use local packages amongs the `video_player{,_android,_platform_interface}` modules to compile, but I'm not sure how this is normally done. See Notes below
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
  * Should this PR change CHANGELOG.md when its not versioned?
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

## Further Notes

1. The DefaultHttpDataSource is based on the exo-player data source of the same name. I added the original version as part of the source and modified it from there so changes from the original can be seen. This _could_ be 
 forwarded to the exoplayer team to allow better customization of the exoplayer, but:
  * I dont have a full java dev environment setup, so testing and submitting is probably more effort than its worth to me.
2. The `pubspec.yaml`'s for `video_player`, `video_player_android`, `video_player_android/examples` use absolute packages, but I need the relative versions to compile (because the interfaces have not been updated in pub.dev). I'm not sure how this is normally done with PR's? I've left them as is for now, and have them `stash`ed away in my working dir if needed.

### CODE REVIEW

**Comment by mrnicegaius** [comment]
So, as mentioned, this is my first PR. With regards to the failing checks, this has to do with my non-commit's of the `pubspec.yaml` files, and the fact the build system uses the absolute packages for referencing the internal packages. I'm not exactly sure how to solve this so I'm hoping someone from the plugin team can help me here. The problem is that the `video_player_android` package relies on the `video_player` package and the `video_player_platform_interface` package, but both are changed due to the addition of the new interface to the `video_player`. Likewise the unit tests and integration tests for some reason use absolute packages instead of relative packages, which causes more build errors. 

How I built it in my repository was by overriding the dependencies to use the local versions (see attached patch). Whats the correct way of doing this? Should I have submitted multiple PR's to address this, by first targetting `video_player` and `video_player_platform_interface`, then  wait for the PR to be resolved before submitting the `video_player_android` PR?

**Comment by stuartmorgan** [comment]
Thanks for the contribution! Answering some of the questions above:

> Is this a deal breaker?

Yes; as the bot response said:

>> Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

> * Is this PR exempt from version changes?

No, the link in the PR checklist explains what the exemptions are.

> Whats the correct way of doing this?

Please see our contributing documentation (linked from the first checklist item), which covers this: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins

**Comment by mrnicegaius** [comment]
> > Whats the correct way of doing this?
> 
> Please see our contributing documentation (linked from the first checklist item), which covers this: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins

Thanks for your help @stuartmorgan. Just to nitpick, the first item in the checklist (which i read and checked), refers to [this](https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md) contribution guide, not the [one you linked](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins). Maybe the flutter/plugins contribution guide needs updating?

So I read the flutter/flutter contribution guide. To be honest, given i have to make changes to 3 plugins (`video_player`, `video_player_platform_interface`, and `video_player_android`) and wait for the PR's to go through, this is probably going to take up too much of my time. I only submitted this because I had implemented the fix in my local branch and saw it solved an existing issue, but waiting for the approval of 3 PR's is probably more effort than I was going for :-) 

> > Is this a deal breaker?
> 
> Yes; as the bot response said:

Given i dont have a gmail account linked to my github account, doesnt look like i can sign the CLA either (if you have any contacts with the CLA team, maybe remind them not everyone has a gmail account :-)?). Having said that. if anyone wants to pick up these changes and resubmit them, feel free, all the source is already under existing LICENCES, and I consent to anyone using the changes I made for any reason whatsoever. 

Thanks again, flutter's a great project, feel free to close this PR if its not of any help!

**Comment by stuartmorgan** [comment]
> Just to nitpick, the first item in the checklist (which i read and checked), refers to [this](https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md) contribution guide, not the [one you linked](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins).

Thanks for the feedback, but our guide already includes:

> > [Contributing to Plugins and Packages](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages), for more information about how to make PRs for this repository, especially when changing federated plugins.

which is what I linked to. (The expectation is that people will read the resources it links to, not just the list itself.)

Without a signed CLA we cannot accept the PR, so if you have no plans to sign it I'm going to go ahead and close this.

**Comment by mrnicegaius** [comment]
> which is what I linked to. (The expectation is that people will read the resources it links to, not just the list itself.)

Ah, sorry @stuartmorgan, really dont know how I missed that on my read through, I even reread before posting to see if it was linked :sigh: 

> so if you have no plans to sign it I'm going to go ahead and close this.

Happy to sign, just dont have a gmail account so cant :-) Thanks anyway, sorry for taking up your time.

**Comment by stuartmorgan** [comment]
> just dont have a gmail account so cant

I'm not sure why you're saying "Gmail account"; the CLA requires a Google Account, which doesn't have to involve Gmail, and is free to create.

If at some point you change your mind, please feel free to reopen the PR. Thanks!

**Comment by mrnicegaius** [comment]
> > just dont have a gmail account so cant
> 
> I'm not sure why you're saying "Gmail account"; the CLA requires a Google Account, which doesn't have to involve Gmail, and is free to create.

Haha, sorry again! When I clicked on the CLA link it took me to the google login page, and when i clicked on create new account it auto-filled a gmail address, I didnt see the use other account button :facepalm: This contribution was a attempt at being a good netizen while developing a side project of mine, so I'll give the PR derby another go when I get to 80% of my current side project and decide to move on :slightly_smiling_face:

**Pull request closed without merging**
