### PR TITLE
Update Flutter SDK constraint to match templates; plugins I-P

### PR DESCRIPTION
**Pull request by mit-mit**
## Description

Align plugins with new templates, removing unused upper constraint

## Related Issues

https://github.com/flutter/flutter/pull/68437

### CODE REVIEW

**Review by mvanbeusekom — APPROVED** [review]
LGTM

**Review by ditman — APPROVED** [review]
LGTM!

**Comment by jinfagang** [comment]
```
Because no versions of local_auth match >0.6.3+4 <0.7.0 and local_auth 0.6.3+4 depends on intl >=0.15.1 <0.17.0, local_auth ^0.6.3+4 requires intl >=0.15.1 <0.17.0.
And because easy_localization >=2.1.0+1 depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, local_auth ^0.6.3+4 is incompatible with easy_localization >=2.1.0+1.
So, because potato_notes depends on both local_auth ^0.6.3+4 and easy_localization ^2.3.2, version solving failed.

```

**Comment by jinfagang** [comment]
Anybody could help upgrade intl constrains for master flutter?

**Comment by ditman** [comment]
@jinfagang thanks for reaching out! Can you please create a new issue so the owners of the relevant packages can be notified? :)

https://github.com/flutter/flutter/issues/new/choose

Thanks!

**Pull request merged**
