### PR TITLE
[ci] Initial migration to Cirrus Apple silicon

### PR DESCRIPTION
**Pull request by stuartmorgan**
This adopts the new Apple silicon images for:
- macOS platform tests
- iOS build-all

This gives us build coverage across both architectures for both iOS and
macOS.

Ideally we would use ARM for iOS platform tests instead of build-all,
but driving the iOS tests currently has flaky hangs on ARM. See
https://github.com/flutter/plugins/pull/5693 for details. Completing
that part of the migration is left as a TODO.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@fkorotkov FYI. This will get us on the subset of https://github.com/flutter/plugins/pull/5693 that seems to be problem-free while the simulator issues are investigated more.

**Comment by stuartmorgan** [comment]
Oh, I didn't realize we still had a `pod lint` issue.

@jmagman AFAICT it's using ARM for the synthetic app target it creates to build against. Any idea how to convince it not to do that? If not, I can move linting back for now.

**Comment by jmagman** [comment]
> Oh, I didn't realize we still had a `pod lint` issue.
> 
> @jmagman AFAICT it's using ARM for the synthetic app target it creates to build against. Any idea how to convince it not to do that? If not, I can move linting back for now.

Ugh yeah I don't know how to fix that.  `pod lib lint` generates a fake app and imports the framework.  flutter tooling is figuring out not to build the app for arm64 simulator, but `pod lib lint` doesn't have any knobs to do the same for its generated app.  I managed to avoid building for it on Intel by specifying `--configuration=Debug` so it only builds for the local architecture https://github.com/flutter/plugins/pull/3653, but that's not going to work on arm.

Let's move linting back to x64 for now.

**Comment by stuartmorgan** [comment]
Does that affect what the simulator itself supports? Because the OpenGL codepath for iOS in the Flutter engine will be removed shortly.

**Comment by fkorotkov** [comment]
@stuartmorgan there is not much of the documentation around `FramebufferRendererHint` but my guess is that it doesn't limit Metal support inside the simulator for iOS but only changes how the simulator renderers the frame on your macOS. Is there an option to force Metal codepath in Flutter engine?

**Comment by stuartmorgan** [comment]
> Is there an option to force Metal codepath in Flutter engine?

I'm guessing not at the `flutter run` level (i.e., it would probably require building a custom engine). @jmagman would probably know for sure.

(Also @jmagman ping on approving this PR to start the transition while we figure the rest out 🙂)

**Review by jmagman — APPROVED** [review]
LGTM!

**Comment by jmagman** [comment]
> > Is there an option to force Metal codepath in Flutter engine?
> 
> I'm guessing not at the `flutter run` level (i.e., it would probably require building a custom engine). @jmagman would probably know for sure.

Looking into this...

**Comment by stuartmorgan** [comment]
I filed https://github.com/flutter/flutter/issues/104523 to track moving the other tests; we can continue discussion there.

**Pull request merged**
