### PR TITLE
[google_maps_flutter] Switch web to structured options

### PR DESCRIPTION
**Pull request by stuartmorgan**
Web portion of https://github.com/flutter/plugins/pull/5825

In order to avoid needing to keep both the JSON-based and the new structured-object based implementations of option handling, this makes a breaking change and only implements the new methods (rather than our usual practice of having all versions of a method implemented for maximal compatibility). As a result this version will only work with the version of the app-facing package that is published when https://github.com/flutter/plugins/pull/5825 lands.

Fixes https://github.com/flutter/flutter/issues/70330

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by ditman** [comment]
Checking why tests are failing

**Comment by ditman** [comment]
When running locally (with --no-headless), the test is failing with the following:

Screen Shot 2022-06-14 at 11 12 26 AM

But it seems the tester is not detecting that failure and "breaking" the test, so it just times out. Diving slightly deeper :P

**Comment by ditman** [comment]
Ah, I know what's the issue in this case: the `projection_test.dart` is using the `GoogleMap` from dart to render its test case:

* https://github.com/flutter/plugins/blob/511850636df69a6dbc7331a2d715e1a43da73c71/packages/google_maps_flutter/google_maps_flutter_web/example/integration_test/projection_test.dart#L255-L258

And that's why we're using an unimplemented (not yet migrated) call to `buildView`. If we restored buildView in the web implementation, this might work.

(I remember @stuartmorgan flagging this as "SMELLY" when I merged that test)

**Comment by stuartmorgan** [comment]
> If we restored buildView in the web implementation, this might work.

I think I may be able to instead land the two remaining pieces in the other order. I need to work through that to make sure I'm not missing something though.

**Comment by stuartmorgan** [comment]
Yes, flipping the order should work. The app-facing version will call the new versions, which will get the default platform interface implementation that converts to JSON and then forwards to the old version, so it should be a no-op for web. Then we can switch the web implementation to implement the new methods which will eliminate all calls to buildView.

**Comment by ditman** [comment]
> I think I may be able to instead land the two remaining pieces in the other order. I need to work through that to make sure I'm not missing something though.

@stuartmorgan sounds good too, feel free to revert my latest commit in the branch!

**Comment by ditman** [comment]
Rebasing with master, and dropping my change, so this can be merged.

**Review by ditman — APPROVED** [review]
Tests seem to be passing in my local machine, let's go!

**Pull request merged**
