### PR TITLE
Added isNull filtering to Firestore Query

### PR DESCRIPTION
**Pull request by pulyaevskiy**
* Added isNull filtering to Firestore Query; 
* Fixed DocumentChange oldIndex and newIndex to be treated as signed integers (iOS)

### CODE REVIEW

**Comment by pulyaevskiy** [comment]
Changelog and pubspec are updated so this is ready to be merged ;)

**Comment by mit-mit** [comment]
cc @kroikie

**Comment by pulyaevskiy** [comment]
Just a reminder. Anyone can take a look?

**Comment by mit-mit** [comment]
Sorry about the delay; last week was a holiday in the US. cc @kroikie @collinjackson

**Comment by pulyaevskiy** [comment]
Awesome, thanks everyone!

**Pull request merged**
