### PR TITLE
[google_sign_in] Add ability to request serverAuthCode on Android

### PR DESCRIPTION
**Pull request by ambernardino**
## Description

Before this it was not possible to request an authCode from GoogleSignIn in order to authenticate with a backend.

## Related Issues

flutter/flutter#16613

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by ambernardino** [comment]
I signed it!

**Comment by cyanglaz** [comment]
It seems to be similar to https://github.com/flutter/plugins/pull/879. 
@ambernardino Is your PR trying to do the same thing as the other PR?

**Comment by collinjackson** [comment]
> It seems to be similar to #879.
> @ambernardino Is your PR trying to do the same thing as the other PR?

It seems they are solving similar problems. This one is using what's in google-services.json whereas #879 is requiring the developer to pass the `serverClientID` manually.

**Comment by cyanglaz** [comment]
Closing this PR since it doesn't have iOS implementation.  
https://github.com/flutter/plugins/pull/2116 seems have both implementations.

**Pull request closed without merging**
