### PR TITLE
[quick_actions] Fixed plugin on iOS. Entire lifecycle was not taken care of

### PR DESCRIPTION
**Pull request by olivierbrand**
## Description

The PR includes an entire iOS lifecycle, allowing the actions to trigger when the app is in the background and/or not running.
Also modified the Dart example to provide a more accurate view of what is going on by using a dialog rather than changing the title bar (the title bar was not changing when triggered without actions, making it more confusing for the developer)

## Related Issues

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ X] All existing and new tests are passing.
- [ X] I updated/added relevant documentation (doc comments with `///`).
- [ X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ X] I read and followed the [Flutter Style Guide].
- [X ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X ] I updated CHANGELOG.md to add a description of the change.
- [ X] I signed the [CLA].
- [ X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by jonmountjoy** [comment]
I can't get QuickActions to fire on iOS at all, so I'm hoping this PR will fix it - thank you @olivierbrand .  Is there anyway for me to easily test your changes locally?  I hope the Flutter team can look at them.  I saw your previous PR sat around for ages with no action :-(

**Comment by Niek** [comment]
This PR fixes our issues with quick_actions on iOS. To use is in your project @jonmountjoy, use this is your pubspec.yaml:
```yaml
  quick_actions: # in place till this PR is merged: https://github.com/flutter/plugins/pull/2887
    git:
      url: https://github.com/Ingenio/flutter-plugins
      path: packages/quick_actions
```

**Comment by Niek** [comment]
Can this PR be updated and merged? It's required but still open after 3+ months.

**Comment by Tregan** [comment]
Yeah, would be great if this could be merged.

**Comment by olivierbrand** [comment]
> Thanks for the contribution! We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.
No problem
> We're in the process of working through various issues and PRs related to `quick_actions` (/cc @mvanbeusekom) so we should be able to get this into the review queue. However, I'm not seeing the tests in the PR that you've indicated in the checklist are included; please be sure you've added those to the PR that's been pushed here.
I am unsure this can be automatically tested as it involves the home screen of the phone. What was fixed is a collection of things including mainly the underlying mobile platforms lifecycle events, not sure this is testable

**Comment by stuartmorgan** [comment]
At least the backgrounded app case should be testable via integration tests.

**Comment by olivierbrand** [comment]
> At least the backgrounded app case should be testable via integration tests.
Not sure, can you trigger a long press on home screen to validate this? How would you do these tests, also a critical one was: app killed on iOS. Thanks for pointing me in the right direction or any other help is welcome

**Comment by stuartmorgan** [comment]
Yes, XCUITest allows interacting with items on the home screen. See https://stackoverflow.com/questions/63901807/is-there-a-way-to-test-quick-actions-using-xcuitest for instance.

**Comment by olivierbrand** [comment]
> Yes, XCUITest allows interacting with items on the home screen. See https://stackoverflow.com/questions/63901807/is-there-a-way-to-test-quick-actions-using-xcuitest for instance.

Ahhh!! I thought about a Flutter UI test and was wondering how that would be possible, I can create a XCUITest

**Pull request closed without merging**
