### PR TITLE
remove unnecessary new from samples

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by mit-mit** [comment]
Analysis issues around constructor order are also showing up in head, and look related to a Dart roll, not this PR.

**Comment by mit-mit** [comment]
LGTM, but let's get the CI job working in head before we merge this

**Comment by mit-mit** [comment]
cc @cbracken is someone looking at the CI issue?

**Comment by a14n** [comment]
I'm fixing the CI issues.

**Comment by a14n** [comment]
As the build failures are now the same as in master (and as this PR only touch READMEs and docs) I'm tempted to merge this PR.

WDYT?

**Comment by mit-mit** [comment]
@cbracken can we land this?

**Comment by mit-mit** [comment]
Merging as CI is passing now

**Comment by mit-mit** [comment]
@a14n looks like the CI job failed after the merge; does this look related to your changes?
https://cirrus-ci.com/build/6241182061428736

**Comment by a14n** [comment]
I don't think it's related to my PR (only README and comments had been changed).

**Pull request merged**
