### PR TITLE
Move various first-party plugins into this repo

### PR DESCRIPTION
**Pull request by goderbauer**
* image_picker
* firebase_analytics
* firebase_storage
* google_sign_in
* firebase_auth
* firebase_database

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
LGTM

**Comment by Hixie** [comment]
LGTM

**Comment by eseidelGoogle** [comment]
I support this!  But I'm also curious to know why this was done? :)  Presumably there are no limitations to having plugins not in this repo, right?

**Comment by goderbauer** [comment]
Plugins can live anywhere. We just wanted to have all the first-party plugins (maintained by the flutter team) in one place to make it easier to adapt them to changes. If the plugin system changes, this is the one place where you need to update everything (instead of hunting down all relevant repositories).

**Pull request merged**
