### PR TITLE
[camera] Move camera operations to background thread

### PR DESCRIPTION
**Pull request by mehmetf**
- Move camera operations to background thread whenever possible.
- Add an example for doing image stream processing to the sample app.

### CODE REVIEW

**Comment by mehmetf** [comment]
@bparrishMines please review, thanks!

**Comment by mehmetf** [comment]
@bparrishMines Please review so I can merge this on Friday. Since there are multiple PRs in flight for camera, it is best to focus and get these out as soon as possible. Otherwise, the branches will get a bit unwieldy. 

I am going to work on QR integration next. Most likely will include a refactor of startImageStream() so that it accepts a series of processors.

**Comment by mehmetf** [comment]
Closing this PR. We will be forking this plugin internally. Hopefully we can merge changes back when we have more bandwidth for reviews.

**Comment by PerLycke** [comment]
@mehmetf That last comment from you, what does it mean? Moving camera operations to background thread sounds like a great improvement for us who streams images.

**Comment by mehmetf** [comment]
@PerLycke  Yeah it would be.

We are working on performance improvements to Camera plugin in a private forked repo. We will share it with the plugins team when it is ready.

**Pull request closed without merging**
