### PR TITLE
Disposed state not to show an ad when it loaded after being disposed

### PR DESCRIPTION
**Pull request by VolodymyrLykhonis**
It seems that if one calls to load and show and then dispose, Ad may still show up on the screen. I think there is a state issue when an ad is disposed, but once it's loaded it would still call show.

### CODE REVIEW

**Comment by HansMuller** [comment]
Thank you for the contribution!

It looks like this problem can be reproduced in the example by just tapping the show and remove banner buttons before the banner actually shows up.

I'm a little swamped at the moment, will try and review this fix soon.

**Comment by VolodymyrLykhonis** [comment]
@HansMuller I am not sure if I fixed it actually, I also see calling dispose does not remove BannerAd anymore (0.2.0 version, before it worked on 0.0.1 I think or around).

I will have sometime tonight and later next week, will try to check that too.

**Comment by HansMuller** [comment]
Thanks for the help!

**Comment by Hixie** [comment]
@HansMuller any chance you can review this or pass this to someone else? Thanks!

**Comment by VolodymyrLykhonis** [comment]
@Hixie @HansMuller I may need to revisit this. I think the issue still persists. I can see that my mobile ad does not get removed once I call dispose on it. Sorry for delay in response on this PR.

**Comment by Hixie** [comment]
@VolodymyrLykhonis I'm going to close this PR since you're not waiting for review right now, but please don't hesitate to reopen it, or submit a new one, once you are ready for review. Thanks!

**Pull request closed without merging**
