### PR TITLE
[webview_flutter] Add unimplemented features to the web version.

### PR DESCRIPTION
**Pull request by FlafyDev**
- <b>Adds support for Javascript channels and raw evaluation of Javascript for the web.</b>
The methods that were implemented in this PR are the following:
`evaluateJavascript`, `runJavascript`, and `runJavascriptReturningResult`
These only work when setting the content with `loadHtmlString` because of security reasons browsers have with iframes.
The methods will also not work with `loadRequest`, because it can load things other than HTML and I don't know how to detect whether it is HTML or not (The HTML needs to be preprocessed.)

* <b>Fixes the unreliable encoding of the data in `loadRequest`.</b>
`loadHtmlString` also had the unreliable encoding, but it's been changed and now doesn't have any encoding.
The new encoding is taken from [WebViewX](https://github.com/adrianflutur/webviewx/blob/4e625e8234ebcabbdf731815810d934a697388a9/lib/src/utils/html_utils.dart#L92).

### Tests added
- `testWidgets('loadHtml', ...)` - Tests the functionality of `loadHtmlString`. This test doesn't pass without solving the issue linked above.
- `testWidgets('JavascriptChannel', ...)` - Tests the communication between Flutter and the Webview with Javascript channels and raw Javascript evaluation.

## Technical Details
<details>
  <summary>Technical Details</summary>

The communication between the IFrame's HTML and the global scope is done by preprocessing the HTML to add a script element to expose the IFrame's Window object to the global scope. With the Window object of the IFrame's HTML you can evaluate raw Javascript.
Preprocessing the HTML also handles the Javascript channels, which is why you can't add/remove them after loading the HTML.

The preprocessing of the HTML creates the necessary elements ("<!DOCTYPE html>", "html", "head", "body") in case they aren't present. It also creates a script element to expose the Window object and handle Javascript channels.

So for example, `<div>Hello, world</div>` will turn into this after the preprocessing:
```html
<!DOCTYPE html>
<html>
  <head>
    <script>
      parent.webview0_getWindow(window);
      window.Echo = { postMessage: (message) => parent.webview0_channel("Echo", message) };
    </script>
  </head>
  <body>
    <div>Hello, world</div>
  </body>
</html>
```

</details>

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by FlafyDev** [comment]
Why do the tests fail? I don't understand the output.

**Comment by FlafyDev** [comment]
Where are these tests located at? I don't see them in `webview_flutter_web/example/integration_test/webview_flutter_test.dart ` and the tests there all pass

**Comment by balvinderz** [comment]
https://github.com/FlafyDev/plugins/blob/98ce7a8e53b1ee73666eafbfd2219371ee8db16e/packages/webview_flutter/webview_flutter_web/test/webview_flutter_web_test.dart#L57
https://github.com/FlafyDev/plugins/blob/98ce7a8e53b1ee73666eafbfd2219371ee8db16e/packages/webview_flutter/webview_flutter_web/test/webview_flutter_web_test.dart#L89

**Comment by FlafyDev** [comment]
> Thanks for the submission! Please split this into two separate PR; this is doing two very different things:
> 
>     * Fixing a bug, which would would definitely accept a high-quality PR for
> 
>     * Adding a (very) partial implementation of a feature in a way that may have very surprising side effects for people, which needs discussion and evaluation to decide if it's something we would move forward with.

I agree, this should be 2 different PRs. I'll revert the bug fix and make a new PR for it.

**Comment by stuartmorgan** [comment]
Based on the comments above, I'm going to close this, as it's not an implementation we would move forward with. If you are interesting in supporting message posting in general, using an approach like the one described in @ditman's comment above, the next step would be a [design document](https://docs.flutter.dev/resources/design-docs), which could be posted for discussion in https://github.com/flutter/flutter/issues/101758 once drafted. Thanks!

**Pull request closed without merging**
