### PR TITLE
iOS APNS Fix

### PR DESCRIPTION
**Pull request by polbatllo**
Fix for APNS not being correctly registered, which makes notifications fail when uninstalling and re-installing the application.

### CODE REVIEW

**Comment by polbatllo** [comment]
I signed it!

**Comment by alibitek** [comment]
Travis fails due to a problem with formatting https://travis-ci.org/flutter/plugins/jobs/320127067#L672

You can run the following to fix it and commit the changes:
```
pub global activate flutter_plugin_tools
pub global run flutter_plugin_tools format --plugins firebase_messaging
pub global run flutter_plugin_tools analyze --plugins firebase_messaging
pub global run flutter_plugin_tools test --plugins firebase_messaging
```

**Comment by mit-mit** [comment]
@polbatllo have you had a chance to look at the formatting issues?

**Comment by polbatllo** [comment]
There you go :) Sorry for the delay, I've been on holidays

**Comment by mit-mit** [comment]
cc @kroikie @collinjackson for review

**Pull request merged**
