### PR TITLE
Set iOS deployment target to 8.0, fixes compilation errors

### PR DESCRIPTION
**Pull request by pulyaevskiy**
Fixes https://github.com/flutter/flutter/issues/21363.

### CODE REVIEW

**Comment by ahmedb** [comment]
Just a curiosity question: Why is the deployment target being set so low? iOS 6.0 is very, very old and the user base right now is very low ( https://data.apteligent.com/ios/ ). 

However, my major concern right now is that using such a low deployment target may prevent us from adopting modern APIs and development practices. Apple deprecates so many APIs between major releases that we may also be at risk of using something they are no longer allowing to be used in apps.

**Comment by pulyaevskiy** [comment]
Short answer: I used what is already set in cloud_firestore plugin.

Long answer: I’m not too familiar with how pods resolve this thing. :) 

It looks like without it xcode thinks it supports 5.0 and fails to compile. Note that per Firebase dev answer here https://stackoverflow.com/questions/31076786/error-while-compiling-firebase-based-project-in-objective-c 6.0 is the lowest supported by the sdks.

When I run pod update it prints in the end something like “setting deployment target to 8.0”, do this setting probably works more like minimum supported target?

I’m just thinking out loud though and someone with more experience should weigh in.

Nevertheless this fixes the issue at least.

**Comment by pulyaevskiy** [comment]
@ahmedb 

From this page in official docs: https://guides.cocoapods.org/syntax/podspec.html#deployment_target

> The minimum deployment targets of the supported platforms.

So I guess it does work as `>=`.

**Comment by ahmedb** [comment]
Hi @pulyaevskiy, 

Thank you for your notes. I hope someone else can chime in too.

From my personal experience (iOS dev since 2009, former iOS instructor, Cocoapods user since 2013), `deployment_target` is meant to set the deployment target for the iOS framework generated by the Pod. The deployment target setting in XCode sets the minimum system version the framework can run on, and limits the available APIs to only those available between that minimum setting and the latest version of iOS. 

In other words, only allow compilation for APIs that are available on all iOS SDK versions from 5.0 up through 12.0. This excludes all APIs that were introduced after iOS 5.0, as well as all APIs that were deprecated since iOS 5.0 was initially released.

When I was looking at the `Runner` project Flutter generates, I noticed its deployment target is set to `8.0` . Although I personally think this is also too low, I think it would be a good experiment to see if setting the deployment target to `8.0` has the same result as your changes from setting the version to `6.0` .

Unless there is a bug, Cocoapods should print out `setting deployment target to 6.0` if the podfile is configured correctly. There are two quick experiments I think might be good to try out to see what is happening.

1. Manually specify the the platform is `iOS` to see if that sets the target correctly (The `platform` line for most podfiles look like this: `platform :ios, '9.0'`)
2. Set the deployment target to 11.0 to see if it that prints out `setting deployment target to 11.0`. It may be the case that Cocoapods does not support iOS 6.0 .

This may be of some help as well: https://github.com/CocoaPods/CocoaPods/issues/7314#issuecomment-356192161

One last comment, Apple sent shockwaves through the iOS community when they released iOS7 and then again when they released Swift with iOS8. iOS7 ushered in the modern iOS UI, and Swift greatly changed the development workflow for iOS (some may say the dust still hasn't settled from either yet.)

Thanks,
Ahmed

**Comment by pulyaevskiy** [comment]
Thanks for thorough explanation! This is really helpful.

As a side note, It'd be ok with me to change it to as high a number as makes sense to people more experienced in iOS development.

But, I also think that changing it in just one Firebase plugin of many won't make a big difference. To address the "deployment target" issue we should probably update all of them at once.

I created this PR to address a different blocking issue - adding `cloud_functions` to an existing project completely breaks it, it just won't compile otherwise. I'd probably prefer to keep it small so that it can be merged sooner and unblock people's work.

That said, I do see value in your suggestions, however my expertise is simply not enough to tackle such a project. I can only encourage you submit a separate PR with updates to deployment targets across all Firebase plugins. This would at least facilitate discussion with the Flutter team and help to resolve it sooner.

**Comment by pulyaevskiy** [comment]
Also a friendly ping to @kroikie for a chance to get this reviewed. :)

**Comment by ahmedb** [comment]
Thanks @pulyaevskiy . Sounds like a good plan.

**Comment by kmorkos** [comment]
Flutter only supports iOS 8.0 and above so there would be no point in setting the deployment target to anything below 8.0: https://flutter.io/ios-release/#review-xcode-project-settings

**Comment by Coeur** [comment]
@pulyaevskiy, CocoaPods together with a line of code in Swift anywhere (in your app or in a dependency) will mechanically require framework support (or the newer CocoaPods 1.5.x with Swift static lib support) and iOS 8+ support. So in order to have the older targets iOS 7 (or iOS 6) supported, one prerequisite would be to have a pure Objective-C app (including all your pods). That's not a popular audience; it's better to encourage Swift+CocoaPods compatibility and have everybody say goodbye to iOS 7 or older.

The next big upcoming goodbye will be 32 bits apps (both on iOS and macOS).

**Comment by pulyaevskiy** [comment]
Just pushed a fix for null pointer error when callable function fails with exception.

Also friendly reminder for @kroikie . Would be nice to get this merged and remove dependency override finally. :)

**Comment by beardo01** [comment]
I've stumbled onto this error too. Could we please get this pull request merged @kroikie?

**Comment by radvansky-tomas** [comment]
dispatch_queue_t callbackQueue;

This error is still present: https://github.com/flutter/flutter/issues/21363

**Comment by beardo01** [comment]
> dispatch_queue_t callbackQueue;
> 
> This error is still present: [flutter/flutter#21363](https://github.com/flutter/flutter/issues/21363)

Does using my above recommendation fix that for you?

**Comment by radvansky-tomas** [comment]
Yes if I manually go to cloud functions / firestore plugin podspec and change deployment target to 8.0 and reinstall pods it works.

ie. I still dont understand why this is not by default set to at least 8.0

**Pull request merged**
