### PR TITLE
Added Firestore's equivalent to RDB's FirebaseList and AnimatedFirebaseList

### PR DESCRIPTION
**Pull request by gildaswise**
The only thing that's left is making the unit tests working, I would like some help with that as I couldn't make them work. Tried following the ones already defined in `cloud_firestore_test` and `firebase_list_test` but no success.

Resolving issue [#17332](https://github.com/flutter/flutter/issues/17332).

### CODE REVIEW

**Comment by gildaswise** [comment]
I signed it!

**Comment by gildaswise** [comment]
Had to add `?` to `DocumentSnapshot`'s `documentID` getter, it was returning an exception on the tests.

```dart
/// Returns the ID of the snapshot's document
String get documentID => _path?.split('/')?.last;
```

Also, removed `new` keywords from the example and changed `MessageList` to the new `FirestoreAnimatedList`.

Is this ready for review as the checks say or should I add anything else, @kroikie?

**Comment by kroikie** [comment]
@gildaswise Thanks for this PR, however we are trying to focus on getting these plugins functionally complete before adding UI widgets. We would also likely make those UI widgets in a separate repo. I'll close this one, look out for when we start work on the UI widgets.

**Comment by gildaswise** [comment]
@kroikie Would be okay if I released this as a separate Dart plugin depending on cloud_firestore?

**Comment by kroikie** [comment]
@gildaswise Sure, that would be cool however note that the cloud_firestore plugin is not yet 1.0.0 so it may change so if you are ok with a bit of change then go for it.

**Comment by Elgeor** [comment]
> @kroikie Would be okay if I released this as a separate Dart plugin depending on cloud_firestore?

Can you please mention here name of this plugin after release?

**Comment by gildaswise** [comment]
@Elgeor No problem! It'll be `firestore_ui` and I'll release it in a few hours

**Comment by gildaswise** [comment]
I actually got a lot busy and more than a few hours have passed, but finally `firestore_ui` is available as a package! You can see it on pub [here](https://pub.dartlang.org/packages/firestore_ui)!

@Elgeor @branflake2267 @kroikie

**Pull request closed without merging**
