### PR TITLE
[video_player]bugfix:url filename null

### PR DESCRIPTION
**Pull request by tonyzzp**
If the url looks like  http://video.com/?id=12345, it will crash.

### CODE REVIEW

**Comment by tonyzzp** [comment]
I signed it!

**Comment by Hixie** [comment]
The whole approach of this function (including from before your PR, your patch doesn't change this) seems quite bogus... we shouldn't be dispatching based on the filename, we should be contacting the server and dispatching based on the returned headers.

**Comment by cbenhagen** [comment]
@tonyzzp thank you for your contribution! Unfortunately the structure of the plugin has changed lately to support implementations on more platforms. Mainly the plugin was moved to a new subdirectory and now uses a common platform interface. Adapting your PR to the new structure should be straight forward. If you have questions please ask!

Please also make sure to include tests for the new functionality. Dispatching based on the returned headers indeed sounds like a better way to handle this. Do you have time to work on this?

**Comment by Hixie** [comment]
The right fix here is to not derive things from the filename at all, as noted above.
I'm going to close this PR since it is not the right approach for the fix.

**Pull request closed without merging**
