### PR TITLE
`[camera]` switch camera while recording video

### PR DESCRIPTION
**Pull request by BradenBagby**
**Fixes:** 

Packages/camera/camera and Packages/camera/camera_platform_interface
-  Allows camera to be switched while recording a video with
   `cameraController.setDescriptionWhileRecording(newDescription)`
as requested here: https://github.com/flutter/flutter/issues/82467

**Missing:**
- Tests
- Switch camera from front to back on Android can cause quality decrease
- Switch camera on Android drops audio/video frames during switch
- Packages in pubspec.yaml still point to old versions

**Info:** 
iOS:
iOS switch camera was easy to implement. To create a seamless transition, I separated the capture session into two sessions, one for audio and one for video. When user is recording and wishes to switch the camera, the video session is reconfigured to the new camera.

Android:
Android was more complicated to implement because the MediaRecorder class does not allow setting recording orientation hint after it is started. Which needs to happen based on the new camera, or switched video is upside down. Because of this, a video recording is routed through a surfaceTexture that is modified by OpenGL to set the frame's correct rotation. An encoder picks up the modified frame and writes it to a muxer which writes it to a file. The audio waits for the first video frame to come through, then goes straight through an encoder into the muxer into the file.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@BradenBagby Are you still planning on completing this PR?

**Comment by BradenBagby** [comment]
> @BradenBagby Are you still planning on completing this PR?

I definitely plan on improving the Android implementation at some point in the future. Not sure when I will have time to write tests. I was hoping If I put this out there in its almost complete state someone might help finish it. Being able to switch cameras while recording is a major needed feature in a modern camera app

**Comment by stuartmorgan** [comment]
Since this is marked as a draft and hasn't been updated in several months I'm going to close it to clean out our review queue. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

**Comment by aytunch** [comment]
Hi @BradenBagby 
Do you have any plans to continue with this awesome PR?
Thanks.

**Comment by BradenBagby** [comment]
> Hi @BradenBagby Do you have any plans to continue with this awesome PR? Thanks.

At some point I plan to come back to it. I have it working enough for what I need right now and have not had time to really dedicate to a complete PR

**Comment by kareldb** [comment]
@BradenBagby Hi,
Is this PR stable enough to use in production?

Thanks!

**Comment by BradenBagby** [comment]
> @BradenBagby Hi, Is this PR stable enough to use in production?
> 
> Thanks!

This branch is stable and I am working on an official/complete PR based off of it
https://github.com/BradenBagby/plugins/tree/feature/switch-camera

**Comment by aytunch** [comment]
Can't wait for this to be merged in to Flutter. Thanks for your efforts @BradenBagby

**Pull request closed without merging**
