### PR TITLE
[camera] fix video recording crash on iOS

### PR DESCRIPTION
**Pull request by EkilDeew**
## Description

When capturing video in iOS after a few seconds the app crashes. The error message is `A pixel buffer cannot be appended when readyForMoreMediaData is NO`
This fixes the crash.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by EkilDeew** [comment]
The tests checks are not failing because of this PR. All the [camera] tests from others PR are also failing..

**Comment by bparrishMines** [comment]
Hi @EkilDeew, which iphone are you seeing this error on. I wasn't able to reproduce it with the `iPhone X` or `iphone 6s`.

Also: 
Is it crashing with the latest version of the plugin?
Is audio enable?

**Comment by EkilDeew** [comment]
I'm seeing this on a iPhone XS running iOS 13.2.
Audio is enabled and its crashing with the version 0.5.6+3 which I have. I haven't yet tested the latest version.

**Comment by mvanbeusekom** [comment]
Closing this PR as the issue can no longer be reproduced in the latest version of the camera plugin.

**Pull request closed without merging**
