### PR TITLE
[image_picker] ios: copy all meta data from the original image.

### PR DESCRIPTION
**Pull request by cyanglaz**
## Description

Follow up https://github.com/flutter/plugins/pull/1586. Copying over all the metadata, including GPS, orientation and more.

Note that because orientation is copied, we have to revert the orientation that iOS has done on the picked image to make the image show up in a correct way on the phone.

## Related Issues

flutter/flutter#31751

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by cyanglaz** [comment]
@ko2ic Do you mind to take a look at this as well?

**Comment by ko2ic** [comment]
@cyanglaz I was able to confirm on real devices that the correct value was obtained also for GPS and so on.
Thank you very much for driving this problem and I could learn a lot.

**Comment by cyanglaz** [comment]
@ko2ic Great! Thanks. will merge this in today. The only problem left now is gif and we might have to come up a way to either support scaling gifs or fail properly if the scaling parameters are passed.

**Comment by mikron123** [comment]
iOS still rotates the picked image 90 degrees? Am I supposed to see the change using the latest Flutter SDK?

**Pull request merged**
