### PR TITLE
Improve image_picker android dependencies

### PR DESCRIPTION
**Pull request by sir-boformer**
Fixes https://github.com/flutter/flutter/issues/20482

> image_picker only depends on android.support.v4.content.FileProvider and android.support.v4.app.ActivityCompat. Both are included in the utils package.
> 
> The full appcompat is not needed.

I'm not sure why the old build gradle used `api` instead of `implementation` for the dependency. `api` is not required, so I fixed that as well.

### CODE REVIEW

**Comment by gerryhigh** [comment]
See also this PR https://github.com/flutter/plugins/pull/712 which I'm waiting for it to be merged

**Comment by sir-boformer** [comment]
@goderbauer Done.

While we are at it, can you take a look at https://github.com/flutter/plugins/pull/716?

**Comment by sir-boformer** [comment]
I think the analyzer issues are now resolved? I bumped the version number again because 0.4.7 was already taken

**Comment by goderbauer** [comment]
Can you also update the version in the pubspec.yaml?

**Comment by sir-boformer** [comment]
done

**Comment by goderbauer** [comment]
This is live on pub now.

**Comment by slightfoot** [comment]
@goderbauer we started getting issues with this today. Although this might seem a small change but its not a revision change. Because of the dependency change it should at least be a minor version change. I believe that's in the semver recommendations. Either way, it breaks a lot of builds that use `image_picker: "^0.4.6"` caret restriction.

Currently any 3rd party library, firebase/google or other that depend on play-services currently will break. All of the play service libraries depend on `play-services-basement`. Which in it's latest version `com.google.android.gms:play-services-basement:15.0.1` depends on `com.android.support:support-v4:26.1.0`.

So for the moment we're building against `image_picker` `0.4.7`.

https://mvnrepository.com/artifact/com.google.android.gms/play-services-basement/15.0.1

**Comment by sir-boformer** [comment]
@slightfoot To fix this, add this to your build.gradle:

```gradle
dependencies {
    ...
    implementation 'com.android.support:support-v4:27.1.1'
}
```

@goderbauer The dependency change introduced by this PR caused issues for quite a few people (at least 2 reports today. I also experienced issues when I added Firebase to my app a few days ago, because Firebase ships with an old version of the support library.

To fix this, one must explicitly add the full support library as a dependency.

Maybe it would be better to add the full support library dependency again? It is technically not required for image_picker (and increases the APK size by 1MB), but makes it easier to use for people who use Firebase or other outdated libraries.

**Comment by goderbauer** [comment]
@sir-boformer For now we should probably change the dependency back. Do you want to send a PR?

**Comment by l-k22** [comment]
I'm having this issue trying to using the current package of image_picker

**Pull request merged**
