### PR TITLE
[webview_flutter] Support loading data directly in WebView via loadData and loadDataBase64

### PR DESCRIPTION
**Pull request by philip-peterson**
## Description

This PR adds support for loading data directly via the underlying OS's WebView API if possible.

## Related Issues

* Fixes flutter/flutter#32827 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by philip-peterson** [comment]
@googlebot I signed it!

**Comment by ndusart** [comment]
Is there a possibility that this PR can be merged anytime soon ?
From the CI, it seems some incompatibilities with dependencies versions. Could this be fixed with a rebase ?

**Comment by philip-peterson** [comment]
I never got this feature working unfortunately, and since I'm not writing code for the Flutter ecosystem anymore, this PR is up for grabs to whoever can work on it.

**Comment by stuartmorgan** [comment]
Thanks for the contribution! It sounds from the above like there are no plans to complete this PR, so I'm going to close it. If anyone is interested in moving forward with it, please fork it and submit a new, complete PR.

**Pull request closed without merging**
