### PR TITLE
[shared_preferences] Allow to specify the suiteName for NSUserDefaults

### PR DESCRIPTION
**Pull request by gaetschwartz**
## Description

This PR allows to specify a `suiteName` when creating getting an instance of `NSUserDefaults` in `MethodChannelSharedPreferencesStore` on iOS. This is pretty much needed if the user wants its app extensions to be able to access the `NSUserDefaults` saved by Flutter. See [Apple documentation](https://developer.apple.com/documentation/foundation/nsuserdefaults/1409957-initwithsuitename?language=objc).

## Related Issues

https://github.com/flutter/flutter/issues/64739

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Blaxou** [comment]
Im not sure if this should be a 0.5.X or 0.5.8+X ? Is it a big enough change to be 0.5.X ?

**Comment by Blaxou** [comment]
@stuartmorgan Sorry for the mention but I saw you recently worked on shared_prferences, would it be possible to review this PR ? It hopefully is all good but it's the first time I contribue here so I might have done mistakes.

**Comment by jimmyrogue** [comment]
@Blaxou  fix the conflicts plz. I need this feature too

**Comment by Blaxou** [comment]
> @Blaxou fix the conflicts plz. I need this feature too

I''m waiting for someone to review it and as soon as it is I will resolve the conflicts, but this PR doesn't seem to get enough attention to get reviewed.

**Comment by stuartmorgan** [comment]
@Blaxou I didn't see your earlier message, but I'm not a maintainer of the mobile `shared_preferences` plugin.

I recommend reading https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process; note in particular that reviews are prioritized by issue priority, so not filling an issue describing this proposal is likely why it hasn't gotten attention.

**Comment by Blaxou** [comment]
@stuartmorgan Oh you are right I completely forgot about this part. I just filed an [issue](https://github.com/flutter/flutter/issues/64739) on the main repo !

@jimmyrogue I posted the issue on the main repo, feel free to react to it so that it gets review faster ! https://github.com/flutter/flutter/issues/64739

**Comment by makepanic** [comment]
How would a user be able to set the `suiteName` with the documented methods?

Am I understanding it correctly that one can't use `await SharedPreferences.getInstance()` but has to manually initialize a `MethodChannelSharedPreferencesStore` instance?

**Comment by gaetschwartz** [comment]
> How would a user be able to set the `suiteName` with the documented methods?
> 
> Am I understanding it correctly that one can't use `await SharedPreferences.getInstance()` but has to manually initialize a `MethodChannelSharedPreferencesStore` instance?

```dart
 SharedPreferencesStorePlatform.instance = MethodChannelSharedPreferencesStore(suiteName: 'mySuiteName');
await SharedPreferences.getInstance(); // Always now returns the right instance with suite name specified
```

**Comment by walsha2** [comment]
hi @gaetschwartz! Do we know the status of this MR and getting it officially merged into `shared_preferences` ? 

Seems like this issue has stagnated since April?

**Comment by stuartmorgan** [comment]
Since this is marked as a draft and hasn't been touched in a few months I'm going to close it to clean out our review queue. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

**Pull request closed without merging**
