### PR TITLE
Ignore unnecessary_import in legacy analysis options

### PR DESCRIPTION
**Pull request by srawlins**
This mirrors the change to analysis_options.yaml in https://github.com/flutter/plugins/commit/642a4831e65190011f18180432cee1f03967b2cf.

This change is needed in order to land the new unnecessary_import Hint. There are many violations of this new Hint. If we do not ignore them, the flutter roll breaks.

Related to flutter/flutter#74381

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by srawlins** [comment]
Note on "analyze CHANNEL:stable" CI:

```
warning - analysis_options.yaml:1:10 - Warning in the included options file /tmp/cirrus-ci-build/analysis_options_legacy.yaml(428..445): 'unnecessary_import' isn't a recognized error code. - included_file_warning
warning - analysis_options.yaml:1:10 - Warning in the included options file /tmp/cirrus-ci-build/analysis_options_legacy.yaml(428..445): 'unnecessary_import' isn't a recognized error code. - included_file_warning
```

The error code will be recognized when it lands.

**Comment by stuartmorgan** [comment]
> The error code will be recognized when it lands.

How will landing a new option change the behavior on *stable*?

This can't land with analyze being red; it'll close the tree. It's not clear to me what the path for landing this is.

**Comment by srawlins** [comment]
The error code does exist in Dart now, as of https://github.com/dart-lang/sdk/commit/2bcc415510abf73e8d8b993625b5c3a0f9c8476d#diff-7788abdb7b889d06cb0bd29803f0f11dda64c2cf17c791c54968eabea51607dd.

Do we just need to wait until the code gets through to Flutter stable?

**Comment by stuartmorgan** [comment]
If you want to add an ignore but doing so is an error until it's on stable, then yes.

Usually changes like this have been made by fixing the violations, not ignoring them, as that can be done in advance.

**Comment by srawlins** [comment]
Sorry for the delay. Now that stable has bumped to know about the `unnecessary_import` code, ignoring it in analysis_options is legal.

> Usually changes like this have been made by fixing the violations

Yes. This is a case where there are simply too many to clean up ahead of time, and new ones are added faster than I can cycle through and clean them up. Ignoring them allows the check to land.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Pull request merged**
