### PR TITLE
Cancel the Firebase stream subscriptions.

### PR DESCRIPTION
**Pull request by branflake2267**
setState is getting called after the the firebase list is disposed, which is inducing a memory leak. To fix this, list.clear() is used to clear the subscriptions to the firebase streams in the list.

### CODE REVIEW

**Comment by branflake2267** [comment]
This looks related. https://github.com/flutter/flutter/issues/12257

**Comment by mit-mit** [comment]
cc @kroikie

**Comment by branflake2267** [comment]
@kroikie if you need a test case let me know. 

If I built a test case I'd do this. I have a page with two tabs, each tab main scaffold body is an firebase animated list. If you build a page with tabs, the first tab being a firebase animated list and the second tab has an input that would change a property in an item in the list. If you swipe back in forth you create a few leaks to the listeners and then you can fire the exception if you try to modify a child in the list on the second tab.

**Comment by branflake2267** [comment]
Ping...

**Comment by eliezedeck** [comment]
Not sure, but this patch may have caused this bug: https://github.com/flutter/flutter/issues/13295

**Comment by branflake2267** [comment]
It looks like length is getting set, so I'm assuming a path with list.clear() is getting called that is calling the super clear() which sets the length of the list, which cannot happen. It may be easier to remove the unsupported assertion or add an override down stream.

**Pull request merged**
