### PR TITLE
[cloud_firestore] Update firebase-firestore to 18.2.0

### PR DESCRIPTION
**Pull request by jul1u5**
Update `firebase-firestore` dependency to `18.2.0`. Previously, using `setData` method on `DocumentReference` would result in a crash.

Resolves https://github.com/flutter/flutter/issues/28082

### CODE REVIEW

**Comment by ened** [comment]
@jul1u5 could you update the PR to cloud_firestore 18.1.0 & also bump the version / update changelog?

**Comment by ened** [comment]
@jul1u5 Is multidex *strictly* required? Seems like a parameter local to your project?

**Comment by ened** [comment]
@collinjackson @kroikie this seems like a good PR for you to review?

The firestore version bump is 17 -> 18, should the plugin then also make a major version bump (or minor, as it's still 0.x). So 0.9.7+2 -> 0.10.0 ?

**Comment by collinjackson** [comment]
If behavior changed, the version should increase, but since this isn't a breaking change (I think) and it's 0.x the increase should be minor.

**Pull request merged**
