### PR TITLE
[share] Update README.md

### PR DESCRIPTION
**Pull request by kagouda**
I just tried to update the links. The old links worked too but redirected to the current links. I just had the idea to put the current links directly.

https://pub.dartlang.org/packages/share to https://pub.dev/packages/share/

and
https://flutter.io/platform-plugins/ to https://flutter.dev/docs/development/packages-and-plugins/using-packages

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by cyanglaz — APPROVED** [review]
LGTM! Thanks

**Comment by cyanglaz** [comment]
@kagouda It looks like some build failed, you probably need to sync the PR with TOT.

**Comment by kagouda** [comment]
> @kagouda It looks like some build failed, you probably need to sync the PR with TOT.


Excuse me, how could I do that ?

**Comment by hamdikahloun** [comment]
Hi @kagouda 

```
git fetch upstream
git checkout patch-1
git merge upstream/master
git push -u origin patch-1
```
If you haven't added upstream :

```
cd plugins
git remote add upstream https://github.com/flutter/plugins.git
```
[Contributing to Flutter Plugins](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md)
[Syncing a fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)

**Comment by cyanglaz** [comment]
@kagouda Also, we'd like the pub page to be in sync with the latest changes in README, so please update the version of the plugin.

**Comment by kagouda** [comment]
@cyanglaz . Please it's ok now ?

**Review by hamdikahloun — CHANGES_REQUESTED** [review]
Please update CHANGELOG.md & pubspec.yaml.

**Comment by kagouda** [comment]
@hamdikahloun sorry why are you talking about CHANGELOG.md & pubspec.yaml? This is the readme file only I had modified .
How to update Changelog and pubspec ?

**Comment by cyanglaz** [comment]
@kagouda Generally, we want to keep the README update-to-date on pub. (https://pub.dev/packages/share)
And that's been done by publish a new version to pub. Thus the version update. 
Since it is a documentation change, it would be a patch version update ( so 0.6.5+4 -> 0.6.5+5); for CHANGELOG, you can just add an entry there and saying something like:
```
Update README with the new documentation urls. 
```

**Review by hamdikahloun — APPROVED** [review]
LGTM

**Pull request merged**
