### PR TITLE
[google_maps_flutter] Polylines, Map Tap, Map Long Tap added to Google Maps Flutter plugin

### PR DESCRIPTION
**Pull request by jan1za**
Google Maps Flutter plugin **feature** addition.

- Added polylines
- Added tap event listener
- Added long tap event listener
- Added tap my location listener
- Added tap my location button listener
- Added enable or disable my location button

Polylines have been added to both iOS and Android, however iOS lacks styles and patterns, the feature is not available in the iOS version of google maps.

Example application extended to include:
- Map UI example shows tap and long tap events.
- Additional page that shows how to use Polylines.

### CODE REVIEW

**Comment by awazgyawali** [comment]
Great, a PR was already present here https://github.com/flutter/plugins/pull/1049. Either way, I have added further supports like polygon and map tap. Whichever gets accepted, I will make sure it will blend in.

**Comment by hayahyts** [comment]
How do we use this?

**Comment by jan1za** [comment]
@awazgyawali either wait for this branch to be merged into the baseline or clone my master [repo](https://github.com/jan1za/plugins). 

Copy the packages/google_maps_flutter folder to the same level as your flutter app for example:

```
- workspace
 |_myflutterapp
   |_lib
   |_android
   |_ios
   |_pubspec.yaml
 |_google_maps_flutter
```

Then change your dependencies to point to this version and not the official version i.e. in your pubspec.yaml file change it to:

```
dev_dependencies:
  flutter_test:
    sdk: flutter

  google_maps_flutter:
    path: ../google_maps_flutter
```

Then follow the instructions on the google flutter [library](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter)

Checkout the example app to see how to use polylines and taps.

**Comment by hayahyts** [comment]
> @awazgyawali either wait for this branch to be merged into the baseline or clone my master [repo](https://github.com/jan1za/plugins).
> 
> Copy the packages/google_maps_flutter folder to the same level as your flutter app for example:
> 
> ```
> - workspace
>  |_myflutterapp
>    |_lib
>    |_android
>    |_ios
>    |_pubspec.yaml
>  |_google_maps_flutter
> ```
> Then change your dependencies to point to this version and not the official version i.e. in your pubspec.yaml file change it to:
> 
> ```
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 
>   google_maps_flutter:
>     path: ../google_maps_flutter
> ```
> Then follow the instructions on the google flutter [library](https://github.com/flutter/plugins/tree/master/packages/google_maps_flutter)
> 
> Checkout the example app to see how to use polylines and taps.

Thank you

**Comment by tolotrasamuel** [comment]
Why is this not merged yet ?

**Comment by jan1za** [comment]
Hi @nandymandy1 

Create a handler 

When the map is created add the long tapped and marker tapped handlers:
 void _onMapLongTapped(LatLng location) {
     print('tapped');
     // add place marker code here
}

// Add an event for the map created
void _onMapCreated(GoogleMapController controller) {
    setState(() {
      mapController = controller;
      mapController.onMapLongTapped.add(_onMapLongTapped);
      mapController.onMapTapped.add(_onMapTapped);
}     


Create your map widget, adding the event handler for map created:
 return GoogleMap(
      onMapCreated: _onMapCreated,
      ....

This should display the map and print a message each time a long press occurs
Now add the add marker feature

Call this method from the long tapped method to add the marker. (Don't forget to define Marker _myMarker)

Future<void> _addMyMarker(LatLng location) async {
    if (_myMarker != null) {
      mapController.updateMarker(
        _myMarker,
        MarkerOptions(
            position: LatLng(
          location.latitude,
          location.longitude,
        )),
      );
    } else {
      _myMarker = await mapController.addMarker(
        MarkerOptions(
          position: LatLng(
            location.latitude,
            location.longitude,
          ),
        ),
      );
    }
  }

**Comment by LatinaIsaac** [comment]
just waiting 4 this

**Comment by joaquinperaza** [comment]
iOS my location button not working could be because using this branch?

**Comment by jan1za** [comment]
@joaquinperaza I noticed that too. I need to debug why. I do not think it is due to a change I made, I have also just merged in the baseline code. Have you tested it using the master branch?

**Comment by joaquinperaza** [comment]
No, I will use flutter location to use a custom solution i don't like the default button also

**Comment by LatinaIsaac** [comment]
Bump!!

**Comment by wabir** [comment]
For when, please I am waiting for this solution since I have very important projects that require this functionality. Thank you! @googlebot

**Comment by joaquinperaza** [comment]
I am using the fork directly, you may try that way.

**Comment by joaquinperaza** [comment]
#1157 is the problem/solution but dont know if your pull request included it, i am still with the ios problem, still after manually tried moving the camera

**Comment by jan1za** [comment]
@joaquinperaza Thank you for the feedback, I have included some additional functionality like the ability to disable the my location button when my location is enabled. I have also merged in all the latest code from master

**Comment by stevenspiel** [comment]
@awazgyawali @jan1za Where is the polygon support you mentioned?

**Comment by jan1za** [comment]
@stevenspiel at the moment, I have just created polylines, @awazgyawali added polygon support to his [fork](https://github.com/awazgyawali/plugins).

**Comment by amam1212** [comment]
It's not work on my Android.

**Comment by jan1za** [comment]
@amam1212 what does not work? Please be a little more specific. Did you try the example? What version of Android,

**Comment by amam1212** [comment]
It works well on my iOS include real device 
but in Android, there are no any error in console log.
Everything seem to be work fine but it's not showing polyline.
I used Android Version 8.1 in emulator and 9.0 in a real device. 
I can't find your example, can you provide the link to me. Thanks a lot @jan1za 

this is my repo
https://github.com/amam1212/cmtransit

**Comment by jan1za** [comment]
@amam1212 the example is in the repository. It is in the example folder. The polylines do work on both Android and iOS. I am currently using it on both platforms.

**Comment by amam1212** [comment]
My Android is working now, I found the mistake on colour parameter in PolylineOption.
I did convert hex colour(string) to integer and the return value was wrong. But it can use in iOS.
Thank you so much @jan1za

**Comment by jan1za** [comment]
@amam1212 That's fantastic. Glad to hear it is sorted.

**Comment by awazgyawali** [comment]
The flutter team has changed the google maps heavily to adopt the widget based approach while creating a marker, as a result, there is a heavy merge conflict on this PR. 

As I already had a PR to cover polyline here at #1049. I have successfully changed the polyline functionality to a widget-based approach. But my PR lacks the ability of Map Tap and Map Long Tap.

If you want to use the polyline on widget based approach, you can use that PR. Details are on the description.

**Comment by MattL-NZ** [comment]
@jan1za Whats the latest on this? Are you going to be fixing the conflicting files so we can get this PR merged?

**Comment by jan1za** [comment]
@MattL-NZ I will fix it asap, its just been a little hectic of late.

**Comment by FaRedAhmed01** [comment]
thank you for this it working good but how to make route between to points when i use polyline it's drawing a straight line between points i want to draw route between points

**Comment by joaquinperaza** [comment]
I think you should implement a route creation method using google maps api for routes and and draw polylines with that data using this branch

**Comment by jan1za** [comment]
@MattL-NZ :) it's fixed. Thank you for your patience. I refactored my code, and now it works the same way as Markers. The changes are breaking changes. See the example code to see how to implement it.

**Comment by jan1za** [comment]
@iskakaushik @amirh I have refactored the code to work in the same way Marker does, please could you merge this pull request into master.

**Comment by iskakaushik** [comment]
Hi @jan1za , firstly, thanks for your contribution. That's a lot of features :-)

To make it easier for me to review could you break up your PR into smaller separate pull requests:

1. Long tap events.
2. Polylines: There's a PR that is pretty close to done. https://github.com/flutter/plugins/pull/1049, if you think it's missing some features, or if you do not agree with parts of it, could you please comment on that.
3. Tap events for maps merged yesterday: https://github.com/flutter/plugins/pull/985, so we might not need it.

Could you explain what the following features are?

- Added tap my location listener
- Added tap my location button listener
- Added enable or disable my location button

It might also make sense to do them as a different PR.

**Comment by jan1za** [comment]
@iskakaushik I will break it apart into multiple pull requests.

- Long tap events.
- Polylines: There's a PR that is pretty close to done. #1049, if you think it's missing some features, or if you do not agree with parts of it, could you please comment on that. ** cool **
- Tap events for maps merged yesterday: #985, so we might not need it. **I saw that, removed my version and merged with #985**

- Added tap my location listener ** Event when tapping on the my location blue dot**
- Added tap my location button listener ** Intercepts when someone taps on the my location button, this button shows your location, and centers the screen on your location. This feature just intercepts that, so that you can perform additional functionality, like so a popup etc**
- Added enable or disable my location button ** in my case I wanted to plot the users position on the screen, but I wanted my own button that shows the users position. Enabling my location, shows your location but also shows the my location button, I wanted to disable that and therefor add this feature**

**Comment by MattL-NZ** [comment]
@jan1za Where is the PR for the long tap events? Is that being merged into Google Maps Flutter?

**Comment by MattL-NZ** [comment]
Hi all

Does anyone know how to get the long taps working with Google Maps Flutter?

**Comment by mrzuliann** [comment]
I'm using mapbox on flutter with flutter_map package and need to add marker on map when tapped on map and then get marker lat and long to send to server. How get it?

**Pull request closed without merging**
