### PR TITLE
[video_player]fix playing local file get illegal duration occasionally on iOS

### PR DESCRIPTION
**Pull request by akindone**
This [commit](https://github.com/flutter/plugins/commit/3f940429d0e73e2cadfa8a3d487354e0e06f2206) update the `FLTCMTimeToMillis` function. This function may return 0 or TIME_UNSET. Before sending  initialized message to flutter, we should check duration to make sure it's not 0 or TIME_UNSET.
```
static inline int64_t FLTCMTimeToMillis(CMTime time) {
  // When CMTIME_IS_INDEFINITE return a value that matches TIME_UNSET from ExoPlayer2 on Android.
  // Fixes https://github.com/flutter/flutter/issues/48670
  if (CMTIME_IS_INDEFINITE(time)) return TIME_UNSET;
  if (time.timescale == 0) return 0;
  return time.value * 1000 / time.timescale;
}
```

*List which issues are fixed by this PR. You must list at least one issue.*
flutter/flutter#87334

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
> Before sending initialized message to flutter, we should check duration to make sure it's not 0 or TIME_UNSET.

Could you point to official docs (preferably) or other sources that explain why indefinite time is equivalent to uninitialized? Wouldn't, e.g., a livestream have indefinite time?

**Comment by akindone** [comment]
> > Before sending initialized message to flutter, we should check duration to make sure it's not 0 or TIME_UNSET.
> 
> Could you point to official docs (preferably) or other sources that explain why indefinite time is equivalent to uninitialized? Wouldn't, e.g., a livestream have indefinite time?

Sorry I did not consider this situation, I will check the document later

**Comment by akindone** [comment]
> > Before sending initialized message to flutter, we should check duration to make sure it's not 0 or TIME_UNSET.
> 
> Could you point to official docs (preferably) or other sources that explain why indefinite time is equivalent to uninitialized? Wouldn't, e.g., a livestream have indefinite time?

I search the official docs: [AVPlayerItem.duration](https://developer.apple.com/documentation/avfoundation/avplayeritem/1389386-duration)

> The value of this property will be reported as indefinite until the duration of the underlying asset has been loaded. There are two ways to ensure that the value of duration is accessed only after it becomes available:
>
> Wait until the status of the player item is AVPlayerItem.Status.readyToPlay.
>
> Register for key-value observation of the property, requesting the initial value. If the initial value is reported as indefinite,  the player item will notify you of the availability of its duration via key-value observing as soon as its value becomes known.
>
> Note
>
> The value of duration may remain indefinite for live streams.
 
Then I write a demo , you can see detail from [here](https://github.com/flutter/flutter/issues/87334#issuecomment-985156019). The demo print duration and status. we can see status is 1(AVPlayerItem.Status.readyToPlay) but duration is -9223372036854775807 which means checking the status is not enough. 

If it is not live stream and duration is not 0 or TIME_UNSET, then send the initialized event.
```
if ([path hasSuffix:@".m3u8"]){
    isTypeNormal = false;
}
```

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
