### PR TITLE
[camera] Fixed captured image stretching issue on some low end android devices

### PR DESCRIPTION
**Pull request by techievbv**
## Description

This PR fixes an issue where the captured image using the camera plugin comes out as stretched/inappropriate aspect ratio on some low end android devices.
I encountered this issue few weeks ago, with devices like Vivo, and redmi devices.

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by alexcohn** [comment]
I believe this change is important not only on low-end devices. The general rule of thumb is that the aspect ratio of capture and preview should match. 

Even if there is no stretching (which is a device bug), the user expects the captured picture to match the viewfinder. If the aspect ratios differ, the picture will either have extra unintended content, or crop out some content. Worse, there is no guarantee which case will happen for given resolutions (different devices can handle this differently).

Second, switch of aspect ratio often results in extra delay, lost focus, bad exposure compensation – even if the capture comes out formally correct.

**Comment by cyanglaz** [comment]
I'm going to close the PR because the CLA is not signed. Feel free to ping me when the CLA is signed and I'll re-open the PR. Or you can open a new PR after signing the CLA.

**Comment by techievbv** [comment]
@cyanglaz Hey I signed the CLA.
Could you please re-open the PR ?

**Comment by stuartmorgan** [comment]
The Android camera implementation just went through a major overhaul; is this PR still needed in the current implementation?

If so, this will need to be updated to resolve the conflicts with master, as well as have tests added per repository policy (see the link in the checklist), before it can be reviewed.

**Comment by stuartmorgan** [comment]
@techievbv You'll also need to follow the instructions in [the comment above](https://github.com/flutter/plugins/pull/2931#issuecomment-673411721) to confirm your CLA.

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
