### PR TITLE
[ci] Pin master in Cirrus

### PR DESCRIPTION
**Pull request by stuartmorgan**
This uses a pinned version from a file instead of `master` when checking out Flutter for `master` channel testing in Cirrus. Currently it's a static version, but this will be updated by an auto-roller.

This uses a version of `master` from several days ago to avoid the current tree breakage due to https://github.com/flutter/flutter/issues/96661

This will not affect LUCI tests; that will require a separate recipe change.

Part of https://github.com/flutter/flutter/issues/93811

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by gaaclarke — COMMENTED** [review]
Do we want to wait until we have an autoroller before we land this?

**Comment by stuartmorgan** [comment]
Well, we need the text file here for the autoroller to be set up. Normally I would have done it as:
1. Just add the text file
1. Get the autoroller set up and working
1. Make the other changes here

But right now the tree has been closed for a day already, and re-opening it requires a fix-forward in the engine that hasn't even been written yet. It needs to be written, reviewed, landed, and rolled into the framework before `master` will work for us again. Given that, landing everything with a static pinned version is strictly better, as it means we can re-open the tree now instead.

If it turns out that the autoroller takes longer to set up than `master` being fixed, then I can just temporarily revert part of the .cirrus.yaml file once `master` works.

**Review by gaaclarke — APPROVED** [review]
lgtm

**Comment by stuartmorgan** [comment]
Landing on red to re-open tree.

**Pull request merged**
