### PR TITLE
[url_launcher] Added a note to the README

### PR DESCRIPTION
**Pull request by kalkotekedar**
The action won't work on the simulator works on physical iOS device which was not mentioned here so it was added

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by mklim** [comment]
Thanks again for the contribution @kalkotekedar. It looks like this PR has been sitting for a little while since the last round of feedback, do you still have time to work on it? If not, let us know and one of the Flutter maintainers will be happy to shepherd it forward from here.

**Comment by mklim** [comment]
I've added the requested changes in the latest commit. Thanks again for the contribution @kalkotekedar!

**Comment by xni06** [comment]
Had this README been part of the documentation, I'd have saved myself a lot of time yesterday - please address the branch conflicts so that it can be merged and to save others the same pain - thanks.

@mklim @amirh

**Review by stuartmorgan — APPROVED** [review]
Thanks for the contribution! This looks like a straightforward change that just fell through the cracks. I've resolved the conflicts, and adjusted the wording slightly, and now it should be good to land once the tree is open.

We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

**Comment by stuartmorgan** [comment]
Landing with the red macOS run since that was a known issue with master for a day, and clearly this change can't break macOS so there's no risk of hidden test failures.

**Pull request merged**
