### PR TITLE
[connectivity] Clear networkCallback object as soon as stream is cancelled

### PR DESCRIPTION
**Pull request by ened**
## Description

Resolves a issue I noticed when 2 streams are quickly created in succession. 
The networkCallback object should be cleared as soon as possible.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by hamdikahloun** [comment]
@ened can you describe which exception does it fix? have you any logs ?

**Comment by ened** [comment]
@hamdikahloun:

```
E/EventChannel#plugins.flutter.io/connectivity_status(25620): Failed to close event stream
E/EventChannel#plugins.flutter.io/connectivity_status(25620): java.lang.IllegalArgumentException: NetworkCallback was not registered
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:52)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4235)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at io.flutter.plugins.connectivity.ConnectivityBroadcastReceiver.onCancel(ConnectivityBroadcastReceiver.java:53)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onCancel(EventChannel.java:201)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:169)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at android.os.Looper.loop(Looper.java:183)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/EventChannel#plugins.flutter.io/connectivity_status(25620): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following PlatformException was thrown while de-activating platform stream on channel
plugins.flutter.io/connectivity_status:
PlatformException(error, NetworkCallback was not registered, null)
When the exception was thrown, this was the stack:
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:572
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:161
<asynchronous suspension>
#2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:334
#3      EventChannel.receiveBroadcastStream.<anonymous closure>
package:flutter/…/services/platform_channel.dart:554
#4      EventChannel.receiveBroadcastStream.<anonymous closure>
package:flutter/…/services/platform_channel.dart:551
#24     ConnectivityCheck._awaitReconnect.<anonymous closure>
package:connect/services/connectivity_check.dart:56
(elided 32 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
The following PlatformException was thrown while de-activating platform stream on channel plugins.flutter.io/connectivity_status:
PlatformException(error, NetworkCallback was not registered, null)

When the exception was thrown, this was the stack
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:572
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:161
<asynchronous suspension>
#2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:334
#3      EventChannel.receiveBroadcastStream.<anonymous closure>
package:flutter/…/services/platform_channel.dart:554
...
════════════════════════════════════════════════════════════════════════════════
```

**Comment by ened** [comment]
@hamdikahloun @cyanglaz could we fast-track this one?

**Review by hamdikahloun — APPROVED** [review]
LGTM

**Pull request merged**
