### PR TITLE
[various] Import flutter_test for future compatibility

### PR DESCRIPTION
**Pull request by Hixie**
The service mocks are going to move from services.dart to flutter_test/.

See https://github.com/flutter/flutter/pull/76288

## Pre-launch Checklist

- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
Would you like me to also update the changelogs and so forth, or should I land this silently? (I am fine either way; I hadn't done those changes because I wanted to make sure the tests pass first, but now that I know they pass and it's been approved I can do those and land it without worrying about conflicts as I fix tests etc.)

**Comment by stuartmorgan** [comment]
I don't see a need to publish these changes; I doubt very much that people are running tests from pub-pulled packages rather than cloning. So silent SGTM.

**Comment by Hixie** [comment]
Roger. I've marked it to land when green. Thanks!

**Pull request merged**
