### PR TITLE
[video_player] : Flutter's video plugin can cause crashes after a closing a flutter vi…

### PR DESCRIPTION
**Pull request by shihchanghsiungsonos**
…ew on simulator model iPhone X or higher

## Description

The latest video player plugin changes weren't actually overriding the correct method signature.
Updated the override and verified that we are now getting disposed, and we don't crash on iPhone X running iOS 12.

## Related Issues

https://github.com/flutter/plugins/pull/2124

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by dannyvalentesonos** [comment]
@otopba @cyanglaz Is there a reason this hasn't been merged yet?

**Comment by otopba** [comment]
@dannyvalentesonos I'm not a part of the Google team. So, I think you can merge last master changes and just wait =(

**Comment by shihchanghsiungsonos** [comment]
Also check and see if we can have this on merged? Thanks!

**Comment by dannyvalentesonos** [comment]
@cyanglaz Can we consider this change please? The `onTextureUnregistered` signature was not correct and therefore wasn't getting called. The temporary disposal code in `handleMethodCall` can also be removed.

**Comment by Salakar** [comment]
Can confirm this is PR is valid; the correct signature is `- (void)onTextureUnregistered:(NSObject<FlutterTexture>*)texture;` as defined in `FlutterTexture.h`: https://github.com/flutter/engine/blob/be8839f59e1c2390815f5197dcb5be95018df335/shell/platform/darwin/common/framework/Headers/FlutterTexture.h#L31

**Review by Salakar — APPROVED** [review]

**Review by russellwheatley — APPROVED** [review]
LGTM

**Review by stuartmorgan — APPROVED** [review]

**Pull request merged**
