### PR TITLE
show AuthMessage On LocalAuth Import

### PR DESCRIPTION
**Pull request by kopianan**
AuthMessage can not be detected from LocalAuth Import. 
I have updated and export code line so AuthMessage shown ... 

Changes : 
`export 'package:local_auth_windows/types/auth_messages_windows.dart'
    show WindowsAuthMessages;
export 'package:local_auth_android/types/auth_messages_android.dart'
    show AndroidAuthMessages;
export 'package:local_auth_ios/types/auth_messages_ios.dart'
    show IOSAuthMessages;
export 'package:local_auth_platform_interface/types/auth_messages.dart';
`

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Thanks for the submission, but documenting the need for the imports for this use case rather than re-exporting was a deliberate choice. We generally prefer not to re-export from implementation packages as it forces breaking changes to cascade. It also makes it much harder to understand how to use unendorsed implementations.

(For future submissions, please be sure to follow the PR checklist rather than removing it, as it explains many required steps for PRs in this repository.)

**Comment by kopianan** [comment]
i got issue on authmessage , it is not show the class

AndroidAuthMessage, Ios, Windows

**Comment by stuartmorgan** [comment]
If the instructions in the readme aren't working for you, please file an issue with details and we can investigate.

**Comment by RaulUrtecho** [comment]
Was this issue fixed can we now import the `AndroidAuthMessages` and `IOSAuthMessages` without a problem?

**Comment by stuartmorgan** [comment]
@RaulUrtecho Please see my comment just above yours.

**Comment by RaulUrtecho** [comment]
Ok that's a no for me.

**Pull request closed without merging**
