### PR TITLE
Move plugin tools code

### PR DESCRIPTION
**Pull request by blasten**
Moves the files from plugin_tools over.

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
RSLGTM

**Comment by stuartmorgan** [comment]
I missed that this only moved `lib`. What about `test`?

**Comment by blasten** [comment]
Do we want to test it in addition to the plugin test code? I thought that after removing the public contract, and running it alongside the plugin tests is sufficient.  FWIW, similar to the device lab code used to run tests in the Flutter repo.

**Comment by stuartmorgan** [comment]
Do we re-run all the plugin tests for all script changes? If not, we have the potential to break something in the test code and then not notice for a while.

**Comment by blasten** [comment]
I wonder if it could be a good refactor of the scripts since this has happened in the past due to the incremental build logic in the scripts. It might worth to migrate that logic into  the GitHub action file patterns, which can be extended to cover this case. E.g build and test all the plugins if the plugin tool code changed. Any thoughts?

**Comment by stuartmorgan** [comment]
Yep, that seems like a good change.

I was thinking more about relying on that to catch failures though; imagine a change to the tools that, say, accidentally causes it to skip every plugin when deciding what tests to run (something I can imagine happening from a change like the ones made to support desktop, since it changed the evaluation logic to include determining which plugins support which platforms, and there could easily have been a bug there). The test run there would be totally green. But that regression would be easy to catch with at unit test.

Is there a good reason *not* to have unit tests for this code?

**Comment by blasten** [comment]
I can see that it’s important to have such test. 
The main reason I thought about is to move the conversation from this tool to the actual plugins, and in that way test the tool.

**Pull request merged**
