### PR TITLE
Adds a plugin for the Android AlarmManager

### PR DESCRIPTION
**Pull request by zanderso**

### CODE REVIEW

**Comment by mit-mit** [comment]
I tried to run this, but it's failing during compilation. Does this require a different engine?

```
mit-macbookpro2:example mit$ flutter run -d A
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                0.6s
Resolving dependencies...                             6.7s
Running 'gradlew assembleDebug'...
/Users/mit/tmp/android-alarm-manager/packages/android_alarm_manager/android/src/main/java/io/flutter/androidalarmmanager/AlarmService.java:87: error: method runFromBundle in class FlutterView cannot be applied to given types;
      flutterView.runFromBundle(appBundlePath, null, entrypoint, true);
                 ^
  required: String,String
  found: String,<null>,String,boolean
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.
```

**Comment by mit-mit** [comment]
Ah, looks like that is underway: https://github.com/flutter/flutter/pull/12692

**Comment by zanderso** [comment]
The engine roll landed. This should work now. PTAL.

**Comment by mit-mit** [comment]
Great! I can build and run now, but I don't see any output from the `print()` statements. Where am I supposed to see those? And should I run this in some special way?

**Comment by zanderso** [comment]
You don't have to run it any special way. 'flutter run' will work fine. The messages will be in the system log that you can see with 'logcat -d'.

**Comment by zanderso** [comment]
I should also note that the maximum frequency for alarms on my device is 1 minute, and on more recent versions on Android the timing is not guaranteed to be exact. So in order to see something print in the log, you might have to wait around for 2 - 3 minutes, depending on what your version of Android thinks about alarm frequencies.

**Comment by sethladd** [comment]
cc @demarco

**Comment by zanderso** [comment]
Friendly ping.

**Pull request merged**
