### PR TITLE
Fix analysis errors by declaring dependencies on other plugins

### PR DESCRIPTION
**Pull request by mit-mit**
Fixes https://github.com/flutter/flutter/issues/10528

### CODE REVIEW

**Comment by mit-mit** [comment]
@goderbauer why are we not seeing this in Travis?

**Comment by mit-mit** [comment]
Oh, wait, just re-read https://github.com/flutter/flutter/issues/10015 again -- is it only the example apps for these that have these dependencies, and not the plugins themselves?

**Comment by goderbauer** [comment]
It's only the example app that have these dependencies and they shouldn't be declared on the plugin itself. Please don't merge this.

We are not seeing any analyzer errors on Travis because on Travis we are using the analyzer server (via package:tuneup), which can properly deal with nested packages. The one-off analyzer command (as used by flutter analyzer) has issues with this as documented by the bug you quoted.

**Comment by mit-mit** [comment]
Got it, thanks

**Pull request closed without merging**
