### PR TITLE
[sensors] Make Android sensor events fire frequently enough for realtime UI usage

### PR DESCRIPTION
**Pull request by JonLatane**
## Description

Currently, sensor events do not come through quick enough to make a smooth UI experience in a Flutter app on Android. This should correct that issue. From [this PR which now has merge conflicts](https://github.com/flutter/plugins/pull/1563), we can see that currently iOS refreshes sensor data at about 100Hz and Android only at <20Hz. It is impossible to create a smooth sensor-based UX on Android. This will bring the Android refresh rate up to 50Hz or higher, enough for a smooth UX. We can also close that PR with this (and worry about that person's other changes later).

## Related Issues

https://github.com/flutter/flutter/issues/25971

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by JonLatane** [comment]
@googlebot I fixed it

**Comment by JonLatane** [comment]
@googlebot I fixed it.

**Comment by JonLatane** [comment]
@googlebot I fixed it.

**Comment by derTuca** [comment]
Just chiming in on this pull request, but shouldn't this be an option (for battery-related purposes)? From what I remember sensors usually poll slightly faster than the normal setting on Android, but that doesn't mean our apps shouldn't be a good citizen.

**Comment by stuartmorgan** [comment]
Thanks for the submission! However, we’re currently not accepting non-critical PRs for this plugin, as we hope in time to be able to transition users to the corresponding plugin in [the Flutter Community Plus Plugins repository](https://plus.fluttercommunity.dev/). We encourage you to submit your PR there.

We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

**Comment by bjornwinther1996** [comment]
SENSOR_DELAY_GAME can be used to set a faster refresh rate for the sensor data for Android. Is there a similar setting to adjust to achieve the same, when building for web? I'm using the Sensors_plus plugin, which is the only sensor package for web-applications, however the sample rate/refresh rate for the sensordata seem to be 15 event per second (similar to SENSOR_DELAY_NORMAL), which was the same as what androids sensor delay was by default.

**Pull request closed without merging**
