### PR TITLE
[camera] android-rework part 10: fixed final orientation issues. 

### PR DESCRIPTION
**Pull request by BeMacized**
This PR fixes some regressions regarding setting the focus point, as well as some other related issues regarding orientation:
- Rotation of the preview widget now stays in sync with the UI orientation.
- Setting the focus point now properly triggers the autofocus sequence.
- Coordinates for setting the focus- and exposure point now properly rotate according to the ui orientation.

This is the final tenth PR in a series of pull-requests which will gradually introduce changes from PR #3651, making it easier to review the code (as discussed with @stuartmorgan).

As of right now, this PR will still be kept in draft mode, as it also contains changes it depends on from the previous parts. Once those have been merged and any changes from those have been merged back into this PR, the draft status will be removed.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
  - Although these PRs technically did not introduce a breaking change, it likely still warrants a major version bump due to the scale of this refactor. (See [here](https://github.com/flutter/plugins/pull/4059#discussion_r666308215))
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
> This PR fixes some regressions

Can you elaborate on what these regressions are from? Earlier PRs in the series?

If so, why are we landing the switch with known regressions and then fixing them, rather than fixing the in-progress PR?

**Comment by BeMacized** [comment]
> Can you elaborate on what these regressions are from? Earlier PRs in the series?

Setting the focus point would retrigger the autofocus sequence before the android refactor, but no longer in part 9. 
As for the other issues listed, I am not fully sure if they were present before the refactor, but they had to be fixed regardless. 

> If so, why are we landing the switch with known regressions and then fixing them, rather than fixing the in-progress PR?

As mentioned in part 9, after discussion with @mvanbeusekom, to keep the size of the PRs down so they're easier to review. Other than that, there is no consideration. Part 9 and 10 might as well be a single PR as far as I'm concerned.

**Comment by stuartmorgan** [comment]
> Setting the focus point would retrigger the autofocus sequence before the android refactor, but no longer in part 9.

We should not deliberately land known regressions.

> As mentioned in part 9, after discussion with @mvanbeusekom, to keep the size of the PRs down so they're easier to review. Other than that, there is no consideration. Part 9 and 10 might as well be a single PR as far as I'm concerned.

I'm not sure what the combined size is, but if it's too big with the regression fixed we should see if there's another way to cut it.

**Comment by BeMacized** [comment]
Closing this in favour of being merged with #4059 instead.

**Pull request closed without merging**
