### PR TITLE
[video_player] Update ExoPlayer to version 2.11.0

### PR DESCRIPTION
**Pull request by cbenhagen**
## Description
(Replaces https://github.com/flutter/plugins/pull/1868)

Updates ExoPlayer for Android
https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by cbenhagen** [comment]
@ened did you have a chance to test this?

**Comment by ened** [comment]
@cbenhagen as discussed, I took your fork and upgraded to ExoPlayer 2.11.0, then tested the example app on the following phones successfully:
- samsung - zerofltexx - SMG920F - 70 (API 24)
- samsung - crownltexx - SMN960F - 9 (API 28)
- google - blueline - Pixel3 - 10 (API 29)
- Sony - F8132 - F8132 - 800 (API 26)
- HUAWEI - MYAL11 - MYAL11 - 60 (API 23)
- google - marlin - PixelXL - 10 (API 29)
- google - walleye - Pixel2 - 10 (API 29)
- Sony - E5303 - E5303 - 60 (API 23)
- samsung - j6primeltexx - SMJ610FN - 9 (API 28)
- HUAWEI - CLTL09 - CLTL09 - 9 (API 28)
- Sony - G3312 - G3312 - 70 (API 24)
- samsung - j3xnltexx - SMJ320FN - 511 (API 22)
- HUAWEI - CLTAL01 - CLTAL01 - 9 (API 28)
- motorola - aljetern - motog6play - 9 (API 28)

The example apps all kept playing the tracks when the app was suspended to the background using the back button. Not a good user experience in demo but not the key issue of this PR.

There were problems on this device when pressing the back button:
- lge - mm1vnglobalcom - LGK350 - 60 (API 23)
```
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: io.flutter.plugins.videoplayerexample, PID: 10341
                         E  java.lang.RuntimeException: Cannot execute operation because FlutterJNI is not attached to native.
                         E      at io.flutter.embedding.engine.FlutterJNI.ensureAttachedToNative(:2)
                         E      at io.flutter.embedding.engine.FlutterJNI.markTextureFrameAvailable(:2)
                         E      at io.flutter.embedding.engine.d.c.a(:22)
                         E      at io.flutter.embedding.engine.d.c.a(:2)
                         E      at io.flutter.embedding.engine.d.b.onFrameAvailable(:2)
                         E      at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:203)
                         E      at android.os.Handler.dispatchMessage(Handler.java:102)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5551)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:731)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:621)
```

@mklim @matthew-carroll the JNI error may be interesting to you as it's about the new embedding?

Besides that, the PR is LGTM, once based on ExoPlayer 2.11.0.

**Comment by cbenhagen** [comment]
Thanks @ened! I updated to 2.11.0.

**Comment by urakozz** [comment]
Hello here, any plans to update ExoPlayer in the near future?

**Comment by stuartmorgan** [comment]
Thanks for the contribution! This has since been updated (https://github.com/flutter/plugins/pull/3204), so closing as obsolete.

**Pull request closed without merging**
