### PR TITLE
[file_selector_web] Add dummy ios directory.

### PR DESCRIPTION
**Pull request by ditman**
When attempting to publish the `file_selector_web` plugin, the tool complained that it didn't have an `ios` directory (or a much more recent version of the flutter sdk as a minimum bound):

```
pubspec.yaml allows Flutter SDK version prior to 1.20.0, which does not support having no `ios/` folder.
Please consider increasing the Flutter SDK requirement to ^1.20.0 or higher (environment.sdk.flutter) or create an `ios/` folder.

See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin

pub finished with exit code 1

Publish failed. Exiting.
```

This PR adds the `ios` directory, so the plugin is publishable.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by blasten** [comment]
Should this be fixed in the plugin tool code?

**Comment by ditman** [comment]
@blasten I'm not sure where's this error coming from exactly, but it'd be nice if it showed up in the "publishable" verification step.

**Comment by blasten** [comment]
It seems to be coming from https://github.com/dart-lang/pub-dev/blob/f472394eadb4c6a183e0be35c8f28582ccc78d6d/pkg/pub_package_reader/lib/pub_package_reader.dart#L412-L416.

If you really want to support 1.20.0, then you will need the ios folder

**Review by blasten — APPROVED** [review]

**Comment by ditman** [comment]
I've created this issue:

https://github.com/dart-lang/pub/issues/2828

Our "publishable" step should report these issues at PR time so the contributor can fix them (and not the person responsible for merging the package).

**Pull request merged**
