### PR TITLE
[path_provider] Switch to Pigeon for macOS

### PR DESCRIPTION
**Pull request by stuartmorgan**
Converts from direct method channel use to the new experimental Swift generator. Also switches from a one-call-per-method approach to a single method with an enum, since it's easy to do that in a maintainable way with Pigeon (unlike manual method channels, where keeping enum indexes in sync across the language boundary is error-prone, and requires manual int/enum conversion).

Part of https://github.com/flutter/flutter/issues/117844

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I'm definitely happy with how this conversion turned out. The native test code is much simpler, the Dart test code has better locality, the hand-authored implementation code is about the same length but without any magic strings, and there's actually not much boilerplate in the generated (since I ended up going with just one method).

There was one issue I had to temporarily work around, but that was in the Dart generator rather than the Swift generator (https://github.com/flutter/flutter/issues/105742). I'll fix that shortly, but hand-fixed it for now to avoid blocking this PR.

**Comment by tarrinneal** [comment]
@stuartmorgan This will be very helpful for me later thank you! I'll let @cbracken give the approval though.

**Comment by stuartmorgan** [comment]
@cbracken Ping on this review.

**Comment by stuartmorgan** [comment]
@cbracken Monthly ping 🙂

**Review by cbracken — APPROVED** [review]
LGTM stamp from a Japanese personal seal

**Pull request merged**
