### PR TITLE
[image_picker] Fix images changing to incorrect orientation

### PR DESCRIPTION
**Pull request by vashworth**
When you take an image with an iPhone in portrait mode, it's actually taking the image in landscape mode and saving rotation information into the image's metadata. The `UIImage` class will then automatically transform the image to be the correct orientation. You can read more about it [here](https://developer.apple.com/documentation/uikit/uiimageorientation?language=objc).

Now, in the plugin code, when the user resizes an image that has orientation metadata, we resize it differently to handle the rotation.

https://github.com/flutter/plugins/blob/d699b4a91381c213d67345938d73d6395bd64a06/packages/image_picker/image_picker_ios/ios/Classes/FLTImagePickerImageUtil.m#L86-L105

https://github.com/flutter/plugins/pull/7084 changed the plugin so that every image returns basic metadata, which includes the orientation/rotation info. However, it wasn't doing to metadata scaling process which was causing the images to get incorrect orientation.

Fixes https://github.com/flutter/flutter/issues/120356.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by vashworth** [comment]
@cyanglaz @jmagman Any ideas on how to test this? I could use a real image to test it, but I'm struggling to get a small image with the orientation metadata in it. For example, if I can a picture on my iPhone it will have the orientation data in it and is 260KB. If I resize it or compress it, it loses the orientation metadata.

**Comment by jmagman** [comment]
> @cyanglaz @jmagman Any ideas on how to test this? I could use a real image to test it, but I'm struggling to get a small image with the orientation metadata in it. For example, I can take a picture on my iPhone and it will have the orientation data in it and is 260KB. If I resize it or compress it, it loses the orientation metadata.

Can you re-add the orientation metadata with something like [exiftool](https://exiftool.org/)? There also might be some `imagemagick` flags that resize/compress without stripping the metadata.

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
> LGTM

Once the formatter is happy.

**Pull request merged**
