### PR TITLE
[shared_preferences] Fix example in readme for mocking values

### PR DESCRIPTION
**Pull request by ueman**
This fixes the example for mocking values in the readme of shared_preferences.
After the NNBD migration mock values can only be of type `Object`.

There are no issues for this small readme error.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@bparrishMines Ping on this trivial review.

**Review by bparrishMines — COMMENTED** [review]
Just one small nit and it looks like the `CHANGELOG` needs one more update.

**Comment by stuartmorgan** [comment]
@bparrishMines It's been updated; PTAL

**Review by bparrishMines — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
Nevermind, the GitHub UI issue resolved itself, so I was able to resolve the conflicts directly.

**Comment by stuartmorgan** [comment]
This needs master merged in to pick up the fix for the `publishable` failure (which was caused by a `pub` change). I'm not able to do that from the GitHub UI without a conflict to resolves, so @ueman please merge in master and push when you have a chance.

**Pull request merged**
