### PR TITLE
[in_app_purchase]  Fix assertion error on SKPaymentQueueWrapper init

### PR DESCRIPTION
**Pull request by Gerrel**
Allow observer to be set on initialization, because the observer is invoked immediately.

Fix: Exception has occurred.
_AssertionError ('package:in_app_purchase/src/store_kit_wrappers/sk_payment_queue_wrapper.dart': Failed assertion: line 133 pos 12: '_observer != null': [in_app_purchase]: (Fatal)The observer has not been set but we received a purchase transaction notification. Please ensure the observer has been set using `setTransactionObserver`. Make sure the observer is added right at the App Launch.)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by cyanglaz** [comment]
@mklim I remember we talked about this approach when we initially implemented this. Do you remember what stopped us from doing so? Was it to just match the StoreKit's implementation?

**Comment by cyanglaz** [comment]
@Gerrel Thanks for sending out this PR. Do you mind to share a detailed step-to-reproduce so we might have a better understanding of what caused the issue. (Creating a github issue with a detailed description would be the best way to do it, it also helps us to prioritize the issue based on the number of thumbs-up)

I see that this PR is making a potential break change, since we probably want to set the argument   `{SKTransactionObserverWrapper observer}` to be required.
Another way to achieve the same (without a breaking change) would be adding `callbackChannel.setMethodCallHandler(_handleObserverCallbacks);` to `setTransactionObserver` :

```dart
  void setTransactionObserver(SKTransactionObserverWrapper observer) {
    _observer = observer;
    callbackChannel.setMethodCallHandler(_handleObserverCallbacks);
  }
```

**Comment by Gerrel** [comment]
Will probably create a detailed step-to-reproduce on the end of the month.
(It happens when you reinstall the app while you have a active subscription or purchase a subscription in the App Store and install the app afterwards.
https://developer.apple.com/app-store/promoting-in-app-purchases/)

**Comment by cyanglaz** [comment]
@Gerrel Thanks. I will circle back after you provide the steps to reproduce!

**Comment by Gerrel** [comment]
1. Create a app in iTunes Connect.
2. Goto > Features tab and In-App Purchases.
3. Click + to add an in-app purchase.
4. Select Auto-Renewable Subscription.
5. Fill in `Reference Name` > Subscription.
6. Fill in `Product ID` > com.example.app.subscription.
7. Click Next.
8. Fill in `Subscription Group Reference Name` > default.
9. Click Create/Next.
10. Select `Subscription Duration` > 1 month
11. Click Save.
12. Click + next to Subscription Prices.
13. Select 'EUR' and the price €0,49.
14. Click Next.
15. Click Create in the follow-up screen.
16. Click Save & return back to features page.
17. Click + next to Localizations.
18. Select 'English (U.S.)'.
19. Fill in `Subscription Display Name` > Subscription.
20. Fill in `Description` > Unlimited access.
21. Click Save.
22. Start iPhone Simulater and wait for boot.
23. Press CMD+S in Simulator.
24. Screenshot should be available on your desktop.
25. Upload screenshot in `Review information` section.
26. Fill in `Review Notes` > Test for auto-renewable subscription.
27. Click Save.
28. Go to the `subscription groups` section and select default.
29. Click + next to Localizations.
30. Select 'English (U.S.)'.
31. Fill in `Subscription Group Display Name` > default.
32. Click Save.
33. Your status should now be `Ready to Submit`.
34. Follow the `Getting Started` on in_app_purchase for subscriptions.
35. Start the app with `catching all exceptions`.
36. Purchase the test-subscription in the app.
37. Once the subscription is active delete the app.
38. Reinstall the app.
39. Start the app with catching all exceptions.
40. You will immediately notice the assertion error on start.

> The library should make sure it supports SKPaymentTransactionObserver method handling on [startup / first install] to process this transaction.

**Comment by cyanglaz** [comment]
cc @LHLL

**Comment by LHLL** [comment]
This looks like a not following documentation issue to me:
As long as the client app follows the [documentation](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart#L56), repeat the steps above will not reproduce the issue.

**Comment by eduribas** [comment]
I'm having the exact same problem and I'm subscribing to `InAppPurchaseConnection.instance.purchaseUpdatedStream` on my main app class, as described on the the plugin documentation.

**Comment by stx** [comment]
> I'm having the exact same problem and I'm subscribing to `InAppPurchaseConnection.instance.purchaseUpdatedStream` on my main app class, as described on the the plugin documentation.

I'm also having this issue 100% of the time with literally 3 lines of code:

```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  InAppPurchaseConnection.enablePendingPurchases();
  InAppPurchaseConnection.instance.purchaseUpdatedStream.listen((_) {});
}
```

image

@LHLL How are you supposed to get this to work?...

**Comment by LHLL** [comment]
Thanks for providing reproduce steps, and I do agree the documentation in this plugin is not the easiest one to follow, but I don't think following code is a legitimate instruction:
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  InAppPurchaseConnection.enablePendingPurchases();
  InAppPurchaseConnection.instance.purchaseUpdatedStream.listen((_) {});
}
```
According to [documentation](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/lib/src/in_app_purchase/in_app_purchase_connection.dart#L80), `InAppPurchaseConnection.enablePendingPurchases();` is no-op on iOS, thus should be irrelevant to this issue.

According to [documentation for iOS](https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/lib/src/store_kit_wrappers/sk_payment_queue_wrapper.dart#L56), observer needs to be set as soon as **app launches**. With this being said, this needs to be done in your first widget setup instead of a plain main method without calling `runApp`.  For example:
```
void main() {
  // For play billing library 2.0 on Android, no-op on iOS
  InAppPurchaseConnection.enablePendingPurchases();
  runApp(MyApp());
}
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final InAppPurchaseConnection _connection = InAppPurchaseConnection.instance;
  StreamSubscription<List<PurchaseDetails>> _subscription;
  @override
  void initState() {
    Stream purchaseUpdated =
        InAppPurchaseConnection.instance.purchaseUpdatedStream;
    _subscription = purchaseUpdated.listen((purchaseDetailsList) {
      // Handles unfinished transactions here.
    }, onDone: () {
     // Handle UI here
    }, onError: (error) {
      // handle error here.
    });
    super.initState();
  }
  ...
}
```

**Comment by pmagnuson** [comment]
@LHLL I followed your example, and I get the same failure.  

Screen Shot 2020-06-17 at 5 04 57 PM

**Comment by TheTrainor** [comment]
Getting the exact same error on iOS. For me, it happened after subscribing to a product, clsoing the app, and then rebuilding. Did not have to delete or remove the app.

Otherwise, I appear to be following best practices (i.e. "observer needs to be set as soon as app launches.").

**Comment by LHLL** [comment]
Do you mind adding some tests?

**Comment by Gerrel** [comment]
Will check this week what I can do.

**Comment by Gerrel** [comment]
Not able to reproduce the assertion error with latest version.

**Pull request closed without merging**
