### PR TITLE
Update url_launcher/README.md  

### PR DESCRIPTION
**Pull request by kagouda**
'RaisedButton' is deprecated and shouldn't be used . Use ElevatedButton instead

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Thanks for the contribution! You’ve checked boxes in the PR checklist above that are not reflected in this PR, so I’m assuming this is a work in progress and am marking it as a Draft. Please review the checklist, updating the PR as appropriate, and when the checklist reflects the state of the PR as posted please feel free to mark it as ready for review.

**Comment by stuartmorgan** [comment]
Now you haven’t checked off any of the items in the PR checklist above, nor have you followed it; this is not an improvement. The checklist is there for a reason.

I'm going to mark this as a draft again. If you are interested in moving forward with this PR you need to follow our PR process, which is detailed in the checklist; once you have done that, please mark it as ready for review. Otherwise, we can close the PR.

**Comment by kagouda** [comment]
I don't know which checklist I should check. In my case, I only replace the name of the button. So please help me to choose, I don't know what to check and what not to check.  
I just updated the Readme by replacing RaisedButton with ElevatedButton.

**Comment by kagouda** [comment]
I think it's OK now .

**Comment by stuartmorgan** [comment]
Please read the links in the items you skipped. In particular you do not appear to have read https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#faq

**Comment by kagouda** [comment]
Thans you @stuartmorgan  . I think it's ok now . I also updated the `changelog` by following [Wiki/Contributing-to-Plugins-and-Packages#faq](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#faq.)

This is the link of the `changelog` pull  : https://github.com/flutter/plugins/pull/4689

**Comment by stuartmorgan** [comment]
All of the required elements need to be part of this PR. That's why they are in the PR checklist.

**Comment by kagouda** [comment]
It's OK now .

**Comment by stuartmorgan** [comment]
No, it's not. You're still ignoring parts of the checklist, including parts I specifically pointed you to a FAQ about being required. And I see now that you had a previous PR where all of these same things were explained several times as well for a very similar change.

I'm going to close this. If at some point you are willing to actually read and follow our contribution process, feel free to open a new PR.

**Pull request closed without merging**
