### PR TITLE
[google_maps_flutter] Modified `README.md` to fix minor syntax issues

### PR DESCRIPTION
**Pull request by DEVSOG12**
I fixed minor code style issue in the example. e.g. change `final` to `const` because `final` wasn't neccessary in the case. 

- Fixed minor code style issues in the `README.md`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [] I added new tests to check the change I am making, or this PR is [test-exempt].
- [] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by DEVSOG12** [comment]
Thank you @stuartmorgan!
 
I have added the code excerpts to the README.

**Comment by stuartmorgan** [comment]
The excerpt process is failing in CI; it looks like you didn't set a `path-base`. Did this actually work when you ran it locally?

I'm going to mark this as a draft, since it's not passing CI; please feel free to mark it for review again once it's passing. Note that as part of fixing CI you'll need to do several steps that you checked off in the checklist but didn't actually do:
> - [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates).
> - [x] I updated CHANGELOG.md to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style).

Please also do this as well:
> - [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]

(In the future, please follow the checklist, rather than just checking items in it; it's part of the template for a reason.)

**Comment by DEVSOG12** [comment]
@stuartmorgan I have fixed all the issues.

**Comment by stuartmorgan** [comment]
Sorry, I missed the earlier update. Could you address the remaining CI issues ([here](https://cirrus-ci.com/task/5521027921346560) and [here](https://cirrus-ci.com/task/5380290432991232)).

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
Please also remove this package from script/configs/temp_exclude_excerpt.yaml now that it's been converted over.

Otherwise, this looks great, thanks for contributing this!

**Comment by DEVSOG12** [comment]
@stuartmorgan I have made the change, but only one test fails.

**Review by stuartmorgan — APPROVED** [review]
I re-added the existing CHANGELOG entries that you deleted; with that, this LGTM. Thanks!

(No tests are failing, that's just the tree status.)

**Comment by stuartmorgan** [comment]
@tarrinneal or @ditman could you do the secondary review on this README conversion to excerpts?

**Review by tarrinneal — APPROVED** [review]
Looks solid to me, it's cool to see the excerpts rules catching issues with the readme code ( with the help of @DEVSOG12 of course).

**Pull request merged**
