### PR TITLE
Image source selection support for ImagePicker plugin

### PR DESCRIPTION
**Pull request by roughike**
This PR makes it possible to control whether the image comes from _gallery_ or _camera_. The old behavior is preserved as the default option, which lets the user decide.

Here are the available options:

```dart
enum ImageSource {
  /// Let the user choose an image from a source they prefer.
  /// (the old default behavior)
  askUser,

  /// Opens up the device camera on both Android and iOS.
  camera,

  /// On Android, presents a grid of images from the users gallery. On iOS,
  /// opens the users photo library.
  gallery,
}
```

Here's how someone might pick an image from the device camera now:

```dart
Future<File> imageFile = ImagePicker.pickImage(source: ImageSource.camera);
```

### CODE REVIEW

**Comment by roughike** [comment]
cc @collinjackson since you seem to be the image_picker plugin review guy.

**Comment by roughike** [comment]
Fixed the test description, but I have no idea why the tests would fail.

**Comment by goderbauer** [comment]
Does https://github.com/flutter/plugins/pull/266 help you with fixing the test failures?

**Comment by roughike** [comment]
Thanks! Just applied that commit to my tests.

**Comment by roughike** [comment]
I think I might have messed something up when merging/rebasing stuff. At least the changes are humongous.

 I'll look into it when I have time.

**Comment by roughike** [comment]
I signed it!

**Comment by roughike** [comment]
@goderbauer I started over: #271

**Pull request closed without merging**
