### PR TITLE
Remove a wrong assertion.

### PR DESCRIPTION
**Pull request by kdy1**
Google play games service does not give us displayName.
Closes flutter/flutter#19442

### CODE REVIEW

**Comment by kdy1** [comment]
I signed it!

**Comment by kroikie** [comment]
Hi @kdy1 Thanks for the PR could you please fix the formatting? I'll be happy to merge then.

**Comment by kdy1** [comment]
I fixed it.

**Comment by kdy1** [comment]
Most of them are timeout, but I couldn't find a retry button.
@kroikie Can you retry?

**Comment by kroikie** [comment]
@kdy1 would you mind rebasing on master and trying again. Some formatting that is failing in your PR should be fixed and we should get a successful build.

**Comment by kdy1** [comment]
Done, but now I got some more formatting issues..

**Comment by kdy1** [comment]
I guess the failure is related to flutter version.


### Output of `flutter format .`:

```
PS C:\Users\kdy\Documents\projects\plugins> flutter format .
Formatting directory .:
Unchanged packages\android_alarm_manager\example\lib\main.dart
Unchanged packages\android_alarm_manager\lib\android_alarm_manager.dart
Unchanged packages\android_intent\example\lib\main.dart
Unchanged packages\android_intent\lib\android_intent.dart
Unchanged packages\battery\example\lib\main.dart
Unchanged packages\battery\lib\battery.dart
Unchanged packages\battery\test\battery_test.dart
Unchanged packages\camera\example\lib\main.dart
Unchanged packages\camera\lib\camera.dart
Unchanged packages\cloud_firestore\example\lib\main.dart
Unchanged packages\cloud_firestore\lib\cloud_firestore.dart
Unchanged packages\cloud_firestore\lib\src\blob.dart
Unchanged packages\cloud_firestore\lib\src\collection_reference.dart
Unchanged packages\cloud_firestore\lib\src\document_change.dart
Unchanged packages\cloud_firestore\lib\src\document_reference.dart
Unchanged packages\cloud_firestore\lib\src\document_snapshot.dart
Unchanged packages\cloud_firestore\lib\src\firestore.dart
Unchanged packages\cloud_firestore\lib\src\firestore_message_codec.dart
Unchanged packages\cloud_firestore\lib\src\geo_point.dart
Unchanged packages\cloud_firestore\lib\src\query.dart
Unchanged packages\cloud_firestore\lib\src\query_snapshot.dart
Unchanged packages\cloud_firestore\lib\src\snapshot_metadata.dart
Unchanged packages\cloud_firestore\lib\src\transaction.dart
Unchanged packages\cloud_firestore\lib\src\utils\push_id_generator.dart
Unchanged packages\cloud_firestore\lib\src\write_batch.dart
Unchanged packages\cloud_firestore\test\cloud_firestore_test.dart
Unchanged packages\cloud_functions\example\lib\main.dart
Unchanged packages\cloud_functions\example\test\widget_test.dart
Unchanged packages\cloud_functions\lib\cloud_functions.dart
Unchanged packages\cloud_functions\test\cloud_functions_test.dart
Unchanged packages\connectivity\example\lib\main.dart
Unchanged packages\connectivity\lib\connectivity.dart
Unchanged packages\device_info\example\lib\main.dart
Unchanged packages\device_info\lib\device_info.dart
Unchanged packages\firebase_admob\example\lib\main.dart
Unchanged packages\firebase_admob\lib\firebase_admob.dart
Unchanged packages\firebase_admob\test\firebase_admob_test.dart
Unchanged packages\firebase_analytics\example\lib\main.dart
Unchanged packages\firebase_analytics\example\lib\tabs_page.dart
Unchanged packages\firebase_analytics\lib\firebase_analytics.dart
Unchanged packages\firebase_analytics\lib\observer.dart
Unchanged packages\firebase_analytics\test\firebase_analytics_test.dart
Unchanged packages\firebase_analytics\test\observer_test.dart
Unchanged packages\firebase_auth\example\lib\main.dart
Unchanged packages\firebase_auth\lib\firebase_auth.dart
Unchanged packages\firebase_auth\test\firebase_auth_test.dart
Unchanged packages\firebase_core\example\lib\main.dart
Unchanged packages\firebase_core\lib\firebase_core.dart
Unchanged packages\firebase_core\lib\src\firebase_app.dart
Unchanged packages\firebase_core\lib\src\firebase_options.dart
Unchanged packages\firebase_core\test\firebase_core_test.dart
Unchanged packages\firebase_database\example\lib\main.dart
Unchanged packages\firebase_database\lib\firebase_database.dart
Unchanged packages\firebase_database\lib\src\database_reference.dart
Unchanged packages\firebase_database\lib\src\event.dart
Unchanged packages\firebase_database\lib\src\firebase_database.dart
Unchanged packages\firebase_database\lib\src\on_disconnect.dart
Unchanged packages\firebase_database\lib\src\query.dart
Unchanged packages\firebase_database\lib\src\utils\push_id_generator.dart
Unchanged packages\firebase_database\lib\ui\firebase_animated_list.dart
Unchanged packages\firebase_database\lib\ui\firebase_list.dart
Unchanged packages\firebase_database\lib\ui\firebase_sorted_list.dart
Unchanged packages\firebase_database\lib\ui\utils\stream_subscriber_mixin.dart
Unchanged packages\firebase_database\test\firebase_database_test.dart
Unchanged packages\firebase_database\test\firebase_list_test.dart
Unchanged packages\firebase_dynamic_links\example\lib\main.dart
Unchanged packages\firebase_dynamic_links\lib\firebase_dynamic_links.dart
Unchanged packages\firebase_dynamic_links\lib\src\dynamic_link_parameters.dart
Unchanged packages\firebase_dynamic_links\lib\src\firebase_dynamic_links.dart
Unchanged packages\firebase_dynamic_links\test\firebase_dynamic_links_test.dart
Unchanged packages\firebase_messaging\example\lib\main.dart
Unchanged packages\firebase_messaging\lib\firebase_messaging.dart
Unchanged packages\firebase_messaging\test\firebase_messaging_test.dart
Unchanged packages\firebase_ml_vision\example\lib\detector_painters.dart
Unchanged packages\firebase_ml_vision\example\lib\main.dart
Unchanged packages\firebase_ml_vision\lib\firebase_ml_vision.dart
Unchanged packages\firebase_ml_vision\lib\src\barcode_detector.dart
Unchanged packages\firebase_ml_vision\lib\src\face_detector.dart
Unchanged packages\firebase_ml_vision\lib\src\firebase_vision.dart
Unchanged packages\firebase_ml_vision\lib\src\label_detector.dart
Unchanged packages\firebase_ml_vision\lib\src\text_detector.dart
Unchanged packages\firebase_ml_vision\test\firebase_ml_vision_test.dart
Unchanged packages\firebase_performance\example\lib\main.dart
Unchanged packages\firebase_performance\lib\firebase_performance.dart
Unchanged packages\firebase_performance\lib\src\firebase_performance.dart
Unchanged packages\firebase_performance\lib\src\http_metric.dart
Unchanged packages\firebase_performance\lib\src\performance_attributes.dart
Unchanged packages\firebase_performance\lib\src\trace.dart
Unchanged packages\firebase_performance\test\firebase_performance_test.dart
Unchanged packages\firebase_remote_config\example\lib\main.dart
Unchanged packages\firebase_remote_config\lib\firebase_remote_config.dart
Unchanged packages\firebase_remote_config\lib\src\remote_config.dart
Unchanged packages\firebase_remote_config\lib\src\remote_config_fetch_throttled_exception.dart
Unchanged packages\firebase_remote_config\lib\src\remote_config_last_fetch_status.dart
Unchanged packages\firebase_remote_config\lib\src\remote_config_settings.dart
Unchanged packages\firebase_remote_config\lib\src\remote_config_value.dart
Unchanged packages\firebase_remote_config\test\firebase_remote_config_test.dart
Unchanged packages\firebase_storage\example\lib\main.dart
Unchanged packages\firebase_storage\lib\firebase_storage.dart
Unchanged packages\firebase_storage\lib\src\firebase_storage.dart
Unchanged packages\firebase_storage\lib\src\storage_metadata.dart
Unchanged packages\firebase_storage\lib\src\storage_reference.dart
Unchanged packages\firebase_storage\lib\src\upload_task.dart
Unchanged packages\firebase_storage\test\firebase_storage_test.dart
Unchanged packages\google_maps_flutter\example\lib\animate_camera.dart
Unchanged packages\google_maps_flutter\example\lib\main.dart
Unchanged packages\google_maps_flutter\example\lib\map_ui.dart
Unchanged packages\google_maps_flutter\example\lib\move_camera.dart
Unchanged packages\google_maps_flutter\example\lib\page.dart
Unchanged packages\google_maps_flutter\example\lib\place_marker.dart
Unchanged packages\google_maps_flutter\lib\google_maps_flutter.dart
Unchanged packages\google_maps_flutter\lib\src\bitmap.dart
Unchanged packages\google_maps_flutter\lib\src\callbacks.dart
Unchanged packages\google_maps_flutter\lib\src\camera.dart
Unchanged packages\google_maps_flutter\lib\src\controller.dart
Unchanged packages\google_maps_flutter\lib\src\location.dart
Unchanged packages\google_maps_flutter\lib\src\marker.dart
Unchanged packages\google_maps_flutter\lib\src\platform_overlay.dart
Unchanged packages\google_maps_flutter\lib\src\ui.dart
Unchanged packages\google_sign_in\example\lib\main.dart
Unchanged packages\google_sign_in\lib\google_sign_in.dart
Unchanged packages\google_sign_in\lib\src\common.dart
Unchanged packages\google_sign_in\lib\testing.dart
Unchanged packages\google_sign_in\lib\widgets.dart
Unchanged packages\google_sign_in\test\google_sign_in_test.dart
Unchanged packages\image_picker\example\lib\main.dart
Unchanged packages\image_picker\lib\image_picker.dart
Unchanged packages\image_picker\test\image_picker_test.dart
Unchanged packages\in_app_purchase\example\lib\main.dart
Unchanged packages\in_app_purchase\example\test\widget_test.dart
Unchanged packages\in_app_purchase\lib\in_app_purchase.dart
Unchanged packages\local_auth\example\lib\main.dart
Unchanged packages\local_auth\lib\auth_strings.dart
Unchanged packages\local_auth\lib\error_codes.dart
Unchanged packages\local_auth\lib\local_auth.dart
Unchanged packages\package_info\example\lib\main.dart
Unchanged packages\package_info\lib\package_info.dart
Unchanged packages\path_provider\example\lib\main.dart
Unchanged packages\path_provider\lib\path_provider.dart
Unchanged packages\path_provider\test\path_provider_test.dart
Unchanged packages\quick_actions\example\lib\main.dart
Unchanged packages\quick_actions\lib\quick_actions.dart
Unchanged packages\sensors\example\lib\main.dart
Unchanged packages\sensors\example\lib\snake.dart
Unchanged packages\sensors\lib\sensors.dart
Unchanged packages\sensors\test\sensors_test.dart
Unchanged packages\share\example\lib\main.dart
Unchanged packages\share\lib\share.dart
Unchanged packages\share\test\share_test.dart
Unchanged packages\shared_preferences\example\lib\main.dart
Unchanged packages\shared_preferences\lib\shared_preferences.dart
Unchanged packages\shared_preferences\test\shared_preferences_test.dart
Unchanged packages\url_launcher\example\lib\main.dart
Unchanged packages\url_launcher\lib\url_launcher.dart
Unchanged packages\url_launcher\test\url_launcher_test.dart
Unchanged packages\video_player\example\lib\main.dart
Unchanged packages\video_player\lib\video_player.dart

```

As an app developer, I don't want to switch to dev branch. Does flutter support configuring channel only for a directory?

**Comment by kroikie** [comment]
@kdy1 Sorry for those errors, those formatting issues have been resolved. Please rebase again and I will merge.

**Comment by kdy1** [comment]
It failed. I guess I should revert 'format with flutter .`? Is this right?

**Pull request merged**
