### PR TITLE
[in_app_purchase] Move in_app_purchase into sub-folder.

### PR DESCRIPTION
**Pull request by mvanbeusekom**
This moves the in_app_purchase app facing package into a new sub-folder (`in_app_purchage/in_app_purchase`)
to prepare for the migration to federated architecture.

Note: since this only changes the directory layout of the project but doesn't change anything in the plugin itself I decided not to update the version number in the pubspec.yaml and/or CHANGELOG.md.

Implements part of issue flutter/flutter#78525

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
  - I believe this is not necessary since this change doesn't require a release to pub.dev
- [ ] I updated CHANGELOG.md to add a description of the change.
  - I believe this is not necessary since this change doesn't require a release to pub.dev
- [ ] I updated/added relevant documentation (doc comments with `///`).
  - This change doesn't require any documentation to be updated.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
  - Since the update only changes the projects directory structure and no new code was added there is no need to write additional tests. Of course I made sure all existing tests are passing.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by BeMacized** [comment]
LGTM!

**Review by BeMacized — APPROVED** [review]
LGTM! Waiting to see if the tree goes green

**Comment by cyanglaz** [comment]
@jmagman This PR moves the plugin code to a sub folder but the iOS build failed when import in_app_purchase module. 
`Module 'in_app_purchase' not found`

Did you know what might cause this?

**Comment by cyanglaz** [comment]
Thanks to @jmagman finding the issue. I have created a PR implementing the fix Jenn suggested in a separate PR, it should be fixed now. https://github.com/flutter/plugins/pull/3744
I'm closing this PR in favor of the above one.

**Comment by jmagman** [comment]
> @jmagman This PR moves the plugin code to a sub folder but the iOS build failed when import in_app_purchase module.
> `Module 'in_app_purchase' not found`
> 
> Did you know what might cause this?


It was a redux of https://github.com/flutter/flutter/issues/67175

**Pull request closed without merging**
