### PR TITLE
[video_player] fix Timer Leak

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
## Description

Currently, when `play` is called twice, i.e. `play` is called again before `pause`, the `_timer` leaks, which can create very frequent calls of listener **and** more importantly will never stop notifying, even when the video is paused.

I would say that this is a pretty severe issue as calling `play` on a controller can easily happen more than once and should not have side effects.

## Tests

I tried to add the following integration test:

```dart
testWidgets('cancels timers', (WidgetTester tester) async {
      await _controller.initialize();

      var eventCount = 0;
      final listener = () => eventCount++;
      _controller.addListener(listener);

      // Play for a second, then pause, and then wait a second.
      await _controller.play();
      // Call play twice to test if timers leak.
      await _controller.play();
      await tester.pumpAndSettle(_playDuration);

      final prePauseEventCount = eventCount;
      await _controller.pause();
      await tester.pumpAndSettle(_playDuration);

      // If timers were properly canceled, there should only be one new event
      // (from pausing). If timers were not canceled, there will be more events.
      expect(eventCount, prePauseEventCount + 1);

      _controller.removeListener(listener);
    }, skip: Platform.isIOS);
```

However, I was not able to get the existing integration tests to succeed, which is why I figured that this can do without a regression test for now.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]). (more below)
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
(I have the feeling that the failing smoke test has nothing to do with my PR)

**Review by Ehesp — APPROVED** [review]
LGTM - replicated & confirmed this fix works.

**Review by iskakaushik — APPROVED** [review]
LGTM

**Comment by creativecreatorormaybenot** [comment]
@Ehesp @iskakaushik Thanks a lot for taking the time ❤

PS will the `video_player` update be pushed to Pub? I am just wondering as I know it is not automated for `flutter/plugins`.

**Pull request merged**
