### PR TITLE
[firebase_storage] Return error when failing to read file

### PR DESCRIPTION
**Pull request by LinusU**
## Description

Currently, when trying to upload a `File` that doesn't exist, the entire app crashes deep inside the firebase sdk: https://github.com/firebase/firebase-ios-sdk/pull/2458/files#r276273826

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

-----

Not sure how to add tests since the tests since to mock out the Objective-C part of the plugins, any help would be appreciated!

### CODE REVIEW

**Comment by collinjackson** [comment]
Integration tests are being added in https://github.com/flutter/plugins/pull/1513

**Comment by collinjackson** [comment]
Added an assertion on the Dart side since the current API doesn't provide a way to catch this exception. I think that this situation could be improved in the future, but also I don't see a downside to adding extra error handling for the missing file case. @kroikie do you think we should go ahead and merge this one?

**Comment by collinjackson** [comment]
This seems like a low risk change so I'll go ahead and merge it.

**Comment by LinusU** [comment]
Thanks for moving forward with this @collinjackson, been away for the past days ❤️

**Pull request merged**
