### PR TITLE
[image_picker] Added initial support.

### PR DESCRIPTION
**Pull request by azchohfi**
Adds windows(Win32) support for the image_picker.

Fixes https://github.com/flutter/flutter/issues/92108

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@azchohfi Are you planning on continuing with this PR?

**Comment by azchohfi** [comment]
I believe it would be best to abandon this, in favor for something based on top of #4424.

**Comment by stuartmorgan** [comment]
Sounds good; I'll close this then, and once that PR lands if you want to adapt the filter code here to a wrapper-based implementation that would be great.

**Comment by azchohfi** [comment]
Status update: I've got this implemented for when source == ImageSource.gallery, using a wrapper on the FileSelector for windows. Still implementing it for when source == ImageSource.camera, which will use the camera_windows plugin.

**Comment by stuartmorgan** [comment]
Great! Feel free to submit a PR with what you currently have; we can land it as an unendorsed implementation that only supports the gallery source, then camera can be added in a later PR. Incremental PRs are definitely encouraged :)

**Comment by azchohfi** [comment]
@stuartmorgan https://github.com/flutter/plugins/pull/4863

**Pull request closed without merging**
