### PR TITLE
[video_player] Update texture on seekTo

### PR DESCRIPTION
**Pull request by cbenhagen**
## Description

Explicitly mark texture frame available on `seekTo`. This is necessairy since https://github.com/flutter/engine/commit/6a90b7f95bd87e74b8d6e6771729644527bbc365 has changed the external texture data flow from a producer-consumer model. Now ios_external_texture_gl caches previous opengl texture, if no new frame are available, it does not execute the `copyPixelBuffer` method, just uses cached opengl texture to draw.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/43567

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by cbenhagen** [comment]
@ened PTAL

**Comment by cbenhagen** [comment]
@cyanglaz do you have time for a quick review? This is a very simple change that would fix a bug present since the last flutter stable release.

**Comment by amirh** [comment]
Can you please add more details on the nature of the change and the reasoning behind it to the PR description?

**Comment by cbenhagen** [comment]
Done. Hopefully it does make more sense now.

**Comment by amirh** [comment]
I'm not sure I fully understand https://github.com/flutter/engine/commit/6a90b7f95bd87e74b8d6e6771729644527bbc365 does it mean we need to call `textureFrameAvailable` every time there's a new frame? if so who's calling it for each video frame?

cc @cbracken who landed https://github.com/flutter/engine/pull/11524 and probably better understands this.

**Comment by cbenhagen** [comment]
CADisplayLink here: https://github.com/flutter/plugins/blob/f43e418c6c0656b0a1264191b53966cd96e309ce/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m#L20-L31

**Comment by amirh** [comment]
I see, thanks.

**Comment by amirh** [comment]
I don't see an obvious way to test this, @collinjackson do you have any suggestion?

**Comment by cbenhagen** [comment]
@amirh can we release this without a test? I mean I'd really love to have one but I really don't know how as the simulator would not even show an image.

**Comment by amirh** [comment]
We need some test, how about an XCTest that mocks the texture registry, invokes `handleMethodCall` with a `"seekTo"` and asserts that `textureFrameAvailable` was invoked?

(we'll have to mock a few other objects to be able to deliver a mock texture registry, I may be missing something but it seems reasonably doable)

**Comment by cyanglaz** [comment]
@cbenhagen https://github.com/flutter/plugins/pull/2445 I recently set up a similar test mentioned by @amirh above in the webview plugin. You can use it as a reference.

**Comment by wterrill** [comment]
I'm seeing that the ios version of video_player does not perform a frame update on "seekTo()" when the video is paused. (but does update on seekTo() when playing)

Android works for both paused videos and running videos.

I believe that this issue is related to that?

**Comment by jpiabrantes** [comment]
I really need this merged. The newest version of video_player still doesn't fix this issue.

**Comment by dthuering** [comment]
Hi @jpiabrantes I think some changes in the repo make this PR breaking. The `FLTVideoPlayerPlugin.m` file changed a lot.
:(

**Comment by cbenhagen** [comment]
Closing in favor of https://github.com/flutter/plugins/pull/2758

**Pull request closed without merging**
