### PR TITLE
[local_auth]Fix lock out alert message iOS

### PR DESCRIPTION
**Pull request by severance88**
Description
Fixed an issue with an alertMessage crashing the application after failing to authenticate with fingerprint 5 times (3 + 2) on iOS

Related Issues
Fixes:
flutter/flutter#57129
flutter/flutter#48140

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by ajviera** [comment]
Can anyone approve this PR? It is super necessary since the error is 100% replicable

**Comment by severance88** [comment]
Format is failing. I can't seem to install the formatting tools. Someone pick it up and format it?

**Comment by ShvetsDima** [comment]
Same for me, can't install the formatting tools. 
May anybody check it please ?

**Comment by trunghieuvn** [comment]
i have sam as issue, 
please merger this PR 
thanks

**Comment by TMSantos** [comment]
Please put some urgency into this PR, its reproducible

**Comment by silverhsu1120** [comment]
I have sam as issue.
Any update?

**Comment by fransboumans** [comment]
Any updates on this? The app still crashes after the 5th attempt.

**Comment by yaizudamashii** [comment]
When will this PR be merged!???  Touch ID on iOS is definitely crashing.

**Comment by fransboumans** [comment]
Any updates on this?

**Review by lorant-csonka — APPROVED** [review]

**Comment by stuartmorgan** [comment]
Thanks for the submission! We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

The underlying issue here is that `evaluatePolicy:localizedReason:reply:`'s callback can be called on any thread; this PR one specific bug related to that, but there's other code—notably the replies to the Flutter engine—in that codepath that should also be done on the main thread, so the dispatch needs to be moved up a level.

@severance88 Are you still interested in working on this? If so, you can adjust it as described above. If not, I can take over this PR to make the necessary changes (and look into adding a test).

**Comment by stuartmorgan** [comment]
The fix ended up being more involved as other methods were impacted, and there was additional refactoring for testability, so I ended up making a new PR. Closing in favor of https://github.com/flutter/plugins/pull/3778.

Thanks again for the initial pass at a fix!

**Pull request closed without merging**
