### PR TITLE
[in_app_purchases] Remove TypeMatcher reference

### PR DESCRIPTION
**Pull request by Piinks**
This removes a reference to the TypeMatcher class that is scheduled for removal in https://github.com/flutter/flutter/pull/73751

An identically named `TypeMatcher` class is being used from `package:test/test.dart`.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by cyanglaz — APPROVED** [review]
LGTM!

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by cyanglaz** [comment]
rebase after https://github.com/flutter/plugins/pull/3502 will fix the ci issue.

**Comment by Piinks** [comment]
@cyanglaz this appears to be blocked for a different reason now, what is the `publishable` check?

**Comment by cyanglaz** [comment]
the `publishable` checks if the updated package meets all the requirement to be published (e.g. Is the version update correct?) 
I don't think the failure is legit. It could be a flake. I'm going to fire off a re-run

**Comment by cyanglaz** [comment]
CI issue fixed in https://github.com/flutter/plugins/pull/3506, you should be able to pass the ci after rebasing. @Piinks

**Comment by Piinks** [comment]
🤦‍♀️  lol

**Pull request merged**
