### PR TITLE
[local_auth] Replace `USE_FINGERPRINT` to `USE_BIOMETRIC` post deprecation in example and README

### PR DESCRIPTION
**Pull request by iamsahilsonawane**
Replacing deprecated `android.permission.USE_FINGERPRINT` permission with `android.permission.USE_BIOMETRIC`

Fixes https://github.com/flutter/flutter/issues/106298
Part of https://github.com/flutter/flutter/issues/78137

No change in flutter/tests

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by iamsahilsonawane** [comment]
Maintainers, please let me know what I need to add/update more for passing tests. I am new to contributing to the `flutter/*` open source. 

Thanks

**Comment by iamsahilsonawane** [comment]
@blasten @stuartmorgan 
The `USE_FINGERPRINT` is deprecated from API 28. In the code, there's implementation done for using biometrics for API 28 and higher and use fingerprint manager for less than that. How do we add biometric permission just for API 29 and higher but keep the fingerprint permission for API versions below 29?

I just added the `USE_BIOMETRIC` instead but that will add errors in the FingerprintManager, it requires `USE_FINGERPRINT` permission.

I am new to open source. I've marked this pull as draft. Thanks for the support.

**Comment by stuartmorgan** [comment]
> Maintainers, please let me know what I need to add/update more for passing tests.

The "Details" link for `publishable` will tell you why it is failing. The steps you skipped in the checklist have useful links for resolving that failure.

**Comment by iamsahilsonawane** [comment]
> > Maintainers, please let me know what I need to add/update more for passing tests.
> 
> The "Details" link for `publishable` will tell you why it is failing. The steps you skipped in the checklist have useful links for resolving that failure.

Thank you @stuartmorgan for the help. I'll check and continue on that.

**Comment by stuartmorgan** [comment]
> If you want to remove the need for this permission you'll need to restructure the code somewhat so that it doesn't use `FingerprintManager` at all.

This was done in https://github.com/flutter/plugins/pull/6059, so you could update this to just update the `local_auth` README and example.

**Comment by iamsahilsonawane** [comment]
@stuartmorgan Okay works! I'll update the README and example

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
> * [ ]  I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates).
> * [ ]  I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style).

These steps are needed for the `local_auth` change. (`local_auth_android`'s change only affects running a local checkout, so doesn't need them.)

**Comment by iamsahilsonawane** [comment]
@stuartmorgan 

> > * [ ]   I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates).
> > * [ ]   I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style).
> 
> These steps are needed for the `local_auth` change. (`local_auth_android`'s change only affects running a local checkout, so doesn't need them.)

I am not 100% sure if I should update the version from 2.1.0 to 2.1.1? Or just update to 2.1.0+1?

**Comment by iamsahilsonawane** [comment]
Yes as our change in the example doesn't fall into:
> PRs that only affect unpublished parts of example apps.

I think we should increase the version to 2.1.1

**Comment by iamsahilsonawane** [comment]
Sorry for the commits, I messed up with the message

**Comment by iamsahilsonawane** [comment]
Fixed the commit message issue

**Comment by iamsahilsonawane** [comment]
Please, let me know if there is still pending stuff. I'll update them ASAP. Thanks

**Comment by stuartmorgan** [comment]
> Or just update to 2.1.0+1?

We follow the guidance at https://dart.dev/tools/pub/versioning#semantic-versions (linked from the PR checklist), and do not use build numbers for anything >= 1.0.0.

**Review by stuartmorgan — APPROVED** [review]
LGTM, thanks!

@camsim99 will do the secondary review.

**Review by camsim99 — APPROVED** [review]
Thanks!!

**Comment by iamsahilsonawane** [comment]
Thank you guys!

**Pull request merged**
