### PR TITLE
Bracketing and properties preview

### PR DESCRIPTION
**Pull request by joecks**
New camera with bracketing and camera properties live preview.

Please have a look if you are interessed, I could cleanup the PR and create a proper request asap:

TODO
- add docs
- add the bracketing functionality to the example app 
- fix other platforms (right now only Android works , and I am not sure if I can implement the iOS support - but it should be possible)
- fix local paths in the pubspec

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [ ] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by ditman** [comment]
Hey @joecks, a few questions:

* are you planning on keeping working on the TODOs that you listed? I think I'll mark this PR as a "WIP" until you're done.
* is this a new feature, or are you working on an existing issue? Can you add a link to the flutter issue? (If this is a new feature, can you please create the issue yourself, and link to it in the description of this PR?)
* are you planning on adding more platforms to this, or only Android? Is this supported in other platforms? (Looking at the web [it seems that bracketing is not supported as a standard capability](https://developer.mozilla.org/en-US/docs/Web/API/ImageCapture/getPhotoCapabilities#return_value), what should this do in the web? Return a single photo? Crash with an UnimplementedException?)

**Comment by joecks** [comment]
I would love to continue on that. There is no Issue related to that (or I need to check if I find one) but I can create one. 
- Web: unimplemented exception would be the way to go for now (quick google search revealed that there is  Webcam.burst_snap, so maybe this could work in the future)
- iOS: I would love to add this functionality but I need to submerge myself in the ios camera api


@ditman  would you be so kind and give me a bit of feedback on the API that I have chosen, so that I can avoid extra refactors down the line.

**Comment by ditman** [comment]
> @ditman would you be so kind and give me a bit of feedback on the API that I have chosen, so that I can avoid extra refactors down the line.

@joecks I'm not an Android Camera expert by any means, but in general I'd recommend you:

* Do not delete the checklist from the new PR template, it has useful info on what extra steps need to be done (I'll restore this for you)
* **Create a new issue** where you describe the issue that you're trying to solve, and maybe your ideas on how to solve this. That way people will be able to refer to that issue to understand why this PR happened (in this case, it'd be something like: "camera plugin does not support bracketing exposure, so I can't do HDR imaging" or similar)
* Small typo in `BracketingCamara` class, should be `BracketingCamera` (Note: Cam<ins>**e**</ins>ra)
* Why a new camera that only takes bracketed images? Can that feature be incorporated in the already existing camera? It seems a little bit wasteful to do: new BracketedCamera(); then discard it right away?
* Needs way more tests :)

Again, I'm not the best person for this particular bit of code. I'm going to mention @blasten (for more concrete Android guidance) and @mvanbeusekom (to ensure this doesn't clash with future developments of the camera plugin), see if they have better ideas/comments WRT the chosen API.

**Comment by ditman** [comment]
Note, about iOS:

* https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/capturing_still_and_live_photos/capturing_a_bracketed_photo_sequence

**Comment by Hixie** [comment]
@joecks Since you have not signed the CLA I'm afraid we can't take this contribution. If you would like to sign the CLA we would be more than happy to look at the PR. I'm going to close this one for now but don't hesitate to submit a new one if you are able to sign the CLA. Thanks!

**Pull request closed without merging**
