### PR TITLE
Fix FirebaseSortedList onChange handling

### PR DESCRIPTION
**Pull request by kroikie**
_snapshots was not being updated when a change was made.
This resulted in list items displaying stale values. This
change matches what is used in FirebaseList which does
correctly handle onChange.

### CODE REVIEW

**Comment by sethladd** [comment]
Thanks!

cc @collinjackson

**Comment by sethladd** [comment]
cc @goderbauer while @collinjackson is OOO

**Comment by goderbauer** [comment]
Thanks!

**Comment by goderbauer** [comment]
This is now live: https://pub.dartlang.org/packages/firebase_database

**Pull request merged**
