### PR TITLE
[flutter_fire] Use Gradle BoM with FlutterFire

### PR DESCRIPTION
**Pull request by kroikie**
## Description

Use Gradle BoM to keep Android dependencies compatible.

### CODE REVIEW

**Comment by ened** [comment]
Please update the README to reflect what is needed (settings.gradle changes) once the PR has landed.

**Comment by creativecreatorormaybenot** [comment]
Well, also it does not work for me: https://github.com/flutter/flutter/issues/30606

**Comment by J1GGZ** [comment]
Did you already upgrade your project to androidX?

**Comment by creativecreatorormaybenot** [comment]
@J1GGZ Can you even use the latest FlutterFire without doing so?

**Comment by kroikie** [comment]
@ened Added BoM instruction to READMEs

**Comment by kroikie** [comment]
Sounds good, I will revert `firebase_core` and `cloud_firestore` to version matching those found in `firebase-bom:17.0.0`

**Pull request closed without merging**
