### PR TITLE
[google_sign_in] Add implementations of requestScopes.

### PR DESCRIPTION
**Pull request by emerssso**
## Description

Adds implementation for `requestScopes` method introduced to the plugin interface in  #2547.

Recreated since I messed up rebasing after first PR. 

## Related Issues

* flutter/flutter#50208

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by ditman** [comment]
The web part of this, looks good to me!

**Comment by emerssso** [comment]
That's the primary one (basically approach scopes the same as other permissions). This way, we ask for permission to sensitive data in the context where it makes sense.

The other is to handle adding scopes as part of an app update. We see issues adding new scopes to the constructor when a user has signed in before an update that adds a scope (issues vary by platform). This way, we won't have to sign users out when we add scopes.

**Comment by ditman** [comment]
> We see issues adding new scopes to the constructor when a user has signed in before an update that adds a scope

This sounds very interesting. I'm not sure if this is documented anywhere in the Google Sign In API or similar, but it'd probably be worth a medium blog post or similar! We can help you publish an article about this progressive approach to scopes, if you're interested in writing it!

**Comment by emerssso** [comment]
> if you're interested in writing it!

It does sound like something worth writing, I'll ping you about it offline.

**Comment by emerssso** [comment]
> iOS and Android part looks good. Could we possibly add JUnit tests and XCTests?
Happy to, I just couldn't find any existing ones for this plugin (and couldn't figure out how to add some easily). Do they live somewhere else and I just missed them?

**Comment by ditman** [comment]
PS @emerssso, a g3 issue just prompted [this PR](https://github.com/flutter/plugins/pull/2602), it'll cause some (easy) conflicts in the pubspec + changelog of your _web changes. My apologies!

**Comment by emerssso** [comment]
@ditman, No problem, thanks for the heads up!

**Pull request merged**
