### PR TITLE
[video_player] not muted video sound when mute control of device is muted

### PR DESCRIPTION
**Pull request by jerryzhoujw**
[issues:48558](https://github.com/flutter/flutter/issues/48558)

### CODE REVIEW

**Comment by cbenhagen** [comment]
This is already done on plugin init. https://github.com/flutter/flutter/issues/47524 tracks this issue and https://github.com/flutter/plugins/pull/2434 fixes it.

**Comment by otopba** [comment]
Also this is about AVAudioSession
https://github.com/flutter/plugins/pull/1174

**Comment by jerryzhoujw** [comment]
Thank you for mention me about that. @cbenhagen @otopba

I simply query issue by `[video_player]`, and didn't see any obvious issue title mentioned `mute`, so I create this.

Maybe I need read more details in every related issues.

I'll leave this PR open till your mentioned PR get merged, after that I will close this.

Thanks.

**Comment by cbenhagen** [comment]
https://github.com/flutter/plugins/pull/2434 has been merged. Can this PR be closed?

**Comment by jerryzhoujw** [comment]
@cbenhagen sure.

**Pull request closed without merging**
