### PR TITLE
[video_player_platform_interface] Migrate to null safety

### PR DESCRIPTION
**Pull request by blasten**
Null safety migration.

FYI @gaaclarke the Dart code generated by Pigeon had trailing whitespaces.

### CODE REVIEW

**Review by gaaclarke — APPROVED** [review]
I read through the pigeon stuff, looks good to me.  The addition of the dart-null-saftey flag happens in a different repo right?

**Comment by blasten** [comment]
The linter for darwin plugins is complaining about  the generated file `messages.m`. https://api.cirrus-ci.com/v1/task/4714658705702912/logs/main.log

FYI @gaaclarke 

@jmagman do you know if there's a way to disable the linter for auto generated files?

**Comment by jmagman** [comment]
> The linter for darwin plugins is complaining about the generated file `messages.m`. https://api.cirrus-ci.com/v1/task/4714658705702912/logs/main.log
> 
> FYI @gaaclarke
> 
> @jmagman do you know if there's a way to disable the linter for auto generated files?

I don't think we should ignore it, our developers using the plugin will see the same warning.  Can we fix the generation?

**Comment by gaaclarke** [comment]
https://github.com/flutter/flutter/issues/63966  This is the issue.  If i remember correctly that it is no longer an analysis error in later versions of clang =(

**Comment by gaaclarke** [comment]
This analyzer can be turned off with the CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION environment variable.  Since the objection isn't a problem according to later versions of clang I'd rather disable that check.  You might be able to do it in the source file too but I didn't see a way.

**Comment by gaaclarke** [comment]
Alternatively, you can use the [`__clang_analyzer__`](https://clang-analyzer.llvm.org/faq.html#exclude_code) macro if you don't want to affect the other code.  Maybe we should add a flag for that since everyone could have all different analyzer settings.

**Comment by blasten** [comment]
@gaaclarke Done. 

@jmagman I agree. Ideally, the analyzer doesn't complain, but mostly likely we won't be able to enforce the same analyzer rules/version.

**Comment by jmagman** [comment]
> @jmagman I agree. Ideally, the analyzer doesn't complain, but mostly likely we won't be able to enforce the same analyzer rules/version.

True we can't enforce it, but most people won't change the default from the `flutter create` template.  Ideally the plugins would have as many checks on as possible and then not have warnings in the strictest mode.

**Comment by blasten** [comment]
Agreed. For my own understanding, what file is defining the linter rules?   Is this file/configuration from `flutter create` or custom made for the plugins repo?

**Comment by jmagman** [comment]
In this case, it's coming from the CocoaPods tooling
https://github.com/CocoaPods/Xcodeproj/blob/08ed2bf777e9108a6445ea3fdd9718af4f684e3e/lib/xcodeproj/constants.rb#L357

**Comment by gaaclarke** [comment]
> many checks on as possible and then not have warnings in the strictest mode.

The problem is that clang has redefined the meaning of some checks.  In this case something that was a warning in one version became acceptable in a later version.  It's untenable to maintain support for the union of the strictest settings of all versions of clang for all possible settings.  Ideally we run the analyzer once as part of CI for pigeon, then opt out of analysis when it's used (with a flag to turn it on if people want).

**Pull request merged**
