### PR TITLE
[google_maps_flutter] Adds support for displaying the traffic layer

### PR DESCRIPTION
**Pull request by athornz**
## Description

Adds a toggle for the Google Maps Traffic layer.

## Related Issues

https://github.com/flutter/flutter/issues/25334

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by athornz** [comment]
@iskakaushik @amirh would really appreciate your review if you get a chance.

**Comment by iskakaushik** [comment]
Can you add some tests which get `isTrafficLayerEnabled` information from the underlying google maps sdk? Take a look at https://github.com/flutter/plugins/pull/1809/files#diff-348a670c92aab89f861ab1aa02260a7b for example on how to do this. Thanks!

**Comment by athornz** [comment]
@iskakaushik done :)

**Comment by athornz** [comment]
@iskakaushik do you require any other changes for this to merge?

**Comment by sensudipta** [comment]
@iskakaushik I have been waiting for this merge to complete, my production app needs the feature this branch provides. Thanks in advance.

**Comment by iskakaushik** [comment]
Thanks for this contribution!

**Comment by monnguyen2512** [comment]
@athornz please fix trafficEnabled on Android

**Comment by athornz** [comment]
@monnguyen2512 should be an easy fix - maybe give it a go yourself?

**Comment by monnguyen2512** [comment]
@athornz ok, I fixed it

**Pull request merged**
