### PR TITLE
[cloud_functions] fix `Firebase/Functions` pod version

### PR DESCRIPTION
**Pull request by hariprasadiit**
## Description

Recent `cloud_functions` update tries to load `Firebase/functions` `6.0` version which doesn't exists. Most recent version of [`Firebase/functions`](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseFunctions.podspec) pod is `2.5.0`.

This PR removes version dependency to let pod use the recent version of `Firebase/functions`

## Related Issues

fixes [#32400](https://github.com/flutter/flutter/issues/32400)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by collinjackson** [comment]
Since the cloud_functions integration tests are running fine on Cirrus I'm wondering what's different between your setup and CI. Does running "pod repo update" help?

**Comment by hariprasadiit** [comment]
```
 Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "Firebase/Functions":
      In Podfile:
        cloud_functions (from `.symlinks/plugins/cloud_functions/ios`) was resolved to 0.0.1, which depends on
          Firebase/Functions (~> 6.0)
    Specs satisfying the `Firebase/Functions (~> 6.0)` dependency were found, but they required a higher minimum deployment target.
```

@collinjackson this is the `pod install` output. It says it can't find compatible version because `Firebase/Functions (~> 6.0)` doesn't exists.

below is the snippet which shows `Firebase/Functions` pod version from the official repo
```
Pod::Spec.new do |s|
  s.name             = 'FirebaseFunctions'
  s.version          = '2.5.1'
  s.summary          = 'Cloud Functions for Firebase iOS SDK.'

  s.description      = <<-DESC
iOS SDK for Cloud Functions for Firebase.
```

**Comment by collinjackson** [comment]
Here's my Podfile.lock for the Cloud Functions example. You can see it's referencing `Firebase/Functions (6.1.0)`. So that isn't problem.

It looks like the issue is in the error message: `Specs satisfying the `Firebase/Functions (~> 6.0)` dependency were found, but they required a higher minimum deployment target.`

Can you try increasing the minimum deployment target and see if that helps?

```
PODS:
  - cloud_functions (0.0.1):
    - Firebase/Core
    - Firebase/Functions (~> 6.0)
    - Flutter
  - Firebase/Core (6.1.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.0.1)
  - Firebase/CoreOnly (6.1.0):
    - FirebaseCore (= 6.0.1)
  - Firebase/Functions (6.1.0):
    - Firebase/CoreOnly
    - FirebaseFunctions (~> 2.5.1)
  - firebase_core (0.0.1):
    - Firebase/Core
    - Flutter
  - FirebaseAnalytics (6.0.1):
    - FirebaseCore (~> 6.0)
    - FirebaseInstanceID (~> 4.1)
    - GoogleAppMeasurement (= 6.0.1)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (6.0.1):
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/Logger (~> 6.0)
  - FirebaseFunctions (2.5.1):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 6.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseInstanceID (4.1.0):
    - FirebaseCore (~> 6.0)
    - GoogleUtilities/Environment (~> 6.0)
    - GoogleUtilities/UserDefaults (~> 6.0)
  - Flutter (1.0.0)
  - GoogleAppMeasurement (6.0.1):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.0)
    - GoogleUtilities/MethodSwizzler (~> 6.0)
    - GoogleUtilities/Network (~> 6.0)
    - "GoogleUtilities/NSData+zlib (~> 6.0)"
    - nanopb (~> 0.3)
  - GoogleUtilities/AppDelegateSwizzler (6.2.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.2.0)
  - GoogleUtilities/Logger (6.2.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (6.2.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (6.2.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.2.0)"
  - GoogleUtilities/Reachability (6.2.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (6.2.0):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.2.2)
  - nanopb (0.3.901):
    - nanopb/decode (= 0.3.901)
    - nanopb/encode (= 0.3.901)
  - nanopb/decode (0.3.901)
  - nanopb/encode (0.3.901)

DEPENDENCIES:
  - cloud_functions (from `.symlinks/plugins/cloud_functions/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - Flutter (from `.symlinks/flutter/ios`)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - Firebase
    - FirebaseAnalytics
    - FirebaseAuthInterop
    - FirebaseCore
    - FirebaseFunctions
    - FirebaseInstanceID
    - GoogleAppMeasurement
    - GoogleUtilities
    - GTMSessionFetcher
    - nanopb

EXTERNAL SOURCES:
  cloud_functions:
    :path: ".symlinks/plugins/cloud_functions/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  Flutter:
    :path: ".symlinks/flutter/ios"

SPEC CHECKSUMS:
  cloud_functions: 19aaf8cd4dd6beac9ccd43422d5225338e1931c2
  Firebase: 8d77bb33624ae9b62d745d82ec023de5f70f7e4f
  firebase_core: c96aa8b2fcf7f5167d32f22034f502f9304952b8
  FirebaseAnalytics: 629301c2b9925f3537d4093a17a72751ae5b7084
  FirebaseAuthInterop: 0ffa57668be100582bb7643d4fcb7615496c41fc
  FirebaseCore: 66bdef3b310a026880e2a5bc8aa586ab62ce4543
  FirebaseFunctions: 5af7c35d1c5e41608fecbb667eb6c4e672e318d0
  FirebaseInstanceID: 27bed93a59b6685f5c3e0c028a878a764fd75c33
  Flutter: 9d0fac939486c9aba2809b7982dfdbb47a7b0296
  GoogleAppMeasurement: 51d8d9ea48f0ca44484d29cfbdef976fbd4fc336
  GoogleUtilities: 996e0db07153674fd1b54b220fda3a3dc3547cba
  GTMSessionFetcher: 61bb0f61a4cb560030f1222021178008a5727a23
  nanopb: 2901f78ea1b7b4015c860c2fdd1ea2fee1a18d48

PODFILE CHECKSUM: aff02bfeed411c636180d6812254b2daeea14d09

COCOAPODS: 1.5.3
```

**Comment by collinjackson** [comment]
I tried setting a deployment target of 8.0 and that seemed to work for me as well. When I use a deployment target of 7.0 I get an error.

```
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
[!] CocoaPods could not find compatible versions for pod "cloud_functions":
  In Podfile:
    cloud_functions (from `.symlinks/plugins/cloud_functions/ios`)

Specs satisfying the `cloud_functions (from `.symlinks/plugins/cloud_functions/ios`)` dependency were found, but they required a higher minimum deployment target.
```

After updating to 8.0:

```
jackson-macbookpro4:ios jackson$ pod update cloud_functions
Updating local specs repositories
  $ /usr/local/git/current/bin/git -C /Users/jackson/.cocoapods/repos/master fetch origin --progress
  remote: Enumerating objects: 14, done.        
  remote: Counting objects: 100% (14/14), done.        
  remote: Compressing objects: 100% (7/7), done.        
  remote: Total 9 (delta 5), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     d095fe35c75..de543b1a19e  master     -> origin/master
  $ /usr/local/git/current/bin/git -C /Users/jackson/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/git/current/bin/git -C /Users/jackson/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at de543b1a19e [Add] MocaLock 0.1.0

CocoaPods 1.7.1 is available.
To update use: `gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.7.1

Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `cloud_functions` from `.symlinks/plugins/cloud_functions/ios`
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
Downloading dependencies
Using Firebase (6.1.0)
Using FirebaseAnalytics (6.0.1)
Using FirebaseAuthInterop (1.0.0)
Using FirebaseCore (6.0.1)
Using FirebaseFunctions (2.5.1)
Using FirebaseInstanceID (4.1.0)
Using Flutter (1.0.0)
Using GTMSessionFetcher (1.2.2)
Using GoogleAppMeasurement (6.0.1)
Using GoogleUtilities (6.2.0)
Using cloud_functions (0.0.1)
Using firebase_core (0.0.1)
Using nanopb (0.3.901)
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 13 total pods installed.
```

I'm not sure if there's an action to be taken here, but I don't think this PR is the answer. I don't think we should remove the 6.0 minimum because we're using APIs that were introduced in that release. 

If you have suggestions for ways to improve this situation further, please open a new issue or PR. Thanks!

**Pull request closed without merging**
