### PR TITLE
Update README.md adding device_info

### PR DESCRIPTION
**Pull request by mit-mit**
Add device info and local auth

### CODE REVIEW

**Comment by mit-mit** [comment]
Actually, looks like `device_info` and `local_auth` havn't been published yet. Are they not ready to consume yet? @yjbanov @mehmetf

**Comment by mehmetf** [comment]
`device_info` Probably ready.
`local_auth` See discussion https://github.com/flutter/plugins/pull/151 about i18n. We have not done the fix suggested there yet. I will reach out to Alan to figure out how.

**Comment by yjbanov** [comment]
Some customers started reporting Dart exceptions to Sentry and other places, and might want to use `device_info` soon. It would be nice to publish it.

**Comment by mit-mit** [comment]
I'm leaving for vacation tonight. Please merge this PR once they have been published!

**Comment by mit-mit** [comment]
Hi @mehmetf, any news on getting these published?

**Comment by mehmetf** [comment]
@mit-mit Let's publish device_info and submit that portion of this PR.

It will take a while to figure out the story for local_auth. @HansMuller is working on i18n and his work will decide when `local_auth` is ready.

**Comment by mit-mit** [comment]
Sounds good, PR updated

**Pull request merged**
