### PR TITLE
[share] add native file sharing feature

### PR DESCRIPTION
**Pull request by Kiruel**
Add native file sharing functionality and fix issue from https://github.com/flutter/plugins/pull/970

### CODE REVIEW

**Comment by ca333** [comment]
I signed it!

**Comment by ca333** [comment]
I signed it!

**Comment by Kiruel** [comment]
I signed it!

**Comment by ca333** [comment]
@ianloic @sethladd can you plz help us - we signed both the CLA but the commit email is diff. We cant change that. Can you set cla:yes plz

**Comment by bbedward** [comment]
Would love to see this get merged, I've been using it for months now as a git dependency.

**Comment by Kiruel** [comment]
I signed it.

**Comment by Kiruel** [comment]
@ianloic @sethladd Hi guys, how many time we need to wait for this PR ? (opening in mars 2019.)

**Comment by Kiruel** [comment]
Btw I use this change in my main project with no problem during all this months.

**Comment by pboos** [comment]
Thanks for your fixes :). Didn't see this pull request. Could probably have saved myself time rewriting everything and start off from your branch!
I have updated my pull request #970 and actually fixed a small bug that seems to exist in this code (on iOS related to text + file if I remember correctly).

Please try my branch to see if that one works as well for you. Or if you have any comments there.

**Pull request closed without merging**
