### PR TITLE
[video_player]Get duration from underlying asset

### PR DESCRIPTION
**Pull request by cbenhagen**
Fixes https://github.com/flutter/flutter/issues/26817

### CODE REVIEW

**Comment by iskakaushik** [comment]
Can you describe why getting the duration from the underlying asset fixes this issue?

**Comment by cbenhagen** [comment]
The value of duration property will be reported as kCMTimeIndefinite until the duration of the underlying asset has been loaded.  So we can either wait for AVPlayerItemStatusReadyToPlay or get the duration from the underlying asset.

**Comment by cbenhagen** [comment]
Please also check the the example in the linked issue: https://github.com/flutter/flutter/issues/26817

**Comment by iskakaushik** [comment]
After looking at the docs at: https://developer.apple.com/documentation/avfoundation/avplayeritem/1389386-duration?language=objc, it seems to me that getting it from the asset also doesn't guarantee correctness as seen in the question at: https://stackoverflow.com/questions/23874574/avplayer-item-get-a-nan-duration.

Should we follow the doc guidelines and take one of:

1. Wait until the status of the AVPlayerItem is AVPlayerItemStatusReadyToPlay.

or

2. Register for key-value observation of the duration property, requesting the initial value. If the initial value is reported as kCMTimeIndefinite, the AVPlayerItem will notify you of the availability of the item's duration via key-value observing as soon as its value becomes known.

@cbenhagen let me know what you think.

**Comment by cbenhagen** [comment]
I am not sure what would be the best option. My guess would be to wait for `AVPlayerItemStatusReadyToPlay`.

**Comment by iskakaushik** [comment]
@cbenhagen agreed, can you make that change to this PR?

**Comment by cbenhagen** [comment]
Hmm in the current code it actually looks like we are correctly waiting for `AVPlayerItemStatusReadyToPlay`. I am also unable to reproduce the issue with the code I posted in https://github.com/flutter/flutter/issues/26817. I guess I'll close both this PR and the issue.

**Comment by cbenhagen** [comment]
Sorry I need to reopen this. While in the test code I was not being able to reproduce, in a full app I was. Need to check why. The fix in here, or another solution still needs to be applied.

**Comment by recastrodiaz** [comment]
Looks like this may have already been fixed in master with https://github.com/flutter/plugins/pull/1554/files#diff-e534c460662d39cc715c4eed77a31c3fR308

I'm not seeing any duration issues on iOS anymore.

**Pull request closed without merging**
