### PR TITLE
[url_launcher]ios whose view is not in the window hierarchy!

### PR DESCRIPTION
**Pull request by LDXu**
ios error whose view is not in the window hierarchy!find presentedViewController and use it

### CODE REVIEW

**Comment by cyanglaz** [comment]
Could you explain the issue that this PR is trying to fix in more detail? Or link this PR to an issue ticket?

**Comment by ashkryab** [comment]
when Navigator.push called new page openned under th webView (safari controller)... launched url didnt close

**Comment by cyanglaz** [comment]
@ashkryab Do you want to explain the detail in an issue ticket?

**Comment by stuartmorgan** [comment]
Closing since it's still not clear what issue this is trying to address. If you still want to move forward with this, please file an issue clearly describing the issue, with a reproducible sample, then open a PR referencing that issue. We would also need tests associated with the PR. Thanks!

**Pull request closed without merging**
