### PR TITLE
[share] Do not tear down channel onDetachedFromActivity.

### PR DESCRIPTION
**Pull request by zhenqiu1101**
We should not tear down the method channel onDetachedFromActivity. That will cause MissingPluginException for the following method calls. internal: b/183065251. Open source issue: flutter/flutter#12264

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by zhenqiu1101** [comment]
Open source issue: https://github.com/flutter/flutter/issues/12264

**Comment by xster** [comment]
This is sooooo good! Awesome find! This totally makes sense. The current implementation doesn't work since it's not symmetrical between engine attach/detach and activity attach/detach.

**Review by xster — APPROVED** [review]

**Comment by zhenqiu1101** [comment]
@cyanglaz 

Hi Chris, could you advice on the test failures?

**Comment by zhenqiu1101** [comment]
Chris is on leave. @stuartmorgan could you please advice on the test failures? It looks unrelated the PR. iOS share test and url_launcher plugin. Wanna make sure that the PR is safe to merge. Thanks!

**Comment by stuartmorgan** [comment]
We can land this since it's affecting an internal customer, but we're in the process of turning this plugin down in favor of https://pub.dev/packages/share_plus; see the notice in CONTRIBUTING.md. You should submit this fix there as well since at some point there should be a transition to that version, and you'll want to have this fix there as well.

**Pull request merged**
