### PR TITLE
[ci] Run iOS drive master tests on Apple Silicon

### PR DESCRIPTION
**Pull request by jmagman**
In the `master` drive tests use `--enable-software-rendering` flag implemented in https://github.com/flutter/flutter/pull/105161

Part of https://github.com/flutter/flutter/issues/104523
See also https://github.com/flutter/plugins/pull/5794 and https://github.com/flutter/plugins/pull/5693

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by fkorotkov** [comment]
Seems like the same hanging symptoms like before. Will try to reproduce locally [like before](https://github.com/flutter/flutter/issues/104523#issuecomment-1138909885) but since you are forcing not to use Metal inside the simulator it means the GPU is crashing when simulator's UI is rendered. Seems like the problem is isolated to the outside of Flutter's environment inside the simulator.

Which means that the original workaround might be a better option. Just add the following command as the first line in `create_simulator_script`. @stuartmorgan what do you think?


```
defaults write com.apple.CoreSimulator.IndigoFramebufferServices FramebufferRendererHint 3
```

**Comment by stuartmorgan** [comment]
Seems worth trying.

Is there a longer term strategy to address this problem? Relying on an undocumented default is fragile; it could break in any simulator update. Is there a a Radar we can reference in a comment on this hack?

**Comment by jmagman** [comment]
> Which means that the original workaround might be a better option. Just add the following command as the first line in `create_simulator_script`. @stuartmorgan what do you think?
> 
> ```
> defaults write com.apple.CoreSimulator.IndigoFramebufferServices FramebufferRendererHint 3
> ```

Reverted the `--enable-software-rendering` change, trying `FramebufferRendererHint`

**Comment by stuartmorgan** [comment]
It seems like if anything it's even worse now.

**Comment by fkorotkov** [comment]
@stuartmorgan seems the same. Let me see what could change since May 26th.

**Comment by fkorotkov** [comment]
I have good news and bad news. I was able to get a hold on a support engineer from Apple who looked into my report and talked to the people behind `Virtualization.Framework` and related stuff internally.

Bad news is that they don't believe that `IndigoFramebufferServices` does anything. It seems I was wrong and got a wrong impression that the command passed. I think I might have copy/pasted a command for `macos` tests instead of `ios` or something like that.

The support engineer asked me a bit more questions but his general suggestion and a message from the rest of the team was to try out macOS Ventura.

So I tried the private beta of Ventura with the current stable Xcode 13.4.1 and everything worked. This time I've tripple checked that I was running the right `./script/tool_runner.sh drive-examples --ios` command and not `--macos`. I repeated the experiment several times in fresh VMs and every time it passed.

Unfortunately it seems we don't have other options but to wait for macOS Ventura Public Beta in a month or so (I don't think we can legally use macOS Ventura for public CI while it's in private beta). On a bright side we found the issue with `master` -> `main` mirroring which caused unwanted builds and we also dropped prices on both old and new macOS instances. Sorry about this blocker. We are doing some bleeding edge stuff here after all.

**Comment by jmagman** [comment]
Closing.

**Pull request closed without merging**
