### PR TITLE
[video_player]added adaptive track selector for MPEG-dash format in android

### PR DESCRIPTION
**Pull request by smm13344331**
The default implementation was not using adaptive track selector and the player was unable to play resources pointing to a MPD manifest file for MPEG-dash format.
I have used AdaptiveTrackSelection factory as the default TrackSelectionFactory.
Tested against normal MP4 and MPEG-dash formats.

### CODE REVIEW

**Comment by smm13344331** [comment]
I signed it!

**Comment by smm13344331** [comment]
Would anyone care to explain what when wrong with my pull request and how can I make it right?

**Comment by Hixie** [comment]
@smm13344331 looks like it got confused when you rebased. I recommend trying to submit a new PR and closing this one. Alternatively, you can try to rebase locally and squash your commits such that you have one local commit, then force push to your branch (which will cause the PR to update and the  clabot to be happier).

**Comment by smm13344331** [comment]
@Hixie seems like one of the checks is stalled. can I do anything about this?

**Comment by Hixie** [comment]
Looks like a GitHub bug. If you look in the list of checks, the same check on Cirrus says it passed.

**Comment by iskakaushik** [comment]
reviewer note: consider unifying the logic https://github.com/flutter/plugins/pull/756 and this PR for uri filetype parsing.

**Comment by DQvsRA** [comment]
Hello, when to expect this will be merged?

**Comment by smm13344331** [comment]
> Looks like a GitHub bug. If you look in the list of checks, the same check on Cirrus says it passed.

Is this going to be a problem? Do I need to take any further action?

**Comment by smm13344331** [comment]
> Hello, when to expect this will be merged?

Hi,
This PR has been around for sometime and I have no idea if it's ever going to be merged! All the changes are in android and they are rather safe to use, so feel free to cherry pick the changes and add them to your local version of flutter.

**Comment by cbenhagen** [comment]
@smm13344331 thank you for your contribution! Unfortunately the structure of the plugin has changed lately to support implementations on more platforms. Mainly the plugin was moved to a new subdirectory and now uses a common platform interface. Adapting your PR to the new structure should be straight forward. If you have questions please ask!

Please also make sure to include tests for the new functionality.

**Comment by Hixie** [comment]
Looking at this PR, I presume the reason it hasn't been merged is that it is lacking tests. I'm not sure if we yet have the technology to write tests for this kind of plug-in, though.

cc @mklim @cyanglaz @collinjackson

**Comment by smm13344331** [comment]
@Hixie I was going to ask about ideas around, how to write a test for this. :))

**Comment by mklim** [comment]
Thank you for the contribution and your patience. I'm sorry this PR has been left hanging for so long.

I think there's two potential ways to test this.

Assuming I'm understanding the fix right, the first and most robust way would be to add a Flutter driver test with e2e asserting that the plugin can play the MPD manifest file correctly now. That would also involve adding that file type to the example app. You would add a test case [here](https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/example/test_driver/video_player_e2e.dart).

If for some reason that doesn't work, you could also add a JUnit test directly testing `VideoPlayerPlugin.java` directly. We don't have an example of this in `video_player` yet but some of our other plugins do it, like [camera](https://github.com/flutter/plugins/blob/master/packages/camera/android/src/test/java/io/flutter/plugins/camera/DartMessengerTest.java). The difficult part here is importing the plugin into Android Studio or another Java IDE so that you can develop JUnit tests there. What's always worked for me is opening the `android` folder of the example app of the plugin.

**Comment by blasten** [comment]
Thank you for your contribution. While your efforts are well intentioned, it is with regret that we have to close this PR as we are only accepting patches from existing contributors at this time. If you have not yet done so I encourage you to file an issue describing the problem you have attempted to fix here. If you mention this PR on that issue, we will return to it when we have the bandwidth to address that issue.

**Comment by smm13344331** [comment]
> Thank you for your contribution. While your efforts are well intentioned, it is with regret that we have to close this PR as we are only accepting patches from existing contributors at this time. If you have not yet done so I encourage you to file an issue describing the problem you have attempted to fix here. If you mention this PR on that issue, we will return to it when we have the bandwidth to address that issue.

I'm sorry to hear that. I know how hard it is to handle a huge number of PRs and Issues. 
Flutter is a great project and you guys are doing a great job. I hope I'll be able contribute to this project in the future.

**Pull request closed without merging**
