### PR TITLE
[path_provider] Bump kotlin to 1.7.10

### PR DESCRIPTION
**Pull request by GaryQian**
Fixes https://github.com/flutter/flutter/issues/109397 after large gradle bump in https://github.com/flutter/plugins/pull/6189

### CODE REVIEW

**Review by camsim99 — APPROVED** [review]
Thanks!

**Review by christopherfujino — APPROVED** [review]
Thanks!

**Comment by GaryQian** [comment]
Landing to fix tree

**Comment by christopherfujino** [comment]
@GaryQian FYI the `waiting for tree to go green` label has been deprecated, `autosubmit` is the new hotness.

**Comment by GaryQian** [comment]
Ahh! Ok, I've been seeing Autosubmit, was not aware of the formal switch to it. Thanks!

**Pull request merged**
