### PR TITLE
[camera] Check supportsAVCaptureSessionPreset for init camera on iOS

### PR DESCRIPTION
**Pull request by britov**
We have a recurring crash from users with iPhone 7 and iPhone 7 Plus 

```
Crashed: Thread
NSInvalidArgumentException *** -[AVCaptureSession addInputWithNoConnections:] Can't add <AVCaptureDeviceInput: 0x28b27c760 [Камера на передней панели]> because the device does not support AVCaptureSessionPresetHigh - Use -[AVCaptureDevice supportsAVCaptureSessionPreset:]
0  CoreFoundation           __exceptionPreprocess + 216
1  libobjc.A.dylib          objc_exception_throw + 56
2  AVFCapture               -[AVCaptureSession _addInputWithNoConnections:exceptionReason:] + 0
3  camera                   -[FLTCam initWithCameraName:resolutionPreset:enableAudio:orientation:dispatchQueue:error:] + 988
4  camera                   -[CameraPlugin handleMethodCallAsync:result:] + 1264
5  libdispatch.dylib        _dispatch_call_block_and_release + 24
6  libdispatch.dylib        _dispatch_client_callout + 16
7  libdispatch.dylib        _dispatch_lane_serial_drain$VARIANT$mp + 612
8  libdispatch.dylib        _dispatch_lane_invoke$VARIANT$mp + 424
9  libdispatch.dylib        _dispatch_workloop_worker_thread + 712
10 libsystem_pthread.dylib  _pthread_wqthread + 272
11 libsystem_pthread.dylib  start_wqthread + 8
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Thanks for the contribution!

> [ ] [NO NEED] I added new tests to check the change I am making, or this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests).

I'm not sure what in our documentation led you to believe this PR doesn't need tests; it definitely does. This doesn't meet the criteria for any of the test exemptions.

**Comment by stuartmorgan** [comment]
Also, you've checked a number of items in the list for things you haven't actually done: this doesn't have a version and CHANGELOG update, nor does it pass the auto-formatter check.

I'm going to mark this as a draft; please mark it as ready for review once you've actually completed the checklist. If you need help with any of the items, please let us know.

**Comment by britov** [comment]
> I'm going to correct the state of the checklist and mark this as a draft; please mark it as ready for review once you've actually completed the checklist. If you need help with any of the items, please let us know.

How to run failed ios-platform_test localy?

**Comment by stuartmorgan** [comment]
> [x] I added new tests to check the change I am making, or this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests).

Where is this test? I don't see it in the PR.

**Comment by britov** [comment]
> > [x] I added new tests to check the change I am making, or this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests).
> 
> Where is this test? I don't see it in the PR.

https://github.com/flutter/plugins/pull/4622/files#diff-613be77b84226d2c0776f1dd74e9909304627248c9b8f0536041048bd4bb0007R32
Is that not enough? I can add test like [this](https://github.com/flutter/plugins/pull/4622/files#diff-613be77b84226d2c0776f1dd74e9909304627248c9b8f0536041048bd4bb0007R52), but fix to reuse the code instead of duplicating it, if that test is what you want

**Comment by stuartmorgan** [comment]
> Is that not enough?

Adding some mocks to an existing test that was already paying is not enough, no. Nothing in that that test was asserting anything relating to what you are changing in this PR.

> I can add test like [this](https://github.com/flutter/plugins/pull/4622/files#diff-613be77b84226d2c0776f1dd74e9909304627248c9b8f0536041048bd4bb0007R52), but fix to reuse the code instead of duplicating it, if that test is what you want

Does that test fail if you revert your changes to the non-test code? I haven't tried running it, but reading it I don't see why it would (maybe I'm missing a key assertion, in which case adding comments would help).

If the answer to that question is no, then this isn't a meaningful test for this PR, as discussed in the contribution docs. You need a test that asserts that the thing you want to be true--here that appears to be that a specific API is not called under certain conditions--is true.

**Comment by britov** [comment]
You're right, but the thing is, it's a floating bug that I can't reproduce. Apparently these changes will remain here waiting for when I can reproduce this bug.

**Comment by stuartmorgan** [comment]
I'm a little confused. Are you saying you don't know that your changes are correct and fix the issue, or just that you're not sure how to test it?

**Comment by stuartmorgan** [comment]
Closing absent an answer to the question above. If you are interested in adding a test that the logic here works as expected (by using mock objects and validating the calls), please feel free to open a new PR.

**Pull request closed without merging**
