### PR TITLE
[WIP] [share] Add web support for share plugin

### PR DESCRIPTION
**Pull request by sidrao2006**
## Description

Add web support for share plugin

## Related Issues

[#55330](https://github.com/flutter/flutter/issues/55330)

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by jesusrp98** [comment]
@sidrao2006 any news on this?

**Comment by sidrao2006** [comment]
@jesusrp98 Not sure, but the maintainer suggested using flutter community's  plus plugins.

**Comment by QuentinCG** [comment]
Thanks for the update @sidrao2006

Are you speaking of this one ? (is it compatible with Desktop too ?)
https://pub.dev/packages/share_plus

**Comment by sidrao2006** [comment]
@QuentinCG for the 1st question, yes. As mentioned [here](https://github.com/fluttercommunity/plus_plugins#share_plus), MacOS is not supported yet

**Comment by QuentinCG** [comment]
Thanks a lot, really useful link :)

**Pull request closed without merging**
