### PR TITLE
[package_info] [firebase_remote_config] Allow reset of static variables in testing

### PR DESCRIPTION
**Pull request by thomas-stockx**
## Description

This adds a reset method to package_info and firebase_remote_config, to allow making sure that the behavior is always the same between multiple tests.

## Related Issues

We would have discrepancies when certain tests were run in a different order. Resetting the static variables between tests solves this.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by collinjackson** [comment]
Can you give me an example of what a test looks like that would use this test API? Is it a local unit test, a live test that runs on a device, or a driver test? It feels like we might want to push these singletons more in the direction of dependency injection but I'd like to understand more about how they're being used.

**Comment by cyanglaz** [comment]
For [package_info], we can add an optional parameter for `PackageInfo.fromPlatform()` to let it get a refreshed result. This way we don't break the API.
For example 
```
  static Future<PackageInfo> fromPlatform({bool refreshResult = false}) async {
    if (_fromPlatform == null || refreshResult) {
      final Completer<PackageInfo> completer = Completer<PackageInfo>();

      // TODO(amirh): remove this on when the invokeMethod update makes it to stable Flutter.
      // https://github.com/flutter/flutter/issues/26431
      // ignore: strong_mode_implicit_dynamic_method
      _kChannel.invokeMethod('getAll').then((dynamic result) {
        final Map<dynamic, dynamic> map = result;

        completer.complete(PackageInfo(
          appName: map["appName"],
          packageName: map["packageName"],
          version: map["version"],
          buildNumber: map["buildNumber"],
        ));
      }, onError: completer.completeError);

      _fromPlatform = completer.future;
    }
    return _fromPlatform;
  }
```

**Comment by thomas-stockx** [comment]
> For [package_info], we can add an optional parameter for `PackageInfo.fromPlatform()` to let it get a refreshed result. This way we don't break the API.
> For example
> 
> ```dart
>   static Future<PackageInfo> fromPlatform({bool refreshResult = false}) async {
>     if (_fromPlatform == null || refreshResult) {
>       final Completer<PackageInfo> completer = Completer<PackageInfo>();
> 
>       // TODO(amirh): remove this on when the invokeMethod update makes it to stable Flutter.
>       // https://github.com/flutter/flutter/issues/26431
>       // ignore: strong_mode_implicit_dynamic_method
>       _kChannel.invokeMethod('getAll').then((dynamic result) {
>         final Map<dynamic, dynamic> map = result;
> 
>         completer.complete(PackageInfo(
>           appName: map["appName"],
>           packageName: map["packageName"],
>           version: map["version"],
>           buildNumber: map["buildNumber"],
>         ));
>       }, onError: completer.completeError);
> 
>       _fromPlatform = completer.future;
>     }
>     return _fromPlatform;
>   }
> ```

Thanks for the feedback, and I agree this should probably be added.

But wouldn't this mean I'd always need to set refreshResult to true for my widget tests to succeed?
As a result, my code in production will also always refresh package_info, even though I only need to refresh during testing (which is why I annotated the reset method with @visibleInTesting in the first place).

**Comment by collinjackson** [comment]
> We noticed that methods like PackageInfo.fromPlatform() which return a Future, would only resolve in the first widget test, while following tests would fail due to the future not resolving anymore.

Can you give a simple test case of some code that would cause this to happen? You should be able to `await` the same `Future` returned by `PackageInfo.fromPlatform()` in multiple widget tests, and it should always return the same value, so I want to understand why additions to the API are needed.

**Comment by stuartmorgan** [comment]
Thanks for the submission! However, we’re no longer accepting non-critical PRs for this plugin, as we hope in time to be able to transition users to the corresponding plugin in [the Flutter Community Plus Plugins repository](https://plus.fluttercommunity.dev/). We encourage you to submit your PR there.

**Pull request closed without merging**
