### PR TITLE
[google_maps_flutter] Fixed typo in LatLngBounds constructor

### PR DESCRIPTION
**Pull request by OTDE**
## Description

Trivial change to documentation on LatLngBounds. Fixing typo.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by amirh** [comment]
@OTDE can you sign the CLA?

**Comment by OTDE** [comment]
@googlebot I fixed it.

**Comment by OTDE** [comment]
I just confirmed that I have for the email I used for this commit. Do I need to sign for a different email address?

**Comment by OTDE** [comment]
@googlebot I fixed it.

**Comment by OTDE** [comment]
@googlebot I fixed it.

**Comment by amirh** [comment]
Actually I think it's my fault I used a new laptop with misconfigured
email, will fix later today

**Comment by OTDE** [comment]
@amirh I know this probably isn't super high on the Google tm list of priorities, but is there an ETA on this? Totally fine if the answer is "later," just checking in :)

**Pull request merged**
