### PR TITLE
Adds platform-specific IDs, new "show interstitial" button to AdMob example

### PR DESCRIPTION
**Pull request by RedBrogdon**
This is a clean redo of PR #312, of which I made a mess when attempting to rebase onto upstream changes. There shouldn't be anything in here other than code changes to the firebase-admob example, a version bump to the pubspec, and a corresponding CHANGLEOG update.

The changes to the example are:

* Load and Show functionality for interstitials has been separated into two separate buttons, which is more in line with our best practices for AdMob.
* Separate, platform-specific ad unit IDs and App IDs have been added.

### CODE REVIEW

**Comment by HansMuller** [comment]
These changes look good, thank you!

Once Travis approves I'll update the version number, land the PR, and publish a new version of the plugin.

**Comment by RedBrogdon** [comment]
Thanks!

**Comment by HansMuller** [comment]
Published as 0.2.2 https://pub.dartlang.org/packages/firebase_admob

**Comment by HansMuller** [comment]
I will review https://github.com/flutter/plugins/pull/328 soon, a little swamped at the moment

**Comment by RedBrogdon** [comment]
No problem. I'm mostly done with the iOS and Android implementations, and was planning to add them to the PR in a day or two, so it'd probably be more efficient to hold off anyway.

**Pull request merged**
