### PR TITLE
[wifi_info_flutter_platform_interface] Ready to publish

### PR DESCRIPTION
**Pull request by cyanglaz**
Make the plugins ready to be published

### CODE REVIEW

**Comment by amirh** [comment]
Please make sure to wait for @bparrishMines's approval before landing.

**Comment by slightfoot** [comment]
@amirh we have been looking at splitting the `connectivity_plus` plugin up into `network_info_plus` to address the current permissions problem. Happy to take this PR over in the plus repo. Let me know. /cc @mhadaily

**Review by bparrishMines — COMMENTED** [review]
In the `pubspec.yaml`, we should change 

```
wifi_info_flutter_platform_interface:
    path: ../wifi_info_flutter_platform_interface
```

to 

```
wifi_info_flutter_platform_interface: 1.0.0
```

It will cause the PR to fail until it is published though.

**Comment by cyanglaz** [comment]
@bparrishMines How about we only land the platform interface change in the PR, publish interface, then land another PR for the plugin change.

**Review by bparrishMines — APPROVED** [review]
@cyanglaz That plan works for me.

LGTM

**Comment by cyanglaz** [comment]
Im going to land on red as the failure are about not updating the version. This PR didn't update the version because the last version wasn't published.

**Comment by cyanglaz** [comment]
@bparrishMines actually, it looks like the version in CHANGELOG.MD and pubspec didn't match. I fixed it, could you take another look?

**Review by bparrishMines — APPROVED** [review]
LGTM

**Pull request merged**
