### PR TITLE
Change datasource without redrawing the component

### PR DESCRIPTION
**Pull request by leonetosoft**
## Description

I believe that many programmers need a way to change the video datasource without having to redesign the video component, just with a "nextVideo" doctor.

This was the implementation I used to make my video playback system work properly.

As mentioned in https://github.com/flutter/flutter/issues/24565
After some time doing the video update the program ends up freezing and freezing.

I did not perform the perfect implementation, but my purpose is to show the need for this method that will help other developers who will experience the same problem.

## Related Issues

https://github.com/flutter/flutter/issues/24565
https://github.com/flutter/flutter/issues/44690

## Checklist
- [x] Add nextVideo local file Only in Android
- [ ] Add nextVideo for external link Only in Android
- [ ] Add nextVideo local file Only in IOS
- [ ] Add nextVideo for external link Only in IOS
- [ ] Update tests file

### CODE REVIEW

**Comment by leonetosoft** [comment]
@googlebot I signed it!

**Comment by JasurbekA** [comment]
Now is it possible to change video source without using dispose() and initialize() each and every time

**Comment by leonetosoft** [comment]
> Now is it possible to change video source without using dispose() and initialize() each and every time

as well? can show example ....?

**Comment by JasurbekA** [comment]
> > Now is it possible to change video source without using dispose() and initialize() each and every time
> 
> @JasurbekA
> as well? can show example ....?

I am asking? Is it possible now? Since I am facing this issue, where I have list of URLs then I want to play them on user choose any of the URLs. Player stays on the top of the screen then user choose one url from the listview

**Comment by leonetosoft** [comment]
@JasurbekA Oh yes, sorry I thought I was saying!
With this pull request of mine this will be possible ...
I made a method to change the dataSource ..
take a look at my pull request.

**Comment by aytunch** [comment]
Are you planning on implementing iOS side of the same logic? Reusing a controller is a must for infinite Video Lists.

**Comment by leonetosoft** [comment]
> Hey would you be able to explain some of the changes you made in the pull request?

This pull request refers to changing the dataSource of the video_player component without having to redesign the component.

**Comment by leonetosoft** [comment]
> Are you planning on implementing iOS side of the same logic? Reusing a controller is a must for infinite Video Lists.

Unfortunately I have no experience with the IOS platform...

**Comment by stuartmorgan** [comment]
> I did not perform the perfect implementation, but my purpose is to show the need for this method that will help other developers who will experience the same problem.

Thanks for the submission! It sounds like this isn't actually intended to land, so a PR isn't the right format for it; given that, I'm going to close this. If at some point you are interested in moving forward with code that's intended for production, please open a new PR.

**Pull request closed without merging**
