### PR TITLE
[google_sign_in_web] Add empty podspec to plugin.

### PR DESCRIPTION
**Pull request by ditman**
## Description

Add an empty podspec file, so this plugin doesn't break compilation on IOS.

Similar to [this](https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher_web/ios).

## Related Issues

* https://github.com/flutter/flutter/issues/45571

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by hterkelsen** [comment]
Is there a tracking issue for not breaking iOS compilation when plugins don't have a Podspec?

**Comment by ditman** [comment]
> Is there a tracking issue for not breaking iOS compilation when plugins don't have a Podspec?

I thought this wasn't needed anymore. I am not aware of a tracking issue. Looking at this, it seems that maybe there's extra work that needs to be done in addition to adding a fake podspec in the plugin?

https://github.com/flutter/plugins/pull/2177

/cc @mklim

**Comment by mklim** [comment]
> > Is there a tracking issue for not breaking iOS compilation when plugins don't have a Podspec?
> 
> @hterkelsen I thought this wasn't needed anymore. I am not aware of a tracking issue. Looking at this, it seems that maybe there's extra work that needs to be done in addition to adding a fake podspec in the plugin?
> 
> #2177
> 
> /cc @mklim

I'm not up to date with this, sorry. @jmagman, do you know?

**Comment by jmagman** [comment]
`pod lint` runs on pre-submit for any edited or new podspecs (see https://cirrus-ci.com/task/4992659592052736).  If you want to skip the lint for a podspec, like a place-holder one, you should add it to the `skipped_podspecs` list https://github.com/flutter/plugins/blob/master/script/lint_darwin_plugins.sh#L18

**Comment by jmagman** [comment]
Was this merged before all the presubmit checks passed?  Or was lint_darwin_plugins actually passing? @ditman

**Comment by ditman** [comment]
@jmagman it was indeed merged before the lint passed, my bad! I found out about the check after clicking merge :/

**Comment by jmagman** [comment]
@ditman Can you add it to the list in the script in a new PR?  You can test it by changing something in that plugin and running the script locally.  The next person who edits this plugin will fail that lint.

**Comment by ditman** [comment]
@jmagman on it, thanks!

**Pull request merged**
