### PR TITLE
Remove all the examples' podfiles

### PR DESCRIPTION
**Pull request by xster**
So the podfile template can be exercised instead of checking in stale ones

### CODE REVIEW

**Comment by xster** [comment]
Did flutter assets in a separate PR #350

The Podfiles are a bit inconvenient but I'd argue it's the 'right' behaviour to have the workspace be in a dirty state after running building an example. If you want share the example with other people, the Podfile needs to be 'materialized' so everyone's builds are consistent.

**Comment by mravn-google** [comment]
The regular project templates surely do not gitignore the Podfiles. But for the template instantiations checked into our own repos, we've taken the approach so far to set them up to be clean after `flutter run`. The Gradle wrapper executables for instance are in gitignore for this reason.

**Comment by xster** [comment]
Ah I see. Makes sense to keep in sync with gradle wrappers. Done

**Comment by mravn-google** [comment]
Thanks. I think we can merge this now?

**Comment by Hixie** [comment]
@xster is this ready to land?

**Comment by xster** [comment]
My bad, I thought I already merged it.

**Pull request merged**
