### PR TITLE
[google_maps_flutter]Added support for drawing polylines to the google_maps flutter plugin…

### PR DESCRIPTION
**Pull request by irevans**
This includes the flutter layer, android code and example application, but not iOS.

### CODE REVIEW

**Comment by irevans** [comment]
I would like to run the flutter_plugin_tools. From the google_maps_flutter directory I have ran:

`flutter packages pub global activate flutter_plugin_tools`

This appears to have worked. I then ran:

`flutter packages pub global run flutter_plugin_tools format --plugins google_maps_flutter`

However this fails with an error message: Error: Cannot find a "packages" sub-directory.

I realise this may be a novice question but I would appreciate some advice on how to overcome the above problem.

**Comment by amirh** [comment]
You should run it from the root folder of the plugins directory.

**Comment by irevans** [comment]
Hi Amir,

When I run the command from the plugins directory it fails with the following error:

`Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.`

**Comment by amirh** [comment]
Ohh just noticed you are running: `flutter packages pub run` it should be `pub run`.

**Comment by irevans** [comment]
Thanks Amir.

When you review these code changes I would be particularly interested in whether you think using `null` to represent the default pattern in the `PolylineOptions` class is a good idea.  Perhaps using an empty list would be better, such that `null` is used to consistently mean "do not change this configuration option".

**Comment by amirh** [comment]
Can you make the googlebot happy ?

**Comment by irevans** [comment]
Hi Amir, I'm just waiting on my employer to confirm that they waive any rights to IP before signing the cla. Merely a formality that won't take long. Sorry for the delay.

**Comment by irevans** [comment]
I signed it!

**Comment by kunit1** [comment]
@irevans looks like bot is still not happy about cla.

Would be nice to have this merged (after it's been reviewed)

**Comment by irevans** [comment]
@kunit1 I'm waiting for my employer's "authorized signer" to complete the CLA signing process. It should be done soon.

I'm not sure what the following checks are failing, is this likely to be a consequence of the cla issue?

build-apks+java-test PLUGIN_SHARDING:--shardIndex 0 --shardCount 2
build-apks+java-test PLUGIN_SHARDING:--shardIndex 1 --shardCount 2

**Comment by joaquinperaza** [comment]
Great! I am looking to start coding polygon support, is nobody on that?

**Comment by irevans** [comment]
@joaquinpereaza only polyline support in this pull request (not polygon).

**Comment by ZatacaSystems** [comment]
@irevans hey! any news on the conflicts? I'm looking forward for this!

**Comment by irevans** [comment]
I signed it!

**Comment by irevans** [comment]
@amirh Hi Amir, the cla has been signed, any idea why that didn't trigger a rebuild of the project?

**Comment by irevans** [comment]
@amirh Hi Amir, are you able to shed some light on why the google bot claims the cla is not signed when I have supplied the information requested (when contributing on behalf of an employer) and it's been signed by the authorised signer? 

I don't see any information from the build that would help me diagnose the problem, am I missing anything?

**Comment by bright2kwame** [comment]
how do I add this pull request to my flutter project ??

**Comment by irevans** [comment]
@bright2kwame I would suggest you use pull request #1049 instead, since it has added iOS support on top of the android support in this pull request. You can use that by adding the following to your pubspec.yaml:

  ```
google_maps_flutter:
      git:
        url: git://github.com/awazgyawali/plugins/
        path: packages/google_maps_flutter
        ref: google_maps_polyline
```

**Comment by mendoza02** [comment]
I will do the same, Google is taking too much time to merge this pull
request to the master. I definitely need polylines. Thanks guys

**Comment by joaquinperaza** [comment]
Me too, also would try to add the pr of polygons, I am needing to continue working


Joaquin Peraza
Cel: 099 355553
e-mail: joaquin@peraza.uy

**Comment by irevans** [comment]
FYI. A fork of this pull request (#1049) has now been approved and merged.

**Comment by irevans** [comment]
FYI. A fork of this pull request (#1049) has now been approved and merged.

**Pull request closed without merging**
