### PR TITLE
Firebase storage getDownloadUrl

### PR DESCRIPTION
**Pull request by procedurallygenerated**

### CODE REVIEW

**Comment by kroikie** [comment]
Hi @procedurallygenerated thanks for the PR. Couple things:

- Add tests.
- Resolve formatting issues.

**Comment by kroikie** [comment]
@procedurallygenerated thanks again for this PR if you could make the suggested updates I'd be happy to merge.

**Comment by procedurallygenerated** [comment]
@kroikie Will do 👍

**Comment by kroikie** [comment]
@procedurallygenerated if you can resolve those build issues I'd love to merge in this change, thanks!

**Comment by collinjackson** [comment]
Landing this in #457

**Pull request closed without merging**
