### PR TITLE
[image_picker] Fix ios scaling in portrait mode

### PR DESCRIPTION
**Pull request by Xavjer**
## Description

Fixes the issue, that within image_picker when taking a picture on iOS in Portrait mode, the scaling did not work as intended (AspectRatio was flipped)

## Related Issues

https://github.com/flutter/flutter/issues/40334 => Will be fixed with this PR

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [(X) ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
=> No new unit tests added, as the existing should already cover this, but the image did not have the values that were returned from the channel.
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Xavjer** [comment]
I did just sign the CLA for flutter/plugins

**Comment by Xavjer** [comment]
@googlebot I fixed

**Comment by Xavjer** [comment]
@googlebot I fixed it.

**Comment by Xavjer** [comment]
@googlebot I fixed it.

**Comment by Xavjer** [comment]
Reopening due to wrong commiter idenitity

**Comment by Xgamefactory** [comment]
issue still on lates version   image_picker: ^0.6.1+4

**Comment by Xavjer** [comment]
@Xgamefactory this PR was not merged, recreated in #2061 but not merged yet, therefore the error still exists

**Pull request closed without merging**
