### PR TITLE
Revert "[path_provider] Use the application ID in the application support path"

### PR DESCRIPTION
**Pull request by dnfield**
Reverts flutter/plugins#2845

This broke master - Linux is consistently timing out after this.

TBR @robert-ancell @stuartmorgan 

/cc @ditman

### CODE REVIEW

**Comment by dnfield** [comment]
I will wait for the test that's been timing out to pass before merging this.

**Comment by ditman** [comment]
path_provider_linux 0.1.0 seems to [NOT have been published yet](https://pub.dev/packages/path_provider_linux/versions), so this looks safe to land (then reland the fixed 0.1.0)

**Comment by dnfield** [comment]
Hm. I'm not sure if this will make the version check permanently angry?

**Comment by ditman** [comment]
You may be able to "revert" to `0.1.0+1` (with a CHANGELOG entry), then the original code can be re-landed as 0.2.0?

**Comment by dnfield** [comment]
That seems pretty wrong to me - we'd never want to publish those versions, and users are likely to get confused when reading the CHANGELOG :\

**Comment by ditman** [comment]
@dnfield when we publish the 0.2.0 we can erase all mentions to 0.1.x changelog, as if this never happened :P

**Comment by dnfield** [comment]
Given that this has broken the tree, going to land - we can always reland it when it's ready.

**Comment by stuartmorgan** [comment]
> Go for this! Maybe get an ACK from Stuart that this is being reverted?

Noted. I'm actually not sure the PR should have landed before https://github.com/flutter/flutter/pull/60053 anyway.

**Comment by robert-ancell** [comment]
> Noted. I'm actually not sure the PR should have landed before [flutter/flutter#60053](https://github.com/flutter/flutter/pull/60053) anyway.

This change is only supposed to work if an application ID is set, and reverts to the old behaviour if not, so PRs are independent.

**Comment by robert-ancell** [comment]
@dnfield do you have a link to the log of the failure?

**Comment by dnfield** [comment]
https://cirrus-ci.com/task/6312004510023680

**Pull request merged**
