### PR TITLE
Feature/switch camera android fix

### PR DESCRIPTION
**Pull request by BradenBagby**
This PR fixes the crash for old devices when switching cameras while recording (Android sdk < 26). See here: https://github.com/flutter/plugins/pull/7109

Split from this root PR https://github.com/flutter/plugins/pull/6478

### CODE REVIEW

**Comment by BradenBagby** [comment]
Forgot to update the Java android tests. Will do

**Comment by hellohuanlin** [comment]
@BradenBagby To clarify, is this PR also split from https://github.com/flutter/plugins/pull/6478 which I reviewed previously? If so can you update the description?

**Comment by BradenBagby** [comment]
@bparrishMines Wondering if you have a chance to check this out? Its what you already reviewed before with a few small changes and updated tests

**Review by hellohuanlin — APPROVED** [review]
Stamping the iOS part which is split from the original PR that I reviewed previously.

**Comment by stuartmorgan-g** [comment]
We've just completed the migration of the plugin code to the flutter/packages repository, as described in https://flutter.dev/go/flutter-plugins-repo-migration, and this repository is now being archived. Unfortunately that means that all in-progress PRs here must be moved to flutter/packages.

Please see [our instructions](https://github.com/flutter/flutter/wiki/Migrating-Plugins-repository-PRs-to-Packages) for an explanation of how to move your PR, and if you have any issues moving your PR please don't hesitate to reach out in the #hackers-ecosystem channel in [Discord](https://github.com/flutter/flutter/wiki/Chat).

Our apologies that your PR was caught in this one-time transition. We're aware that it's disruptive in the short term, and appreciate your help in getting us to a better long-term state!

**Pull request closed without merging**
