### PR TITLE
[google_maps_flutter]Customising map's style.

### PR DESCRIPTION
**Pull request by ilap**
This simple PR is adding an initial support for customising map by using a static client's JSON asset file.

### CODE REVIEW

**Comment by ilap** [comment]
I signed it!

**Comment by Hixie** [comment]
@ilap This is great, thanks! We would like to wait until we have maps implemented on both iOS and Android before actually further augmenting the API, because we are worried that they'll get out of sync otherwise. Would you be ok with resubmitting this with iOS support in a few weeks once we have the iOS work more fleshed out?

**Comment by ilap** [comment]
Yep, no issue at all. I will try to resubmit it /w iOS support. However, I do not have any experience w/ ObjectC but Swift.

**Comment by Hixie** [comment]
cc @amirh Please let @ilap know when you are ready for contributions on the iOS side. Thanks!

**Comment by jnorkus** [comment]
@ilap any update on this? I was about to go and implement this myself.

**Comment by ilap** [comment]
> @ilap any update on this? I was about to go and implement this myself.

Ooops, Sorry, Just had a look at it now and quickly come up /w the code below, which should be added into the [GoogleMapController.m](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/ios/Classes/GoogleMapController.m) file.

I have not tested it as the map does not load.

``` ObjectiveC
    _mapView.delegate = weakSelf;
    _registrar = registrar;

   / ******* NEW CODE

    NSString* assetPath = [_registrar lookupKeyForAsset:@"assets/map/style.json"];
    NSString* path = [[NSBundle mainBundle] pathForResource:assetPath ofType:nil];
    NSURL *styleUrl = [NSURL fileURLWithPath:path];
    NSError *error;

    GMSMapStyle *style = [GMSMapStyle styleWithContentsOfFileURL:styleUrl error:&error];

    if (!style) {
      NSLog(@"The style definition could not be loaded: %@ ... %@", error, assetPath);
    }

    _mapView.mapStyle = style;
  /********* NEW CODE ENDS
```

**Comment by joelalcedo** [comment]
@Hixie @amirh are there any plans to implement a [mapStyleOptions parameter](https://developers.google.com/android/reference/com/google/android/gms/maps/model/MapStyleOptions) natively?

**Comment by ilap** [comment]
Added map styling for both platforms.

**Comment by ilap** [comment]
@Hixie @amirh pls check it.

**Comment by cdmoro** [comment]
Hi! any update? Can't wait for this!

**Comment by dvlj** [comment]
@ilap instead of waiting for the feedback, can you extend this to your own package and put it on pub?

**Comment by pharaouk** [comment]
Hi, thanks for your work everyone. Is it possible to implement this feature now?

**Comment by chist3r** [comment]
Thanks everyone for the great work.
Any plans to fix the conflicts and get this PR merged soon?
Now days styling map is very important specially that location based apps are growing in MENA market . I have 2 apps on the pipeline and the only thing that prevents going with Flutter is styling the map

**Comment by YourFavouriteOreo** [comment]
@ilap Thanks for all the work you are doing on this. Any idea on when these conflicts will be solved and this merged?

**Comment by ilap** [comment]
Have no clue, as that's out of my control. It should've been already merged as it did not affect any part of the code when it was PRed.

**Comment by chist3r** [comment]
@ilap Looks like there are conflicts in files `packages/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java` and `packages/google_maps_flutter/ios/Classes/GoogleMapController.m`

**Comment by ilap** [comment]
Fixed now.

**Comment by cyanglaz** [comment]
@ilap Thank you for sending this PR. It looks great.
Maybe instead of using static json that is set in the platform (iOS, Android, etc), we send the json from dart to the platform as part of initialization of the map or even better as a separate method? It might be easier to document this functionality and users don't have to deal with assets in iOS or Android platforms.

A suggestion of the API would be something like 
`Future<void>setCustomStyle({String json});`

**Comment by cyanglaz** [comment]
@ilap I saw that we have `setMapStyle`(https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/lib/src/controller.dart#L187-L207) method in the plugin already. I wonder if user can just use this method to read a static JSON from asset? I think this would solve the problem that you are trying to solve. I'm going to relentlessly close the PR. If you think this PR is still useful, please feel free to tag me and we can discuss it in more details.

**Pull request closed without merging**
