### PR TITLE
[webview_flutter] Expose loadData function for webviews

### PR DESCRIPTION
**Pull request by GeertJohan**
## Description

Expose `loadData` on the webview controller. This allows developers to load html directly into the webview.

This is a draft PR. I'm using this change in a product, but it is not ready to be merged into flutter/plugins yet. For example: e2e tests for this feature are still missing.

I wanted to open this PR anyway to get early feedback. I have seen @amirh reply to earlier PR's regarding this feature. I hope you can give some feedback on this approach?

For example; should we make loadUrl and loadData throw an exception when the other one was used before? We can keep that knowledge on the dart side and just throw a dart exception, or should it be tried and possibly return an error depending on the platform implementation handles it?

## Related Issues

This fixes flutter/flutter#32827

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by ahyenz** [comment]
Nice

**Comment by CanRau** [comment]
That'd be amazing 👏

**Comment by GeertJohan** [comment]
I've rebased this feature-branch on the latest master. Please review :)

**Comment by GeertJohan** [comment]
I think https://github.com/flutter/plugins/pull/3214 is better and should be merged instead of this.

**Comment by stuartmorgan** [comment]
Thanks for the submission! We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

> For example; should we make loadUrl and loadData throw an exception when the other one was used before?

Can you clarify the question here? What is the motivation for this exception?

> Please review :)

As you noted originally, this PR isn't ready for review yet as it's missing tests. It looks like it should be relatively straightforward to review once they are ready though.

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
