### PR TITLE
[google_maps_flutter] fix to properly place polyline at initial camera position in example app

### PR DESCRIPTION
**Pull request by klaes-ashford**
## Description

since in the code `_polylineIdCounter` is used to offset the latitude and it being 2 for initial polyline, goes out of the map viewport and when ever you add a polyline it is not visible at first. you have to pan around to see the initially added polyline. This at first gives a false impression that the polyline is not working. this change when merged will fix that issue.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by aswinkviswanath** [comment]
@cyanglaz this being a small fix in example app, I am not sure if I should add a changelog since none of the api's is being touched.

**Comment by cyanglaz** [comment]
Thank you for sending this PR. Yes, we need to update the CHANGLOG and version for a fix in the example app. Could you explain more in detail what are you trying to fix here? Is there an issue that you can link this to?

**Comment by aswinkviswanath** [comment]
ezgif-5-171a032b2f8d

as you can see in the gif, initially, you can not see the polyline at first when you click the add button. you have to pan around to see the polyline. this might confuse a naive user (it occured to me :P), so I thought, it would be great to see the initial polyline at first time itself.

@cyanglaz with a slight modification to the initialCameraPosition latitude we can place the initial polyline to the center of view port.

**Comment by cyanglaz** [comment]
@aswinkviswanath I see thanks for the fix! Please update the changelog and version. I will land this!

**Comment by aswinkviswanath** [comment]
@cyanglaz CHANGELOG and version updated.

**Comment by cyanglaz** [comment]
@klaes-ashford The PR is almost ready to merge, it looks like you have to sign the CLA.

**Comment by klaes-ashford** [comment]
@cyanglaz  Sorry, but I used the wrong email address in PR, and I don't have access to the same.

**Comment by klaes-ashford** [comment]
@cyanglaz please see https://github.com/flutter/plugins/pull/2941. These changes have been moved there.

**Pull request closed without merging**
