### PR TITLE
[in-app-purchase] update README: more emphasis on not updating build.gradle

### PR DESCRIPTION
**Pull request by jurrdb**
I think it's good to put more emphasis on not adding 'com.android.billingclient:billing' to your own app's build.gradle. The reason is that the documentation that is referenced earlier in the README explicitly instructs you to include the line in your build.gradle. If you miss this line telling you not to add it, you will have quite some trouble, especially since the package gives no error message at all when this goes wrong. The app just stops loading the InAppPurchase instance without any error message. Took me quite some time to debug!

No mentioned issue since it's a 1 words change of the README.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by jurrdb** [comment]
@googlebot I signed it!

**Comment by stuartmorgan** [comment]
@mvanbeusekom @cyanglaz Thoughts on this change? It's not clear to me that changing one word here will actually make this more noticeable, and it seems odd to start with "Important", but then have the text say, "it is not necessary" (which sounds very optional, not important).

> * [ ]  I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
> * [ ]  I updated CHANGELOG.md to add a description of the change.

These steps are missing; please see the FAQ in the first link.

**Comment by cyanglaz** [comment]
> especially since the package gives no error message at all when this goes wrong. The app just stops loading the InAppPurchase instance without any error message.

I agree this is troublesome, but I don't think change one word in README would make much a difference.
I think the right fix is to somehow expose some error message for easier debugging.

If you could open a new issue and describe the steps to reproduce with plugin version that you used (or your pubspec.lock). (for example, which play billing library version you added to your app, which features are not working.), that'd be great. Then we can try to reproduce and figure out if it is easy to just expose some error message.

**Comment by jurrdb** [comment]
Created an issue for it: Issue #90666

**Pull request closed without merging**
