### PR TITLE
Port google_maps_flutter to use AndroidView for embedding the map.

### PR DESCRIPTION
**Pull request by amirh**
This change adds a GoogleMap widget which shows a map as part of the  widget tree.
Each map uses a dedicated method channel named 'plugins.flutter.io/google_maps_$id',
The Java GoogleMapsController class now extends PlatformView, and is the
Java endpoint of the per map method channel.

This change disables the plugin on iOS until we have an inlining solution
for iOS.

flutter/flutter#73

### CODE REVIEW

**Comment by amirh** [comment]
Thanks for the review, will land on green.

**Comment by tiagofalves** [comment]
So i have tried out the example in plugins/google_maps_flutter and ran into some errors,

error: no interface expected here
error: incompatible types: GoogleMapFactory cannot be converted to PlatformViewFactory

anyone managed to run this cleanly?

**Comment by amirh** [comment]
This uses features that are currently only available on the Flutter master
channel.

**Comment by tiagofalves** [comment]
Thanks for the heads up

**Comment by tiagofalves** [comment]
Hi @amirh, got another issue. When i use a map in a tab the map controller doesn't seem to be receiving the swipe commands... Is there any way of overlapping the map controller on the tab controller that i am unware of? This is not a big issue, its just something i came across...

**Comment by amirh** [comment]
Check the example in #755

**Comment by gerryhigh** [comment]
@tiagofalves Make sure you are doing like in the example of using navigatorObservers https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/example/lib/main.dart (IMO not that practical since it requires you to create your widget in advance) or else do something like activating and deactivating the overlays. I have an example here: https://github.com/gerryhigh/Flutter-Google-Maps-Demo/blob/master/lib/venues.dart

**Pull request merged**
