### PR TITLE
Changing all plugins to use a static registerWith method that returns an instance of the plugin

### PR DESCRIPTION
**Pull request by abykov2**

### CODE REVIEW

**Comment by mehmetf** [comment]
This looks fine. However, how will the app code get a reference to these plugins? We should change the generated registrant class as well. Unfortunately, I am not familiar with that part of the code externally. Should not be hard to track it down though.

**Comment by goderbauer** [comment]
What's the context for this change?

**Comment by mit-mit** [comment]
cc @mravn-google

**Comment by goderbauer** [comment]
I think we decided to go down another path. Closing this PR for now.

**Pull request closed without merging**
