### PR TITLE
[camera] Use startVideoCapturing and expose concurrent stream/record

### PR DESCRIPTION
**Pull request by adam-harwood**
This uses the new startVideoCapturing implementation, that supports concurrent stream/record.

This is the final piece from https://github.com/flutter/plugins/pull/6808.

Closes https://github.com/flutter/flutter/issues/83634

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [X] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by adam-harwood** [comment]
The checks will pass once a new version of `camera_android`, `camera_avfoundation`, `camera_platform_interface`, and `camera_web` are released. What's the timeline of that happening?

**Comment by stuartmorgan** [comment]
It happens automatically once post-submit tests finish running, so normally it would have happened yesterday, but there was some post-submit test flake that we didn't notice. I'm re-running those now.

**Comment by stuartmorgan** [comment]
I hit some CI snags with autopublish, but I've now published them manually. Sorry for the delay!

**Review by bparrishMines — APPROVED** [review]
LGTM

Request for secondary review from @stuartmorgan

**Comment by jorger5** [comment]
Looking forward to have this merged, awesome job @adam-harwood !

**Comment by neil-yagao** [comment]
Dude， I am reeeeally looking forward to this feature. Can't wait for this PR to be released.  Big thanks for your effort.

**Review by stuartmorgan — APPROVED** [review]
LGTM, it'll just need a merge from `main`. Sorry for the delay on this last piece, I was on vacation for a few weeks and then have still been catching up.

**Comment by adam-harwood** [comment]
Done, ready for merge I think @stuartmorgan .

**Review by stuartmorgan — APPROVED** [review]

**Pull request merged**
