### PR TITLE
Revert "[camera]Fix crash due to calling engine APIs from background thread"

### PR DESCRIPTION
**Pull request by jmagman**
Reverts flutter/plugins#4608

I don't think this is the best way to solve this, let's revert until @stuartmorgan and I can review.

No version change:
That PR didn't bump the version, so there's no publication issue.

### CODE REVIEW

**Comment by jmagman** [comment]
Hm, not sure why `publishable` is still failing after adding `No version change:` and an empty commit.

**Comment by hellohuanlin** [comment]
@jmagman did you edit the PR description after you created this PR?

**Comment by jmagman** [comment]
> @jmagman did you edit the PR description after you created this PR?

I didn't have `No version change:` initially, but then I added it, and added an empty commit to re-run.

**Comment by hellohuanlin** [comment]
@jmagman FYI I had similar issue and tried resetting and recommitting the original commit and it worked.

**Review by hellohuanlin — APPROVED** [review]

**Comment by jmagman** [comment]
> @jmagman FYI I had similar issue and tried resetting and recommitting the original commit and it worked.

Hm, let me try that...

**Comment by jmagman** [comment]
Let me just reopen this.

**Comment by jmagman** [comment]
Worked this time: https://github.com/flutter/plugins/pull/4630

**Pull request closed without merging**
