### PR TITLE
[camera] Added support for flash/torch mode in iOS and Android

### PR DESCRIPTION
**Pull request by acoutts**
## Description

This PR implements the ability to toggle torch mode on/off in iOS and Android. You can use this to run the camera's flash continuously as a torch and can use it as a flash for photo capture (by turning it on/off before/after your capture), and during video capture as a continuous light.

It adds the following new methods to the `CameraController`:
* `Future<bool> hasTorch()`
* `Future<void> disableTorch()`
* `Future<void> enableTorch()`

It has been tested on an iPhone 8 running iOS 13 and a Pixel 4 running Android 29. It works during video and photo capture as well. The example app has been updated with a new toggle switch for enabling/disabling the torch. The toggle switch will be disabled (20% opacity and non-interactive) if the current selected camera does not support torch mode.

## Related Issues
Closes https://github.com/flutter/flutter/issues/66252
https://github.com/flutter/flutter/issues/31225
https://github.com/flutter/flutter/issues/58218
https://github.com/flutter/flutter/issues/57307
https://github.com/flutter/flutter/issues/54548
https://github.com/flutter/flutter/issues/41785

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by orestesgaolin** [comment]
Unfortunately on Android it doesn't work properly because you don't handle the precapture measurements. The photos on Samsung S8 are oversaturated.

**Comment by orestesgaolin** [comment]
> After looking at https://github.com/gummie4444/flutter-better-camera where they did do the proper flash implementation, that is definitely way outside of the scope of what I wanted to accomplish here.

Yeah, and I tried to improve on that but frankly there are some edge cases like some LG or Huawei phones that still work differently than what you'd expect

**Comment by acoutts** [comment]
> > After looking at https://github.com/gummie4444/flutter-better-camera where they did do the proper flash implementation, that is definitely way outside of the scope of what I wanted to accomplish here.
> 
> Yeah, and I tried to improve on that but frankly there are some edge cases like some LG or Huawei phones that still work differently than what you'd expect

I think all we can do is follow the Android API docs and implement it to that spec, and if any phone manufacturers don't implement the API correctly then there isn't much we can do about it.

**Comment by ghunkins** [comment]
@acoutts Huge thanks for putting this out. Really looking forward to seeing this in action, there's a *lot* of interest in the Flutter community for shipping this feature.

**Comment by acoutts** [comment]
@bparrishMines is there anything I can do to help speed this along for merging?

**Comment by malikdoksoz** [comment]
> @bparrishMines is there anything I can do to help speed this along for merging?

İf you want check this library for focus and many flash attributes: [https://github.com/react-native-community/react-native-camera/tree/master/android/src/main/java/com/google/android/cameraview](url)

**Comment by acoutts** [comment]
> > @bparrishMines is there anything I can do to help speed this along for merging?
> 
> İf you want check this library for focus and many flash attributes (you can find ios part on the main section):
> https://github.com/react-native-community/react-native-camera/tree/master/android/src/main/java/com/google/android/cameraview

For the scope of this PR I do not want to do anything else except torch mode like I've done here.

**Comment by acoutts** [comment]
@ghunkins do you know anyone I can tag here to get this reviewed / merged? Seems like it is not maintained so far..

**Comment by ghunkins** [comment]
Tagging reviewers on #1969 here to hopefully bring this across the finish line. Can anyone please add themselves to help review and merge this?

@orestesgaolin @JoseGeorges8 @GustavoFigueira @VictorAlves @cyanglaz @mklim  @mehmetf  @bparrishMines . Thanks in advance! cc: @acoutts

**Comment by orestesgaolin** [comment]
As a user of the plugin I wouldn't like to see this feature implemented without proper handling of precapture measurements. It wasn't tested on variety of devices and I know that there are slight differences across manufacturers that will cause the output images to look incorrectly. 

Merging this to the plugin repo would mean that now the Flutter team would have to handle all the issues related to this implementation and I guess they won't be investing into that in the nearest future. Sorry to say that, but I suspect that this PR won't land in the repo as there was no interaction from the team at all.

**Comment by malikdoksoz** [comment]
> As a user of the plugin I wouldn't like to see this feature implemented without proper handling of precapture measurements. It wasn't tested on variety of devices and I know that there are slight differences across manufacturers that will cause the output images to look incorrectly.
> 
> Merging this to the plugin repo would mean that now the Flutter team would have to handle all the issues related to this implementation and I guess they won't be investing into that in the nearest future. Sorry to say that, but I suspect that this PR won't land in the repo as there was no interaction from the team at all.

Is it so difficult to add flash support to the camera library? Really !!?

**Comment by acoutts** [comment]
> As a user of the plugin I wouldn't like to see this feature implemented without proper handling of precapture measurements. It wasn't tested on variety of devices and I know that there are slight differences across manufacturers that will cause the output images to look incorrectly.
> 
> Merging this to the plugin repo would mean that now the Flutter team would have to handle all the issues related to this implementation and I guess they won't be investing into that in the nearest future. Sorry to say that, but I suspect that this PR won't land in the repo as there was no interaction from the team at all.

Just to reiterate, torch mode != flash mode. While you can indeed get by using the torch as a flash by simply turning it on/off before capturing an image, torch mode is simply the flash running constantly. The primary use case is when you need the flash turned on for the camera preview, such as for scanning QR codes, or really if you just want to build a simple flutter flashlight app.

I do hope someone can add the proper flash mode in the future for image capture, but I simply want to get torch mode merged here. Let's not hold it up for something outside of the scope of the original PR.

**Comment by acoutts** [comment]
Hello is anyone out there?

**Comment by acoutts** [comment]
cc @TahaTesser do you know anyone that can take a look at this?

**Comment by malikdoksoz** [comment]
> cc @TahaTesser do you know anyone that can help take a look at this? Seems like there's been no activity on this plugin for the last month..

The Flutter team is making efforts to avoid this feature :)

**Comment by leonardodavila** [comment]
@acoutts Thanks for the contribution, is there any example code of what you did? I'd like to use the code in your branch until it gets merged.

**Comment by acoutts** [comment]
> @acoutts Thanks for the contribution, is there any example code of what you did? I'd like to use the code in your branch until it gets merged.

You can see the files changed tab here and it will show the diff of this PR:
https://github.com/flutter/plugins/pull/2837/files

As for how to use it, that is as simple as calling `await controller.enableTorch();` on the camera controller now.

**Comment by bparrishMines** [comment]
cc @cyanglaz 

Hi @acoutts 

Thanks for the contribution! Unfortunately, this feature is non-trivial and we don't have anyone focused on adding new features to this plugin at the moment. We typically follow [issue hygiene](https://github.com/flutter/flutter/wiki/Issue-hygiene) when prioritizing issues and PRs. We'll keep this on our radar, but I can't give a time frame when we'll be able to work on it.

Everyone is also free to use this PR by adding a [git dependency](https://dart.dev/tools/pub/dependencies#git-packages) to their `pubspec.yaml`.

**Comment by felipesses** [comment]
Hello, could you help me on how do I use this PR on my project? I don't know how to import it in my pubspec.yaml file, I have used by copying your code and it's working really well, thanks for that PR by the way, you saved my life :D hope the Flutter community accept your this PR soon.

**Comment by lukepighetti** [comment]
> Thanks for the contribution! Unfortunately, this feature is non-trivial and we don't have anyone focused on adding new features to this plugin at the moment.

I'm a little confused. Is `camera` is no longer supported?

**Comment by AhmedNourJamalElDin** [comment]
hmmmm

**Comment by TahaTesser** [comment]
Hi @acoutts 
I edited your OP to add https://github.com/flutter/flutter/issues/66252 
Let me if you know disagree
Thank you

**Comment by nombrekeff** [comment]
I appreciate the effort done to get this done, but I think a camera plugin without the option to use the flash/lamp is kinda weird. I think this is a critical feature that the plugin **should** have... 

Is the PR code stable enough for use in a production APP or should we wait until it's merged?

**Comment by acoutts** [comment]
> Hi @acoutts
> I edited your OP to add [flutter/flutter#66252](https://github.com/flutter/flutter/issues/66252)
> Let me if you know disagree
> Thank you

Thanks!

**Comment by acoutts** [comment]
> I appreciate the effort done to get this done, but I think a camera plugin without the option to use the flash/lamp is kinda weird. I think this is a critical feature that the plugin **should** have...
> 
> Is the PR code stable enough for use in a production APP or should we wait until it's merged?

It's been stable enough for me to use without issue so far since I created this PR months ago.

**Comment by nombrekeff** [comment]
> > I appreciate the effort done to get this done, but I think a camera plugin without the option to use the flash/lamp is kinda weird. I think this is a critical feature that the plugin **should** have...
> > Is the PR code stable enough for use in a production APP or should we wait until it's merged?
> 
> It's been stable enough for me to use without issue so far since I created this PR months ago.

Okay, thanks! I will give it a go and if no issue arises I will make use of it. In case I find any weird behavior or bug I will let you know.

I will be keeping an eye on this, let me know if I can do anything to get this moving quicker.

**Comment by acoutts** [comment]
> > > I appreciate the effort done to get this done, but I think a camera plugin without the option to use the flash/lamp is kinda weird. I think this is a critical feature that the plugin **should** have...
> > > Is the PR code stable enough for use in a production APP or should we wait until it's merged?
> > 
> > 
> > It's been stable enough for me to use without issue so far since I created this PR months ago.
> 
> Okay, thanks! I will give it a go and if no issue arises I will make use of it. In case I find any weird behavior or bug I will let you know.
> 
> I will be keeping an eye on this, let me know if I can do anything to get this moving quicker.

Unfortunately this plugin is not being updated for new features, so I would suggest looking to this community one for something more actively maintained: https://pub.dev/packages/camerawesome

**Comment by nombrekeff** [comment]
Nice thanks a lot! I will check that out. It's a shame it's not supported in the official plugin though 😐

**Comment by Rossdex** [comment]
I have tested this on about 7 devices. There seems to be some oddities upon taking a photo, where the torch on the device flashes while taking a photo, causing the image to be under exposed. 

This happens on every device I have tested so far but only seems to affect some (e.g. Samsung A71 running Android 10).

The best test of this is if you are in a completely dark environment you can see the preview is fully lit, however the photo that comes out of the 'takePicture' function comes out completely black.

**Comment by mvanbeusekom** [comment]
Closing this PR in favor of #3314

**Comment by szuwest** [comment]
> ## Description
> This PR implements the ability to toggle torch mode on/off in iOS and Android. You can use this to run the camera's flash continuously as a torch and can use it as a flash for photo capture (by turning it on/off before/after your capture), and during video capture as a continuous light.
> 
> It adds the following new methods to the `CameraController`:
> 
> * `Future<bool> hasTorch()`
> * `Future<void> disableTorch()`
> * `Future<void> enableTorch()`
> 
> It has been tested on an iPhone 8 running iOS 13 and a Pixel 4 running Android 29. It works during video and photo capture as well. The example app has been updated with a new toggle switch for enabling/disabling the torch. The toggle switch will be disabled (20% opacity and non-interactive) if the current selected camera does not support torch mode.
> 
> ## Related Issues
> Closes [flutter/flutter#66252](https://github.com/flutter/flutter/issues/66252)
> [flutter/flutter#31225](https://github.com/flutter/flutter/issues/31225)
> [flutter/flutter#58218](https://github.com/flutter/flutter/issues/58218)
> [flutter/flutter#57307](https://github.com/flutter/flutter/issues/57307)
> [flutter/flutter#54548](https://github.com/flutter/flutter/issues/54548)
> [flutter/flutter#41785](https://github.com/flutter/flutter/issues/41785)
> 
> ## Checklist
> Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.
> 
> * [x]  I read the [Contributor Guide](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
> * [x]  My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md)).
> * [x]  All existing and new tests are passing.
> * [x]  I updated/added relevant documentation (doc comments with `///`).
> * [x]  The analyzer (`flutter analyze`) does not report any problems on my PR.
> * [x]  I read and followed the [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo).
> * [x]  The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
> * [x]  I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://www.dartlang.org/tools/pub/versioning).
> * [x]  I updated CHANGELOG.md to add a description of the change.
> * [x]  I signed the [CLA](https://cla.developers.google.com/).
> * [x]  I am willing to follow-up on review comments in a timely manner.
> 
> ## Breaking Change
> Does your PR require plugin users to manually update their apps to accommodate your change?
> 
> * [ ]  Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
> * [x]  No, this is _not_ a breaking change.

how to use your branch in a flutter project?

**Comment by mvanbeusekom** [comment]
@szuwest flash and torch features on Android and iOS is available since version 0.6.3+2 of the camera plugin and is available on pub.dev.  I recommend updating to the latest version 0.6.4+5.

**Comment by szuwest** [comment]
> @szuwest flash and torch features on Android and iOS is available since version 0.6.3+2 of the camera plugin and is available on pub.dev. I recommend updating to the latest version 0.6.4+5.

Thank you, I found it.

**Pull request closed without merging**
