### PR TITLE
[in_app_purchases] fixed typo

### PR DESCRIPTION
**Pull request by eldermao1**
## Description

Fixed typo 'manuelly' for 'manually'

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by eldermao1** [comment]
> LGTM! Thanks for fixing this. Could you please update the CHANGELOG and pubspec.yaml with a new version please?

Sure! I'm not so experienced with this so I'm not sure exactly what you mean. Would you like me to download the latest CHANGELOG and pubspec.yaml into this branch and resubmit?

**Comment by eldermao1** [comment]
Also @cyanglaz I'm not sure where is the best place to have a live chat about a suggestion to improve this package's documentation [in_app_purchase]? I recently spent a lot of time getting it up and running with the different stores and I took some notes. I figured it could be useful to somehow share this notes and collaborate to write a comprehensible guide that covers some of the subtleties to get this package up and running and test it. Not sure where how is the best way to go about this. Can you point me in the right direction?

**Comment by cyanglaz** [comment]
@eldermao1 every time we update a plugin, we need to update the CHANGELOG.MD and pubspec.yaml. 
You can take a look at https://github.com/flutter/plugins/pull/2739/files as an example.

**Comment by eldermao1** [comment]
@googlebot I fixed it

**Comment by eldermao1** [comment]
@googlebot i fixed this

**Comment by eldermao1** [comment]
@googlebot i fixed it

**Comment by eldermao1** [comment]
@googlebot I fixed it

**Comment by eldermao1** [comment]
@googlebot I fixed it.

**Comment by eldermao1** [comment]
@cyanglaz For some reason my fork picked up other commits that weren't mine and now it's complaining about CLA. Do you suggest I just do this again in a new branch and drop this commit since it's only a one letter typo I was fixing?

**Comment by cyanglaz** [comment]
@eldermao1 Sure. Please ping me when the new PR is ready. :)

**Comment by cyanglaz** [comment]
This is fixed in https://github.com/flutter/plugins/pull/2902

**Pull request closed without merging**
