### PR TITLE
[webview_flutter] Add support for onPageStarted event

### PR DESCRIPTION
**Pull request by jeremie-movify**
## Description

Added support for onPageStarted event on both Android and iOS.
Bound to WebViewClient's `public void onPageStarted(WebView view, String url, Bitmap favicon)`
and WKWebView's `- (void)webView:(WKWebView *)webView 
didStartProvisionalNavigation:(WKNavigation *)navigation`.

## Related Issues

None

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by ened** [comment]
Hi @jeremie-movify thank you for the PR!
I noticed webview_flutter also has integration tests in `example/test_driver`. They cover `onPageFinished` / `onPageLoaded` already. Could you extend this PR so that `onPageStarted` is included as well? 
Thank you!

**Comment by jeremie-movify** [comment]
Hi @ened,
Of course ; I'll get it done before the end of the week. Thank you for your suggestion.

**Comment by ened** [comment]
Hi @jeremie-movify looks like we're getting close. Please resolve the formatting issues and we can merge once everything else is green :)

**Comment by luohao8023** [comment]
Hi@ened how can I get the latest version with 'onPageStarted'?

**Comment by luohao8023** [comment]
I have tried changing the version to 0.3.18,but got nothing.

**Comment by jeremie-movify** [comment]
Hi @luohao8023,

This PR is not yet merged ; you'll be able to access the latest API (with support for `onPageStarted`) as soon as it is.

In the meantime, you may want to point your dependency to my fork of this repository, and use the latest commit hash as reference.

Cheers,

Jérémie

**Comment by amirh** [comment]
nit: this PR should have updated the version in pubspec.yaml as well

**Comment by jeremie-movify** [comment]
> nit: this PR should have updated the version in pubspec.yaml as well

You're right, my bad ; this was done in a different branch, and got lost at some point.

**Comment by ened** [comment]
Argh, I didn't spot that. Sorry, will check more careful as well, next time. Thx @amirh

**Pull request merged**
