### PR TITLE
[camera] combine release messages and versions

### PR DESCRIPTION
**Pull request by cyanglaz**
Combine release messages and versions for below commits:
https://github.com/flutter/plugins/commit/100c7470d4066b1d0f8f7e4ec6d7c943e736f970
https://github.com/flutter/plugins/commit/71a831790220f898bf8120c8a23840ac6e742db5
https://github.com/flutter/plugins/commit/da1b4638b750a5ff832d7be86a42831c42c6d6c0
https://github.com/flutter/plugins/commit/831344490984b1feec007afc9c8595d80b6c13f4
https://github.com/flutter/plugins/commit/5916f55664e1772a4c3f0c02c5c71fc11e491b76
https://github.com/flutter/plugins/commit/980b674cb4020c1927917426211a87e275346d5e
https://github.com/flutter/plugins/commit/d0b7109f6b00a0eda03506fed2c74cc123ffc6f3
https://github.com/flutter/plugins/commit/6d18db83f00f4861ffe485aba2d1f8aa08845ce6

### CODE REVIEW

**Review by mvanbeusekom — APPROVED** [review]
LGTM, thanks!

**Review by bparrishMines — APPROVED** [review]
LGTM

**Comment by mvanbeusekom** [comment]
I have been looking into the reason why the tree is failing, but not sure how to resolve it.

The problem is caused by the camera plugin depending on `quiver: ^2.1.5` and the google_sign_in_platform_interface depending on `quiver: ^3.0.0+nullsafety.2`. This is causing a resolution conflict in the `build_all_plugins_*` build steps.

The only thing I can think of at the moment is to exclude either the camera or the google_sign_in  projects from the `script/build_all_plugins_app.sh` script. @cyanglaz, @bparrishMines, do you have any thoughts on this?

**Comment by bparrishMines** [comment]
@cyanglaz @mvanbeusekom I believe this has already been fixed by https://github.com/flutter/plugins/commit/d950dda867539370af8b79d9b921f569cb074390. This PR just needs to pull in the latest changes.

**Pull request merged**
