### PR TITLE
Add support for FieldPath for where-clause querying to Firestore Plugin.

### PR DESCRIPTION
**Pull request by slightfoot**
Firestore Plugin: This change add's the ability to query nested fields in documents by using a forward slash to separate the field levels. Documentation added to `Query.where` function. Support added on iOS and Android.

### CODE REVIEW

**Comment by kroikie** [comment]
Hi @slightfoot thanks for the PR, however nested fields are already supported. Field names can use a `.` to define hierarchy much like you are doing with the `/`. See an example of this being used in the [Firestore documentation](https://firebase.google.com/docs/firestore/solutions/arrays#solution_a_map_of_values).

**Comment by slightfoot** [comment]
@kroikie thanks for the reply. I am a bit bemused by the fact their are separate functions for this FieldPath. But even so, I'd like to update my PR to just update the documentation on the `where` function to let the user's know that they can access field-paths with `.`.

What are your thoughts?

**Comment by kroikie** [comment]
@slightfoot Sounds good, we welcome PRs, especially those that improve the documentation. Thanks!

**Comment by slightfoot** [comment]
@kroikie I removed the old code changes the PR is now reflected in #629

**Comment by shashikantdurge** [comment]
How to query when the Field name consists '.' ? For example what if the field name is _abc@gmail.com_

**Pull request closed without merging**
