### PR TITLE
[url_launcher_ios] Backfill unit tests

### PR DESCRIPTION
**Pull request by Serdnad**
Backfills basic unit tests for the `url_launcher` iOS plugin, in preparation of migrating the plugin to Swift (https://github.com/flutter/flutter/issues/119102).

Ticket: https://github.com/flutter/flutter/issues/119102

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by Serdnad** [comment]
Both iOS native testing and Objective-C are admittedly out of my familiarity zone, so please let me know if there's any improvements I can make to this. I'm pretty sure these tests can be made more thorough using [POP](https://docs.google.com/document/d/1XsaulkJA6_ZSpM7chkQLhQY25sQqhEMiqHMYzw8H85o/edit?resourcekey=0-_cUjF1c0iBvRLKfV-3gK5A#) and a mock class or two, but I imagine that's a lot easier to add during the Swift migration.

**Comment by hellohuanlin** [comment]
> I'm also pretty sure these tests can be made more thorough using POP and a mock class or two, during the Swift migration.

It is important to get full coverage BEFORE the migration, so that the contributors/reviewers are fully aware of what the existing behavior is (and with bonus point to discover new bugs). 

You can follow [this](https://www.swiftbysundell.com/tips/gathering-test-coverage-in-xcode/) to get a test coverage report in Xcode. To be clear, this coverage report is just a tool, not a metric - we need to actually read the test and decide whether we have full coverage. 

If we can get good coverage without using OCMock, then just writing Swift test is fine. But if we need OCMock, then we may have to do the backfill in ObjC first due to OCMock limitation discussed [here](https://docs.google.com/document/d/1XsaulkJA6_ZSpM7chkQLhQY25sQqhEMiqHMYzw8H85o/edit?resourcekey=0-_cUjF1c0iBvRLKfV-3gK5A#heading=h.py19jr5irfws).

**Comment by jmagman** [comment]
Code coverage before this PR:

Screenshot 2023-02-08 at 6 28 51 PM


And on this PR:
Screenshot 2023-02-08 at 6 26 47 PM

**Comment by stuartmorgan-g** [comment]
We've just completed the migration of the plugin code to the flutter/packages repository, as described in https://flutter.dev/go/flutter-plugins-repo-migration, and this repository is now being archived. Unfortunately that means that all in-progress PRs here must be moved to flutter/packages.

Please see [our instructions](https://github.com/flutter/flutter/wiki/Migrating-Plugins-repository-PRs-to-Packages) for an explanation of how to move your PR, and if you have any issues moving your PR please don't hesitate to reach out in the #hackers-ecosystem channel in [Discord](https://github.com/flutter/flutter/wiki/Chat).

Our apologies that your PR was caught in this one-time transition. We're aware that it's disruptive in the short term, and appreciate your help in getting us to a better long-term state!

**Pull request closed without merging**
