### PR TITLE
[webview_flutter]Adding error message display on iOS WebView

### PR DESCRIPTION
**Pull request by hatzyuta**
On iOS, when WebView failed to load web pages for some reasons(e.g. ['ATS' on iOS](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33)),there is no process to show error messages to developers in the current version of 'webview_flutter' plugin.
I added error message display especially on iOS so that developers realize the reason why webview fails to load.

### CODE REVIEW

**Comment by hatzyuta** [comment]
I signed it!

**Comment by ened** [comment]
Could this also happen on Android?

**Comment by hatzyuta** [comment]
@ened 
'ATS' is specific to iOS,but Android's webview often fails to load due to mis-setting(e.g. [permission](https://stackoverflow.com/questions/12543301/android-webview-can-not-open-a-url-but-browser-of-mobile-can-open-it)).
Should I add the same code on Android ,too?

**Comment by ened** [comment]
@hatzyuta Perhaps yes, especially as the INTERNET permission on Android is not per se a requirement for WebView. (It could be used to display a bundled HTML file, too). I think it would be good to have complete error logs on all platforms.

**Comment by hatzyuta** [comment]
@ened
OK, I will. Thanks.

**Comment by amirh** [comment]
It actually seems that what I've suggested is addressed by https://github.com/flutter/plugins/pull/1788 given that the other PR is closer to be merge-able I'd suggest closing the current PR.

**Comment by amirh** [comment]
Closing this PR as the issue is addressed by #1788

**Pull request closed without merging**
