### PR TITLE
Support for specifying a database URL in firebase_database

### PR DESCRIPTION
**Pull request by KevinTheGray**
Previous implementation required that we specify a FirebaseApp if we wanted to specify a database URL to use.  However, it is possible to only specify the database URL which doesn't require you to configure a FirebaseApp.  

With this pull request, to specify a different database is just, `new FirebaseDatabase(databaseURL: 'https://examplefirebaseapp-db2.firebaseio.com/');`

### CODE REVIEW

**Comment by mit-mit** [comment]
Thanks for contributing @KevinTheGray! Looks like there are a few formatting errors:
https://travis-ci.org/flutter/plugins/jobs/327394005

**Comment by mit-mit** [comment]
Please also update changelog and pubspec with a new minor version.

**Comment by KevinTheGray** [comment]
@mit-mit Thanks for the feedback.  I have updated the changelog/pubspec.  I believe the formatter errors are all fixed, and I've also updated the tests for my code changes.  

However I believe the tests are failing

Format+Test I see
`The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libstdc++6 fonts-droid clang-format-5.0" failed and exited with 100 during .`

and Build-example-APKs I see
`The command "echo y | sdkmanager "extras;google;m2repository" >/dev/null" failed and exited with 1 during .`

Is there something I need to do here? Thanks!

**Comment by KevinTheGray** [comment]
@mit-mit I merged with the master branch this morning and pushed, and looks like the tests are all passing now

**Comment by mit-mit** [comment]
Great, cc @collinjackson @kroikie for review

**Pull request merged**
