### PR TITLE
[in_app_purchase] Created first unit tests on Android for IAP

### PR DESCRIPTION
**Pull request by renefloor**
This PR makes a start with unit tests for IAP on Android. Having a folder and some example tests will help other developers add unit tests for new changes.

Starts https://github.com/flutter/flutter/issues/78538

I didn't change the pubspec of changelog as nothing really changed, so I don't think a new release is needed.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by nt4f04uNd** [comment]
> Starts to fix flutter/flutter#78538

beware that with such syntax this pr will close the mentioned issue

**Review by cyanglaz — COMMENTED** [review]
We've already have similar tests in https://github.com/flutter/plugins/blob/master/packages/in_app_purchase/example/android/app/src/test/java/io/flutter/plugins/inapppurchase/MethodCallHandlerTest.java

Why did we need this tests? (I didn't look into details of the implementation of the tests, but I assume they are mostly testing the same thing).

**Comment by renefloor** [comment]
@cyanglaz sorry my bad. I looked for tests, but couldn't find them. I expected the tests to be in `in_app_purchase/android/src` instead of `in_app_purchase/example/android/src`. Should they be in example or should we move them to the source of the plugin? For example path_provider has them in the package folder: https://github.com/flutter/plugins/tree/master/packages/path_provider/path_provider/android/src

**Comment by cyanglaz** [comment]
@renefloor Talked to @mvanbeusekom offline. I think we can move the tests to android/ if possible.

**Comment by renefloor** [comment]
@cyanglaz I made PR #3732. Tomorrow I'll check if I can still use any of these new test and otherwise close this PR.

**Comment by stuartmorgan** [comment]
Sounds like this is obsolete as-is; I'm going to close it, but you can always pull code out into a new PR (or re-open) if there are tests here that need to be added once the existing tests are moved.

**Pull request closed without merging**
