### PR TITLE
[connectivity] Android Code Inspection and Clean up

### PR DESCRIPTION
**Pull request by hamdikahloun**
## Description

- Handle deprecation & unchecked warning as error

- Avoiding uses or overrides a deprecated API

- Update README with the updated information about WifiInfo on Android O or higher.

## Related Issues

https://github.com/flutter/flutter/issues/65970

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
Can you fix up the merge conflicts?

@xster - will this cause any problems with the v1 deprecation?

**Comment by hamdikahloun** [comment]
> Can you fix up the merge conflicts?
Thanks @dnfield .
Ofcorse I will fix it

**Comment by xster** [comment]
LGTM

**Comment by hamdikahloun** [comment]
@dnfield 
merge conflict(s) fixed .
Thank you

**Comment by hacker1024** [comment]
This seems to break building for me on the Flutter dev branch with `connectivity` version `0.4.9+5`:

```
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
error: warnings found and -Werror specified

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':connectivity:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by hamdikahloun** [comment]
Hi @hacker1024 

Can you try with JDK 8 please .

Thank you

**Comment by hacker1024** [comment]
I added the following to `android/app/build.gradle`, but it doesn't help.

```gradle
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

**Comment by hamdikahloun** [comment]
Can you please provide your `flutter doctor -v`, your `android/build.gradle`, your `android/gradle/wrapper/gradle-wrapper.properties` and the JDK version that installed on your computer?
Thank you

**Comment by hacker1024** [comment]
`$ flutter doctor -v`

```
[✓] Flutter (Channel dev, 1.23.0-18.0.pre, on Microsoft Windows [Version 10.0.20236.1005], locale en-AU)
    • Flutter version 1.23.0-18.0.pre at C:\Users\<USER>\AppData\Local\Flutter
    • Framework revision 37ebe3d82a (6 days ago), 2020-10-13 10:52:23 -0700
    • Engine revision 6634406889
    • Dart version 2.11.0 (build 2.11.0-213.0.dev)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Android\android-sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 15+36-1562)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Users\<USER>\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\<USER>\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.4818.26
    • Flutter plugin installed
    • Dart plugin version 203.4818.26

[✓] VS Code, 64-bit edition (version 1.50.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile) • <SERIAL>   • android-arm64  • Android 11 (API 30)
    • Windows (desktop)      • windows    • windows-x64    • Microsoft Windows [Version 10.0.20236.1005]
    • Web Server (web)       • web-server • web-javascript • Flutter Tools
    • Chrome (web)           • chrome     • web-javascript • Google Chrome 88.0.4292.2

! Doctor found issues in 1 category.
```

`android/build.gradle` (note: I've tried with the default Kotlin 1.3.50 as well)
```gradle
buildscript {
    ext.kotlin_version = '1.4.10'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

`gradle-wrapper.properties`
```properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
```

**Comment by hamdikahloun** [comment]
Can you install JDK 8, Set JAVA_HOME and update gradle-wrapper.properties to  : 

`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip`

**Set JAVA_HOME:**

- Right click My Computer and select Properties.

- On the Advanced tab, select Environment Variables, and then edit JAVA_HOME to point to where the JDK software is located, for example,` C:\Program Files\Java\jdk1.8.0_211`.

**Comment by hacker1024** [comment]
That version of Gradle is too old, it's not compatible with the default Android Gradle Plugin version.
Switching to Java 8 did nothing.

I don't really understand how this can be an issue on my end, or how the plugin even builds at all - isn't the error due to a warning that the plugin uses a Java 7 language level, that fails due to the `-Werror` argument? Doesn't the plugin need to target a language level of 1.8?

**Comment by hamdikahloun** [comment]
@hacker1024 you are welcome

**Pull request merged**
