### PR TITLE
[battery] Port battery to use platform interface

### PR DESCRIPTION
**Pull request by yash1200**
## Description

In this PR, I have ported `battery` to use `battery_platform_package` .

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by yash1200** [comment]
Hey @ditman kindly have a look at this one :)

**Comment by yash1200** [comment]
Sounds good :) Thank you @ditman .

**Comment by ditman** [comment]
Tagged and [published](https://pub.dev/packages/battery/changelog#105) as `battery: ^1.0.5`

**Comment by yash1200** [comment]
Thank you sir!

**Comment by yash1200** [comment]
Hey @ditman , I had a query, I was working on it's linux version and and for that I don't need to make method call as I can get data by opening 2 files in dart only. For that to work I have to make `get` methods `batteryLevel` and `onBatteryStateChanged` and then override the platform functions in `battery_platform_interface` to get data, which means I have to rename platform functions to get that working. Am I in right direction or is there some other method to get this working?

**Comment by ditman** [comment]
@yash1200 on Linux you just need to implement the calls to the Method Channel of the battery interface in C++, similar to this:

https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_linux/linux/url_launcher_plugin.cc

No need to override anything on the platform interface.

I hope that helps!

**Comment by yash1200** [comment]
Method channel can be implemented in Linux but I don't know about event channels. I couldn't find anything on it on flutter engine docs. That's why I was trying to implement it like [this](https://github.com/flutter/plugins/blob/master/packages/path_provider/path_provider_linux/lib/path_provider_linux.dart).

This way it can be done using Dart only, as I have to listen to file `/sys/class/power_supply/BAT1/status` for getting battery status and it can be done in Dart.

**Comment by ditman** [comment]
@yash1200 shared_preferences_linux seems to be written in Dart also, you might want to use it as an additional example: https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences_linux

What's the problem?

Also, do you think there's a more portable way to check the battery? it seems there can be multiple BATx devices (some blog posts I see BAT0)

**Comment by yash1200** [comment]
Thanks for the information @ditman . Just had a little confusion in it and it's resolved now. And for the BATx , there are only two versions of it. This differs with distros. I'll add a check for this in the plugin 😀. Thanks again.

**Pull request merged**
