### PR TITLE
[shared_preferences] Replace AsyncTask class with AsyncHandler to handle async task for Android

### PR DESCRIPTION
**Pull request by rh-id**
## Description

Replace AsyncTask class with AsyncHandler to handle async task for Android

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by rh-id** [comment]
hi @matthew-carroll / @stuartmorgan , would you review this? else just close this pull.

**Comment by stuartmorgan** [comment]
We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

If you're still interest in moving forward with this you're welcome to re-open it, and we'll get to it as we triage and prioritize the PR backlog. If not, I understand, and hope you'll consider contributing again in the future once the PR triage/review situation has improved.

**Comment by rh-id** [comment]
Hi @stuartmorgan i believe the issue is not only about PRs that takes too long to be triage and reviewed.

I had done a quick check on some of the PRs and I'm not comfortable if these are going to be merged to the plugins:

1. Issues with AsyncTasks and thread pools https://github.com/flutter/plugins/pull/3481, https://github.com/flutter/plugins/pull/3244 Usually i have one thread pool to be used anywhere for efficiency and these do not cater to my need. also there seemed to be an issue with that `MethodCallHandlerImpl.commitAsync`  and I'm not sure why it is merged into the main branch. it is creating handler and executorService object every time the method is called, both should be field variables not local variables and I'm worried if my app will have memory and performance issue if user often change shared preferences value.

2. Unnecessary kotlin migration adding more dependencies https://github.com/flutter/plugins/pull/3139

I will have to fork and maintain different version for my app for a while. If you think this PR is good I will re-open, if not just close it.

**Comment by stuartmorgan** [comment]
> I had done a quick check on some of the PRs and I'm not comfortable if these are going to be merged to the plugins

I wouldn't judge a plugin by unreviewed PRs. Anyone can open a PR, and the quality of those PRs vary significantly. One of those already had a comment explaining that we don't currently have any plans to accept it, and would require a formal proposal with discussion.

As for the merged PR, the best way to express feedback about a PR is to comment on it. If you think there are ways to improve it, you can note them there. Perhaps you have a suggestion for improvement that the reviewer missed, which could be addressed in a follow-up.

**Comment by SirusCodes** [comment]
> As for the merged PR, the best way to express feedback about a PR is to comment on it. If you think there are ways to improve it, you can note them there. Perhaps you have a suggestion for improvement that the reviewer missed, which could be addressed in a follow-up.

Yes if I'm doing something wrong letting me know would be better maybe I could improve it.

**Pull request closed without merging**
