### PR TITLE
Fixed fcm crash

### PR DESCRIPTION
**Pull request by kwmt**
I also encountered the same problem as this issue, https://github.com/flutter/flutter/issues/19017.

After updating the com.google.firebase:firebase-messaging version, I will not crash so I will PR.
https://firebase.google.com/docs/cloud-messaging/android/client?hl=en

If you have problems, please close this PR.

### CODE REVIEW

**Comment by alamboley** [comment]
Hey any news on this @kroikie? It's a bit critical.

**Comment by kroikie** [comment]
@kwmt @alamboley Could you provide the type of message being sent that causes the crash?

@kwmt Thanks for the PR much appreciated: Would you also bump the version of:

google-services plugin: 4.0.1
android plugin: 3.1.3 (in both example and plugin)
pubspec version: 1.0.4

@kwmt could you also please add a note in the CHANGELOG

**Comment by alamboley** [comment]
@kroikie yes sir, here it is (via cloud functions):
```node.js
exports.followedUser = functions.https.onCall((data, context) => {

  var info = {
    date:Math.floor(Date.now() * 0.001),
    type:"follow",
    message:data.message,
    other_id:data.other_id,
    other_user_name:data.other_user_name,
    photo_url:data.photo_url
  };

  admin.database().ref(`/notifications/` + data.id).push(info);

  const payload = {
    notification: {
      title: 'You have a new follower!',
      body: data.message,
      icon: data.photo_url
    }
  };

  admin.messaging().sendToDevice(data.tokens, payload);
});
```

**Comment by kwmt** [comment]
@kroikie Thank you for your review. I bumped these versions and added a note in the CHANGELOG.

**Comment by kroikie** [comment]
@kwmt @alamboley closing this PR since it will be part of an update of all FlutterFire Android dependencies.

**Pull request closed without merging**
