### PR TITLE
[google_maps_flutter] Add Groundoverlay support for Android

### PR DESCRIPTION
**Pull request by UDAYBIDKAR**
Adds APIs to support adding GroundOverlay to the MapView.

This PR adds a feature to Android to begin with, iOS implementation will follow.

*Issues*
https://github.com/flutter/flutter/issues/26479

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by UDAYBIDKAR** [comment]
@googlebot I signed it!

**Comment by tuemaytinh1981** [comment]
How to update on Maps SDK for Android. An upgraded map renderer is available as of version 18.0.0 of the Maps SDK for Android.
From Google:
We're writing to inform you that we released a major update of Maps SDK for Android (version 18.0.0), and it is now available via Google Play services. | We're writing to inform you that we released a major update of Maps SDK for Android (version 18.0.0), and it is now available via Google Play services.

**Comment by stuartmorgan** [comment]
@tuemaytinh1981 Please stop spamming maps PRs with this off-topic question.

**Comment by stuartmorgan** [comment]
Marking as a draft since this isn't fully review-ready yet.

**Comment by Hixie** [comment]
@UDAYBIDKAR Thanks for your contribution so far; are you interested in addressing the code review comments above so that we can take this PR all the way to landing?

**Comment by Hixie** [comment]
Looks like @UDAYBIDKAR is unfortunately no longer around to work on this, but if anyone else would like to take this PR and run with it, please don't hesitate to step up. It looks like it's close, there's just code review comments to address.

**Comment by stuartmorgan** [comment]
Since this doesn't have an active owner, I'm going to go ahead and close it. If anyone is interested in moving forward with implementing this feature, forking this PR would be a good starting point.

**Pull request closed without merging**
