### PR TITLE
[url_launcher_web] Fix a typo in a test name and fix quote consistency

### PR DESCRIPTION
**Pull request by jamesderlin**
## Description

Fix a typo in a test name and fix quote consistency.

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by ditman — APPROVED** [review]
Good change, thanks @jamesderlin!

**Review by ditman — CHANGES_REQUESTED** [review]
PS: Can you please bump the CHANGELOG.md and pubspec.yaml? That way we can publish this PR (even though it doesn't have external-facing changes, maybe a +1 bump is enough?)

**Comment by jamesderlin** [comment]
Okay, I wasn't sure if it was worth the churn of bumping the package version.

**Comment by ditman** [comment]
> Okay, I wasn't sure if it was worth the churn of bumping the package version.

Thanks @jamesderlin, this way this revision can be published to pub without having to think "why is this revision failing" :)

**Review by ditman — APPROVED** [review]
Let's merge this when the CI finishes.

**Comment by ditman** [comment]
Published, thanks for merging!

**Pull request merged**
