### PR TITLE
[sensors]Added gravityEvents to the sensors package

### PR DESCRIPTION
**Pull request by ljungqvist**
I've added gravity events to the sensors plugin.
The gravity and the user-acceleration streams are merged on the native side, since they are generated from the same data. On ios they also come in the same event. Gravity and the user-acceleration are then split up again on the Flutter side to make two different streams.

### CODE REVIEW

**Comment by ljungqvist** [comment]
I signed it!

**Comment by ljungqvist** [comment]
I do not understand why the task `test+format` is failing

**Comment by chrishens** [comment]
Any updates on this?

**Comment by ljungqvist** [comment]
> Any updates on this?

I'll merge and try to get it working again and pass all tests

**Comment by chrishens** [comment]
Any updates on this?

**Comment by stuartmorgan** [comment]
Thanks for the submission! However, we’re currently not accepting non-critical PRs for this plugin, as we hope in time to be able to transition users to the corresponding plugin in [the Flutter Community Plus Plugins repository](https://plus.fluttercommunity.dev/). We encourage you to submit your PR there.

We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

**Comment by chrishens** [comment]
Many thanks and not to worry. However, what is not critical for you might be critical for us. As a general comment, it is exactly this slowness in triaging and responding to PRs that has pushed us away from flutter altogether.

**Pull request closed without merging**
