### PR TITLE
[multi-packages] Migrate packages and examples to AGP 7.0.0 & Gradle 7.0.2

### PR DESCRIPTION
**Pull request by TahaTesser**
Fixes https://github.com/flutter/flutter/issues/88666

Based on https://github.com/flutter/plugins/pull/4079, I am not sure if this requires tests but let me know if it does 

FYI, keeping this PR as a draft until https://github.com/flutter/flutter/issues/87649 is merged. I think it will be better if Flutter migration is completed before this PR is merged 

### Todo

- [ ] Update changelog and `pubpsec.yaml` for all updated packages. (Since this might take a while to be merged if I make any version changes now, it will most likely need to be updated again so I will do this once the PR is ready to be reviewed).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by TahaTesser** [comment]
This is not breaking change but I still locally tested each package/example migrated, they're all building and running fine on the emulator

**Comment by stuartmorgan** [comment]
It appears that this requires Java 11, which [was problematic](https://github.com/flutter/flutter/issues/84706) last time we (inadvertently) tried to switch to it. Fixing issues with Java 11 so that we're not pinned to 1.8 will be necessary as a precursor PR.

/cc @blasten Have you had a chance to look into why 11 doesn't work for us since that tree closure incident?

**Comment by stuartmorgan** [comment]
Does this pass if you rebase to master? We should have Java 11 in CI now.

**Comment by blasten** [comment]
Any updates on this?

**Comment by TahaTesser** [comment]
@blasten 
I will look into this asap

**Comment by TahaTesser** [comment]
@blasten @stuartmorgan 
If I am not mistaken, looks like some unit tests are failing after the upgrade, any ideas?

**Comment by TahaTesser** [comment]
Closing this for now as it has become very polluted

**Pull request closed without merging**
