### PR TITLE
[video_player] Add onComplete callback

### PR DESCRIPTION
**Pull request by smkhalsa**
## Description

Adds an onComplete callback to the video_player plugin.

### CODE REVIEW

**Comment by smkhalsa** [comment]
@googlebot I signed it!

**Comment by cbenhagen** [comment]
@smkhalsa thank you for your contribution! Unfortunately the structure of the plugin has changed lately to support implementations on more platforms. Mainly the plugin was moved to a new subdirectory and now uses a common platform interface. Adapting your PR to the new structure should be straight forward. If you have questions please ask!

Please also make sure to include tests for the new functionality.

**Comment by mockturtl** [comment]
@smkhalsa Thanks for implementing this!  Your changes work great with the current version (0.10.7).

Do you think you'll be able to fix this PR (see above) soon?

**Comment by smkhalsa** [comment]
@mockturtl I don't have time to dive back into this at the moment, but if you want to apply these changes to a new PR, I'd be happy to close this in favor of yours.

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
