### PR TITLE
Pass a Uri to package:http APIs

### PR DESCRIPTION
**Pull request by natebosch**
Prepare for https://github.com/dart-lang/http/issues/375

### CODE REVIEW

**Review by ditman — COMMENTED** [review]
Thanks for the fix @natebosch, before merging we'll have to bump the version in the pubspec + CHANGELOG so this becomes publishable!

**Comment by natebosch** [comment]
I bumped to a `-dev` version so it is clear this has changed since it was last published. https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change

There is no need to publish just for this - it won't have any real impact for places where it is fetched from pub. Where this will make a difference is google3.

**Comment by ditman** [comment]
I need to do a quick real world test with this, I remember Safari having trouble when parsing Blob URLs before doing the ajax fetch. I'll merge this once that's done.

Also, there's a similar package: `cross_file` that might need a similar fix to this (but it's probably not imported into g3), I'll take care of that one!

**Comment by natebosch** [comment]
> I need to do a quick real world test with this, I remember Safari having trouble when parsing Blob URLs before doing the ajax fetch. I'll merge this once that's done.

There should be no impact. That `Uri.parse` call happens today already, it's just happening deep in the `http` functions instead of at the call site.

https://github.com/dart-lang/http/blob/d473635f0dbb72936664696162127c2209986356/lib/src/base_client.dart#L110

> Also, there's a similar package: `cross_file` that might need a similar fix to this (but it's probably not imported into g3), I'll take care of that one!

Thanks!

Note that this won't have an impact on any package until it changes it's dependency constraints in `pubspec.yaml`. This will come with a major version bump in `http`. The main reason I need to do google3 packages in advance is because pubspec constraints don't have any impact there.

**Comment by natebosch** [comment]
It looks like tests are failing due to the `-dev` suffix on the version I mentioned in  https://github.com/flutter/plugins/pull/3309#issuecomment-741341246. This is a pattern that we use to indicate when the code in the repo does not match the code as published under that version, and until we go to do a publish we don't know whether the code will match.

Since this repo doesn't take that approach which is prefered - do you eagerly bump the version when the code changes even without user facing changes, or do you wait to bump the version until there is a user facing change to document in the changelog?

**Comment by ditman** [comment]
> do you eagerly bump the version when the code changes even without user facing changes

@natebosch yes, let's bump the minor version and document in the CHANGELOG that this passes `Uri` objects instead of `Strings` to `package:http` methods. I can do this, now that you've touched the files themselves from the web UI, I think!

Thanks for the clarification about the major version and the links to the http source!

**Review by ditman — APPROVED** [review]
LGTM, thanks for the fix @natebosch!

**Comment by ditman** [comment]
@googlebot I consent.

**Pull request merged**
