### PR TITLE
[in_app_purchase] Ensure the `introductoryPriceMicros` field is populated correctly.

### PR DESCRIPTION
**Pull request by mvanbeusekom**
Due to a typo the `SkuDetailsWrapper.introductoryPriceMicros` field wasn't populated correctly with the values send from the native side. 

The first [commit](https://github.com/flutter/plugins/commit/1b1ec27222107eee976faae18476bf088502b1d0) of this PR updates the existing unit tests to prove the existence of the issue. The second [commit](https://github.com/flutter/plugins/commit/77e2c6ddaae95600b1b93f9d51350fb155a045f9) fixes the implementation of the `SkuDetailsWrapper` class so the tests succeed and populate the field correctly.

Fixes flutter/flutter#90244

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Review by cyanglaz — APPROVED** [review]
LGTM

**Comment by 781flyingdutchman** [comment]
I believe this commit breaks  queryProductDetails on Android, because the defaultValue for this field is set to be a string, when it should be an int. As a result, I am getting `Unhandled Exception: type 'int' is not a subtype of type 'String?' in type cast` on line 15 of the generated file sku_details.wrapper.g.dart

**Comment by cyanglaz** [comment]
cc @mvanbeusekom

**Comment by mvanbeusekom** [comment]
Will provide a fix today.

**Comment by mvanbeusekom** [comment]
@cyanglaz, I have just created a new [PR](https://github.com/flutter/plugins/pull/4370) which should resolve the problem.

**Pull request merged**
