### PR TITLE
Changing user info in Firebase Auth

### PR DESCRIPTION
**Pull request by MarcinusX**
Resolves flutter/flutter#10580

Since I don't have mac, iOS version was not even compiled. Before merging can someone check if it works as supposed, please?

I had no idea what doc I could add to dart class, I think it is pretty self-explaining. If you think otherwise, I'd like add some docs. :)

### CODE REVIEW

**Comment by Patryk1410** [comment]
CLA update

**Comment by MarcinusX** [comment]
CLA update

**Comment by MarcinusX** [comment]
I signed it!

**Comment by MarcinusX** [comment]
I can't format my iOS file due to flutter/flutter#12351

**Comment by mit-mit** [comment]
Hi @MarcinusX are you still interested in completing this PR?

Travis actually has the right format listed for you:

From https://travis-ci.org/flutter/plugins/jobs/283509107, just a single line to fix:
```
-- a/packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
+++ b/packages/firebase_auth/ios/Classes/FirebaseAuthPlugin.m
@@ -117,8 +117,7 @@ NSDictionary *toDictionary(id<FIRUserInfo> userInfo) {
                                           [self sendResult:result forUser:user error:error];
                                         }];
   } else if ([@"updateProfile" isEqualToString:call.method]) {
-    FIRUserProfileChangeRequest *changeRequest =
-        [[FIRAuth auth].currentUser profileChangeRequest];
+    FIRUserProfileChangeRequest *changeRequest = [[FIRAuth auth].currentUser profileChangeRequest];
```

Also, there is a missing type in the dart file, from https://travis-ci.org/flutter/plugins/jobs/283509106
```
Checking project firebase_auth...


  info - Specify type annotations at lib/firebase_auth.dart:42:43 - (always_specify_types)
```

**Comment by MarcinusX** [comment]
Hmm.. I resolved conflicts using GItHub UI but it still says there are conflicts... can you help me with that please?

**Comment by MarcinusX** [comment]
CLA update

**Comment by mit-mit** [comment]
This commit appears to be from a different github account? 
https://github.com/flutter/plugins/pull/222/commits/3c811bb0053c827117ad663216e8f6f37262c492

**Comment by mit-mit** [comment]
Thanks for confirming

**Comment by mit-mit** [comment]
@kroikie can you please do a code review?

**Comment by mit-mit** [comment]
@kroikie did you get this reviewed?

**Comment by kroikie** [comment]
Yes this looks good to me, @MarcinusX thanks for the PR.

**Comment by MarcinusX** [comment]
I'm glad to hear that, however I would like to point out that I haven't tested this functionality on iOS. I think someone should test it on iOS before merging just to be sure (everything should be fine but I have no way to really test it). What do you think?

**Comment by mit-mit** [comment]
I can give it a try on iOS. What are the best ways to test it?

**Comment by MarcinusX** [comment]
Imo quickest way to test it:
1.Create app
2.Setup Firebase https://codelabs.developers.google.com/codelabs/flutter-firebase/#4
3.Enable anonymous auth in Firebase Console -> Auth
4.Paste this code https://gist.github.com/MarcinusX/0a90b9126daea03520a10773bae25ca4 to your app
5.Add dependency of firebase_auth with updateProfile method. The best way might be to clone my branch from which I made pull request.
6.Run app, press FAB -> First label should change to "New display name", second to null.
7.Every time FAB is pressed, first label should change from string to null and otherwise.
If so, updating profile works :)

**Comment by mit-mit** [comment]
Hi @MarcinusX for reasons I don't understand Travis never ran on your last commit. I just pulled this locally, and it didn't pass analysis as there was a missing close bracket. I added that, and now Travis is rerunning and producing some errors. Would you mind taking a look at those?

**Comment by MarcinusX** [comment]
@mit-mit wow, I totally missed your last comment, I will check and fix it ASAP

**Comment by MarcinusX** [comment]
Ok, I fixed merge-related issues. I have 2 problems now:
1. In last build there is an issue with duplicate "case", however I did fix it and it is not in merge request anymore so I assume that in next build it would be ok (still, strange for me).
2. I get following error for dart file:
```
FirebaseAuth updateProfile [E]                                                        
  type '_InternalLinkedHashMap' is not a subtype of type 'Null' of 'function result' where
    _InternalLinkedHashMap is from dart:collection
    Null is from dart:core
```
It is connected to this code:
```
Future<Null> updateProfile(UserUpdateInfo userUpdateInfo) async {
    assert(userUpdateInfo != null);
    return await channel.invokeMethod(
      'updateProfile',
      userUpdateInfo._updateData,
    );
  }
```
The way this method works is that it doesn't return anything, so I guess that `Future<Null>` is appropriate. However I think that the problem is when channel method would return PlatformException and that's why it doesn't pass check. I am not sure how to approach this. I could just invoke method and then `return null;` but I haven't seen anybody doing that. What do you think?

**Comment by Hixie** [comment]
@mit-mit Can you take a look at @MarcinusX's last comment? Thanks!

**Comment by MarcinusX** [comment]
@mit-mit  I resolved conflicts and now I have same problem as in my last comment about defying null as return value. Could you look at it please? :)

**Comment by mit-mit** [comment]
The error is:
```
info - Specify type annotations at lib/firebase_auth.dart:42:43 - (always_specify_types)
```

Try this:
```
   final Map<String, String> _updateData = <String, String>{};
```

**Comment by MarcinusX** [comment]
@mit-mit I did it but it made me even more confused, see details of build :(

**Comment by mit-mit** [comment]
Yeah that was confusing -- it was a transient networking issue, and resolved itself when I re-ran it!

However, there is a new failure:
```
00:00 +8 -1: FirebaseAuth updateProfile [E]                                                        
  type '_InternalLinkedHashMap' is not a subtype of type 'Null' of 'function result' where
    _InternalLinkedHashMap is from dart:collection
    Null is from dart:core
  
  package:firebase_auth/firebase_auth.dart 253:12  FirebaseAuth.updateProfile
  ===== asynchronous gap ===========================
  dart:async                                       _Completer.completeError
  package:firebase_auth/firebase_auth.dart         FirebaseAuth.updateProfile
  ===== asynchronous gap ===========================
  dart:async                                       _asyncThenWrapperHelper
  package:firebase_auth/firebase_auth.dart 251:67  FirebaseAuth.updateProfile
  firebase_auth_test.dart 213:18                   main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                       new Future.microtask
  firebase_auth_test.dart 208:36                   main.<fn>.<fn>
  
00:00 +10 -1: Some tests failed.    
```

What does `updateProfile(UserUpdateInfo userUpdateInfo)` actually return?

**Comment by alibitek** [comment]
> What does updateProfile(UserUpdateInfo userUpdateInfo) actually return?

The method signature says `Future<Null>` , the error message says that `channel.invokeMethod` returns [_InternalLinkedHashMap](https://github.com/dart-lang/sdk/blob/master/runtime/lib/compact_hash.dart#L130) aka a 

> VM-internalized implementation of a default-constructed [LinkedHashMap](https://github.com/dart-lang/sdk/blob/master/sdk/lib/collection/linked_hash_map.dart#L5)

The runtime type of a Dart Map object is: `print(<dynamic, dynamic>{}.runtimeType);` ~  `_InternalLinkedHashMap`

This is because the setUp method of the group within which the updateProfile test runs calls [setMockMethodCallHandler](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/services/platform_channel.dart#L178) on the FirebaseAuth's MethodChannel: https://github.com/MarcinusX/plugins/blob/master/packages/firebase_auth/test/firebase_auth_test.dart#L32
Which will actually return mocked responses instead of making the actual call to the platform when calling `invokeMethod` on the channel. (hence "units tests" 😄 )
```dart
  setUp(() {
      log.clear();
      FirebaseAuth.channel.setMockMethodCallHandler((MethodCall call) async {
        log.add(call);
        switch (call.method) {
          case "getIdToken":
            return kMockIdToken;
            break;
          case "startListeningAuthState":
            return mockHandleId++;
            break;
          default:
            return mockFirebaseUser();
            break;
        }
      });
    });
```
When the updateProfile test is run, the call to:
```dart
channel.invokeMethod(
      'updateProfile',
      userUpdateInfo._updateData,
    );
```
will fallthrough the default case and return a `Map<String, dynamic>`, aka the result of the [mockFirebaseUser method](https://github.com/MarcinusX/plugins/blob/722ee26e857da4ec3c7670d678fe390e08088f97/packages/firebase_auth/test/firebase_auth_test.dart#L291).

To fix the problems with the test failing you need to do the following two changes:
1) Change setUp method to:
```dart
 setUp(() {
      log.clear();
      FirebaseAuth.channel.setMockMethodCallHandler((MethodCall call) async {
        log.add(call);
        switch (call.method) {
          case "getIdToken":
            return kMockIdToken;
            break;
          case "startListeningAuthState":
            return mockHandleId++;
            break;
          case "updateProfile":
            return null;
          default:
            return mockFirebaseUser();
            break;
        }
      });
    });
```

2) Change the expect call to:
```dart
expect(
  log,
  <Matcher>[
    isMethodCall(
      'updateProfile',
      arguments: <String, String>{
        'photoUrl': kMockPhotoUrl,
        'displayName': kMockDisplayName,
      },
    ),
  ],
);
```

Verify results
- `pub global activate flutter_plugin_tools`
- `pub global run flutter_plugin_tools format --plugins firebase_auth`
- `pub global run flutter_plugin_tools analyze --plugins firebase_auth`
- `pub global run flutter_plugin_tools test --plugins firebase_auth`

**Comment by MarcinusX** [comment]
Wow, thank you @alibitek ! I was focused on what is wrong with my method that I didn't think about invalid test.

**Comment by alibitek** [comment]
@MarcinusX It's always good to take a step back and try to isolate the problem as much a possible. A debugger can help a long way :-)

I think you can sign the CLA https://cla.developers.google.com/clas and then this PR is ready to be reviewed.

**Comment by MarcinusX** [comment]
When it comes to CLA, there was a problem with multiple authors but as far as I know, @mit-mit has confirmed everything is ok.

**Comment by mit-mit** [comment]
Yes, the CLA status is due to a single commit from another contributor, but we established [up here](https://github.com/flutter/plugins/pull/222/files/481633e043f41c2301577324afd9c73d9e7a108a..fdd826fa689669eea98d89b7afb1959fdd8bd3f0#issuecomment-342065389) that this is OK.

**Comment by MarcinusX** [comment]
@mit-mit Could we move forward with this PR? :)

**Comment by mit-mit** [comment]
Sorry, hadn't noticed your last commit. cc @collinjackson @kroikie can you give this a review?

**Pull request merged**
