### PR TITLE
Clean up CODEOWNERS

### PR DESCRIPTION
**Pull request by blasten**
Now that we are adding GitHub actions to automatically label PRs, it would be easier to filter PRs based on the paths they have modified.

If you would rather keep your name in the owners file, let me know. I'm happy to update accordingly.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by ditman** [comment]
Wooow! CODEOWNERS is somewhat useful in that it's automatically adding reviewers to PRs. Is that unwanted behavior?

**Comment by blasten** [comment]
@ditman oh no at all! If it's useful to you, sure!

**Comment by ditman** [comment]
Don't keep it around for me, if you move this to automatic labeling somehow, that's good for me too!

**Comment by stuartmorgan** [comment]
Is there a resolution on what we're doing with this file?

**Comment by blasten** [comment]
I think @cyanglaz finds it useful. I can clean the owners file if is preferred. Maybe, I can start by removing folks that don't actively contribute to this repo. Do you have a suggestion?

**Comment by stuartmorgan** [comment]
> Maybe, I can start by removing folks that don't actively contribute to this repo.

Sounds good to me as a starting point. I do have some concerns about having reviewers assigned to issues that they have no intention of reviewing in the foreseeable future though, so I think I'd prefer having it only contain people who opt in who are planning to manage their automatic review requests regularly.

(One we've adjusted the PR queue triage maybe we can revisit.)

**Comment by cyanglaz** [comment]
I created a PR to remove myself from some of the plugins that I don't promptly review.  https://github.com/flutter/plugins/pull/3495

**Comment by blasten** [comment]
PTAL

**Review by stuartmorgan — APPROVED** [review]
LGTM. We can revisit once we made more triage progress to see if we want to adjust further

**Pull request merged**
