### PR TITLE
[local_auth] Add option to AuthenticationOptions to force strong biometrics only.

### PR DESCRIPTION
**Pull request by BeMacized**
This PR adds a `strongBiometricsOnly` flag to the AuthenticationOptions on Android, to enable authenticating with strong biometrics only.

_Note: I have tested this on a device with strong biometrics present. While the appropriate error responses should be returned on a device with only weak biometrics, I have not been able to test this as I have not yet found any hardware that meets this criteria._

~~This PR still lacks tests and pubspec/changelog updates, I'll take care of this tomorrow.~~

Relevant issue:
 - flutter/flutter#81169

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
Finally catching up on these, sorry about that. Could you update this to the latest `main`? We've reworked the auth flow so there are non-trivial conflicts here. Overall they I believe the changes will line up well with what you are changing here, and simplify the PR somewhat.

**Comment by jcho0216** [comment]
@BeMacized When do u think that this job could be done? I want to use this feature in my projects asap :)

**Comment by GaryQian** [comment]
@BeMacized Whenever you get a chance, rebase this PR and we can start to take a look at reviewing

**Comment by Hixie** [comment]
@BeMacized Is this PR still on your radar?

**Comment by reidbaker** [comment]
Closing this as stale and there are conflicts. Please re-open if progress can be made.

**Pull request closed without merging**
