### PR TITLE
[webview_flutter] add gesture navigation for iOS

### PR DESCRIPTION
**Pull request by wwwdata**
## Description

This introduces a boolean for the allowsBackForwardNavigationGestures setting of the WKWebView in iOS. It has no effect on Android.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by ened** [comment]
Hi @wwwdata - thank you for the PR!
It seems like useful addition to the web view plugin.
Could you please rebase & also add a e2e test. You can find the existing e2e test suite in `example/test_driver/webview_flutter_e2e.dart`.
Once both done, we can proceed to the next step. Thank you once again!

**Comment by wwwdata** [comment]
@ened thanks for the fast response. I am a bit confused about the e2e tests. As far as I see it currently, they are basically running some quick unit tests but using the real platform for that, correct? What could I in my case add as a test? In order to test whether it works, I would really have to launch a WebView in iOS then find a link to tap on, which navigates forward, after that use a swipe gesture to navigate back again.

For now, I just added a test that is launching the WebView with my new feature to see that nothing crashes

**Comment by ened** [comment]
@wwwdata That will do it for the moment. Among other behaviour, the key issue is to check whether the native component will load properly and received the right configuration.

Something I'm not sure yet is whether it's ok to no-op the test on Android. Understood it's a non-supported feature on Android, but if it ever will be in the future, the test may be missed.

Besides, the underlying platform implementation should not ignore parameters it doesn't know about.

**Comment by wwwdata** [comment]
> Something I'm not sure yet is whether it's ok to no-op the test on Android. Understood it's a non-supported feature on Android, but if it ever will be in the future, the test may be missed.

You're right will remove the no-op. It should go through and really test that nothing bad happens.

**Comment by ened** [comment]
@wwwdata After reading this a few more times, would you agree that `gestureNavigationEnabled` is more concise & clear to the developer that will use the webview widget?
It also seems to be in line with `debuggingEnabled`.

**Comment by collinjackson** [comment]
I agree with @ened that `gestureNavigationEnabled` works better as a cross-platform name.

**Comment by wwwdata** [comment]
Ok. New name makes sense! Thanks for already making the change.

**Pull request merged**
