### PR TITLE
Avoid manual configuration of repos when consuming image_picker

### PR DESCRIPTION
**Pull request by mravn-google**
Cf https://github.com/flutter/flutter/issues/9881

### CODE REVIEW

**Comment by goderbauer** [comment]
@LarkAscending I think this will allow us to simplify the codelab as we can remove the step where we require people to manually add the jitpack repository.

**Comment by mravn-google** [comment]
@goderbauer Package should be ready to for publication, but I am not authorized to do that.

**Comment by eseidelGoogle** [comment]
If the updated pub site supports group-based acls, we should definitely add a flutter-publishers acl to prevent this kind of thing in the future. :D . @kevmoo

**Comment by goderbauer** [comment]
> Package should be ready to for publication, but I am not authorized to do that.

@mravn-google Added you as an uploader. You should be able to publish now.

> If the updated pub site supports group-based acls

Groups would be sooo awesome!

**Comment by mravn-google** [comment]
Published.

**Comment by LarkAscending** [comment]
@goderbauer Thanks for the heads up! The codelab uses alpha channel...This is in master, so the next time alpha is updated we'll remove this step.

**Comment by LarkAscending** [comment]
Codelab updated! https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#4

**Comment by LarkAscending** [comment]
And image_picker version revved from 0.1.0 to 0.1.1.

**Pull request merged**
