### PR TITLE
[shared_preferences] Fix deprecated API call

### PR DESCRIPTION
**Pull request by Zazo032**
Right now, while building, users get this warning:
```
C:\Users\Cristian\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\shared_preferences-0.5.6+1\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
```
I think this has rolled to stable now so it can be fixed to not use a deprecated API.

Fixes https://github.com/flutter/flutter/issues/48211

### CODE REVIEW

**Comment by cyanglaz** [comment]
LGTM thanks!

**Comment by ditman** [comment]
I don't know much about the Java version of plugins, but if @cyanglaz approves, it's probably OK!

(@cyanglaz ping me if you need a hand merging/publishing this)

**Comment by cyanglaz** [comment]
@ditman This is calling a depreciated API in engine and since the new API is in stable, we can use the new API.
Thanks for offering to help! I will merge it as soon as the post-submit tree goes green :)

**Comment by otopba** [comment]
LGTM

**Comment by wymored** [comment]
Please accept this pr, the message is annoying and I need the plugin to my app

**Comment by ditman** [comment]
This is already tagged as "submit queue", it'll get merged.

**Comment by matt39** [comment]
@cyanglaz could you please review the patch? Would be very helpful.

**Comment by ened** [comment]
Hi @Zazo032 are you available to work on this PR a bit further? The proposed change fixes the problem but is part of a bigger change we need to do for each plugin.
You can refer to this PR for the description / TODO list: https://github.com/flutter/flutter/issues/47153
You can refer to this PR for an complete example: https://github.com/flutter/plugins/pull/2590.

Thank you!

**Comment by xster** [comment]
Our task list for cleanup on the plugins is a bit longer as @ened pointed out. But this is ok to merge incrementally for now.

**Comment by anton-roos** [comment]
I am still getting this, was it merged?

**Pull request merged**
