### PR TITLE
[google_maps_flutter] Allow (de-)serialization of CameraPosition

### PR DESCRIPTION
**Pull request by duzenko**
## Description

Make CameraPosition.toMap public and change visibility of CameraPosition fromMap.
Intended use:

```
              final s = json.encode(lastPosition.toMap());
              prefs.setString('cameraPosition', s);
...
              final map = json.decode(prefs.get('cameraPosition'));
              final cam = CameraPosition.fromMap(map);
              await controller.moveCamera(CameraUpdate.newCameraPosition(cam));
```

## Related Issues

Fixes https://github.com/flutter/flutter/issues/34321

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
_Presumably none needed_
- [ ] All existing and new tests are passing.
_Impossible: https://github.com/flutter/flutter/issues/33964_
- [ ] I updated/added relevant documentation (doc comments with `///`).
_None found_
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
_Pending review_
- [ ] I updated CHANGELOG.md to add a description of the change.
_Pending review_
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by iskakaushik** [comment]
Change looks good. Can you update the pubspec and changelog? Thanks!

**Comment by iskakaushik** [comment]
@duzenko I was busy with some issues in the past couple of weeks. Let me know if you get a change to fix the merge conflicts and we can merge this.

**Comment by duzenko** [comment]
@iskakaushik 
I'm traveling and AFK most of the time. I'll try to do some time.

**Comment by duzenko** [comment]
> 
> 
> @duzenko I was busy with some issues in the past couple of weeks. Let me know if you get a change to fix the merge conflicts and we can merge this.

Fixed

**Comment by iskakaushik** [comment]
Now that marker drag events is in. Can you please rebase?

**Comment by duzenko** [comment]
> 
> 
> Now that marker drag events is in. Can you please rebase?

Done.
What about my other PRs - #1719 & #1821?

**Comment by iskakaushik** [comment]
@duzenko I'm trying to figure out what is wrong with the plugin tools format to drive https://github.com/flutter/plugins/pull/1821 to green and get it merged. For the other PR it will get prioritized per the number of thumbs-up in the issues.

**Pull request merged**
