### PR TITLE
[video_player] Added `muted` attribute

### PR DESCRIPTION
**Pull request by otopba**
## Description

Added `muted` attribute. You can mute video player

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by sanekyy** [comment]
@googlebot I consent.

**Comment by ened** [comment]
Hi @otopba thank you for the PR, the muted argument is a good idea.
In order to be ready for the merge, could you please add e2e tests for in https://github.com/flutter/plugins/blob/master/packages/video_player/video_player/example/test_driver/video_player_e2e.dart ?
As the mute switch also affects the `volume` behaviour, could you please extend the documentation as well (it should explain that the volume goes back to the last set volume, for example). Thank you once again!

**Comment by sanekyy** [comment]
Hi @ened. Thanks for suggestions. Done.

**Comment by ened** [comment]
hi @sanekyy once again. I have asked rgd. the `video_player_web` analysis problem and the suggestion is to *not* change the `video_player_web` *dependency* version in this PR for the moment. Could you please adjust the version so that analysis passes?
So, increment `video_player_web` version, but do not depend on it (because its not yet published).
Thank you.
/cc @amirh

**Comment by sanekyy** [comment]
Done. But there is the same problem with `video_player_platrofm_interface`.

**Comment by ened** [comment]
@sanekyy Sorry, in that case we will have to do the same thing for video_player_platform_interface dependency.  There's a ongoing discussion about this here: https://github.com/flutter/flutter/issues/46264.

**Comment by sanekyy** [comment]
@ened 
I can do it but there is another problem.

We add method mute into platform interface, so if I will use last published version of `video_player_platform_interface` it will not contains my method and build will fail.

For now I will use git dependency of `video_player_platform_interface` with reference to my changes to pass check:

```
video_player_platform_interface: #^1.0.5
    # workaround for success build checks in PR
    git:
      url: git://github.com/sanekyy/plugins.git
      ref: muted-attribute
      path: packages/video_player/video_player_platform_interface
```

But maybe you know the right way?

**Comment by sanekyy** [comment]
@googlebot I consent.

**Comment by otopba** [comment]
@ened 
Check it please

**Comment by ened** [comment]
@otopba, @sanekyy  thank you for the updated PR.

@iskakaushik @mklim could I trouble you for your help to review this PR? The PR adds a new attribute to the platform interface (muted), which does correspond to platform methods.

What is a good approach to implement this? Does it require two PRs (one for platform_interface & one for the plugin itself?).

**Comment by sanekyy** [comment]
Same question for #2429 and #2406

**Comment by cyanglaz** [comment]
I'm going to close the PR because the CLA is not signed. Feel free to ping me when the CLA is signed and I'll re-open the PR. Or you can open a new PR after signing the CLA.

**Pull request closed without merging**
