### PR TITLE
[in_app_purchase]Change a comment.

### PR DESCRIPTION
**Pull request by HiIamAlanOu**
## Description

Change a comment.

### CODE REVIEW

**Comment by HiIamAlanOu** [comment]
@googlebot I signed it!

**Comment by mklim** [comment]
Thanks again for the fix!

**Comment by droidery** [comment]
@mklim Not sure the best place to ask, but can the new versions be published (0.2.2+5/0.2.2+6) to pub.dev (or what's the release cycle) as I need the fix from 0.2.2+5

**Comment by mklim** [comment]
@droidery sorry about the delay there, thanks for the ping. The release process is totally manual and it looks like we missed publishing those PRs (https://github.com/flutter/flutter/issues/27258). They should be available now.

**Pull request merged**
