### PR TITLE
[webview] Added ability to add cookies to CookieManager (Android only currently)

### PR DESCRIPTION
**Pull request by amourinho**
With regards to this issue, https://github.com/flutter/flutter/issues/27597

I've added the ability to set cookies from the cookiemanager.

### CODE REVIEW

**Comment by amourinho** [comment]
I signed it!

First time contributing to an open source project. Apologies! =)

**Comment by wbingz0719** [comment]
Has this problem been solved? I haven't seen a way to set cookies yet.

**Comment by wbingz0719** [comment]
Has this problem been solved? I haven't seen a way to set cookies yet.

**Comment by wbingz0719** [comment]
Has this problem been solved? I haven't seen a way to set cookies yet.

**Comment by bingzhao0719** [comment]
> With regards to this issue, [flutter/flutter#27597](https://github.com/flutter/flutter/issues/27597)
> 
> I've added the ability to set cookies from the cookiemanager.
Has this problem been solved ? I don't know how to use it. Please help

**Comment by bingzhao0719** [comment]
@amourinho Has this problem been solved ?  I don't know how to use it. Please help

**Comment by amourinho** [comment]
@bingzhao0719 I needed a solution for the iOS platform and was unable to create the code myself to get it working. The code I had committed was working on the Android only at the time. This is still it's current state. =/

**Comment by wbingz0719** [comment]
I see that you submitted code with the addCookie method, but why can't you see the addCookie method in the webview_flutter 0.3.14 version of the code?






------------------ 原始邮件 ------------------
发件人: "Andre Mourinho"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 凌晨0:22
收件人: "flutter/plugins"<plugins@noreply.github.com>;
抄送: "上善若水"<545928499@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [flutter/plugins] [webview] Added ability to add cookies toCookieManager (Android only currently) (#1179)




@bingzhao0719 I needed a solution for the iOS platform and was unable to create the code myself to get it working. The code I had committed was working on the Android only at the time. This is still it's current state. =/

**Comment by stuartmorgan** [comment]
Thanks for the contribution! Given that https://github.com/flutter/plugins/pull/2278 covers both platforms and has tests, making it much closer to something that could be landed, I'm going to close this in favor of that PR. Feel free to take a look at that PR and offer feedback if there are elements you think should be adjusted.

We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

**Pull request closed without merging**
