### PR TITLE
[google_sign_in] adds option to re-authenticate on google silent sign in

### PR DESCRIPTION
**Pull request by ThetaSinner**
Adds an optional paramter to the signInSilently method which allows the application using the plugin to decide whether re-authentication should be attempted.

Fixes [#88556](https://github.com/flutter/flutter/issues/88556) 

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [X] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by ditman** [comment]
Thanks @ThetaSinner! As I said, in web I'm not sure that calling signInSilently multiple times will cause the same effect as in android, but that's a gap that can be filled later. We just need to confirm it, so we can document the difference across platforms.

**Comment by ThetaSinner** [comment]
Looks like you're right about the web behaviour, the existing login is [used ](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in_web/lib/google_sign_in_web.dart#L126)to build the response to signInSilently.

The underlying [JavaScript library](https://github.com/google/google-api-javascript-client) does not discuss ID tokens (that I have seen!). The signIn [method](https://github.com/google/google-api-javascript-client/blob/e296cd6faf2adcb2c9ee2dfc3b05f1aae92ff731/docs/samples.md#authorizing-and-making-authorized-requests) it provides is interactive.

It doesn't look like working quietly  with ID tokens on web will work without a change to the google-api-javascript-client library. I don't need it so I'm happy with documented differences. Would you like me to find somewhere for that to go and add it to this PR?

**Comment by ditman** [comment]
The web version is going to need a bunch of rewriting [soonish](https://github.com/flutter/flutter/issues/88084), that might change things. In the meantime, let's do this. I think the web version re-authenticates automatically, so as long as one always requests the current identity from the JS code, the token will always be valid (at least, that's my operating assumption :P)

**Review by ditman — APPROVED** [review]
LGTM! Let me find somebody from the iOS team to verify that this won't hurt there!

**Review by cyanglaz — APPROVED** [review]
LGTM on iOS

**Comment by ditman** [comment]
Thanks for the super-late review @cyanglaz !!

**Comment by Bharathh-Raj** [comment]
Hey @ThetaSinner, I wanted fresh idToken whenever i sign in. So I used this signInSilently method with reAuthenticate param as true. But I keep on getting the same idToken even after using this.

**Comment by Bharathh-Raj** [comment]
So the OAuth API itself won't give us new idtoken unless it is about to/did expire? Is there any way to force the api to respond with new id token whenever I request? I'm using a service which have just 60 seconds window time to validate.

**Pull request merged**
