### PR TITLE
[webview_flutter][android]allow-disable-system-text-zoom

### PR DESCRIPTION
**Pull request by LongXiangGuo**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

Fix the android system font  size effect the webview font size, po asked to disable the system font settings in webview

related issue: https://github.com/flutter/flutter/issues/70731 (comment add `setTextZoom`)
related pr: https://github.com/flutter/plugins/pull/3325/files (comment add `setTextZoom`)

no breaking

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by LongXiangGuo** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Comment by LongXiangGuo** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Comment by LongXiangGuo** [comment]
@googlebot I signed it!

**Comment by LongXiangGuo** [comment]
@googlebot I signed it!

**Comment by Maxim-Gorin** [comment]
When is it ready to be able to use setTextZoom to configure the webview?

**Comment by LongXiangGuo** [comment]
@googlebot I signed it!

**Comment by LongXiangGuo** [comment]
> When is it ready to be able to use setTextZoom to configure the webview?

Only when the webview first created

> When is it ready to be able to use setTextZoom to configure the webview?

The first time it was created.

**Comment by LongXiangGuo** [comment]
> When is it ready to be able to use setTextZoom to configure the webview?

The first time `FlutterWebView` was created

**Comment by stuartmorgan** [comment]
Thanks for the submission! We’re currently working through a large backlog of PRs, and this will require non-trivial review (since we need to evaluate how we want to manage the settings API over time so that it doesn't become unmanageable), so it will take some time before we’re able to review it. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are the primary way we’re prioritizing non-trivial reviews, so we encourage anyone interested in this PR to vote for the corresponding issue.

Please note that you've skipped many steps in the checklist that will need to be addressed. In particular, this will need tests before moving forward.

**Comment by LongXiangGuo** [comment]
> Thanks for the submission! We’re currently working through a large backlog of PRs, and this will require non-trivial review (since we need to evaluate how we want to manage the settings API over time so that it doesn't become unmanageable), so it will take some time before we’re able to review it. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are the primary way we’re prioritizing non-trivial reviews, so we encourage anyone interested in this PR to vote for the corresponding issue.
> 
> Please note that you've skipped many steps in the checklist that will need to be addressed. In particular, this will need tests before moving forward.

Thanks, I will check it tem by item.

**Comment by stuartmorgan** [comment]
Could you file an issue describing the use case here? Neither of the links above explain why this setting is needed, only that it could be added. It's not clear why ignoring the user's text settings is a desirable feature. (And also why if we are exposing it, it should be as a bool and not a pass-through of the zoom setting.)

If we do go forward with this setting, this is probably blocked on https://github.com/flutter/flutter/issues/94051, since this seems like a strong case for a platform-specific extension rather than adding it to the base WebSettings.

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
