### PR TITLE
[shared_preferences] fix typo

### PR DESCRIPTION
**Pull request by HosamHasanRamadan**
Replaced `macOS` with `Android`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by tarrinneal** [comment]
Good catch on that typo. Make sure you sign the cla, as mentioned by the bot above. 

Also, the version change, and changelog can be fixed with a simple command mentioned here https://github.com/flutter/plugins/tree/main/script/tool#update-changelog-and-version

**Comment by stuartmorgan** [comment]
Thanks for the contribution! You haven’t checked off any of the items in the PR checklist above, so I’m assuming this is a work in progress and am marking it as a Draft. Please review the checklist, updating the PR as appropriate, and when that’s complete please feel free to mark the PR as ready for review.

**Comment by HosamHasanRamadan** [comment]
I updated the changelog.

**Comment by stuartmorgan** [comment]
@HosamHasanRamadan It looks like you used two different email addresses for the two commits, and have only signed the CLA for one of them. You'll need to either amend the commit or sign for the other address before we can review this.

**Comment by HosamHasanRamadan** [comment]
> @HosamHasanRamadan It looks like you used two different email addresses for the two commits, and have only signed the CLA for one of them. You'll need to either amend the commit or sign for the other address before we can review this.

Done.

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
Thanks! This will just need a version change, as explained in our contributing docs.

**Comment by HosamHasanRamadan** [comment]
> Thanks! This will just need a version change, as explained in our contributing docs.

Done

**Review by tarrinneal — APPROVED** [review]

**Review by stuartmorgan — APPROVED** [review]

**Pull request merged**
