### PR TITLE
Rebase previous commits

### PR DESCRIPTION
**Pull request by jiahaog**
https://github.com/flutter/plugins/commit/6eda8db6516ac89551450db9483ff88471f95779 accidentally removed some commits on head, so relanding them here:

- [battery] Fixed typo in README.md (#2944)
- [integration_test] Remove debugging statement (#2963)

### CODE REVIEW

**Comment by jiahaog** [comment]
Should I cherry pick these commits on top of master instead to preserve history? I think this repo is set up to only allow squash and merge

**Comment by dnfield** [comment]
This already landed right?  No we shouldn't rewrite history on this repo

**Comment by jiahaog** [comment]
No, this hasn't landed yet. I meant that either the two commits should be cherry picked onto master individually, or this PR should be merged (which squashes them together)

**Comment by dnfield** [comment]
Ahhhh this was my fault.  Argh.  Sorry about that

**Comment by jiahaog** [comment]
No worries :)

**Pull request merged**
