### PR TITLE
[video_player]- support HTTP headers #16466

### PR DESCRIPTION
**Pull request by JarvanMo**
## Description

Sometimes we need HTTP headers to authentication in real development world.
This PR allows developers adding header into *video_player* if constructing `VideoPlayerController`
from `network`.

## Related Issues

see [ flutter/flutter#16466](https://github.com/flutter/flutter/issues/16623)  

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by MichaelMarner** [comment]
Might want to fix your tab width so that your PR doesn't reformat the indentation of every line of code

**Comment by JarvanMo** [comment]
@MichaelMarner reformatted now.

**Comment by MichaelMarner** [comment]
Hey @JarvanMo - look I'm not on the Flutter team so feel free to ignore this.

The big issue with this PR is there have been so many unnecessary changes to files that are not part of the actual feature you've implemented. Most of them look like your code editor automatically reformatting things.

For example, https://github.com/flutter/plugins/pull/2074/files#diff-e534c460662d39cc715c4eed77a31c3fL34

Here your code editor has repositioned the `*` character in the variable declarations:

`@property(readonly, nonatomic) AVPlayer* player;` becomes
`@property(readonly, nonatomic) AVPlayer *player;`

And so on.

Likewise `packages/video_player/example/ios/Runner.xcodeproj/project.pbxproj` has been modified for no reason that I can see.

I think if you update this PR so that it only includes actual functionality changes for the feature you have implemented, it will be much easier to judge the scope of the change and more likely to be merged.

(Again, I'm not on the Flutter team, this is just my view)

**Comment by JarvanMo** [comment]
@MichaelMarner agree. Now this PR will be under review, if there is any problem, I'll re-PR. Thanks bro.

**Comment by JohnGalt1717** [comment]
Did this ever get fixed and merged?

**Comment by peter-weis** [comment]
Hello,
any idea WHEN this will be merged?

**Comment by TRUSTMEIMJEDI** [comment]
Are there any news about merging it to the master need this functionality for my engineer thesis ASAP ?

**Comment by jaysonasenjo** [comment]
It would be nice, if this feature is added. Even better, when the headers won't get transformed to lower case automatically. :)

**Comment by aylanexame** [comment]
What is the problem with this PR?
The feature is much needed.

**Comment by JohnGalt1717** [comment]
The problem is that this uses a hidden iOS api. It should be using the iOS functionality to create a playlist and intercept the http request and pass the token. As a result this could get your apps banned from the store AND this won't ever work if you want to have captions as an example on the video.

So this PR likely has to be redone to support it properly on iOS which means a complete rewrite of the iOS code to be able to start handling captions etc. as part of this. (And of course add all of the rest of this to the web platform etc.)

**Comment by murilosamuel** [comment]
Any update?

**Pull request closed without merging**
