### PR TITLE
[google_maps_flutter] enable/disable indoor view

### PR DESCRIPTION
**Pull request by miguelpruivo**
This commit will provide a property in the `GoogleMapOptions` to enable/disable the indoor view from it (`bool: indoorEnabled`). This, will also prevent app crashing with the current `google_maps_flutter` version (0.0.1) when zooming/scrolling, which at the moment represents a big issue, making the maps unusable.

### CODE REVIEW

**Comment by miguelpruivo** [comment]
Test again.

**Comment by amirh** [comment]
This is great, thanks! We would like to wait until we have maps implemented on both iOS and Android before actually further augmenting the API, because we are worried that they'll get out of sync otherwise. Would you be ok with resubmitting this with iOS support in a few weeks once we have the iOS work more fleshed out?

As for the crash, we should get it fixed nevertheless, even if the indoor view is enabled.

**Comment by miguelpruivo** [comment]
> This is great, thanks! We would like to wait until we have maps implemented on both iOS and Android before actually further augmenting the API, because we are worried that they'll get out of sync otherwise. Would you be ok with resubmitting this with iOS support in a few weeks once we have the iOS work more fleshed out?
> 
> As for the crash, we should get it fixed nevertheless, even if the indoor view is enabled.

That is fine by me. I've been using the `google_maps_plugin` for a while now on Android and needed this feature off, that's the reason why I PR it. Keep up the good work. 👍

**Comment by collinjackson** [comment]
Can you add iOS support?

**Comment by miguelpruivo** [comment]
@collinjackson done. Ready to merge.

**Comment by doc-rj** [comment]
This merge would be awesome. For whatever reason, the crash is extremely easy to reproduce in Flutter with the default GoogleMapOptions, just by alternating camera position between two positions a couple of times. Not sure what version of Play Services will fix it. Maybe another workaround would be to adjust min/max zoom levels?
https://github.com/flutter/flutter/issues?q=is%3Aissue+google_maps_flutter+java.lang.StackOverflowError+is%3Aclosed#issuecomment-429184244

**Comment by miguelpruivo** [comment]
Any news on this? It's been a while since support for both platforms were implemented.

**Comment by iskakaushik** [comment]
Hi @miguelpruivo , could you please resolve the conflicts and rebase?

**Comment by miguelpruivo** [comment]
Sure @iskakaushik. How fast do you need it?

**Comment by iskakaushik** [comment]
@miguelpruivo no rush, just tag me here when it’s ready.

**Comment by miguelpruivo** [comment]
@iskakaushik all done. Let me know if you need something else.

**Comment by iskakaushik** [comment]
Hi @miguelpruivo , There are a few pending things:

1. Can you please add an example for this feature.
2. Can you update the version in pubspec.yml and CHANGELOG.md
3. Can you also remove the `gradle-wrapper.properties` file that is committed.

Thanks!

**Comment by miguelpruivo** [comment]
@iskakaushik done. 👍

**Pull request merged**
