### PR TITLE
[flutter_google_maps] Upgrade google-services-maps v17.0.0 - AndroidX compatible

### PR DESCRIPTION
**Pull request by JamesMcIntosh**
## Description

This library says that it is AndroidX compatible but the Android google-services-maps dependencies have not been upgraded to an AndroidX compatible version

In the checklist below, I am unsure if you would class this as a breaking change and if the version bump is correct.

## Related Issues

For me it was causing an incompatibility with flutter image_picker
https://github.com/flutter/flutter/issues/27194

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [N/A] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by JamesMcIntosh** [comment]
Timeout issues with the builds above, don't think it's caused by my commit.

**Comment by kjeremy** [comment]
Any news on this?

**Comment by JamesMcIntosh** [comment]
@iskakaushik could you please able to give feedback to whether this PR is being reviewed/considered? Many thanks!

**Comment by iskakaushik** [comment]
Hi @JamesMcIntosh i'm worried about any breaking changes that happened between the two versions of the API. Are you aware of any?

**Comment by JamesMcIntosh** [comment]
@iskakaushik I am not aware of any API changes, it looks as though only the underlying Google Maps API other than Android Support Libraries are changed to AndroidX.
I have been running a fork and creating maps using Polygons, Markers, Location and manipulating the camera position etc. with no issue.

Even if you're worried about the Android Support to AndroidX change it is already causing a problem with it not being AndroidX when the plugin says that it should be and the other plugins in the repository having already migrated to AndroidX is causing an incompatibility. If you don't bump it up you're stuck at this release and can't get any of the bugfixes etc. in the Android Google Maps releases. If the Android API changes it shouldn't matter, Flutter Google Maps is in Developer Preview still and you'll need to fix the Android integration anyway as you can't stay on this version forever.

**Comment by JamesMcIntosh** [comment]
I've found the release notes, they're not overly helpful.
https://developers.google.com/maps/documentation/android-sdk/releases
https://developers.google.com/android/guides/releases

**Comment by kjeremy** [comment]
It's just a move to AndroidX. I think most of the other plugins have
already been migrated.

**Comment by iskakaushik** [comment]
I looked through the changes between the versions. Seems like a safe update. LGTM.

**Pull request merged**
