### PR TITLE
[camera_web] Rename `CameraSettings` to `CameraService`

### PR DESCRIPTION
**Pull request by bselwe**
Renames `CameraSettings` to `CameraService` as suggested in https://github.com/flutter/plugins/pull/4207#discussion_r680166147.

Part of https://github.com/flutter/flutter/issues/45297.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by bselwe** [comment]
@ditman @felangel

**Review by ditman — APPROVED** [review]
LGTM!

**Comment by ditman** [comment]
Ooops, this is conflicting with the previous one, I'll rebase.

**Comment by ditman** [comment]
I'm getting a bunch of these errors when attempting to run the flutter tests:

```
00:00 +0: ... /usr/local/google/home/dit/github/plugins/packages/camera/camera_web/test/types/camera_options_test.dart           lib/src/types/camera_error_code.dart:5:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
lib/src/types/zoom_level_capability.dart:5:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
```

At some point, our tests became "tainted" with `dart:html`, so they won't run in the VM 😢.

I'll convert them to integration_test and let @bselwe take a look before merging this branch :)

**Comment by ditman** [comment]
@googlebot I consent.

**Comment by ditman** [comment]
@bselwe please, take a look, a little bit of churn in the tests on this one!

**Comment by bselwe** [comment]
@ditman This looks good, thanks! I've tried to move some integration tests to `integration_test/types` directory but they failed when resolving `../helpers/helpers.dart` so let's leave it as it is now.

**Comment by ditman** [comment]
@bselwe yes, I think the only problem is importing dart:html somewhere in the files that are being exported from the barrel files. If we imported the helpers/types we needed exclusively, it's possible the split would work.

**Review by ditman — APPROVED** [review]
Let's go!

**Pull request merged**
