### PR TITLE
[camera]rename dispatchQueue to captureSessionQueue

### PR DESCRIPTION
**Pull request by hellohuanlin**
Rename the queue to be aligned with [the proposal](https://docs.google.com/document/d/1Znjp-BduXIb1Ix3JOE1YKyJi1Z0d6rB-2q6Lt7j8xSo/edit#). 

I am keeping this PR small and only scoped to renaming. 

Since it's just renaming, I think it's exempt from version bump and unit test

Issue: 
https://github.com/flutter/flutter/issues/96429

No version change: Because it's only renaming

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].*
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].*
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by jmagman** [comment]
> I think it's exempt from unit test

You're right, but you should still get a test exemption from @Hixie in Discord.

> If you need an exemption to this rule, contact Hixie on the #hackers channel in Chat.

@stuartmorgan we usually still do a CHANGELOG `NEXT` when the version isn't bumped?  Or do you not bother on little changes?

**Comment by stuartmorgan** [comment]
> @stuartmorgan we usually still do a CHANGELOG `NEXT` when the version isn't bumped? Or do you not bother on little changes?

I moved us to a policy of generally requiring a CHANGELOG change for everything—see the last sentence of https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog for my rationale—which is why `publishable` is strict about it. But it's kind of a trial; if it turns out to be annoying in practice we can easily relax the policy and change the tooling to only require it when the version changes.

**Comment by stuartmorgan** [comment]
In this case I would lean toward:

```
## NEXT

* Minor internal code cleanup.
```

or something like that. Mostly because if there were some subtle bug introduced by the rename that we didn't notice until the next `camera` release, it would make it easier for us to realize that there would be two PRs to go look at, rather than potentially being misled by the CHANGELOG and looking at only the last change.

**Comment by Hixie** [comment]
test-exempt: code refactor with no semantic change

**Comment by hellohuanlin** [comment]
@stuartmorgan updated the changelog. ptal thanks

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Review by jmagman — APPROVED** [review]
LGTM

**Pull request merged**
