### PR TITLE
[url_launcher_platform_interface] Add webOnlyWindowName parameter to launch()

### PR DESCRIPTION
**Pull request by balvinderz**
## Description

Adds webOnlyWindowName parameter to url_launcher_platform_interface

## Related Issues

https://github.com/flutter/flutter/issues/56867

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by balvinderz** [comment]
@ditman

**Comment by balvinderz** [comment]
tests passed @ditman . Can you merge this so i can add the second pr.

**Comment by ditman** [comment]
This has been merged, I'll publish it to pub.dev once tests pass in `master`.

**Comment by ditman** [comment]
Tagged and [published](https://pub.dev/packages/url_launcher_platform_interface/changelog#108) `url_launcher_platform_interface: ^1.0.8`

**Comment by balvinderz** [comment]
Thank you . This is the 2nd PR : https://github.com/flutter/plugins/pull/2979

**Comment by Bilonik** [comment]
Cant compile for web getting errors from this platform_interface.

Target dart2js failed: Exception: /root/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.2+1/lib/url_launcher_web.dart:60:16:
           Error: The method 'UrlLauncherPlugin.launch' has fewer named arguments than those of overridden method 'UrlLauncherPlatform.launch'.
             Future<bool> launch(
                          ^
           /root/.pub-cache/hosted/pub.dartlang.org/url_launcher_platform_interface-1.0.8/lib/url_launcher_platform_interface.dart:50:16:
           Info: This is the overridden method ('launch').
             Future<bool> launch(

**Comment by ditman** [comment]
@Bilonik you're correct, the fix is incoming: https://github.com/flutter/plugins/pull/2979

Apologies for the breakage! In the meantime, you may be able to dependency-overrides url_launcher_platform_interface to 1.0.7.

**Comment by Bilonik** [comment]
@ditman,  just reporting the breakage. 🤙

Thanks for the good work!!

**Comment by ditman** [comment]
The fix for the breakage has been merged to master. I'll publish url_launcher and url_launcher_web as soon as post-submit passes. (cc @Bilonik @4mitabh)

**Comment by ditman** [comment]
Both url_launcher and url_launcher_web have been published:
* https://pub.dev/packages/url_launcher/changelog#551
* https://pub.dev/packages/url_launcher_web/changelog#013

**Pull request merged**
