### PR TITLE
[WIP] [video_player] Add macOS support

### PR DESCRIPTION
**Pull request by cbenhagen**
## Description

Add macOS support. I tried to keep it as close as possible to the iOS implementation. If possible we should find a way to keep both implementations in one file to prevent them drifting apart.

TODO:
- [ ] Add tests
- [ ] Support loading assets (depends on https://github.com/flutter/flutter/issues/47681)
- [ ] Migrate to pigeon
- [ ] Share code between iOS and macOS (Like being done in the flutterfire plugins).

## Related Issues

Fixes https://github.com/flutter/flutter/issues/41688

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by cbenhagen** [comment]
@lesnitsky I kept this as close to the original implementation as possible. Feel free to rewrite in Swift as you implement DRM support.

**Comment by lesnitsky** [comment]
@cbenhagen `AVPlayerItemVideoOutput` is not a suitable option for DRM protected video on macos (always returns nil). I didn't have a chance to test it on ios, since I was implementing platform view right away (another limitation of videoComposition which is not allowed for HLS)
As far as I understand DRM video working on macOS is only possible with platform views as well (but desktop engine doesn't support platform views yet)

**Comment by cbenhagen** [comment]
@lesnitsky Right, so I guess I will try to land this first as it allows video playback on macOS today. We can then improve all platforms for DRM support later.

**Comment by lesnitsky** [comment]
sounds good

**Comment by vladyslav2** [comment]
@cbenhagen any progress? I'll be happy to help with tests if needed

**Comment by cbenhagen** [comment]
Hi @vladyslav2, sorry for the delay. It would be awesome if you could contribute the tests! I will try to share the code between iOS and macOS.

**Comment by vladyslav2** [comment]
@cbenhagen please tag me the code is ready

**Comment by cbenhagen** [comment]
@vladyslav2 Tried to give you access to this PR's branch but failed. You could create a PR on my fork against this branch.

**Comment by vladyslav2** [comment]
@cbenhagen Ben, just to be clear:
- I'll take your branch
- Will do some tests on the macOS
- Will report any issues I found
- In the best case scenario - I can help with a code but I'm not an expert in the video and I'm not sure where should I start

**Comment by cbenhagen** [comment]
Oh sorry, what I understood is that you have written macOS integration tests (XCTest). Manual testing is of course also useful but without XCTest we will not be able to merge this.

**Comment by vladyslav2** [comment]
@cbenhagen no problem. I'll take a look at `XCTest` if I'll be able to use it in my project I'll try to contribute to your PR too

**Comment by AndroidNils** [comment]
Any updates?

**Comment by stuartmorgan** [comment]
Since this has been marked WIP for nearly a year without activity, I'm going to close it. If you're planning on working on it again at some point, it can be re-opened.

**Pull request closed without merging**
