### PR TITLE
[video_player] Implement caching

### PR DESCRIPTION
**Pull request by 999eagle**
## Description

This PR adds a way to cache videos played from an Uri. Two new parameters (`maxCacheSize` and `maxFileSize`) have been added to the platform method call and the Dart side has been changed to pass these parameters as well.

## Related Issues

Resolves flutter/flutter#28094.

## Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by 999eagle** [comment]
@lukepighetti can you sign the google cla please to be able to merge this?

**Comment by lukepighetti** [comment]
I believe I have signed it in the past

**Comment by lukepighetti** [comment]
@googlebot I consent.

**Comment by lukepighetti** [comment]
@999eagle did you end up getting eyes on the uri stuff on iOS to make sure it was setup appropriately? I kept having issues with certain URLs but I never was able to determine if that was a local issue or not.

**Comment by otopba** [comment]
@999eagle Thank you for your solution. Could you update this branch due master updates please?

**Comment by cbenhagen** [comment]
@999eagle thank you for your contribution! Unfortunately the structure of the plugin has changed lately to support implementations on more platforms. Mainly the plugin was moved to a new subdirectory and now uses a common platform interface. Adapting your PR to the new structure should be straight forward. If you have questions please ask!

Please also make sure to include tests for the new functionality.

**Comment by sanekyy** [comment]
Hello. 
We created [new PR](https://github.com/flutter/plugins/pull/2429) which fix this PR to speed up the process of merging of this feature

**Comment by sanekyy** [comment]
@999eagle Hello.

Can you confirm CLA in [new PR](https://github.com/flutter/plugins/pull/2429)?

**Comment by jimmywongz** [comment]
Hi Would like to ask when would this be merged? really want to have this feature

**Comment by lukepighetti** [comment]
What's blocking this from being merged?

**Comment by lukepighetti** [comment]
It appears this PR should be closed for being stale, and the tracking PR for this feature is located here: https://github.com/flutter/plugins/pull/2429#issuecomment-642653144

**Comment by ditman** [comment]
Closing in favor of #2429

**Pull request closed without merging**
