### PR TITLE
[webview_flutter] fix not working choose file

### PR DESCRIPTION
**Pull request by crazecoder**
## Description
fix webview_flutter not working choose file
Only applicable to android5.0 or above

## Related Issues

https://github.com/flutter/flutter/issues/27924

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by crazecoder** [comment]
@googlebot  I signed it!

**Comment by mantou132** [comment]
I hope to merge soon.

**Comment by NorbertSzydlowski** [comment]
Hello,
I have been select this fix. It is will crash when second time go to webview and select file.

```
E/AndroidRuntime(31232): FATAL EXCEPTION: main
E/AndroidRuntime(31232): Process: pl.cormo.ocenapolis, PID: 31232
E/AndroidRuntime(31232): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=18, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:13549 flg=0x1 }} to activity {pl.cormo.ocenapolis/pl.cormo.ocenapolis.MainActivity}: java.lang.IllegalStateException: showFileChooser result was already called
E/AndroidRuntime(31232): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4423)
E/AndroidRuntime(31232): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4465)
E/AndroidRuntime(31232): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(31232): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(31232): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(31232): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
E/AndroidRuntime(31232): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31232): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(31232): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(31232): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31232): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(31232): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AndroidRuntime(31232): Caused by: java.lang.IllegalStateException: showFileChooser result was already called
E/AndroidRuntime(31232): 	at in.onReceiveValue(PG:8)
E/AndroidRuntime(31232): 	at io.flutter.plugins.webviewflutter.FlutterWebViewChromeClient.onActivityResult(FlutterWebViewChromeClient.java:204)
E/AndroidRuntime(31232): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime(31232): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime(31232): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(31232): 	at android.app.Activity.dispatchActivityResult(Activity.java:7590)
E/AndroidRuntime(31232): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4416)
```

**Comment by crazecoder** [comment]
@NorbertSzydlowski This is a known problem and you go to the first filePathCallback every time, I think it has something to do with the mechanism of flutter, you can set up the public static filePathCallback in the WebViewFlutterPlugin to solve it, but I don't think it's an elegant solution

**Comment by NorbertSzydlowski** [comment]
@crazecoder Second problem is selected multiple files. 

`intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE, allowMultiple);`

It isn't correct get URI from Intent.
`WebChromeClient.FileChooserParams.parseResult(resultCode, data)`

I have been used this method (from flutter_webview_plugin):

```
private Uri[] getSelectedFiles(Intent data) {

        if (data == null) {
            return null;
        }

        if (data.getData() != null) {
            String dataString = data.getDataString();
            if (dataString != null) {
                return new Uri[]{Uri.parse(dataString)};
            }
        }

        if (data.getClipData() != null) {
            final int numSelectedFiles = data.getClipData().getItemCount();
            Uri[] result = new Uri[numSelectedFiles];
            for (int i = 0; i < numSelectedFiles; i++) {
                result[i] = data.getClipData().getItemAt(i).getUri();
            }
            return result;
        }

        return null;
    }
```

**Comment by fyeeme** [comment]
@NorbertSzydlowski @crazecoder  how to use this PR before it's merged?

**Comment by NorbertSzydlowski** [comment]
@fyeeme select PR as dependency
https://dart.dev/tools/pub/dependencies

**Comment by ismanong** [comment]
希望修复

**Comment by cazeredodev** [comment]
Is there any chance that the fix will be delivered in the next few days?

**Comment by sysmesh** [comment]
Any progress? This issue is a REAL pain.

**Comment by deandreamatias** [comment]
Please stop commenting on problems

> any update on this
The best option is to add this emoji :+1: in the initial comment.

To see a priority of each issue, we can see in which Milestone the issue is added. This issue belongs
to milestone Goals, with this description:

> P2: These are tasks we think are worth fixing in the coming years. It includes issues we've identified that might block fully shipping broad consumer-facing apps, correctness issues, and bugs relating to polish and quality. The date on this milestone is utterly arbitrary and just intended to sort the milestone appropriately.

**Comment by stuartmorgan** [comment]
We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

> * [ ]  My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md)).

Per Flutter policy, this will need tests before it can move forward; I believe that means it is blocked on the `webview_flutter` portion of https://github.com/flutter/flutter/issues/83358 since this would show native UI. We can revisit once that scaffolding is in place (and if anyone is interested in moving this forward, a PR to do that would gladly be accepted to accelerate the process).

Also, could you could elaborate on [the discussion above](https://github.com/flutter/plugins/pull/2245#issuecomment-557012009)? If this crashes when used more than once, then it doesn't sound like it's ready for review. Is there a blocking issue preventing fixing that crash?

**Comment by stuartmorgan** [comment]
Since this hasn't received any updated based on the comment above, and since the Android implementation of the plugin has been very substantially changed since this PR was created, I'm going to close it as obsolete. If this is still something you are interested in implementing, please feel free to open a new PR! (Or, preferably, collaborate on https://github.com/flutter/plugins/pull/3225)

**Pull request closed without merging**
