### PR TITLE
[webview_flutter] Migrate to null-safety

### PR DESCRIPTION
**Pull request by mehmetf**
## Description

Migrating webview-flutter to null-safety.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- []  No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by amirh — CHANGES_REQUESTED** [review]
Looks like some tests are failing and we have analysis errors

**Comment by mehmetf** [comment]
I have no idea why. I am possibly setting the dependency versions wrong. Could you (or someone else) help check?

**Comment by amirh** [comment]
The analysis `unnecessary_null_comparison` warnings seems legit.

The Gradle build errors on master channel are a framework regression, @blasten is handling that in https://github.com/flutter/flutter/pull/71964.

The stable channel errors are because the plugin cannot work on stable after this change, as this is the first plugin we migrate on flutter/plugins master that's the first time we need to solve this. The easy fix would be to disable stable channel checks for the entire repository though I'm a little hesitant to do that, I'd prefer to only skip it for pre-release version that can't resolve on stable though I may be over-naive in how simple it is to do that. @blasten any thoughts on that? I can take a look at the CI change.

Side note - I basically have zero non-meeting time today so I only expect to get to it tomorrow.

**Comment by mehmetf** [comment]
Analysis errors are expected. They are coming from asserts. Is that lint turned off for package:flutter ?

**Comment by amirh** [comment]
Is the practice to keep `assert(foo != null)` for non nullable `foo`?

**Comment by mehmetf** [comment]
Yeah. That's what package:flutter has been following since these asserts have value for mixed mode code.

**Comment by amirh** [comment]
AFAICT `unnecessary_null_comparison` is not turned off in flutter/flutter (I'm not an expert of the analysis rules configuration for flutter/flutter though I believe https://github.com/flutter/flutter/blob/master/analysis_options.yaml is the source of truth)

**Comment by mehmetf** [comment]
Weird. How is code like: 

https://github.com/flutter/flutter/blob/f55117840818eae1b3972a6abe9d2784fc8fb9b4/packages/flutter/lib/src/material/color_scheme.dart#L21-L47

passing analysis checks?

**Comment by amirh** [comment]
> AFAICT `unnecessary_null_comparison` is not turned off in flutter/flutter (I'm not an expert of the analysis rules configuration for flutter/flutter though I believe https://github.com/flutter/flutter/blob/master/analysis_options.yaml is the source of truth)

In fact that was not true, it's turned off here: https://github.com/flutter/flutter/blob/52ea6c2a318537eb4d2ab260143bccaf6ec2151a/packages/flutter/analysis_options.yaml#L8

I guess we should do the same then.

**Comment by mehmetf** [comment]
Cool.

**Comment by blasten** [comment]
@mehmetf https://github.com/flutter/plugins/pull/3318 should help get the checks green on stable as it skips this plugin.

**Comment by mehmetf** [comment]
I am going to close this PR and open a new one.

**Pull request closed without merging**
