### PR TITLE
[ci] Switch to macOS VM with Flutter pre-installed

### PR DESCRIPTION
**Pull request by fkorotkov**

### CODE REVIEW

**Comment by amirh** [comment]
@fkorotkov  I'm missing context here - do we still need this?

**Comment by fkorotkov** [comment]
@amirh totally forgot about the PR. Such change can help to reduce the 9 minute `setup` script. I can rebase the PR to see how much faster it is now. 🤔

**Comment by amirh** [comment]
sounds good, thanks!

**Comment by fkorotkov** [comment]
@amirh rebased and it strips of 3+ minutes from the macOS shard build making it almost 2X faster. 🙌

**Comment by amirh** [comment]
Great ! 🎉 
Good to merge?

**Comment by fkorotkov** [comment]
@amirh yes! 🎉

**Pull request merged**
