### PR TITLE
[google_sign_in] Fix Server Authorization code on android

### PR DESCRIPTION
**Pull request by zeeshanhussain**
## Description

The serverAuthCode on an android device was coming null. This pull request resolves that issue.

## Related Issues

flutter/flutter#57712
flutter/flutter#57741

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by zeeshanhussain** [comment]
@googlebot I signed it!

**Comment by abhishek-bm-ai** [comment]
I need this fix to get the `serverAuthCode` such that I can get a refresh token at the backend side to use google API.
Why when we can expect this to be merged?

**Comment by abhishek199-dhn** [comment]
I need this fix to get the serverAuthCode such that I can get a refresh token at the backend side to use google API.
Why when we can expect this to be merged?

**Comment by abhishek-bm-ai** [comment]
@zeeshanhussain I tried running cloning your branch and gave it a shot. But it's not working for me. 


```
dependencies:
  google_sign_in:
    path: ../plugins/packages/google_sign_in/google_sign_in
```
```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
../plugins/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart:48:32: Error: The getter 'serverAuthCode' isn't defined for the class 'GoogleSignInUserData'.
 - 'GoogleSignInUserData' is from 'package:google_sign_in_platform_interface/src/types.dart' ('../../../../lib/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_platform_interface-1.1.2/lib/src/types.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'serverAuthCode'.
        _serverAuthCode = data.serverAuthCode {
                               ^^^^^^^^^^^^^^

Compiler message:
../plugins/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart:48:32: Error: The getter 'serverAuthCode' isn't defined for the class 'GoogleSignInUserData'.
 - 'GoogleSignInUserData' is from 'package:google_sign_in_platform_interface/src/types.dart' ('../../../../lib/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_platform_interface-1.1.2/lib/src/types.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'serverAuthCode'.
        _serverAuthCode = data.serverAuthCode {
                               ^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

```


I can see the same exact error message in some git checks

**Comment by abhishek199-dhn** [comment]
@zeeshanhussain I tried running cloning your branch and gave it a shot. But it's not working for me. 


```
dependencies:
  google_sign_in:
    path: ../plugins/packages/google_sign_in/google_sign_in
```
```
Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...

Compiler message:
../plugins/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart:48:32: Error: The getter 'serverAuthCode' isn't defined for the class 'GoogleSignInUserData'.
 - 'GoogleSignInUserData' is from 'package:google_sign_in_platform_interface/src/types.dart' ('../../../../lib/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_platform_interface-1.1.2/lib/src/types.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'serverAuthCode'.
        _serverAuthCode = data.serverAuthCode {
                               ^^^^^^^^^^^^^^

Compiler message:
../plugins/packages/google_sign_in/google_sign_in/lib/google_sign_in.dart:48:32: Error: The getter 'serverAuthCode' isn't defined for the class 'GoogleSignInUserData'.
 - 'GoogleSignInUserData' is from 'package:google_sign_in_platform_interface/src/types.dart' ('../../../../lib/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in_platform_interface-1.1.2/lib/src/types.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'serverAuthCode'.
        _serverAuthCode = data.serverAuthCode {
                               ^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

```


I can see the same exact error message in some git checks

**Comment by zeeshanhussain** [comment]
There are some changes in google_sign_in_platform_interface as well so you have to clone that locally as well and that's why it was failing few checks.

**Comment by abhishek199-dhn** [comment]
@zeeshanhussain which changes you are referring too? can you please give me the link of the PR?

**Comment by zeeshanhussain** [comment]
@abhishek199-dhn it's in the same pr, this pr has changes in both google_sign_in and google_sign_in_platform_interface. I should probably split it into 2 pr after getting this reviewed.

**Comment by abhishek199-dhn** [comment]
Thanks @zeeshanhussain, it woking now. I pointed both the dependencies `google_sign_in_platform_interface` and `google_sign_in_web` of `google_sign_in` to local package.

**Comment by scaraux** [comment]
> Thanks @zeeshanhussain, it woking now. I pointed both the dependencies `google_sign_in_platform_interface` and `google_sign_in_web` of `google_sign_in` to local package.

Can you show us how you defined this in your `pubspec.yaml` ?

**Comment by scaraux** [comment]
@zeeshanhussain I pulled your branch and pointed `google_sign_in_platform_interface` as well. Still getting `null` as server code. Any idea ?

**Comment by zeeshanhussain** [comment]
> > Thanks @zeeshanhussain, it woking now. I pointed both the dependencies `google_sign_in_platform_interface` and `google_sign_in_web` of `google_sign_in` to local package.
> 
> Can you show us how you defined this in your `pubspec.yaml`?

you can copy all the 3 packages in your project folder which includes [google_sign_in], [google_sign_in_platform_interface] , [google_sign_in_web].

In your project's pubspec.yaml you can add the [google_sign_in] dependency. 
```yaml 
  google_sign_in:
    path: ./google_sign_in
```
In google_sign_in/pubspec.yaml you can add both [google_sign_in_web] and [google_sign_in_platform_interface].
```yaml
  google_sign_in_platform_interface:
    path: ../google_sign_in_platform_interface/
  google_sign_in_web:
    path: ../google_sign_in_web
```

in google_sign_in_web/pubspec.yaml you can add [google_sign_in_platform_interface]
```yaml
  google_sign_in_platform_interface:
    path: ../google_sign_in_platform_interface/
```

**Comment by zeeshanhussain** [comment]
> @zeeshanhussain I pulled your branch and pointed `google_sign_in_platform_interface` as well. Still getting `null` as server code. Any idea ?

go to firebase/authentication/sign in methods/google 
in google sign in go to the web client and update client id and client secret. Download the updated google-services.json file and you are good to go.

**Comment by scaraux** [comment]
> > @zeeshanhussain I pulled your branch and pointed `google_sign_in_platform_interface` as well. Still getting `null` as server code. Any idea ?
> 
> @scaraux go to firebase/authentication/sign in methods/google
> in google sign in go to the web client and update client id and client secret. Download the updated google-services.json file and you are good to go.

Yes I created a new clientId this morning, added it to the whitelist clientIds sections and downloaded the google-services.json. Still no server auth code though :/

**Comment by zeeshanhussain** [comment]
> > > @zeeshanhussain I pulled your branch and pointed `google_sign_in_platform_interface` as well. Still getting `null` as server code. Any idea ?
> > 
> > 
> > @scaraux go to firebase/authentication/sign in methods/google
> > in google sign in go to the web client and update client id and client secret. Download the updated google-services.json file and you are good to go.
> 
> Yes I created a new clientId this morning, added it to the whitelist clientIds sections and downloaded the google-services.json. Still no server auth code though :/

@scaraux you have to add web client id and web client secret in Web SDK configuration, then use the updated google-services.json

**Comment by scaraux** [comment]
> > > > @zeeshanhussain I pulled your branch and pointed `google_sign_in_platform_interface` as well. Still getting `null` as server code. Any idea ?
> > > 
> > > 
> > > @scaraux go to firebase/authentication/sign in methods/google
> > > in google sign in go to the web client and update client id and client secret. Download the updated google-services.json file and you are good to go.
> > 
> > 
> > Yes I created a new clientId this morning, added it to the whitelist clientIds sections and downloaded the google-services.json. Still no server auth code though :/
> 
> @scaraux you have to add web client id and web client secret in Web SDK configuration, then use the updated google-services.json.
> I think the process of adding client id in firebase needs to be documented somewhere.

I can give it a try, I know how to access my "OAuth 2.0 Client IDs" from the https://console.developers.google.com/. But which clientId should I copy ?

**Comment by zeeshanhussain** [comment]
> > > > > @zeeshanhussain I pulled your branch and pointed `google_sign_in_platform_interface` as well. Still getting `null` as server code. Any idea ?
> > > > 
> > > > 
> > > > @scaraux go to firebase/authentication/sign in methods/google
> > > > in google sign in go to the web client and update client id and client secret. Download the updated google-services.json file and you are good to go.
> > > 
> > > 
> > > Yes I created a new clientId this morning, added it to the whitelist clientIds sections and downloaded the google-services.json. Still no server auth code though :/
> > 
> > 
> > @scaraux you have to add web client id and web client secret in Web SDK configuration, then use the updated google-services.json.
> > I think the process of adding client id in firebase needs to be documented somewhere.
> 
> I can give it a try, I know how to access my "OAuth 2.0 Client IDs" from the https://console.developers.google.com/. But which clientId should I copy ?

You should use the one which you want to use in your application. Give it a try and it will definitely work.

**Comment by scaraux** [comment]
> > > > > > @zeeshanhussain I pulled your branch and pointed `google_sign_in_platform_interface` as well. Still getting `null` as server code. Any idea ?
> > > > > 
> > > > > 
> > > > > @scaraux go to firebase/authentication/sign in methods/google
> > > > > in google sign in go to the web client and update client id and client secret. Download the updated google-services.json file and you are good to go.
> > > > 
> > > > 
> > > > Yes I created a new clientId this morning, added it to the whitelist clientIds sections and downloaded the google-services.json. Still no server auth code though :/
> > > 
> > > 
> > > @scaraux you have to add web client id and web client secret in Web SDK configuration, then use the updated google-services.json.
> > > I think the process of adding client id in firebase needs to be documented somewhere.
> > 
> > 
> > I can give it a try, I know how to access my "OAuth 2.0 Client IDs" from the https://console.developers.google.com/. But which clientId should I copy ?
> 
> You should use the one which you want to use in your application. Give it a try and it will definitely work.

It worked, thank you so much. Google seriously need to make an effort on the docs.

**Comment by scaraux** [comment]
> > > > > > @zeeshanhussain I pulled your branch and pointed `google_sign_in_platform_interface` as well. Still getting `null` as server code. Any idea ?
> > > > > 
> > > > > 
> > > > > @scaraux go to firebase/authentication/sign in methods/google
> > > > > in google sign in go to the web client and update client id and client secret. Download the updated google-services.json file and you are good to go.
> > > > 
> > > > 
> > > > Yes I created a new clientId this morning, added it to the whitelist clientIds sections and downloaded the google-services.json. Still no server auth code though :/
> > > 
> > > 
> > > @scaraux you have to add web client id and web client secret in Web SDK configuration, then use the updated google-services.json.
> > > I think the process of adding client id in firebase needs to be documented somewhere.
> > 
> > 
> > I can give it a try, I know how to access my "OAuth 2.0 Client IDs" from the https://console.developers.google.com/. But which clientId should I copy ?
> 
> You should use the one which you want to use in your application. Give it a try and it will definitely work.

It half worked, I am not able to pull the idToken, but my serverAuthCode is still null

**Comment by scaraux** [comment]
> > > > > > @zeeshanhussain I pulled your branch and pointed `google_sign_in_platform_interface` as well. Still getting `null` as server code. Any idea ?
> > > > > 
> > > > > 
> > > > > @scaraux go to firebase/authentication/sign in methods/google
> > > > > in google sign in go to the web client and update client id and client secret. Download the updated google-services.json file and you are good to go.
> > > > 
> > > > 
> > > > Yes I created a new clientId this morning, added it to the whitelist clientIds sections and downloaded the google-services.json. Still no server auth code though :/
> > > 
> > > 
> > > @scaraux you have to add web client id and web client secret in Web SDK configuration, then use the updated google-services.json.
> > > I think the process of adding client id in firebase needs to be documented somewhere.
> > 
> > 
> > I can give it a try, I know how to access my "OAuth 2.0 Client IDs" from the https://console.developers.google.com/. But which clientId should I copy ?
> 
> You should use the one which you want to use in your application. Give it a try and it will definitely work.

All good now, thank you so much.

**Comment by scaraux** [comment]
@zeeshanhussain any idea when this will be merged ?

**Comment by zeeshanhussain** [comment]
> @zeeshanhussain any idea when this will be merged ?

No idea, it has to be reviewed first. you can tag one of the developers for a faster response.

**Comment by scaraux** [comment]
> > @zeeshanhussain any idea when this will be merged ?
> 
> No idea, it has to be reviewed first. you can tag one of the developers for a faster response.

I have no idea who I can tag 😟 
We need your PR merged for production, let me know if there's anything I can do

**Comment by HaitianZhuu** [comment]
For anyone look into this issue and this PR:
1. Download this branch and move `google_sign_in`, `google_sign_in_platform_interface` and `google_sign_in_web` under your project.
2. [Edit the local dependency as author said](https://github.com/flutter/plugins/pull/2792#issuecomment-645024842)
3. If the `serverAuthCode` is still null, you need to know your client id. Refer to this [discussion](https://github.com/flutter/flutter/issues/12140),
you can whether download `google-services.json`, edit root gradle and app gradle.(I didnt try this way, but I think it will work).
I just add
`    <string name="default_web_client_id">YOUR_WEB_CLIENT_ID</string>
`
in android/app/../Strings.xml. Then it works.

**Review by minhthienkt — APPROVED** [review]

**Comment by stuartmorgan** [comment]
Thanks for the submission! We’re currently working through a large backlog of PRs, and this will require non-trivial review, so it will take some time before we’re able to review it. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are the primary way we’re prioritizing non-trivial reviews, so we encourage anyone interested in this PR to vote for the corresponding issue.

**Comment by stuartmorgan** [comment]
Note that per Flutter policy, this will need tests before it can move forward. (You've checked the box indicating that you've added tests, but I'm not seeing them; if you did write tests already please ensure that part of the PR is pushed.)

**Comment by zeeshanhussain** [comment]
@stuartmorgan the previous pr added few tests. httpss://github.com/flutter/plugins/commit/88e85c6a48063cfab9111689179e2582a99b77ff

Let me know if you need more tests.

**Comment by stuartmorgan** [comment]
> @stuartmorgan the previous pr added few tests. [88e85c6](https://github.com/flutter/plugins/commit/88e85c6a48063cfab9111689179e2582a99b77ff)
> 
> Let me know if you need more tests.

The tests in that PR are passing, so clearly aren't testing the issue that this PR is intended to address.

**Comment by saahilmehra** [comment]
@zeeshanhussain  Any update on this? I used the workaround to use local copy of this branch but these 3 packages have not been migrated to null safety. Any idea when this branch will be migrated to null safety or when this issue will be fixed?

**Comment by stuartmorgan** [comment]
Closing as obsoleted by https://github.com/flutter/plugins/pull/4180. Thanks again for the submission!

**Comment by jainkrati** [comment]
Thanks for the fix. Somehow I am still getting null serverAuthCode. Is this change already pushed in latest published package for google_sign_in? 

Also, are you aware of any ongoing or past fix for ios for this scenario? I am integrating google sign in for my app and need both these fixes. Will appreciate any help :)

cc @zeeshanhussain  @stuartmorgan

**Comment by saahilmehra** [comment]
@jainkrati I am also facing the issue of null serverAuthCode for ios. For android, it is working fine. @zeeshanhussain @stuartmorgan Please suggest some fixes.

**Comment by stuartmorgan** [comment]
Please report issues via the issue tracker; PRs are not an issue tracking system.

**Pull request closed without merging**
