### PR TITLE
Timestamps firestore

### PR DESCRIPTION
**Pull request by DennisAlund**
This PR is adding complete support for all Firestore settings. The need originated from the upcoming change of snapshot timestamps that are announced if `timestampsInSnapshotsEnabled` isn't set to `timestampsInSnapshotsEnabled: true`

```
W/Firestore( 9705): (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
W/Firestore( 9705): To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
W/Firestore( 9705): 
W/Firestore( 9705): FirebaseFirestore firestore = FirebaseFirestore.getInstance();
W/Firestore( 9705): FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
W/Firestore( 9705):     .setTimestampsInSnapshotsEnabled(true)
W/Firestore( 9705):     .build();
W/Firestore( 9705): firestore.setFirestoreSettings(settings);
W/Firestore( 9705): 
W/Firestore( 9705): With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
W/Firestore( 9705): 
W/Firestore( 9705): // Old:
W/Firestore( 9705): java.util.Date date = snapshot.getDate("created_at");
W/Firestore( 9705): // New:
W/Firestore( 9705): Timestamp timestamp = snapshot.getTimestamp("created_at");
W/Firestore( 9705): java.util.Date date = timestamp.toDate();
W/Firestore( 9705): 
W/Firestore( 9705): Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
```

The previous function `enablePersistence` that was exposed from the Firestore settings has been left in the SDK to avoid breaking change.

### CODE REVIEW

**Comment by DennisAlund** [comment]
@pulyaevskiy: done

@filleduchaos: I'd be happy to get some help on that

**Comment by DennisAlund** [comment]
@filleduchaos I've merged your branch and I think it's your CLA pending

**Comment by filleduchaos** [comment]
I've accepted the CLA before (on https://github.com/flutter/flutter/pull/16861) - do you have to do that on a per repo basis?

**Comment by DennisAlund** [comment]
Hm, don't know actually. The cla doesn't specify which project. Only GitHub user.

**Comment by pulyaevskiy** [comment]
I just discovered that at least on iOS current codec looses millisecond precision in timestamps and my query which uses `isGreaterThan` behaves incorrectly.

Would be great to get this merged asap. Thanks for working on this @DennisAlund and @filleduchaos .

**Comment by filleduchaos** [comment]
I think a maintainer will have to manually change the label?

@pulyaevskiy You're welcome! :D

**Comment by DennisAlund** [comment]
@pulyaevskiy I've fixed merge conflict and the feedback from build step that seems to have been added in https://github.com/flutter/plugins/commit/1aef7d92e9e77e929ad767320e3f96cbb26efacc. 

But the PR is still hanging on the CLA. Mine is already signed. Is there any input needed from me or @filleduchaos?

**Comment by pulyaevskiy** [comment]
@DennisAlund This question would probably be better to ask someone from the Flutter team. @kroikie seems like have been handling all Firebase PRs recently.

**Comment by filleduchaos** [comment]
@kroikie Would it be possible for you to manually verify author consent? @DennisAlund and I are the only authors and we both have signed the CLA.

**Comment by Akenaide** [comment]
Hello,

Can you explain how we should enable persistence with those changes ?

**Comment by DennisAlund** [comment]
> Can you explain how we should enable persistence with those changes ?

It should auto-complete for you. But you can see [a similar example](https://github.com/flutter/plugins/blob/master/packages/cloud_firestore/example/lib/main.dart#L22) using `timestampsInSnapshotsEnabled` configuration. Just declare the setting that you want to apply.

```dart
final Firestore firestore = Firestore(app: app);
firestore.settings(persistenceEnabled: true);
```

**Pull request merged**
