### PR TITLE
badges for pub.dev scores

### PR DESCRIPTION
**Pull request by bruno-garcia**
## Description

Overview of plugins scores on pub.dev.

## Related Issues

First try was #2954 which was closed until https://github.com/bruno-garcia/badges.bar/issues/2 got resolved.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by ditman** [comment]
Wow, this is so much fun! These badges look great!

IMO, I'd just leave the "pub score" badge to not clutter the table too much, and leave space for other columns (to list the available platforms per plugin, for example, similar to [this one](https://firebase.flutter.dev)).

However I'm not a designer/product person, so don't consider this as an official review 😛 

Thanks for the contribution!

**Comment by mit-mit** [comment]
LGTM from a Dart / pub.dev PoV.

**Comment by mit-mit** [comment]
We need to take this PR and deploy the fix before we take the present PR: https://github.com/bruno-garcia/badges.bar/pull/7

**Comment by bruno-garcia** [comment]
I've publish a new version (v0.1.1) to pub.dev and also rolled out live.
For packages loaded in the last hour will be returning the cached (wrong) badges.

I tested with this package to confirm the right values:
https://badges.bar/flutter_bloc/popularity
https://badges.bar/flutter_bloc/pub%20points

**Comment by bruno-garcia** [comment]
I'll wait for cache to expire before merging this.
Thanks for catching and fixing that bug @mit-mit !

**Comment by mit-mit** [comment]
@csells any thoughts on whether we should show all three scores (as the PR [currently does](https://github.com/flutter/plugins/blob/ba44a22ed1c9886d1591765dab62d1bcea8b5cf9/README.md)), or just one or two of them as mentioned in https://github.com/flutter/plugins/pull/3026#issuecomment-693728364 ? I personally think it looks OK with all three.

**Comment by csells** [comment]
I don't have a strong opinion either way

**Review by mit-mit — APPROVED** [review]

**Comment by bruno-garcia** [comment]
Thanks for approving this.
🎉 merged! Cached did clear yes, it's set for only 1 hour.

Looks awesome.

**Pull request merged**
