### PR TITLE
[integration_test] Added details to setup the iOS application

### PR DESCRIPTION
**Pull request by letsar**
Improved the README by adding details for the iOS section.

This PR aims to fix https://github.com/flutter/flutter/issues/48600

I didn't updated the pubspec.yaml because it's only documentation, but I can do if necessary.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by dnfield — COMMENTED** [review]
This LGTM, but the real home of this is now in the Flutter SDK - can you open this PR there?

under packages/integration_test/README.md

**Comment by letsar** [comment]
Oh I didn't know, I will make it right away!

**Comment by neiljaywarner** [comment]
@letsar  @dnfield  DId this get missed? this is still super confusing afaict
on https://flutter.dev/docs/testing/integration-tests and https://pub.dev/packages/integration_test#ios-device-testing which is linked from there - i.e. the official path.
https://github.com/flutter/flutter/tree/master/packages/integration_test at least looks better from the surface but you can't easily find that from pub.dev or flutter.dev

**Comment by dnfield** [comment]
@johnpryan Was working on the documentation for that. 

Unfortunately, it might be waiting until the SDK vended version hits stable. It did not make the last stable push but will make the next one.

**Comment by neiljaywarner** [comment]
@dnfield  thanks for the reply.  Should i be using the sdk vended one today a) if i'm on stable channel b) if i'm on beta channel?  thanks

**Comment by dnfield** [comment]
The SDK vended version is not available on stable yet, but is available on beta.

If you are on beta, you should use it. On stable you don't have a choice.

**Comment by neiljaywarner** [comment]
also.. @dnfield  i'm still kinda lost even using https://github.com/flutter/flutter/tree/master/packages/integration_test#ios-device-testing
a)
it says to run product->tests . my  xcode version (12.4) has product->test, product -> buildfor-test and product->test plan

yes, it would be nice to see the tests run in my simulator..
b) should it be generating an ipa? or what are the two test artifacts? unfortunately I'm using AWS device farm and it wants an ipa first. the instructions dont' mention an ipa and i don't find one yet.

**Comment by dnfield** [comment]
I believe @johnpryan has a better handle on where the documentation for this is.

**Comment by johnpryan** [comment]
In order to add the instructions to flutter.dev we need to validate the instructions from the README and make any improvements along the way. We can use https://github.com/flutter/website/issues/5645 to track.

@neiljaywarner thanks for the feedback

**Comment by neiljaywarner** [comment]
> The SDK vended version is not available on stable yet, but is available on beta.
> 
> If you are on beta, you should use it. On stable you don't have a choice.

@dnfield  I switched to beta for this reason and others - eg newer versions of build_runner, build, lots of dependency resolution issues, flutter_driver conflicting with crypto, etc

can you please give me any thoughts on a conservative ETA that today's beta or newer will match stable, especially since today's integration_test on pub.dev is marked deprecated  - on how "safe" we are using beta channel, etc?

Thanks so much

**Comment by dnfield** [comment]
I don't have an exact date to share, but our release process (https://medium.com/flutter/flutter-spring-2020-update-f723d898d7af) says we do a stable push about once a quarter.  You can expect a new stable push sometime this quarter.

If it helps at all, Flutter apps at Google effectively run on dev, and there usually aren't too many changes between beta and stable when we do a release. Sorry I don't have much to share beyond that :)

**Comment by johnpryan** [comment]
> The SDK vended version is not available on stable yet, but is available on beta.

@dnfield Isn't `integration_test` is available in the stable channel now that Flutter 2.0.0 is out?

- https://github.com/flutter/flutter/pull/69622
- 2.0.0 [release notes](https://flutter.dev/docs/development/tools/sdk/release-notes/release-notes-2.0.0)

> DId this get missed? this is still super confusing afaict
on https://flutter.dev/docs/testing/integration-tests and https://pub.dev/packages/integration_test#ios-device-testing which is linked from there - i.e. the official path.
https://github.com/flutter/flutter/tree/master/packages/integration_test at least looks better from the surface but you can't easily find that from pub.dev or flutter.dev

@neiljaywarner This will fix the links in [Integration testing page on flutter.dev](https://flutter.dev/docs/testing/integration-tests) 

- https://github.com/flutter/website/pull/5700

**Comment by dnfield** [comment]
Yes, but integration_test NNBD is'n't on stable yet - or am I mixing up issues now?

**Comment by johnpryan** [comment]
I think we're getting off topic from the original issue - @neiljaywarner please follow https://github.com/flutter/flutter/issues/71506 and https://github.com/flutter/flutter/issues/71379 if you are waiting on integration_test to upgrade to null safety. You can import and use the non-null-safe version by using an SDK dependency on the stable channel, though.

**Comment by neiljaywarner** [comment]
Pub.dev only got marked deprecated a few days ago I think and even updated
lately and I think flutter 2.0 was a month ago
....sent from my phone

**Comment by johnpryan** [comment]
I am able to import and use the integration_test package by using `sdk: flutter` in my pubspec on the latest stable channel (2.0.5)

**Pull request closed without merging**
