### PR TITLE
Revert "[ci][image_picker]enable xcode 12/iOS 14 for all tasks except lint"

### PR DESCRIPTION
**Pull request by cyanglaz**
Reverts flutter/plugins#3304
@jmagman @fkorotkov Looks like the post submit was failing, revert and I'll further investigate.

### CODE REVIEW

**Comment by cyanglaz** [comment]
CI failure link: https://cirrus-ci.com/build/4551590315032576

**Comment by jmagman** [comment]
@cyanglaz I see two timeouts and what looks like a legit issue:
```
flutter: PlatformException(evaluateJavaScript_failed, Failed evaluating JavaScript, JavaScript string was:
flutter: 'Echo.postMessage("hello");'
flutter: Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type"
flutter: UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type},
flutter: null)
```

**Review by jmagman — APPROVED** [review]
Revert LGTM

**Comment by cyanglaz** [comment]
The webview issue is https://github.com/flutter/flutter/issues/66318; Applying the workaround in the comment https://github.com/flutter/flutter/issues/66318#issuecomment-701105380 can fix the test.
The other one related to integration_test might be a flake. (I can't repro locally)

**Pull request merged**
