### PR TITLE
[camera] Fix disposed exceptions for the camera example on iOS

### PR DESCRIPTION
**Pull request by AlexV525**
No CHANGELOG change: only affects the example.
No version change: only affects the example.

Related to https://github.com/flutter/flutter/issues/97199.

Controllers were given to the field aggressively, which cause race conditions when initializing controllers. Now the code will remove the references ASAP when a controller has been disposed.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by AlexV525** [comment]
Test result without the fix: image

**Comment by hellohuanlin** [comment]
Hi, can you add more details in the description? is it to hide the permission bug from the example project? (if that's the case it is probably better not to hide it so we know there's a bug there)

**Comment by AlexV525** [comment]
> Hi, can you add more details in the description? is it to hide the permission bug from the example project? (if that's the case it is probably better not to hide it so we know there's a bug there)

@hellohuanlin Updated. It's more like a race conditions issue, and it could happen other than the permission issue.

**Comment by hellohuanlin** [comment]
> @hellohuanlin Updated. It's more like a race conditions issue, and it could happen other than the permission issue.

Will this PR hide the permission issue mentioned in flutter/flutter#97199?

**Comment by AlexV525** [comment]
> Will this PR hide the permission issue mentioned in [flutter/flutter#97199](https://github.com/flutter/flutter/issues/97199)?

Indeed.

**Comment by stuartmorgan** [comment]
> No CHANGELOG change: only affects the example.

We generally changelog for example-only changes; see the discussion in the link for that PR item. (Otherwise the bot would be configured not to require the override for that case.)

**Comment by Hixie** [comment]
What's the status of this PR?

**Comment by AlexV525** [comment]
> What's the status of this PR?

I'm holding this and see if it's still necessary after @hellohuanlin apply fixes to flutter/flutter#97199.

**Comment by hellohuanlin** [comment]
since this PR hides the bug in the example code, it may not be a good idea to land it

**Pull request closed without merging**
