### PR TITLE
[webview_flutter] Speculative getTitle fix

### PR DESCRIPTION
**Pull request by stuartmorgan**
Attempts to fix the getTitle flake by running JS before accessing the
title, to force the page to be fully processed by the native code.

No CHANGELOG change: Description would be the same as something that is
already in the NEXT section.

Speculative fix for https://github.com/flutter/flutter/issues/94117

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I'll retry the tests a few times before landing.

**Comment by stuartmorgan** [comment]
Passed once; trying again...

**Comment by stuartmorgan** [comment]
Twice...

**Comment by stuartmorgan** [comment]
Three times (and that's each of the four runs—{master,stable}x{app-facing,impl}—each time). We may have a winner here.

**Review by jmagman — APPROVED** [review]
LGTM. Could also revert the other speculative fix if it didn't work. Up to you though.

**Comment by ditman** [comment]
> Could also revert the other speculative fix if it didn't work. Up to you though.

I'm going to give a shot at reverting the other fix in this branch (that'll give us yet another run of the test)

**Review by ditman — APPROVED** [review]
This'll land on red to fix the tree. After tests finish, the flaky test would have passed 4x in a row.

**Comment by ditman** [comment]
Merged on red to heal the tree.

**Pull request merged**
