### PR TITLE
[integration_test] Deprecate, and stop using in this repository

### PR DESCRIPTION
**Pull request by stuartmorgan**
* Updates integration_test README to note that the published version is deprecated and direct people to the SDK version.
* Updates all plugins here to use the SDK version.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by stuartmorgan** [comment]
This doesn't update the version and CHANGELOG of all the plugins it touches since I would not expect this to be a change that matters in the published version, thus shouldn't need publishing. If there's a reason we need to publish that I missed, I can update the PR accordingly.

**Review by mvanbeusekom — APPROVED** [review]
LGTM

**Comment by mvanbeusekom** [comment]
@stuartmorgan just now I noticed a reference to the `package/intergration_test` package in the `.cirrus.yml` file. Should this also be updated?

**Comment by stuartmorgan** [comment]
> @stuartmorgan just now I noticed a reference to the `package/intergration_test` package in the `.cirrus.yml` file. Should this also be updated?

I was going to deal with that one when I actually remove the `integration_test` code.

**Comment by mvanbeusekom** [comment]
> I was going to deal with that one when I actually remove the `integration_test` code.

Alright that means it is on your radar. I just mentioned it to make sure it was not something you overlooked. Good to go if you ask me.

**Review by ditman — APPROVED** [review]

**Comment by ditman** [comment]
At some point, we need to ask people to unpublish this, maybe? https://pub.dev/packages/integration_test Or mark it as "deprecated"?

**Comment by stuartmorgan** [comment]
Yes, I was going to publish this now to guide people via the README, then eventually (I need to think about how long to wait) mark it as discontinued.

**Comment by ditman** [comment]
@stuartmorgan I've seen that pub.dev redirects to the flutter API docs for some packages. I'm not sure how that's achieved, but check out this link: http://pub.dev/packages/flutter_test. It'd be nice that integration_test eventually redirected to api.flutter.dev as well!

**Comment by stuartmorgan** [comment]
Oh, that's nice! @jonasfj what's the mechanism for adding a redirect like that?

**Pull request merged**
