### PR TITLE
[camera] set useAutoFocus to true by default

### PR DESCRIPTION
**Pull request by markfili**
## Description

There's no way to set Camera for Android's `useAutoFocus` property to `true` and it is `false` by default so auto focusing is not working in preview mode. This change sets the `useAutoFocus` property to `true` by default because the changes in the related pull request (#3383) prior to this one ensures the check for auto focus capability and handles it accordingly. 

## Related Issues

Follow-up patch for [flutter/flutter#73160](https://github.com/flutter/flutter/issues/73160)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by mvanbeusekom** [comment]
@markfili thank you for this contribution, you are on to something here.

Could you please also update the version number in the `camera/pubspec.yaml` (to version 0.6.4+4) and add an entry to the `camera/CHANGELOG.md` file describing the big fix?

**Review by mvanbeusekom — APPROVED** [review]
LGTM

**Comment by markfili** [comment]
@mvanbeusekom the big fix is now documented. Could you maybe confirm with your setup with which you created your pull request that it works properly?

**Comment by mvanbeusekom** [comment]
> @mvanbeusekom the big fix is now documented. Could you maybe confirm with your setup with which you created your pull request that it works properly?

I have tested it on my Samsung Galaxy S6 and LG Nexus 5X and all looks good.

**Pull request merged**
