### PR TITLE
[video_player] Move [player dispose] to `onUnregistered`

### PR DESCRIPTION
**Pull request by cyanglaz**
## Description

Fix the issue where the player object is destructed before the texture finishes unregistering which leads to crashing the app.

The `onTetureUnregistered` callback is only available after https://github.com/flutter/engine/pull/12695. Until this change in engine is moved to "stable", we use a temporary solution.
The temporary fix delays the dispose of the FLTPlayer which avoid the race condition.

This PR also added driver test for the example app which runs the crashing scenario in https://github.com/flutter/flutter/issues/41125 and makes sure it is not crashing. The test will only crash on iOS 12 and above.

## Related Issues

https://github.com/flutter/flutter/issues/41125

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by cyanglaz** [comment]
We will skip the test until we move iOS integration test to firebase device lab. @collinjackson 
To skip test and pass the CI. A fix in the plugin_tools needs to be landed. The PR for the fix is here:
https://github.com/flutter/plugin_tools/pull/64

**Comment by Hixie** [comment]
> We will skip the test until we move iOS integration test to firebase device lab. @collinjackson
> To skip test and pass the CI. A fix in the plugin_tools needs to be landed. The PR for the fix is here:
> [flutter/plugin_tools#64](https://github.com/flutter/plugin_tools/pull/64)

SGTM.

**Comment by cyanglaz** [comment]
@fkorotkov has been looking into the video player hanging issue for flutter driver tests. Meanwhile, since it is a fix to a customer critical issue, we can land it with the skipped tests. We will un-skip it when the Cirrus issue is resolved.

**Comment by fkorotkov** [comment]
@cyanglaz BTW did you test with Xcode 10.2? I did try on 11.2.1 where I had the version error. I'll try 10.2 now. 🤔

**Comment by cyanglaz** [comment]
> @cyanglaz BTW did you test with Xcode 10.2? I did try on 11.2.1 where I had the version error. I'll try 10.2 now. 🤔

The version error you emailed me seems related to the pub version script. It basically says the version in pubspec in your patch is too high compares to the version in pubspec on master. I replied your email with some thoughts about it. Please let me know if you haven't received the email, I can send it again. :D

**Comment by fkorotkov** [comment]
@cyanglaz I've removed the `skip` thing on master and was able to run it locally the tests within the VM. But I have a newer version of the virtualization locally since it's not possible to run the version that Cirrus is using on Catalina. I'm in the process of upgrading the mac infrastruture which includes upgrading to Catalina, migrating to the 2.0 version of virtualization and a few other improvements. If everything will go smooth it will be available in two weeks. I'll ping you once the upgrade will be available so we can test the test. 😅 Sorry for the inconveniences!

**Comment by cyanglaz** [comment]
@fkorotkov Thanks that sounds great!! I have created an issue for it .https://github.com/flutter/flutter/issues/43012, let's track it there :)

**Comment by dannyvalentesonos** [comment]
@cyanglaz I am testing this fix, and `onTextureUnregistered` is never called.

After digging a little, it's because the `FlutterTexture` interface has this method declaration:

```
@optional
- (void)onTextureUnregistered:(NSObject<FlutterTexture>*)texture;
@end
```

Yet, the video player plugin overrides it like this:

```
- (void)onTextureUnregistered {
  dispatch_async(dispatch_get_main_queue(), ^{
    [self dispose];
  });
}
```

When I change it to 
```
- (void)onTextureUnregistered:(NSObject<FlutterTexture>*)texture {
  dispatch_async(dispatch_get_main_queue(), ^{
    [self dispose];
  });
}
```
it works perfectly.

I'm not sure why the FlutterTexture API would pass the texture pointer to itself... Anyway, this has not been fully fixed.

Thanks.

**Comment by cyanglaz** [comment]
@dannyvalentesonos you are absolutely correct! Do you mind opening a PR with your fix? I will be happy to review it. Thanks.

**Comment by shihchanghsiungsonos** [comment]
@cyanglaz here is the PR: https://github.com/flutter/plugins/pull/2480. Please review. Thanks!

**Pull request merged**
