### PR TITLE
Add updatePassword functionality to firebase_auth plugin.

### PR DESCRIPTION
**Pull request by slightfoot**
Required functionality in recent project. Also moved updateProfile in dart code from `FirebaseAuth` to `FirebaseUser` I believe this is the correctly place. So release changelog should be updated to reflect this breaking change.

### CODE REVIEW

**Comment by kroikie** [comment]
@slightfoot Thanks for the PR. This change looks good. Would you mind rebasing on master, I'd be happy to merge then.

**Comment by slightfoot** [comment]
@kroikie rebased on master.

**Comment by ffeu** [comment]
Just linking to issues. 

FirebaseUser.updatePassword() - flutter/flutter#16775 flutter/flutter#19525

**Comment by kroikie** [comment]
@slightfoot There is already a [PR](https://github.com/flutter/plugins/pull/647) that updates email and it should land soon. Would you mind making this PR focus on just the password update?

**Comment by slightfoot** [comment]
@kroikie I think you need to look at how these differ. Mine has the updateEmail/updatePassword/updateProfile in the FirebaseUser. Along with the Android code using the supplied `TaskVoidCompleteListener`. If I was to remove the `updateEmail` it would spread the functionality across classes.

**Comment by slightfoot** [comment]
@kroikie rebased and fixed the merge conflicts.

**Comment by kroikie** [comment]
@slightfoot updateEmail has already been added, if you could remove the updateEmail parts of the PR I'd be happy to merge, thanks.

**Comment by slightfoot** [comment]
@kroikie I'm happy to make changes. I need direction, because as I said in the original PR description and later on, that I moved `updateProfile`/`updateEmail`/`updatePassword` from `FirebaseAuth` to `FirebaseUser`. So if I remove `updateEmail` then `updateProfile` and `updatePassword` will be in `FirebaseUser` and `updateEmail` will be in `FirebaseAuth`. Let me know what you want.

**Comment by ffeu** [comment]
If you guys allow me a suggestion, I would keep updateEmail() inside FirebaseUser (as it is already on the platforms), and would publish this PR with a new major version for the plugin.

The good thing of keeping the method in the "same place" as the Android and iOS SDKs is that currently there's no documentation on firebase for flutter. So I see this similarity as an advantage.

**Comment by slightfoot** [comment]
@ffeu great comments, I agree.
@kroikie let me know if you want me to update anything regarding the above.

**Comment by alardizabal** [comment]
Hi, any updates? Updating a user's password would be great.

**Comment by slightfoot** [comment]
Actually sorting this out now along with fixing flutter/flutter#18312

**Comment by slightfoot** [comment]
@kroikie I've rebased to the latest master. Hold off on any merge. I have another PR coming up which you might want to review, and bring into the same release. I'll bring the other branch on top of this one so as to resolve any conflicts upfront.

**Comment by slightfoot** [comment]
@kroikie I've added `@Deprecated` notices to the old `updateEmail` and `updateProfile` in `FirebaseAuth` to address moving them to `FirebaseUser`. This is now ready to be merged. Also see #775

**Comment by slightfoot** [comment]
@kroikie review changes made.

**Comment by slightfoot** [comment]
nudge @kroikie 😉

**Comment by zanecidan** [comment]
Hi, any updates on this?

**Comment by kroikie** [comment]
@slightfoot Thanks a lot for this, sorry for the delay.

**Comment by slightfoot** [comment]
@kroikie no problem. #775 can be merged in on top. They both have the same version.

**Comment by topex-psy** [comment]
any update on this?

**Comment by slightfoot** [comment]
@topex-psy this was merged a long time ago. You can find the functionality here.
https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseUser/updatePassword.html

**Pull request merged**
