### PR TITLE
[camera] disable auto focus when using front facing camera on Android

### PR DESCRIPTION
**Pull request by mvanbeusekom**
## Description

This pull request fixes a bug with setting auto focus (necessary for the flash feature) which made it impossible on most Android devices to take a picture with the front facing camera.

It also resolves an issue were the preview of the front facing camera is very dark, which had to do with the configured FPS range.

## Related Issues

- Resolves flutter/flutter#73160

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by officer47p — APPROVED** [review]

**Comment by divyanshub024** [comment]
@bparrishMines @mvanbeusekom When this PR can be merged?

**Comment by mvanbeusekom** [comment]
> @bparrishMines @mvanbeusekom When this PR can be merged?

@divyanshub024 once we have approval from the Google Team, which usually happens within a few days, we will merge the PR and I will request to publish this new version.

**Review by bparrishMines — APPROVED** [review]
LGTM

**Comment by aytunch** [comment]
@mvanbeusekom Thanks for the fix, how can we use this with Flutter Stable? is it camera: ^0.6.3+3 ?

**Comment by mvanbeusekom** [comment]
@aytunch this code is part of version 0.6.4+3 which has now been merged into the `master` branch of the `flutter/plugins` repo but has not been released yet to pub.dev. I expect this to happen very soon. 

If you want to continue developing earlier you can make a reference to the git repo directly from your pub.spec file (more details can be found [here](https://dart.dev/tools/pub/dependencies#git-packages)):

```yaml
  camera:
    git:
      url: git@github.com:flutter/plugins.git
      ref: master
      path: packages/camera/camera 
```

**Comment by aytunch** [comment]
@mvanbeusekom I tried it with the new version, however the camera still does not get opened for me
I am testing it in a real device One Plus 7t. It has a Pop-up camera
Pop up camera opens up but the camera view is never shown and init() never ends

**Comment by mvanbeusekom** [comment]
Did you override de dependency for the `camera_platform_interface` in your pubspec.yaml file?

If so remove it, run `flutter clean` followed by `flutter pub get`

**Comment by aytunch** [comment]
@mvanbeusekom I just tried again as you said and no luck :/

**Comment by mvanbeusekom** [comment]
@aytunch that is strange, we are not experiencing any issues on our side on Android (tested on One Plus, Samsung and LG devices). 

Could you maybe submit a new issue and list the output of `flutter doctor -v` and the contents of your `pubspec.yaml` file?

**Comment by mvanbeusekom** [comment]
B.t.w. the new version of the camera plugin containing this fix has just been released on pub.dev.

**Comment by markfili** [comment]
not sure if related, but after update to 0.6.4+3, auto focus seems disabled for the back camera while in preview mode on OnePlus 6, Android 10.... please see Attached.

<details>
  <summary>Attached</summary>

 Screenshot_20210107-150751

</details>

**Pull request merged**
