### PR TITLE
[url_launcher] Fix Link test

### PR DESCRIPTION
**Pull request by stuartmorgan**
One of the Link tests relied on internal implementation details of
url_launcher_platform_interface that have changed, so started failing
when the new version of that plugin was published.

This replaces that test with a test that the relevant
url_launcher_platform_interface function is called, without asserting
anything about how it works internally.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Landing on red to fix the tree.

**Comment by creativecreatorormaybenot** [comment]
@Hixie @stuartmorgan With a combination of these changes you broke the plugin - this is a breaking change.

Specifically, one of the two changes would have needed to be a major version bump (`2.0.3` #3893 in the platform interface changed the type and this PR `6.0.5` also changed the type, which means that `url_launcher: 6.0.5` and `url_launcher_platform_interface: 2.0.2` are incompatible, same for `url_launcher: 6.0.4` and `url_launcher_platform_interface: 2.0.3`). Just helped someone who spent 1 hour not knowing how to debug this problem.

I think you should publish a new version of `url_launcher` that explicitly declares the dependency.

**Comment by stuartmorgan** [comment]
> Specifically, one of the two changes would have needed to be a major version bump

Making this a major version change wouldn't really fix anything; the issue here is that this change uncovered that the other change is breaking in a very subtle way even though it was intended not to be.

I'll need to think about the best combination of releases to minimize the chances of resolving to a bad combination.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan Right, #4000 is **a** fix in this case (making `2.0.3` mandatory).

> Making this a major version change wouldn't really fix anything

I do not think this is true. If the platform interface version would have been `3.0.0`, then you would have **been required to** explicitly bump the dependency.

**Comment by stuartmorgan** [comment]
> > Making this a major version change wouldn't really fix anything
> 
> I do not think this is true. If the platform interface version would have been `3.0.0`, then you would have **been required to** explicitly bump the dependency.

This isn't the platform interface PR, it's the app-facing package PR. The part I was replying to said "one of the two changes would have needed to be a major version bump", which isn't right; a breaking change needs to be changed in the version of the package containing the breaking change, not clients of that package.

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan I see, makes sense. Thinking about it that way, I commented on the wrong PR (did not put thought into which one to choose since I thought they were connected).

But you are right: #3893 would have needed a major version bump because it changed public-facing API.

**Comment by stuartmorgan** [comment]
Having had time to dig into this more, and look more closely at the type mismatch, I think most of the discussion above is incorrect.

> @Hixie @stuartmorgan With a combination of these changes you broke the plugin - this is a breaking change.

I don't think there were any breaking changes, just a broken change (this one).

> Specifically, one of the two changes would have needed to be a major version bump (`2.0.3` #3893 in the platform interface changed the type and this PR `6.0.5` also changed the type

... and as a consequence, I don't think this is true either.

> which means that `url_launcher: 6.0.5` and `url_launcher_platform_interface: 2.0.2` are incompatible

This is definitely true. Specifically: `A value of type 'Future<ByteData> Function(BuildContext, String, {bool debugForceRouter})' can't be assigned to a variable of type 'Future<ByteData> Function(Object?, String)'`, which makes sense.

To be compatible with `url_launcher_platform_interface` 2.0.0-2.0.2, this would have needed to use `BuildContext`, not `Object?`, as the type of the first argument. I.e., of the two variants of the interface, it needs to use the one whose arguments are more specifically typed in order for both of the assignments to be valid.

> same for `url_launcher: 6.0.4` and `url_launcher_platform_interface: 2.0.3`).

I don't think this is true, based both on looking at the code (`pushRouteNameToFramework(context, routeName)` should be a perfectly valid call with the newer signature), and on actually trying it. What error were you seeing with this combination?

**Comment by creativecreatorormaybenot** [comment]
@stuartmorgan Ok that makes sense, thanks 🙏 I did test the second combination properly, your conclusion is correct.

**Pull request merged**
