### PR TITLE
[image_picker] Migrate image_picker to package:cross_file

### PR DESCRIPTION
**Pull request by BeMacized**
Changed all usages of PickedFile to XFile, to follow the changes made to the platform interface (#4072)

This PR will remain in draft state until the platform interface changes (#4072), as well as the web implementation of it (#4083) have been merged and published, so that the pubspec can be updated properly.

Relevant issue:
- flutter/flutter#70886

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by ditman** [comment]
image_picker_for_web will need to be landed *before* the core plugin, so we can update the endorsed version and the platform_interface in one go.

Can you split the changes to `image_picker_for_web` to a new PR?

**Comment by BeMacized** [comment]
@ditman Certainly! The changes have been reverted and moved to a new PR: #4083

**Comment by ditman** [comment]
* image_picker_platform_interface published: https://pub.dev/packages/image_picker_platform_interface/changelog#220
* image_picker_for_web published https://pub.dev/packages/image_picker_for_web/changelog#210

**Comment by BeMacized** [comment]
@ditman It should now be ready to go!

**Comment by ditman** [comment]
@googlebot I consent.

**Comment by ditman** [comment]
This needs to

```
// ignore_for_file: deprecated_member_use_from_same_package
```

In the file `test/image_picker_test.dart`

**Review by ditman — APPROVED** [review]
I think this is ready to go. I'm going to give a manual try to the example app in a couple of platforms (android, web) just to quickly verify.

**Comment by ditman** [comment]
(Looks good on Web and Android. Note that web has *not* implemented the "multi image picking" feature.

**Comment by ditman** [comment]
Thanks @BeMacized!!

**Pull request merged**
