### PR TITLE
[google_sign_in] Correctly passes `serverClientId` to native libs

### PR DESCRIPTION
**Pull request by wannabehero**
This PR compliments https://github.com/flutter/plugins/pull/5250 and https://github.com/flutter/plugins/pull/6034 to fully implement passing `serverClientId` to the native libs during channelled call.

Current implementation works fine if the value is provided via the corresponding plist / json file. But if provided via code only – it doesn't work properly. This PR addresses that problem.

Fixes https://github.com/flutter/flutter/issues/110099

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by jmagman — APPROVED** [review]
iOS part LGTM

**Review by camsim99 — APPROVED** [review]
Android looks good to me!

**Comment by jmagman** [comment]
@stuartmorgan shall I merge this, do you have any concerns?

**Comment by stuartmorgan** [comment]
No concerns. Looking back at some dates, I think what happened is that the original end-to-end PR that supported this was written before I switched `google_sign_in` to internal method channels, but the pieces all landed *after*, and nobody noticed that the open PR had before incomplete due to the method channel change.

**Comment by jmagman** [comment]
Thanks for your continuing work on this, @wannabehero!

**Comment by wannabehero** [comment]
Thanks for accepting this!
❤️

**Pull request merged**
