### PR TITLE
[webview_flutter]fixed javascript redirect #1197 

### PR DESCRIPTION
**Pull request by rakeshlanjewarwork**
can fix #25351,#26009,#26347,#27006

I have added a way from platform channels to enable redirect by using this method

```
         webView.setWebViewClient(new WebViewClient() {
          @Override
          public boolean shouldOverrideUrlLoading(WebView view, String url) {
            return false;
          }
        });
```

### CODE REVIEW

**Comment by phaniteja1** [comment]
Please fix the checks and merge this pr

**Comment by realcarlos** [comment]
@zoechi could  you help ,bro? ☝️

**Comment by amirh** [comment]
I'm not sure exactly how overriding `shouldOverrideUrlLoading` fixes redirects, but I believe the same affect should have been achieved by https://github.com/flutter/plugins/pull/1236.

@rakeshlanjewarwork  Is this PR still needed?

**Comment by rakeshlanjewarwork** [comment]
@amirh , I am not that much confident about PR, But it works and this PR fixes the issue.
You can merge PR if you think its correct or close the PR.

Please work on keyboard issue!

Thank!

**Comment by amirh** [comment]
@rakeshlanjewarwork what issue is this PR fixes? is that issue happening on the latest webview version? (if not, please close this PR).

**Comment by rakeshlanjewarwork** [comment]
Thanks

**Pull request closed without merging**
