### PR TITLE
[camera]Support flash on taking pictures

### PR DESCRIPTION
**Pull request by tungvn**
This PR support flash mode (off, on, auto) on each time take pictures

### CODE REVIEW

**Comment by tungvn** [comment]
I signed it!

**Comment by tungvn** [comment]
I signed it!

**Comment by callumclift** [comment]
@tungvn i've tried to implement your changes but the flash is still not working, would you possibly be able to assist me in getting it to work?

**Comment by tungvn** [comment]
> @tungvn i've tried to implement your changes but the flash is still not working consistently, i've got it to work on a Samsung device however the flash is not working on a Google Pixel 2 XL. Would you possibly be able to assist me in getting it to work?

Yes. Now I test on a Samsung Note 9, it is also not working. I am not a native coder and I am stuck for fixing this issue.

**Comment by MartinHlavna** [comment]
I would also appreciate this feature.

**Comment by lambasoft** [comment]
I would really appreciate this feature. Currently there is no way to turn on flash while using the camera plugin?

**Comment by tungvn** [comment]
> 
> 
> I would really appreciate this feature. Currently there is no way to turn on flash while using the camera plugin?

I test this PR on iOS and some Android devices, it worked. But it has some issues on Samsung devices and I am trying to fix it.

**Comment by MartinHlavna** [comment]
Is this merged?

**Comment by leonardodavila** [comment]
Looking foward to it

**Comment by mitajunior** [comment]
Please add this asap

**Comment by Ahmadre** [comment]
@tungvn why did you close your PR? I got a similar implementation and its working on Pixel 2XL (besides I got a Pixel 2 XL). If you like I can request a PR

**Comment by gisinator** [comment]
Go for it, flash functionality is being highly demanded :)

**Comment by mitajunior** [comment]
> @tungvn why did you close your PR? I got a similar implementation and its working on Pixel 2XL (besides I got a Pixel 2 XL). If you like I can request a PR

How did you get this to work?

**Comment by morbyosef** [comment]
What is the status of this feature? Very important feature :/

**Comment by GustavoFigueira** [comment]
March, 2020. We still need this future! Use flash/torch is a essential feature for a camera package like this! Please merge this PR.

**Comment by surenyonjan** [comment]
Flash/torch is a essential feature for a camera package like this! Please give this a priority

**Comment by Hellomik2002** [comment]
We still need it

**Comment by fekitibi** [comment]
I hope this feature will be implemented soon.

**Comment by paulewetzel** [comment]
I need this feature too for a project I am working on right now.

**Comment by felipesses** [comment]
i also need this feature!

**Comment by feltcorgi4114** [comment]
More than 2 years later, such an elementary feature is missing from such a great framework. Sad to see this (Also, I need this feature very badly!)

Hope the Flutter team sorts out the camera plugin

**Comment by feltcorgi4114** [comment]
Anyone who reaches this page, this issue has been solved now. New features to the camera plugin are no longer being added, but there is a third-party plugin called 'camerawesome'. Do check it out! It has all the features the camera plugin couldn't incorporate (well, almost)!

[https://pub.dev/packages/camerawesome](url)

**Pull request closed without merging**
