### PR TITLE
Enable code coverage for this project

### PR DESCRIPTION
**Pull request by truongsinh**
For example, please take a look at https://github.com/truongsinh/flutter-plugins/pull/5 and https://codecov.io/gh/truongsinh/flutter-plugins
screen shot 2019-01-04 at 2 27 28 pm
Please be noted that we must change the token (at https://github.com/flutter/plugins/compare/master...truongsinh:chore/code-cov#diff-0f7067c31caedf7df2739c9b07efa122R7)

### CODE REVIEW

**Comment by truongsinh** [comment]
This fail because CodeCov is not yet configured for `flutter/plugins`

**Comment by amirh** [comment]
@cbracken @collinjackson FYI

**Comment by truongsinh** [comment]
pinging @cbracken @collinjackson again, though I will rebase my current commit to resolve conflict

**Comment by collinjackson** [comment]
This looks like it could be useful, but it seems not ideal to make every first party plugin dependent on a library that's from third parties though. 

I wonder if we could add the dependency somehow in the CI build scripts instead (see https://github.com/flutter/plugins/tree/master/script)

**Comment by truongsinh** [comment]
> This looks like it could be useful, but it seems not ideal to make every first party plugin dependent on a library that's from third parties.

You mean `com.dicedmelon.gradle:jacoco-android:0.1.3` being third parties library :-?

**Comment by collinjackson** [comment]
Still trying to figure out how this could fit into our overall CI strategy.

> > This looks like it could be useful, but it seems not ideal to make every first party plugin dependent on a library that's from third parties.
> 
> You mean `com.dicedmelon.gradle:jacoco-android:0.1.3` being third parties library :-?

Yeah. I like we're introducing a library into developers' Android builds that they might not want.

Can you explain about how you're imagining this code coverage report would be used? It looks like it's building the example app but not actually running any tests. It seems like we might want to run some driver tests (see the drive-examples command). Is there a reasonable Objective-C equivalent to what is happening here on Android?

**Comment by stuartmorgan** [comment]
I'm going to close this, since it hasn't had activity in over a year and it seems like there significant open questions about the overall approach and goals. I've also unfortunately seen issues maintaining code coverage bots over time in almost every project I've worked on, so we should carefully weigh the benefits before proceeding.

If someone is interested in moving this forward, I think the first step would be [a design doc proposal](https://flutter.dev/docs/resources/design-docs)

**Pull request closed without merging**
