### PR TITLE
[google_maps_flutter]Google maps polygon

### PR DESCRIPTION
**Pull request by Aljoxa88**

### CODE REVIEW

**Comment by awazgyawali** [comment]
Is this only on android?

**Comment by Aljoxa88** [comment]
@awazgyawali Yes

**Comment by Aljoxa88** [comment]
I signed it!

**Comment by Aljoxa88** [comment]
fix CLA

**Comment by stevenspiel** [comment]
This is great! What will it take to get it merged?

**Comment by shailesh-mota** [comment]
Great ! Same question again, when/what about merging this one ?

**Comment by cyanglaz** [comment]
@Aljoxa88  The same functionality was merged in https://github.com/flutter/plugins/pull/1551 + iOS implementation. I'm going to close this PR. If you have any questions please feel free to tag me.

**Pull request closed without merging**
