### PR TITLE
[quick_actions] Update "eponymous concept" link.

### PR DESCRIPTION
**Pull request by happy-san**
## Description

Umm, a measly link update.

## Related Issues
--

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by happy-san** [comment]
@googlebot I signed it!

**Review by mvanbeusekom — APPROVED** [review]
LGTM!

**Review by bparrishMines — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
Unfortunately this never landed, and now has a conflict. If you can update and resolve (it may just be the file move), we can get this landed.

https://github.com/flutter/plugins/pull/2851 is the same fix; whichever gets updated can be landed and the other closed.

**Comment by happy-san** [comment]
Hey, @stuartmorgan do I rebase this against master?

**Comment by stuartmorgan** [comment]
I'm re-running the failed CI jobs since they were network/server issues, then it should be good to land. Thanks for updating!

(Normally we'd do a version bump so we could publish, but I expect this plugin to have other updated published relatively soon so we can just pick it up then.)

**Comment by stuartmorgan** [comment]
Re-run of Windows Plugins was successful, but LUCI doesn't update GitHub status still, so landing.

**Pull request merged**
