### PR TITLE
[scripts/tool] use 'flutter pub get' for both dart and flutter packages

### PR DESCRIPTION
**Pull request by devoncarew**
This PR switches the CI to calling `flutter pub get` for both Dart and Flutter packages (previously, we'd call `dart pub get` for non-Flutter packages). This normalizes the output in CIs a bit - `dart pub get` lists all the packages and versions that were resolved, while `flutter pub get` just emits one line of stdout. See https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8846322703236505168/+/u/analyze_flutter_plugins/stdout for an example of the existing CI output.

This work is generally in service to https://github.com/dart-lang/sdk/issues/45873 (which itself is part of https://github.com/dart-lang/sdk/issues/46075).

*List which issues are fixed by this PR. You must list at least one issue.*

- some work towards https://github.com/dart-lang/sdk/issues/45873

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [-] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [-] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [-] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Isn't this less efficient? Presumably the Flutter version is a superset of the Dart version.

**Comment by devoncarew** [comment]
> Isn't this less efficient? Presumably the Flutter version is a superset of the Dart version.

I don't think this will have any significant impact on time - `flutter packages get` is just a thin wrapper on `dart pub get`.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
> This pull request is not suitable for automatic merging in its current state.
> 
> * The status or check suite Windows Plugins has failed. Please fix the issues identified (or deflake) before re-applying this label.

Follow https://github.com/flutter/flutter/issues/83349

**Comment by christopherfujino** [comment]
I landed https://flutter-review.googlesource.com/c/recipes/+/13920 and re-triggered Windows Plugins, hopefully it goes green.

**Comment by christopherfujino** [comment]
Ok, since the recipe change didn't work, I reverted the tools change and re-triggered "Windows Plugins" again.

**Pull request merged**
