### PR TITLE
[image_picker] Fix exif orientation for pictures taken from camera

### PR DESCRIPTION
**Pull request by charafau**
Added ability to automatically rotate picture taken from camera, with exif preservation.

## Description

Problem:

Some phones take pictures with rotation `right, top` which causes photo to "rotate" 90 degrees when exif data is stripped.  This PR adds one variable to automatically rotate picture and write right exif data.

## Related Issues

This fixes this: https://github.com/flutter/flutter/issues/19458

looking forward to suggestions / changes to this PR. Thanks!

### CODE REVIEW

**Comment by Hixie** [comment]
I think this needs end-to-end tests to verify that for each physical orientation of the phone, the output image has the correct orientation and EXIF data.

**Comment by charafau** [comment]
@Hixie good idea, will try to add some.

**Comment by cyanglaz** [comment]
@charafau I think what we really should do is to copy all the meta data over to the image, instead of just copying rotation. Also, it is prob not necessary to have it as an optional flag. The captured/picked image/video should have the correct meta data by default.

**Comment by charafau** [comment]
Hello @cyanglaz sorry for lack of movement with this one, I was busy with different plugin. Yes I think you're right, I should copy all exif data. and add tests. Not sure if we want to make it a default behaviour though, I will leave that decision to you ;)

**Comment by cyanglaz** [comment]
@charafau Thank you for the quick response! I was thinking about this yesterday and I think that since the cropped image is actually not the original image, does it make sense to copy the exif from the original image?
Instead, we can also return the original image path from the pickImage/video API along with the cropped image path, that way if you want to access the original image's exif, you can get it from the original image. And the cropped image will contain whatever metadata the iOS or android platform decides put inside the image data. Will that solve the problem?
I think it will be more robust and easier to maintain, since we don't have to do these surgeries on metadata of the image.

**Comment by charafau** [comment]
@cyanglaz sorry for late reply. This code doesn't crop the image, it just rotates it, so it will be displayed correctly in portrait mode, when you strip exif data (some phones mount camera differently).

About your suggestions - yes we could just strip the exif data, but I'm not sure if that's what users would like to do (Imagine photo gallery with location of pictures and camera info). 

Other aspect of it would be, is current API good for it? Meaning, would it be better to pass parameter `rotate` or create new method like `pickRotatedImage` ?

**Comment by cyanglaz** [comment]
@charafau You are right. I have been reading all the issues that people have opened for image picker and I think people do want the exif to be copied over to the new image. Let's do that?
There is a PR doing something similar on the iOS side, for your reference. https://github.com/flutter/plugins/pull/866

Are you able to keep working on this PR?

**Comment by charafau** [comment]
@cyanglaz Yes, I think I should be able to. Might ask for help with tests on gitter but I will make it somehow.

**Comment by cyanglaz** [comment]
@charafau I have a PR related to this ready if you want to take a look.
https://github.com/flutter/plugins/pull/1586#pullrequestreview-235881807

**Comment by NGhebreial** [comment]
I made a plugin to fix this, hoping it's useful for you:
[https://pub.dev/packages/flutter_exif_rotation](https://pub.dev/packages/flutter_exif_rotation)

**Comment by charafau** [comment]
Sorry for slow progress, I'm on vacation now and cannot will be back soon-ish. Plan to do that when I'm back

**Comment by cyanglaz** [comment]
@charafau I'm going to close this PR since it has been inactive for a while. :) I encourage you to open another one when you are ready with the fix!

**Pull request closed without merging**
