### PR TITLE
[google_maps_flutter_web] Add Marker drag events

### PR DESCRIPTION
**Pull request by JamesMcIntosh**
Add events to track start of drag and position during drag for Google Maps Flutter Web

Issue: flutter/flutter#26117
Platform changes: flutter/plugins#2653
Flutter app: flutter/plugins#2838

## Pre-launch Checklist

- [/] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [/] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [/] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [/] I signed the [CLA].
- [/] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [/] I listed at least one issue that this PR fixes in the description above.
- [/] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [/] I updated CHANGELOG.md to add a description of the change.
- [/] I updated/added relevant documentation (doc comments with `///`).
- [/] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [/] All existing and new tests are passing.

### CODE REVIEW

**Comment by JamesMcIntosh** [comment]
@stuartmorgan looks like the might still be a problem with the `publishable` check for google maps flutter. This is what the error message is saying when there is both a README.md and CHANGELOG.md file in that package.
```
�[31mERROR: Package validation found the following errors:
* The pubspec is hidden, probably by .gitignore or pubignore.
* You must have a LICENSE file in the root directory.
  An open-source license helps ensure people can legally use your code.
Package validation found the following potential issues:
�[0m
�[31mERROR: * Please add a README.md file that describes your package.
* Please add a`CHANGELOG.md` to your package. See https://dart.dev/tools/pub/publishing#important-files.
Sorry, your package is missing some requirements and can't be published yet.
For more information, see: https://dart.dev/tools/pub/cmd/pub-lish.
�[0m
�[31mERROR: pub finished with exit code 65
�[0m
Unable to publish google_maps_flutter_web
```

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/plugins/pull/4388

**Comment by ditman** [comment]
This branch needs to be updated with `master` for it to pass the `publishable` check. @JamesMcIntosh if you give us permissions in the PR (there's a checkbox near the bottom when creating a PR that says something similar to: "Allow edits from maintainers"), I can do some of these chores for you while I review the code.

**Comment by JamesMcIntosh** [comment]
Both branches already had the "allow maintainers" permission checked.

**Comment by JamesMcIntosh** [comment]
@stuartmorgan Now the `submit-queue` is failing and the "details" link now take you to a page full of JSON rather than the summary.
https://api.github.com/repos/flutter/plugins/check-suites/3911833499/check-runs

This is the format of the other links (not pointing to the api subdomain).
https://github.com/flutter/plugins/pull/4385/checks?check_run_id=3748907644

**Comment by stuartmorgan** [comment]
> @stuartmorgan Now the `submit-queue` is failing

That's a live check indicating that the tree is currently closed so nothing can land. You don't need to do anything.

> and the "details" link now take you to a page full of JSON rather than the summary.

We don't control the format of the check, it's [an external app](https://github.com/cirruslabs/gh-submit-queue)

**Review by ditman — APPROVED** [review]
LGTM! Thanks for including tests, and pushing the updated mocks!

**Pull request merged**
