### PR TITLE
[video_player] RTSP Support

### PR DESCRIPTION
**Pull request by ened**
Builds upon #3933 and:
- bumps to ExoPlayer 2.15.1 (improved RTSP support)
- extends the example app with a RTSP sample

Closes flutter/flutter#82567.

Still TBD: 
- [ ] Improved tests as requested in https://github.com/flutter/plugins/pull/3933#issuecomment-923245081
- [ ] Do something about iOS. Either document the function is not available or throw a error

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] All existing and new tests are passing.

### CODE REVIEW

**Comment by Hixie** [comment]
@ened are you still interested in working on this PR?

**Comment by TheHypnoo** [comment]
Hello, is there any news about updating the video_player plugin to have the option to use it with RTSP?

@ened

**Comment by ened** [comment]
@Hixie do you see a path to merge even if RTSP is only supported on Android, once this is merged? There is simply no RTSP library with compatible license can be included here.

**Comment by Hixie** [comment]
That's more a question for @stuartmorgan, I think.

**Comment by stuartmorgan** [comment]
I don't see any issue with an Android-only implementation here, given that it reflects the limitations of the underlying libraries. `video_player` is already (by necessity) a leaky abstraction in that sense, given that we're limited by platform codecs as well.

**Comment by Hixie** [comment]
@ened Does stuart's answer above help?

**Comment by stuartmorgan** [comment]
Since this is marked as a draft and hasn't been updated in several months I'm going to close it to clean out our review queue. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

**Pull request closed without merging**
