### PR TITLE
[google_sign_in_web] add note how to pass Google Sign-In OAuth client ID

### PR DESCRIPTION
**Pull request by gimKondo**
I add how to pass "Google Sign-In OAuth client ID" for google_sign_in_web.
Now, there is a note that passing by meta tag on web/index.html.
But usually, we want to pass that one from dart code to switch target environment easily.

I add note how to pass Google Sign-In OAuth client ID on README.

> *List which issues are fixed by this PR. You must list at least one issue.*

- https://github.com/flutter/flutter/issues/102977

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
  - no need
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
  - no need
- [x] All existing and new tests are passing.
  - no need

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by gimKondo** [comment]
I've done CLA a few minutes ago.

**Comment by ditman** [comment]
@gimKondo thanks for this contribution!

Two quick notes:

1. This change seems small, but it needs a version bump ("patch" level) in CHANGELOG and pubspec.yaml (to `0.10.1+1`), so the new readme gets published to pub.dev ([here](https://pub.dev/packages/google_sign_in_web)).
2. Please, create a new flutter/flutter issue. In this case, we could have discussed a slightly better approach to code blocks in the README that we're trying to standardize across the whole repo 😅:
    * Here's documentation about [generating code blocks for the README from the Dart source](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#readme-code), so READMEs don't get stale as the example code evolves. See examples in the `camera` plugin: 
      * [README.md](https://github.com/flutter/plugins/blob/main/packages/camera/camera/README.md?plain=1#L64)
      * [Dart code](https://github.com/flutter/plugins/blob/main/packages/camera/camera/example/lib/main.dart#L109-L125)

PS: I've restarted the CLA check, and that's now in order, it won't bother you in future contributions!

**Comment by gimKondo** [comment]
@ditman Thank you for your advise!

I created issue and changed version on pubspec.yaml and CHANGELOG.md for now.

But I didn't touch about "better approach to code blocks".
Because I just added code on existing code block, and that's not on example code.

Of course, I understand the approach you said is very useful to keep document pretty.
I'm just wondering, do I need to update example code format in THIS pull request?

**Comment by stuartmorgan** [comment]
> But I didn't touch about "better approach to code blocks".
> Because I just added code on existing code block, and that's not on example code.

Adding to an existing code block is still adding new code that is not being validated (e.g., would we notice if you typo'd the argument?), so this should include updating to code-based excerpts.

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
Are you still planning to update this PR per the comments above?

**Comment by gimKondo** [comment]
@stuartmorgan 
I'm still thinking to do it in an idle moment.
But, of course, I don't care if someone does it.

**Comment by gimKondo** [comment]
@stuartmorgan 
I read examples and found followings.

- There is actual example on [google_sign_in/google_sign_in/example](https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in/example).
- The example on [google_sign_in/google_sign_in_web/example](https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in_web/example) is not meaningful, because it looks like a copy of default template(?).

So, I think the best way to excerpt code is what set excerpt tags on [google_sign_in/google_sign_in/example](https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in/example).
Can I excerpt code from another example?

**Comment by stuartmorgan** [comment]
> * The example on [google_sign_in/google_sign_in_web/example](https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in_web/example) is not meaningful, because it looks like a copy of default template(?).

It's there to drive integration tests.

> So, I think the best way to excerpt code is what set excerpt tags on [google_sign_in/google_sign_in/example](https://github.com/flutter/plugins/tree/main/packages/google_sign_in/google_sign_in/example). Can I excerpt code from outside example?

No, excerpts need to be in-package. But they don't need to be from the existing example code; see https://github.com/flutter/plugins/blob/main/packages/local_auth/local_auth/example/lib/readme_excerpts.dart for instance.

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
