### PR TITLE
[ci] Shorten dependabot prefixes to comply with config spec.

### PR DESCRIPTION
**Pull request by ditman**
Dependabot prefixes have a maximum of 15 chars ([docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message)).

This PR shortens the prefixes introduced here: https://github.com/flutter/plugins/pull/5440 so the dependabot action doesn't fail.

(Needs to land on red)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by ditman** [comment]
Attempted to shorten the names by removing "redundant" bits, like: `google`, `flutter` and `android` (platform-android should be added by the PR labeler, right?). When that wasn't enough, I shortened some words, attempting to leave the name of the plugin still a sub-string of the longer name (for the future verification script(?))

**Review by blasten — COMMENTED** [review]
it kinds of defeats the purpose. maybe we just don't have prefixes?  

The label should be added to the PR, but if the idea was to search through history using the prefix, then that seems unfeasible.

**Comment by ditman** [comment]
Dependabot seems to also be adding `:` after the specified prefix, and that's going to look weird in our repo as well. [Issue](https://github.com/dependabot/dependabot-core/issues/1666).

We can create an issue on `dependabot` asking them to respect whatever we pass as a prefix, but they might have their limitations on why not to do it :/ For now, I think this is going to look less weird without the prefixes, even the shortened ones (so dependabot commits will look similar to the autoroller's)

**Comment by stuartmorgan** [comment]
> it kinds of defeats the purpose. maybe we just don't have prefixes?
> 
> The label should be added to the PR, but if the idea was to search through history using the prefix, then that seems unfeasible.

It'll become the commit message, so having shortened forms is still better than nothing.

We actually shouldn't have the `_android` suffixes anyway, since the convention we use is to put the conceptual plugin name rather than the package name. Where we can fit the whole plugin name, I'd like to keep that. Most of them should be <15

**Review by stuartmorgan — APPROVED** [review]
Oh, I see, the `[]` puts several of them just over.

This LGTM then.

**Comment by ditman** [comment]
`[google_maps]` should fit, for example, let me minimize the _shortening_.

**Comment by ditman** [comment]
I'm going to land this on red to re-open `main`. This can be easily revisited to tweak the names and/or create an issue for dependabot.

**Comment by ditman** [comment]
Dependabot is at it already!

https://github.com/flutter/plugins/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies

**Comment by stuartmorgan** [comment]
> It'll become the commit message, so having shortened forms is still better than nothing.

Capturing from Discord for posterity: I didn't realize the package path would be in the title. I'm now on board with not having prefixes.

**Comment by fkorotkov** [comment]
Just a heads up. It seems this change made dependabot to create [hundreds PRs](https://github.com/flutter/plugins/pulls?q=is%3Apr+dependabot+is%3Aclosed) that @ditman just closes.

This caused thousands of macos tasks to be created on Cirrus in a very short period of time which is causing some longer then usual processing times.

**Comment by ditman** [comment]
@fkorotkov yes, apologies for the spam. When I realized this would abuse Cirrus, it was probably too late (x_x)

**Comment by fkorotkov** [comment]
No worries. Just wanted to let you know that there is some unintentional slowness. An interesting use case. Haven't seen that many PRs from dependbot at once plus our physical Mac Mini infra is not elastic like everything else in the cloud. 😪

**Pull request merged**
