### PR TITLE
Link email password

### PR DESCRIPTION
**Pull request by kykl**

### CODE REVIEW

**Comment by kykl** [comment]
I signed it!

**Comment by kykl** [comment]
I signed it! 
Unfortunately, my commit was using my personal email address "kenneth.lee@gmail.com". I signed it with my corporation "engineering@carnivorestudios.com" and "kenneth@carnivorestudios.com"

What should I do from here?

**Comment by mit-mit** [comment]
cc @collinjackson can you take a look, please?

**Comment by Prayuta** [comment]
@kykl Could you please add the code to login/singup with the phonenumber as well in the firebase_auth

**Comment by collinjackson** [comment]
Merged and uploaded to pub. Thanks for your contribution!

**Comment by sethladd** [comment]
Sweet, thanks @collinjackson and thanks @kykl for the contribution!

**Pull request merged**
