### PR TITLE
[google_sign_in] Fix Exception leaking in debug mode (#64681)

### PR DESCRIPTION
**Pull request by feinstein**
## Description
This is related to flutter/flutter#26705 and many others. I already fixed this before on flutter/flutter#37343 submitting this PR https://github.com/flutter/plugins/pull/1937.

I am fixing this again.

Could the owners of these files make some sort of mechanism to avoid this from happening again?

________

I need some help with the tests, I honestly don't understand why the `'can sign in after init failed before'` test is failing. For some reason the `MockMethodCallHandler` is only being called once. I didn't change anything on this test (just syntactic sugar, but it also fails if I remove it).

## Related Issues

Fixes flutter/flutter#64681
Fixes flutter/flutter#45146

flutter/flutter#37343
flutter/flutter#26705
dart-lang/sdk#37268

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by feinstein** [comment]
@mehmetf could you help me figure out what's the problem with the tests?

**Comment by stuartmorgan** [comment]
All of the referenced issues are closed, referring to an issue that was recently fixed in the Dart VM. Given that, is this PR still necessary?

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Comment by feinstein** [comment]
Sorry Stuart, I forgot to reply... Yeah I don't think it's necessary anymore.

**Pull request closed without merging**
