### PR TITLE
[in_app_purchase] moved android iap unit tests

### PR DESCRIPTION
**Pull request by renefloor**
Moved in_app_purchase unit tests.

As they were on the wrong place there was a misconception that they were missing.

Fixes flutter/flutter#78538 (as there were already quite some tests).

TextUtils and Logs had to be mocked as well to make the tests succeed in the new project.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by cyanglaz** [comment]
all the log says is ```running java-test
script/tool/lib/src/main.dart: Warning: Interpreting this as package URI, 'package:flutter_plugin_tools/src/main.dart'.
All Java tests successful!```

Is there a way to make sure the tests did actually run? Maybe try to modify a test to intentionally fail and see if ci fails?

**Comment by renefloor** [comment]
@cyanglaz where is the location of the tests set for the CI? I couldn't really find it

**Comment by cyanglaz** [comment]
@renefloor It's this https://cirrus-ci.com/task/6742052697276416

**Comment by cyanglaz** [comment]
https://github.com/flutter/plugins/pull/3742 has landed. we should be able to rebase and run tests in this PR.

**Comment by renefloor** [comment]
Yes I tried to merge this with master yesterday, but this PR makes that close to impossible: https://github.com/flutter/plugins/pull/3744 
I'll just recreate this today.

**Review by mvanbeusekom — APPROVED** [review]
LGTM!

**Pull request merged**
