### PR TITLE
[url_launcher] Update result to `True` when the url was loaded successfully.

### PR DESCRIPTION
**Pull request by lidongze91**
Update result to True when the url was loaded successfully.

We are expecting a proper True/False signal for the dart API. After migrating to null-safety, any nil response will be interpreted as false even though the url was loaded successfully. See more at: b/178609319

*List which issues are fixed by this PR. You must list at least one issue.*
b/178609319

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by cyanglaz — COMMENTED** [review]
Code LGTM, please add tests and version updates.

**Comment by stuartmorgan** [comment]
@lidongze91 Are you planning on updating the pubspec and changelog with a new version?

**Comment by stuartmorgan** [comment]
You'll need to re-sync with master one more time, then this should be ready to go.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Pull request merged**
