### PR TITLE
[all] Update repo links to 'main'

### PR DESCRIPTION
**Pull request by stuartmorgan**
Replaces 'tree/master/...' with 'tree/main/...' in pubspec `repository`
and podspec `source` links, now that `main` is the default branch.

No version change: `master` is being mirrored for the foreseeable
future, so there's no urgency on this; updates can go out as plugins
are updated naturally.

No CHANGELOG change: This is a mechanical mass change.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by Hixie** [comment]
test-exempt: documentation

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by ditman** [comment]
It seems that github supports [`HEAD` as a reference to the tip of the default branch](https://stackoverflow.com/a/65158264) in URLs? Maybe this is a more definitive change?

https://github.com/flutter/plugins/tree/HEAD/packages/camera

(instead of https://github.com/flutter/plugins/tree/main/packages/camera)

((The Github UI looks uglier without specifying the branch name, even though the links seem to point to the same location at the end of the day))

**Review by ditman — APPROVED** [review]
🚀

**Comment by Hixie** [comment]
It's extremely unlikely that we'd change the name of the main branch _again_ any time soon.

**Comment by stuartmorgan** [comment]
Yeah, I'm going to go ahead and just do `main`. The "HEAD" thing makes me a little nervous since it doesn't seem to be officially documented anywhere.

**Pull request merged**
