### PR TITLE
[ci] resets all simulators before creating a new one

### PR DESCRIPTION
**Pull request by cyanglaz**

### CODE REVIEW

**Comment by blasten** [comment]
This is ok, but let's confirm what is going on.

@fkorotkov is this something that Cirrus does/reuse VMs in their current state that may leak processes?

**Comment by jmagman** [comment]
@cyanglaz What issue do you think this is causing?

**Comment by fkorotkov** [comment]
Each task uses a fresh VM cloned from a golden suspended VM. Doesn't seem like this change will do anything from Cirrus perspective  🤔

**Comment by cyanglaz** [comment]
This this the failure log. https://cirrus-ci.com/task/6176805201641472
I'm not sure the root cause, I thought this PR could mitigate the issue and unblock the tree.

**Comment by jmagman** [comment]
> This this the failure log. https://cirrus-ci.com/task/6176805201641472
> I'm not sure the root cause, I thought this PR could mitigate the issue and unblock the tree.

More likely each test is creating a simulator and not cleaning it up?

**Comment by cyanglaz** [comment]
Maybe we can clean up the sims after each task? 
@fkorotkov Do you know what the root cause could be?

**Comment by fkorotkov** [comment]
Im not that familiar with your build. I'd look at the place where the simulator is created and maybe for debugging listed it in the setup step to just make sure the VM is clean.

**Comment by jmagman** [comment]
> > This this the failure log. https://cirrus-ci.com/task/6176805201641472
> > I'm not sure the root cause, I thought this PR could mitigate the issue and unblock the tree.
> 
> More likely each test is creating a simulator and not cleaning it up?

Never mind, the only place I see `Flutter-iPhone` simulators being created is in `create_simulator_script`.  

>  I'd look at the place where the simulator is created and maybe for debugging listed it in the setup step to just make sure the VM is clean.

@fkorotkov It's already doing that.  The first thing is does it list the simulators before creating any more, and sure enough, there's already a bunch in there:

https://github.com/flutter/plugins/blob/42d5325a93ffc80179ab770febcdd79243c3ff87/.cirrus.yml#L201-L203

https://cirrus-ci.com/task/6176805201641472?command=create_simulator#L74-L83

```
xcrun simctl list
...
== Devices ==
-- iOS 14.3 --
    iPhone 8 (D8DA7770-5C57-4693-9236-85BB6BF85CC3) (Shutdown) 
    iPhone 8 Plus (FD292F19-D135-431B-B816-9F55A7B41B2C) (Shutdown) 
    Flutter-iPhone (1C64D9B4-E89D-404F-82C0-4D6AB6C12959) (Booted) 
    Flutter-iPhone (E29D9663-4CC8-435B-BB5D-AE408A3B5D14) (Booted) 
    Flutter-iPhone (90F60129-1DE9-4792-9A54-E938E62FFE40) (Booted) 
    Flutter-iPhone (173C191F-F490-4E01-BBDC-F9F3FDCDD621) (Booted) 
    Flutter-iPhone (B349135D-BDF3-476A-B61D-1C3403E43E25) (Booted) 
    Flutter-iPhone (F44B928E-FF5F-4EF6-A182-3036EE93CD12) (Booted) 
    Flutter-iPhone (17BD7577-2F29-4B5B-80BC-D66BF74BF1B7) (Booted) 
    Flutter-iPhone (7716A5DF-1F1D-43F6-B851-E5A8D99DC5AD) (Booted) 
    Flutter-iPhone (67D6D0A1-07E3-4AA2-BDAC-0B1983C36E75) (Booted) 
    Flutter-iPhone (9168BECF-8E29-4E81-B97D-C104AF53EC25) (Booted) 
```

**Comment by jmagman** [comment]
This LGTM to green out the tree, but it is concerning there seems to be leaking simulators between tasks.  @fkorotkov you want a bug to investigate?  It's literally just cloning the repo, upgrading flutter, then calling `xcrun simctl list`, which shows a whole bunch of booted `Flutter-iPhone` simulators...

**Review by jmagman — APPROVED** [review]
LGTM

**Comment by fkorotkov** [comment]
@jmagman thank you! Definitely seems like an issue on our end. I saw once before "zombie" VMs handing on the workers and yesterday I checked the `k16-5` worker and saw the zombie VMs for the second time. From the logs you provided it seems these zombie VMs are getting reused and reused and therefore accumulating simulators.

It seems only worker `k16-5` had the issue and I removed zombie VMs back when you reported the issue but didn't realize that these VMs got reused. I'm still not quite sure why it happened but we are investigating in https://github.com/cirruslabs/cirrus-cli/issues/248

**Comment by fkorotkov** [comment]
@jmagman I think we figured out what was happening and why this particular worker got into a weird state. There were VMs left on the Mac host and new tasks were starting new VMs but were SSHing into the old ones and therefore reusing it. It should be fix from happening.

**Comment by jmagman** [comment]
@fkorotkov Thanks for the investigation and fix!

@cyanglaz Sounds like this shouldn't be happening anymore.  If you want to merge this to workaround any future versions of this problem, feel free.  Though if it happens again there may be more subtle manifestations of state leaking between tasks.  Whatever you prefer.

**Comment by cyanglaz** [comment]
@jmagman @fkorotkov Re-joining the party late. Thanks for the help!! I'm going to close the PR. I'd prefer it to surface if a similar problem happens next time. (The mitigation isn't too bad, we can add it next time if we want to unblock the tree)

**Pull request closed without merging**
