### PR TITLE
[camera] - Fix bug - app crashes on iOS 9

### PR DESCRIPTION
**Pull request by gisdatasrl**
Enclosed **AVCaptureDeviceDiscoverySession** in a @availabe check and managed older versions with the older versions with the older api

Fixes flutter/flutter#20708

### CODE REVIEW

**Comment by gisdatasrl** [comment]
I signed it!

**Comment by hariprasadiit** [comment]
this won't work as the changes are not handling other `iOS 10+` only  like `AVCapturePhotoOutput`

**Comment by hariprasadiit** [comment]
this won't work as the changes are not handling other `iOS 10+` only  like `AVCapturePhotoOutput`

**Comment by Hixie** [comment]
I'm going through some old PRs to see what we can do with them. First, sorry for dropping this on the floor, we do appreciate your contributions though apparently we don't do a good job of showing it.

For this PR specifically, I'm going to close it because it is lacking tests and all our PRs need to have tests.

**Pull request closed without merging**
