### PR TITLE
[path_provider] refactor: move Directory if statements to function

### PR DESCRIPTION
**Pull request by devhammed**
## Description

There is too much duplicate if statements, I feel it is better to move it in a standalone private function.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by devhammed** [comment]
@googlebot I signed it!

**Comment by stuartmorgan** [comment]
This refactor definitely makes sense; could you update it for null safety so that it applies to the latest master? If so I can review and land it.

We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

**Comment by devhammed** [comment]
> This refactor definitely makes sense; could you update it for null safety so that it applies to the latest master? If so I can review and land it.
> 
> We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

I just did and also fixed the one for directories, removed duplicate logics.

**Review by stuartmorgan — APPROVED** [review]
Looks good, thanks! It's failing the format check on the bots; if you can make that minor change that would be great, otherwise we can do it as part of getting it checked in.

**Comment by devhammed** [comment]
> Looks good, thanks! It's failing the format check on the bots; if you can make that minor change that would be great, otherwise we can do it as part of getting it checked in.

I just used the `pub global run flutter_plugin_tools format` command suggested in the error message to format the code.

**Comment by stuartmorgan** [comment]
Looks like there were infrastructure issues with one of the tests; re-running to see if it will turn green.

**Comment by devhammed** [comment]
> Looks like there were infrastructure issues with one of the tests; re-running to see if it will turn green.

Yeah, I noticed!

**Comment by stuartmorgan** [comment]
Ah, it's failing due to an FFI breaking change that caused issues for path_provider_windows; that's since been fixed. Could you merge master into this branch and re-push? That should get everything green.

**Comment by devhammed** [comment]
> Ah, it's failing due to an FFI breaking change that caused issues for path_provider_windows; that's since been fixed. Could you merge master into this branch and re-push? That should get everything green.

I wasn't able to merge master into the branch, Git is saying everything is up to date.

**Comment by stuartmorgan** [comment]
Your last merge from master was 12 days ago; there have been a number of commits since then. Make sure you are merging from a freshly synced master (e.g., `fetch upstream; merge upstream/master`), not a local, stale master.

**Comment by devhammed** [comment]
> Your last merge from master was 12 days ago; there have been a number of commits since then. Make sure you are merging from a freshly synced master (e.g., `fetch upstream; merge upstream/master`), not a local, stale master.

I have merged the master but that same test keeps failing and I don't think it has to be with code:

```
ERROR: Unable to execute "gcloud auth activate-service-account --key-file=/home/cirrus/gcloud-service-key.json". Stderr:
```

**Comment by stuartmorgan** [comment]
That's an infra issue; I've restarted the tests. Merging in master was to fix a different error that the previous run had, which was a real error at that version of master.

**Comment by devhammed** [comment]
> That's an infra issue; I've restarted the tests. Merging in master was to fix a different error that the previous run had, which was a real error at that version of master.

The previous run error was actually the same as this, kindly look into it.

**Comment by stuartmorgan** [comment]
I'm investigating why this infra failure is now happening persistently. In the meantime, I can manually land, but I'm afraid the last null-safety migrations collided with the changes here; could you merge in the latest master and resolve the conflicts? Once you do, I'll manually land it.

Sorry for the collision; unfortunately getting path_provider migrated was high priority.

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
You've conflated methods that return non-nullable values and throw on error with those that return nullable values. The differences there are intentional.

That's why the PR is failing analyze and the unit tests.

**Comment by stuartmorgan** [comment]
Are you still planning on updating this to correctly account for the null safety changes?

**Comment by devhammed** [comment]
> Are you still planning on updating this to correctly account for the null safety changes?

I have been busy with work these days, I should be able to look into it by Sunday.

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
