### PR TITLE
[video_player] Added new field observeAppLifecycle to enable background playing of v…

### PR DESCRIPTION
**Pull request by Yogeshk25**
…ideo

## Description

This PR introduces a new option to VideoPlayerOptions, which enables user to decide on whether user wants to keep playing video in the background or not. 
This is a much requested feature, in many issues.

## Related Issues

63836 - https://github.com/flutter/flutter/issues/63836
63735 - https://github.com/flutter/flutter/issues/63735
55673 - https://github.com/flutter/flutter/issues/55673
48008 - https://github.com/flutter/flutter/issues/48008
40722 - https://github.com/flutter/flutter/issues/40722
32571 - https://github.com/flutter/flutter/issues/32571

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Yogeshk25** [comment]
@googlebot I signed it!

**Comment by cyanglaz** [comment]
I'm going to close the PR because the CLA is not signed. Feel free to ping me when the CLA is signed and I'll re-open the PR. Or you can open a new PR after signing the CLA.

**Comment by dvasea1** [comment]
@Yogeshk25 how to import this in my project?

**Comment by Yogeshk25** [comment]
@dvasea1 until this is merged, you can use, following to use functionality,

```
  video_player:
    git:
      url: https://github.com/Yogeshk25/plugins.git
      path: packages/video_player/video_player
```

**Comment by IlyaMax** [comment]
@yogeshk25 why can't you just sign it? 

> If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA (login here to double check)

**Pull request closed without merging**
