### PR TITLE
[video_player] add support for content-uri based videos (android only)

### PR DESCRIPTION
**Pull request by byunme**
*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

This PR adds playback from contentUri support for the video_player plugin (Android only).

The current Android implementation uses ExoPlayer, which already supports playback from uri, so this change is just to surface contentUri as a valid video datasource on the dart side.

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/88130

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@byunme Are you planning on splitting this into the component PRs now so that we can move forward with landing this?

**Comment by byunme** [comment]
@stuartmorgan Sorry for the delay, I've split off the interface part here: https://github.com/flutter/plugins/pull/4307

**Comment by jmagman** [comment]
This needs to be merged ASAP to unblock the framework tree.  https://github.com/flutter/plugins/pull/4307

I don't have permissions to push to this branch, taking it to https://github.com/flutter/plugins/pull/4330

**Comment by jmagman** [comment]
Obsolesced by https://github.com/flutter/plugins/pull/4330.

Thanks for the contribution, @byunme, sorry I had to split the PR out to reopen the submit queues ASAP.

**Pull request closed without merging**
