### PR TITLE
Remove dependencies on 'meta'

### PR DESCRIPTION
**Pull request by stuartmorgan**
Flutter re-exports everything from meta that we actually use, and all plugins by definition require Flutter, so there's no need to use `meta` instead of Flutter to access common annotations (e.g., immutable, visibleForTesting).

This removes all use of `meta`, as well as dependencies on the package, from all plugins.

Fixes https://github.com/flutter/flutter/issues/95658

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by Hixie** [comment]
We actually do have a test for this in the flutter/flutter repo, FWIW. It just reads every Dart file and checks for the banned imports.

test-exempt: code refactor with no semantic change

**Comment by stuartmorgan** [comment]
> We actually do have a test for this in the flutter/flutter repo, FWIW. It just reads every Dart file and checks for the banned imports.

I had considered this, but presumably there could be cases where we'd want to use something from `meta` that Flutter doesn't happen to re-export, so an outright ban didn't seem like the right behavior. (I guess in theory we could make it a complicated check that only allowed `import 'meta/meta.dart' show <things not in a list of banned items>`...)

**Comment by Hixie** [comment]
We could also just require that anything we want to use has to be re-exported from foundation. But I don't feel strongly about this either way.

**Comment by ditman** [comment]
I wish this could be done with:

```yaml
meta:
  sdk: flutter
```

That way we don't have to remember the random place from which the framework reexports the meta pkg :/

**Review by bparrishMines — APPROVED** [review]
LGTM once pubspecs and CHANGELOGs are updated

**Comment by Hixie** [comment]
> That way we don't have to remember the random place from which the framework reexports the meta pkg :/

It's not really that random, it's the foundation package of the core framework. :-)

**Review by cyanglaz — APPROVED** [review]
LGTM

**Pull request merged**
