### PR TITLE
[webview_flutter] Added Geolocation support

### PR DESCRIPTION
**Pull request by Immortalin**
## Description
Enables Webview Geolocation support on Android devices. Currently lacking documentation and Geolocation Database is not enabled (FlutterWebView.java, Line 124)

User has to set relevant permissions (on Android it's ACCESS_FINE_LOCATION. or ACCESS_COARSE_LOCATION)

## Related Issues
Related: https://github.com/flutter/flutter/issues/30582#issuecomment-480517336
## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.
- [x] I read and followed the [Flutter Style Guide].
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] I updated/added relevant documentation (doc comments with `///`).

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.
- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Immortalin** [comment]
I signed it!

**Comment by Immortalin** [comment]
Test drive with:
```dart
Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text(widget.title),
        ),
        body: Center(
            // Center is a layout widget. It takes a single child and positions it
            // in the middle of the parent.
            child: WebView(
          initialUrl: "https://leafletjs.com/examples/mobile/example.html",
          javascriptMode: JavascriptMode.unrestricted,
          geolocationMode: GeolocationMode.enabled,
        )),
        floatingActionButton: FloatingActionButton(
          onPressed: () {},
          tooltip: 'Get Current Location',
          child: Icon(Icons.location_on),
        ));
```

**Comment by Immortalin** [comment]
@amirh the permissions prompt does not really work right now. Geolocation works if location has already been enabled.

**Comment by Immortalin** [comment]
@amirh?

**Comment by wghirakawa** [comment]
Any update on this?

**Comment by Immortalin** [comment]
Dunno, ask @amirh

**Comment by TheSunilVarma** [comment]
i have done the changes in these both files but still webview is not getting location and yes i am handling the user location permission on startup of my app so not permission issuse.. can you help me out to achieve this.

(Note : i think _WebSettings is now WebSettings in another file so i made changes accordingly)

Thanks in advance

**Comment by TheSunilVarma** [comment]
> Are you sure you are using the edited copy of the library? Add a printline somewhere and see if you can see it in logs.


Thanks For Your Quick Reply : Yes, i am sure i am using the modified one because i can see the modified file in flutter debuging Tool..

Can You Please have look at my file and help me to achieve it Thanks again !

i am attaching my Files maybe i have done something wrong.
[ModifiedWebviewFiles.zip](https://github.com/flutter/plugins/files/4055117/ModifiedWebviewFiles.zip)

**Comment by tlueder** [comment]
I don't think it is a good idea to use the webview geolocation api. You get these Browser alert dialogs with limited influence on what to show in there. And it just looks strange.
A better way is to make use of flutters geolocator plugin.

I've created a widget that takes care of all that.
And a demo project that works on Android and iOS

https://github.com/tlueder/flutter_example_webview_geolocator

**Comment by TheSunilVarma** [comment]
> I don't think it is a good idea to use the webview geolocation api. You get these Browser alert dialogs with limited influence on what to show in there. And it just looks strange.
> A better way is to make use of flutters geolocator plugin.
> 
> I've created a widget that takes care of all that.
> And a demo project that works on Android and iOS
> 
> https://github.com/tlueder/flutter_example_webview_geolocator

@tlueder actually i don't need user location, but i wanted to give access to Ola or Zomato like Website. ( I am handling user Permission by permission_handler plugin ) but but still webview_flutter is not able to get Location...

If i am wrong please correct me and guide me to achieve this... 
( I want website can able to get user location in webview )  
cc @Immortalin

**Comment by tlueder** [comment]
@TheSunilVarma 

I'm note sure if I understand you.

But my widget overwrites the JS Geo API inside the Webview and lets a website use the GPS data from the geolocator plugin. For the loaded website it makes no difference.

But this way you don't need to patch the webview plugin and the webview will never show the alert dialog "This webpage is trying to access your location ...."

Just checkout the demo project and build the app. 
This widget I'm talking about is this:
https://github.com/tlueder/flutter_example_webview_geolocator/blob/master/lib/widget/webview_geolocator.dart

**Comment by TheSunilVarma** [comment]
I have checked the Example app saidly i am not looking for this.. but thanks @tlueder for your reply.

**Comment by TheSunilVarma** [comment]
> @TheSunilVarma
> 
> I'm note sure if I understand you.
> 
> But my widget overwrites the JS Geo API inside the Webview and lets a website use the GPS data from the geolocator plugin. For the loaded website it makes no difference.
> 
> But this way you don't need to patch the webview plugin and the webview will never show the alert dialog "This webpage is trying to access your location ...."
> 
> Just checkout the demo project and build the app.
> This widget I'm talking about is this:
> https://github.com/tlueder/flutter_example_webview_geolocator/blob/master/lib/widget/webview_geolocator.dart

Hey @tlueder .
Good New This what i was looking For 👍  Thank You .
BUT
Sorry to say but this Plugin is very buggy but i am willing to help or Test if you needed any help from my side.

**Bug Summary**
1. Works Mostly Only First Time Opening Website.
2. Crashes When Opened and disabled the GPS and closing and opening the app Again.
3.works on if GPS disabled (but enabled by default at battery saving mode permission)and opeing the app and website have Google Map via Get Currect Location dot button.

Detailed Video of Bugs is here : https://bit.ly/38dP49E

I have also tried by giving more permission like.( needless to try this but i did 🤓 )
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

Looking Forward to your Reply.

**Comment by TheSunilVarma** [comment]
> > @TheSunilVarma
> > I'm note sure if I understand you.
> > But my widget overwrites the JS Geo API inside the Webview and lets a website use the GPS data from the geolocator plugin. For the loaded website it makes no difference.
> > But this way you don't need to patch the webview plugin and the webview will never show the alert dialog "This webpage is trying to access your location ...."
> > Just checkout the demo project and build the app.
> > This widget I'm talking about is this:
> > https://github.com/tlueder/flutter_example_webview_geolocator/blob/master/lib/widget/webview_geolocator.dart
> 
> Hey @tlueder .
> Good New This is what i was looking For 👍 Thank You .
> BUT
> Sorry to say but this Plugin is very buggy but i am willing to help or Test if you needed any help from my side.
> 
> **Bug Summary**
> 
> 1. Works Mostly Only First Time Opening Website.
> 2. Crashes When Opened and disabled the GPS and closing and opening the app Again.
>    3.works on if GPS disabled (but enabled by default at battery saving mode permission)and opeing the app and website have Google Map via Get Currect Location dot button.
> 
> Detailed Video of Bugs is here : https://bit.ly/38dP49E
> 
> I have also tried by giving more permission like.( needless to try this but i did 🤓 )
> 
> Looking Forward to your Reply.


** Update **
Working Mostly or always on When ( Disabled GPS From Notification, but have Location Access in Setting at only Batter Saving )

ScreenShots
Screenshot_2020-01-16-21-59-46-956_com android settings
Screenshot_2020-01-16-21-59-50-258_com android settings

**Comment by tlueder** [comment]
@TheSunilVarma 

I'll have a look. I never tried it with disabled GPS, but I think this should be an easy fix.

**Comment by TheSunilVarma** [comment]
> @TheSunilVarma
> 
> I'll have a look. I never tried it with disabled GPS, but I think this should be an easy fix.

👍  All the best... looking forward for your Update, and just wanted to let you know in case to missed it .. the Accuracy of Location ! ( not working at High Accuracy )

**Comment by tlueder** [comment]
@TheSunilVarma please check now.

The geolocator plugin has some trouble to return the correct status. 
Status permission granted overwrites deactivated...

**Comment by TheSunilVarma** [comment]
> @TheSunilVarma please check now.
> 
> The geolocator plugin has some trouble to return the correct status.
> Status permission granted overwrites deactivated...


Hello @tlueder !
I have checked your updated ..timeout = parseInt(data['timeout'] ?? 0) edition..
But nothing changed....
And Yes after digging your code i also think there is some issue with geolocator plugin...
**But One Thing**
I have successfuly now able to get location when Location or GPS is turned ON !
But just Switching the value of LocationAccuracy in getCurrentPosition Function...

Before-- 
`position = await geolocator.getCurrentPosition(
          locationPermissionLevel: GeolocationPermission.locationWhenInUse,
            desiredAccuracy: (positionOptions.enableHighAccuracy
                ? LocationAccuracy.best
                : LocationAccuracy.medium));`
Edited-- (Works Fine..)
 `position = await geolocator.getCurrentPosition(
          locationPermissionLevel: GeolocationPermission.locationWhenInUse,
            desiredAccuracy: (positionOptions.enableHighAccuracy
                ? LocationAccuracy.medium
                : LocationAccuracy.best));`

**Remaining Issue**
Something Strange Happening !

See Images : Works on Having Map with Get Location (Dot) button but not works without map View ???
1th and 2th image is of working after clicking on MAP button right side of 3rd Photo...
but does not work after clicking Get Location !.... in image 3rd and 4th.

**Comment by TheSunilVarma** [comment]
> @TheSunilVarma please check now.
> 
> The geolocator plugin has some trouble to return the correct status.
> Status permission granted overwrites deactivated...

Had One Question... is the value of positionOptions.enableHighAccuracy is ever changing from FALSE ? i am not able see changes in value of positionOptions.enableHighAccuracy.

**Comment by Immortalin** [comment]
@tlueder thanks for handling this issue. Much appreciated 👍.

**Comment by Immortalin** [comment]
@TheSunilVarma my changes were made after ensuring that geolocation works outside of the browser using only Flutter. Once you get that working then everything else should automatically work.

**Comment by TheSunilVarma** [comment]
> @TheSunilVarma my changes were made after ensuring that geolocation works outside of the browser using only Flutter. Once you get that working then everything else should automatically work.

@Immortalin sorry but i'm not getting how it will work,
For Example If i have Location with the help of some other Plugin and now how webview will get the location from it without any reference or how it get data from it ?

A Working Example of Demo App may be helpful if possible.

**Comment by Immortalin** [comment]
You miss the point. I am simply saying that you need to ensure geolocation works perfectly in normal flutter, before attempting to debug why the browser pull request does not work. For now, just go with @tlueder's suggestions.

**Comment by TheSunilVarma** [comment]
> You miss the point. I am simply saying that you need to ensure geolocation works perfectly in normal flutter, before attempting to debug why the browser-specific pull request does not work. For now, just go with @tlueder's suggestions.

👍

**Comment by ycv005** [comment]
This advance webview plugin - https://pub.dev/packages/flutter_inappwebview has the feature of the geo location in-built. You could use its' `androidOnGeolocationPermissionsShowPrompt` property to enable it. Implementation- https://github.com/pichillilorenzo/flutter_inappwebview/issues/491#issuecomment-675668165

**Comment by cyanglaz** [comment]
I'm going to close the PR because the CLA is not signed. Feel free to ping me when the CLA is signed and I'll re-open the PR. Or you can open a new PR after signing the CLA.

**Pull request closed without merging**
