### PR TITLE
[local_auth] Convert Windows to Pigeon

### PR DESCRIPTION
**Pull request by stuartmorgan**
Updates `local_auth_windows` to use Pigeon, and moves to a more platform-tailored and Dart-centric implementation (rather than keeping the previous cross-platform method channel interface that the current implementation was duplicated from):
- Eliminates `deviceSupportsBiometrics` from the platform interface, since it's always the same as `isDeviceSupported`, in favor of doing that mapping in Dart.
- Eliminates `getEnrolledBiometrics` from the platform interface, since it was the same implementation as `isDeviceSupported` just with a different return value, in favor of doing that logic in Dart.
- Moves throwing for the `biometricOnly` option to the Dart side, simplifying the native logic.

Related changes:
- Adds a significant amount of previously-missing Dart unit test coverage.
- Removes the `biometricOnly` UI from the example app, since it will always fail.

Part of https://github.com/flutter/flutter/issues/117912

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@azchohfi If you could test this on supported hardware to make sure I didn't accidentally break anything there, that would be great; I don't have any so the only end-to-end manual test I could do was of no support.

**Comment by azchohfi** [comment]
@stuartmorgan absolutely! Any Surface device should support Windows Hello, so I can test this quite easily, as I have one. Also, I've checked the source changes and LGTM. I'll just test it and approve.

**Comment by azchohfi** [comment]
Working perfectly fine on my Windows 11 Lenovo with Windows Hello (PIN only). Call paths are exactly the same for biometric/non-biometric, so LGTM.

**Review by azchohfi — APPROVED** [review]

**Comment by azchohfi** [comment]
Also, I'm assuming this is not a breaking change, since API surface and behavior is the same, right?

**Comment by stuartmorgan** [comment]
> Working perfectly fine on my Windows 11 Lenovo with Windows Hello (PIN only).

Great, thanks for testing!

> Also, I'm assuming this is not a breaking change, since API surface and behavior is the same, right?

It's a grey area, because I changed `biometricOnly` from being a `PlatformException` to the more accurate `UnsupportedError`. That could break someone who was relying in that specific failure behavior, but in this case that seemed very unlikely since it *never* works so I opted not to consider it breaking. (For cases where we expect real-world code to be dealing with specific exceptions at runtime, we generally would.)

**Review by cbracken — APPROVED** [review]
lgtm!

**Comment by stuartmorgan** [comment]
Landing manually to re-open the tree, which is stuck red due to https://github.com/flutter/flutter/issues/116226

**Pull request merged**
