### PR TITLE
[camera] Ignore body_might_complete_normally_catch_error violation

### PR DESCRIPTION
**Pull request by srawlins**
Ignore body_might_complete_normally_catch_error violations

Related to https://github.com/flutter/flutter/issues/105750

No version change: Ignoring lints does not affect plugin clients.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
](https://github.com/srawlins/plugins/pull/new/ignore-catch-error-2)

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@srawlins Could you update the PR description to be something other than the default placeholder?

I've added the notation to suppress `publishable`'s error; you'll need to push a new commit to get it to re-run.

**Comment by srawlins** [comment]
Sorry about that; fixed description.

**Review by stuartmorgan — APPROVED** [review]
LGTM once you push another commit (e.g., a merge from `main`) to get `publishable` passing.

**Comment by srawlins** [comment]
sweet, done

**Comment by stuartmorgan** [comment]
Oh, I missed that this needs two reviews. @camsim99 or @hellohuanlin could you give this a quick look?

**Pull request merged**
