### PR TITLE
FirebaseStorage getData function

### PR DESCRIPTION
**Pull request by aler**
Create a new PR to resolve original PR #207 CLA problems. Added some doc comments as well.

### CODE REVIEW

**Comment by mit-mit** [comment]
@goderbauer can you review, please?

**Comment by sethladd** [comment]
cc @kroikie who can also help with review

**Comment by goderbauer** [comment]
This looks fine to me. Would be cool if you could add an example usage of the new API to the example app in the `example` directory.

@collinjackson Maybe you can take a quick look as well. As the original author of this plugin you're more familiar with the storage API.

**Comment by collinjackson** [comment]
Please bump the version and add a changelog entry so we can publish this after you merge it. If you don't want to write a test (since this plugin has no tests yet), adding to the example app as @goderbauer suggested would be fine. Thank you!

**Comment by goderbauer** [comment]
I tried to `pub publish` the new version, but currently pub seems to be rejecting all package updates. I'll try again in a little bit.

**Comment by goderbauer** [comment]
It's live: https://pub.dartlang.org/packages/firebase_storage

**Comment by sethladd** [comment]
Thanks!

**Pull request merged**
