### PR TITLE
Enforce asterisk alignment for C++ and ObjC pointers

### PR DESCRIPTION
**Pull request by stuartmorgan**
So far we've been using the default mode of prevailing-in-file, which
means we aren't consistent within each language what mode we use. Now
that clang-format can identify ObjC headers (which didn't used to be the
case), we can enforce different styles for the two languages.

This sets left-aligned for C++ to match the Flutter engine, and
right-aligned for ObjC to match the prevaling Apple style.

No version change: automated whitespace-only change with no actual effect on clients.

No CHANGELOG change: uninteresting mechanical change.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@jmagman A lot more code here was using left-aligned than I expected. I assumed we'd want to follow Apple's usual style, but we could also use left-aligned for everything (or as I like to think of it "correct" 😁 ); I leave it entirely up to you.

**Comment by gaaclarke** [comment]
FWIW the google style guides for objc and c++ are agnostic to the placement of the asterisks.

**Comment by stuartmorgan** [comment]
> FWIW the google style guides for objc and c++ are agnostic to the placement of the asterisks.

Google style is agnostic, but I've never been on a team that doesn't have a team-level convention for this in order to have local consistency.

**Comment by gaaclarke** [comment]
sgtm, whatever you all want to do.  I renamed the PR since it sounded very scary, potentially having to do with memory alignment instead of code formatting =)

**Comment by stuartmorgan** [comment]
🤷🏻 "pointer alignment" is the name of the clang-format setting.

**Comment by gaaclarke** [comment]
In the context of formatting code "pointer alignment" makes sense in the context of making changes to a codebase it is ambiguous and scary.  I imaging someone investigating a mysterious crash and that PR title jumping out at them.

**Review by jmagman — APPROVED** [review]
> @jmagman A lot more ObjC code here was using left-aligned than I expected. I assumed we'd want to follow Apple's usual style, but we could also use left-aligned for everything (or as I like to think of it "correct" 😁 ); I leave it entirely up to you.

Let's keep right-alignment to match the Apple style.  As long as it's consistent, and better if a formatter can fix it for me, I can live with either.

LGTM

**Pull request merged**
