### PR TITLE
[in_app_purchase] update gradle tool to 4.1.0

### PR DESCRIPTION
**Pull request by cyanglaz**
The gradle and gradle tool version have been upgraded in in_app_purchase_android https://github.com/flutter/plugins/commit/e83a6833c98f13009c73cb19cc5da5e85dbb130f, which caused a version mismatch in the in_app_purchase plugin

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by stuartmorgan** [comment]
If this mismatch is only an issue for this Android-specific test, wouldn't the better fix be to move the test into the Android plugin?

**Comment by cyanglaz** [comment]
@stuartmorgan there are actually no tests in `in_app_purchase`, the tests that are failing are in `in_app_purchase_android`.
I'm actually not sure why java tests in `in_app_purchase_android` would be executed with `in_app_purchase/example`

I'm trying to figure it out now. @blasten might know.

**Comment by stuartmorgan** [comment]
Do we have a weird configuration left over from https://github.com/flutter/flutter/issues/81695 maybe?

**Comment by cyanglaz** [comment]
I couldn't find anything that's suspicious. Seems like `./gradlew test` tries to build test files in a dependency (in_app_purchase_android)

**Review by stuartmorgan — APPROVED** [review]
Okay, LGTM to fix the tree then. Could you file a bug about this though? We don't want to be running all of our Android unit test twice as we federate more of the plugins.

**Comment by cyanglaz** [comment]
@stuartmorgan Sure
I think there might be a worse issue regarding this tho. If our example app's ./gradlew test can fail because it uses a lower gradle version, any flutter app that uses in_app_purhcase_android would potentially face the same thing when they run ./gradlew test.

**Comment by blasten** [comment]
The Gradle version set in a plugin only matters if you are running the plugin's java tests. 

When an app is built, only one Gradle version is used (the one set by the app). (The analogy I find is, it'd would be like using two or more different Dart SDK versions to build a single app).

**Comment by stuartmorgan** [comment]
@blasten But why is the app-facing package's example app building the tests from the Android implementation package?

**Comment by stuartmorgan** [comment]
I didn't see the issue link before posting, we can continue the discussion there.

**Pull request merged**
