### PR TITLE
[in_app_purchase]: Add macOS Support

### PR DESCRIPTION
**Pull request by Ahmadre**
At first: Many thanks goes out to the every Flutter Dev and the Flutter Team for all plugins that exists. They help me as a professional Software Engineer in Germany to release for all desired platforms for our customers. So thank you guys ❤️ and don't forget to take a break!

I encountered that macOS Support doesn't exist yet for in_app_purchase plugin. Then I followed a drafted PR here and saw a lot of things that were forgotten and furthermore that PR was already outdated on the codebase. 

I did some research and catched the SwiftyStoreKit plugin at the first step. After that I saw that these are not necessary at all and the existing iOS implementation is a perfect fit here to just add symbolic links to them and prepare the codebase in objective-c for macOS platforms. 

Some interfaces should be hidden for macOS and are just iOS specific (IPHONEOS), so that helped for the macOS implementation to just function like it should on macOS Desktops.

While migrating the existing iOS Code I encountered also that some implementations to interfaces where forgotten to check on the iOS 14 respectively iOS 13.4.

The most important checks were here:

```objective-c
- (void)presentCodeRedemptionSheet
``` 

and

```objective-c
- (void)showPriceConsentIfNeeded
```

After migrating the codebase in Dart, Objective-C and the Tests, everything worked like a charm.

Here's an example from a production app in Debug:

<details>

### Buy
Bildschirmfoto 2021-09-05 um 16 33 48

### Check Purchase
Bildschirmfoto 2021-09-05 um 16 34 04

Bildschirmfoto 2021-09-05 um 16 34 15

### Completion
Bildschirmfoto 2021-09-05 um 16 34 21

### Backend Apple Handler
Bildschirmfoto 2021-09-05 um 16 32 00

</details>

## Related Issues

- https://github.com/flutter/flutter/issues/89507 (which is a duplicate of: https://github.com/flutter/flutter/issues/84391 )

### Test results:

```bash
❯ flutter test
00:09 +51: All tests passed!
```

### Build (pub run build)

```bash
❯ flutter packages pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 326ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 9.3s

[INFO] There was output on stdout while compiling the build script snapshot, run with `--verbose` to see it (you will need to run a `clean` first to re-snapshot).

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 662ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Deleting 5 declared outputs which already existed on disk.
[INFO] Checking for unexpected pre-existing outputs. completed, took 4ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 2.9s elapsed, 0/16 actions completed.
[INFO] Generating SDK summary completed, took 2.8s

[INFO] 4.0s elapsed, 24/29 actions completed.
[INFO] 5.1s elapsed, 25/29 actions completed.
[INFO] 10.8s elapsed, 25/29 actions completed.
[INFO] Running build completed, took 11.1s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 44ms

[INFO] Succeeded after 11.2s with 10 outputs (63 actions)
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by Ahmadre** [comment]
@googlebot I fixed it.

**Comment by rebarah** [comment]
@googlebot I fixed it.

**Comment by rebarah** [comment]
@googlebot I consent.

**Comment by Ahmadre** [comment]
@googlebot I consent.

**Comment by Ahmadre** [comment]
To all reviewers: This is not yet publishable, because there isn't a published `in_app_purchase_macos` and I assume that some of you guys are doing that. So this has to be changed in the `in_app_purchase/in_app_purchase`:

```yaml
in_app_purchase_macos:
    path: ../in_app_purchase_macos/
```

**Comment by stuartmorgan** [comment]
Thanks for the submission, but unfortunately the approach you've taken here won't work; you cannot symlink outside of the package boundary. This will work within the context of the flutter/plugins tree, but the published version would be unusable. Symlinking requires sharing a package, which is why I discuss the need to rename `in_app_purchase_ios` in the draft PR you mentioned. I'm going to mark this as a draft, and if you are interested in re-working this as described in the other PR you can remove the draft label once it's ready. Alternately, if you find it easier to close this and open a new PR with that approach feel free to do it that way.

> This is not yet publishable, because there isn't a published `in_app_purchase_macos` and I assume that some of you guys are doing that.

Please read https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins (linked from the contrbution guide.)

**Comment by Ahmadre** [comment]
> https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins

You're totally right! I forgot that case 😅 

I will copy the source files, remove the sym-links, test it again with my app and push everything again.

Thanks for the hint ✌🏼

**Comment by Ahmadre** [comment]
I also removed now a lot of unnecessary iOS interfaces. So thanks @stuartmorgan for making me aware again :)

**Comment by Ahmadre** [comment]
@stuartmorgan 

As mentioned I removed now iOS specific apis & interfaces on the dart and objective-c side. 

I also removed the tests that depends on iOS. 

It works now like before and I tested it locally. 

I would be grateful if you can review it.

Thanks :)

**Comment by stuartmorgan** [comment]
> I will copy the source files, remove the sym-links

This is not at all what I was suggesting. Apologies for not being clearer; I assumed from your PR description that you had read the discussion in the other PR, in particular https://github.com/flutter/plugins/pull/2708#issuecomment-859224033

We do not want to maintain two copies of this code. Having macOS and iOS share a package and implementation—under a new name—is the approach we would accept within this repository.

**Comment by stuartmorgan** [comment]
> How am I going to "export" like it's explained here:

Can you elaborate on what the question is? I'm not sure what specifically the issue you're encountering is.

**Comment by Ahmadre** [comment]
> > How am I going to "export" like it's explained here:
> 
> Can you elaborate on what the question is? I'm not sure what specifically the issue you're encountering is.

Bildschirmfoto 2021-09-06 um 04 24 24

I mean like here in the main `in_app_purchase` plugin: Its it correct to also provide `in_app_purchase_ios` as a dependency? Is this what you mean wiht `export`?

**Comment by stuartmorgan** [comment]
I mean the Dart keyword `export`. There is user code that directly imports and uses `in_app_purchase_ios` as part of using `in_app_purchase`, and it must continue to work exactly as-is or the rename becomes a breaking change.

**Comment by stuartmorgan** [comment]
Since this is marked as a draft and hasn't been touched in a few months I'm going to close it to clean out our review queue. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

If you (or someone else) decides to revisit this, based on recent experience with moving plugin implementations the best way to proceed would be:
1) An initial PR to move (not copy) all the files from the `_ios` version to the `_storekit` version (with necessary minor changes, such as the podspec name), changing `_ios` to export. That would need to make all referencing packages temporarily use path-based references, and make those packages as temporarily unpublishable. See https://github.com/flutter/plugins/pull/4465 for an example of this
2) A follow-up PR to restore the referencing packages to normal references and publishable state
3) A PR to add macOS support to the `_storekit` package.

That avoids the problem of having a giant set of file copies, which makes review extremely difficult and destroys git blame.

**Pull request closed without merging**
