### PR TITLE
[camera] Don't mirror the picture taken from front facing lens

### PR DESCRIPTION
**Pull request by Perfetto2020**
The picture taken from the front camera is mirrored as described in [#27650](https://github.com/flutter/flutter/issues/27650) This change will fix it.

Fixes [#27650](https://github.com/flutter/flutter/issues/27650)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by Perfetto2020** [comment]
@googlebot I signed it!

**Comment by stuartmorgan** [comment]
Thanks for the submission! We’re currently working through a large backlog of PRs, and this will require non-trivial review, so it will take some time before we’re able to review it. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are the primary way we’re prioritizing non-trivial reviews, so we encourage anyone interested in this PR to vote for the corresponding issue.

**Comment by nt4f04uNd** [comment]
@Perfetto2020 this should be a tweakable parameter, if you look closesly at the issue you linked this is what its author requesting for

**Comment by Perfetto2020** [comment]
> @Perfetto2020 this should be a tweakable parameter, if you look closesly at the issue you linked this is what its author requesting for

cannot agree more. make it opt-in later.

**Comment by tjcampanella** [comment]
Any status on this?

**Comment by iqtedar123** [comment]
Would love this! :)

**Comment by Zazo032** [comment]
@Perfetto2020 could you fix the conflicts, please?

**Comment by stuartmorgan** [comment]
Per discussion in https://github.com/flutter/plugins/pull/4420, it's not clear that this is the approach we want to take. (And we should certainly be consistent between iOS and Android about how we handle mirroring.)

It's also not clear to me from the diff what exactly the effect of this PR is. Are you completely disabling mirroring, including for the preview?

**Pull request closed without merging**
