### PR TITLE
Switch `ios_platform_tests` from Cirrus to LUCI

### PR DESCRIPTION
**Pull request by keyonghan**
Follow up of https://github.com/flutter/plugins/pull/6682 to switch `ios_platform_tests` from Cirrus to LUCI completely.

These tasks are running green consistently:
Screen Shot 2022-11-21 at 10 27 42 AM

Part of https://github.com/flutter/flutter/issues/114373

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
LGTM!

Could you do a quick change to mirror the recent changes you've made to the plugins recipe (script arguments, sharding env variable, etc.) to the packages repo recipe? I'm actively working on synchronizing the flutter/plugins and flutter/packages CI in preparation for the repo merge, and realized that I can't spin up these new LUCI tests there without recipe changes.

**Comment by keyonghan** [comment]
> LGTM!
> 
> Could you do a quick change to mirror the recent changes you've made to the plugins recipe (script arguments, sharding env variable, etc.) to the packages repo recipe? I'm actively working on synchronizing the flutter/plugins and flutter/packages CI in preparation for the repo merge, and realized that I can't spin up these new LUCI tests there without recipe changes.

Sure. Script args support: https://flutter-review.git.corp.google.com/c/recipes/+/36541.
As `sharding env` is handled in modules, packages recipe picks it up naturally and no more action is needed here.

**Comment by keyonghan** [comment]
Seems the tree is closed. Is there a bug tracking it? Let me know if you need a bug to track /cc @stuartmorgan

**Comment by stuartmorgan** [comment]
Looks like it's open now; there may have been a doesn't failure.

**Pull request merged**
