### PR TITLE
Update VideoPlayer widget when the attached controller changes

### PR DESCRIPTION
**Pull request by nichtverstehen**
This fixes a bug introduced in https://github.com/flutter/plugins/pull/767: if a State is attached to a new widget it never switched to the new controller.

Also this change makes sure to remove listeners during deinitialization.

### CODE REVIEW

**Comment by nichtverstehen** [comment]
Also added tests for both conditions.

**Comment by nichtverstehen** [comment]
You mean, keep `_isDisposed`, `package`, `timer` members writable?

**Comment by sigurdm** [comment]
Yes.
You can also just mark this as a breaking update - I just worry that people with a dependency on ^0.6 would end up with 0.6.5 that is broken.

**Comment by nichtverstehen** [comment]
Updated the changes.

There are two commits: the first one fixes the bug, the second one changes the interface and introduces the test. I put a minor version bump in the bugfix change (to 0.6.6) and bumped the major version number to 0.7.0 in the second CL (the test + the breaking API change aiding with the test).

What do you think?

**Comment by nichtverstehen** [comment]
(Update the CHANGELOG too)

**Comment by sigurdm** [comment]
The commits LGTM, but I can only land a squashed commit, so it has to be two PRs :(.

**Comment by sigurdm** [comment]
I am going on weekend now. So if you need to land this urgent you need to find another reviewer.

**Comment by cbenhagen** [comment]
The currently published video_player is broken. It would be nice if this could be merged as soon as possible. @sigurdm are you back from the weekend?

**Comment by sigurdm** [comment]
I published a new version on pub

**Comment by sigurdm** [comment]
I haven't made the split, just published the full thing. Let's hope that's good enough.

**Pull request merged**
