### PR TITLE
[google_maps_flutter] fix camera update LatLngBounds.builder 

### PR DESCRIPTION
**Pull request by everton-e26**
## Description

In camera update call LatLngBounds does not correctly calculate the center of the coordinates, to fix it I used LatLngBounds.Builder as I described at https://github.com/flutter/flutter/issues/25298#issuecomment-525862013

## Related Issues

flutter/flutter#25298

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by everton-e26** [comment]
@googlebot I signed it!

**Comment by cyanglaz** [comment]
Thanks for opening this PR. Can we add an e2e test that fails on the original code and pass on the new code?

**Comment by ditman** [comment]
_This PR is compatible with the upcoming [google_maps_flutter federation PR](https://github.com/flutter/plugins/pull/2674)._

**Comment by everton-e26** [comment]
> Thanks for opening this PR. Can we add an e2e test that fails on the original code and pass on the new code?

Sorry but I can't implement this tests right now

**Comment by cyanglaz** [comment]
@everton-e26 Friendly ping :) Do you think you can work on the tests?

**Review by MuBirhan — APPROVED** [review]

**Comment by cyanglaz** [comment]
@everton-e26 Pinging again :) Do you still plan to work on this?

**Comment by stuartmorgan** [comment]
Closing due to inactivity. If you're interested in working on this again, please let us know and we can re-open it.

**Pull request closed without merging**
