### PR TITLE
[video_player] Add speed adjustment support for Android

### PR DESCRIPTION
**Pull request by sfanxiang**
Android implementation for flutter/flutter#16624.

### CODE REVIEW

**Comment by ened** [comment]
@sfanxiang nice PR! Could you work on the formatting issues that prevent the PR from going green?

**Comment by sfanxiang** [comment]
Turns out fd8ad8adb59d53edf9ad73f30e5abd1d763a002b did the formatting, and 3f8abcf627e27af3ed2143f6362e7e85fbb3b55f bumped ExoPlayer to 2.9.1, so I rebased this patch.

Now CI complains:
> \> Could not find com.google.android.exoplayer:exoplayer-core:2.9.1.

**Comment by amirh** [comment]
Note for reviewer: https://github.com/flutter/plugins/pull/1400 seems to be doing the same.

**Comment by cbenhagen** [comment]
@sfanxiang thank you for your contribution! Unfortunately the structure of the plugin has changed lately to support implementations on more platforms. Mainly the plugin was moved to a new subdirectory and now uses a common platform interface. Adapting your PR to the new structure should be straight forward. If you have questions please ask!

Please also make sure to include tests for the new functionality. It would also be great to add this to the iOS and web parts of the plugin.

**Comment by cbenhagen** [comment]
Actually I think this could be closed in favor of https://github.com/flutter/plugins/pull/1400 which also includes the iOS part.

**Comment by sfanxiang** [comment]
@cbenhagen Feel free to close this if you believe #1400 is more helpful.

**Comment by cbenhagen** [comment]
I can not close it. But if you think your Android implementation is better then the one in #1400, you could also comment there to improve it. I know your PR was first. But in the end the only thing that counts is to have the best implementation with the most complete tests and documentation no?

**Comment by ditman** [comment]
Published [video_player v0.11.0](https://pub.dev/packages/video_player/changelog), which contains the playback speed feature!

**Pull request closed without merging**
