### PR TITLE
[url_launcher] fix noop toString() diagnostics

### PR DESCRIPTION
**Pull request by pq**
Fix diagnostics that will get flagged in the next Dart SDK roll.

See breakage:

https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket/8806923775196938257/+/u/flutter_test_flutter_plugins/stdout

Source Linter DEP bump: https://dart-review.googlesource.com/c/sdk/+/253501

/cc @a14n @srawlins 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

**Comment by pq** [comment]
@goderbauer: could you advise about the version check failure reported by the "publishable" bot?

**Comment by goderbauer** [comment]
Th exceptions to requiring a new version are listed here: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version. I think this PR qualifies for the following exception:

> PRs that only affect local development (e.g., changes to ignored lints).

I added the exception label and restarted the check.

**Comment by pq** [comment]
I think for the same reason, we don't need a changelog.  (Tag added.)

**Comment by stuartmorgan** [comment]
> Th exceptions to requiring a new version are listed here: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version. I think this PR qualifies for the following exception:
> 
> > PRs that only affect local development (e.g., changes to ignored lints).
> 
> I added the exception label and restarted the check.

It's not a big deal in this case, but for future reference this did not qualify. This changed actual production code run by clients of the package, and thus should have had a version change, because it could have been wrong. Extremely unlikely here, but possible. "I'm sure this won't break anything" are famously common descriptions of changes that break things 🙂 

That exception is for things like:
```
// ignore: some_lint
```

because that comment does not have *any* impact on the code as run by clients.

**Comment by pq** [comment]
Thanks for chiming in @stuartmorgan!

**Comment by goderbauer** [comment]
Noted!

**Pull request merged**
