### PR TITLE
[google_maps_flutter] Fix circle and polygon stroke width

### PR DESCRIPTION
**Pull request by JamesMcIntosh**
## Description

Stroke width of Polygon and Circles on Android is not independent of the screen density

## Related Issues

flutter/flutter#39476

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [-] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by JamesMcIntosh** [comment]
Hi @iskakaushik, any chance of a review?

**Comment by mklim** [comment]
Thanks again for the contribution. It looks like this PR has been sitting for a little while since the last round of feedback, do you still have time to work on it?

**Comment by JamesMcIntosh** [comment]
Hi @mklim,

Yes I'm happy to build up some tests but I'm not sure that this change a great candidate for Roboelectric testing.

Are you asking for testing specific to this change or general tests on the classes changed outside of the scope of the change?

A unit test on each of the Controller classes could be a candidate to make sure that the density is multiplied against the width, the rest of the classes don't really lend themselves well for testing the density.

Thanks
James

**Comment by mklim** [comment]
> Yes I'm happy to build up some tests but I'm not sure that this change a great candidate for Roboelectric testing.
>
> Are you asking for testing specific to this change or general tests on the classes changed outside of the scope of the change?

Any kind of test that specifically tests the change in this PR would be fine. I was thinking a Java unit test (probably using Robolectric) would be easiest, but if you think another one would be better that's fine with me. Also no need to test anything outside of the scope of this PR. We're trying to test all of our changes going forward but we're not asking for new PRs to backfill the missing test coverage.

> A unit test on each of the Controller classes could be a candidate to make sure that the density is multiplied against the width, the rest of the classes don't really lend themselves well for testing the density.

That sounds reasonable to me. Thank you again for the contribution! Appreciate it.

**Comment by cyanglaz** [comment]
@jamesderlin Are you still able to work on this PR? Just another random thought: we might also be able to add an e2e test for this change.

**Comment by JamesMcIntosh** [comment]
@mklim I've added suitable unit tests across the builders and controllers to check that the density is set when constructing the shapes. Should be ready to go!

**Pull request merged**
