### PR TITLE
[image_picker: iOS] Added AlertViewController to image_picker for iOS 9

### PR DESCRIPTION
**Pull request by MrWinbush**
## Description

The image_picker plugin is using an UIAlertView to prevent a crash when using the camera on simulator. UIAlertView has been deprecated as of iOS target 9.0. This PR adds a revision for iOS 9.0 by adding an AlertViewController.

## Related Issues

https://github.com/flutter/flutter/issues/67831

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by MrWinbush** [comment]
Hey I keep failing the pipeline for formatting issue. The CI isn't giving too much guidance what is causing the formatting/linting issue. Is anyone available for help?

**Comment by MrWinbush** [comment]
@mehmetf I was wondering if I could get some support for this PR? I am not sure why I keep failing the pipeline, and I would like to get some assistance. Who would. be best to contact for this?

**Comment by MrWinbush** [comment]
@cyanglaz Hey Chris, you comment on a PR I had made earlier. I was having issues with the CLA, but had it resolved in this PR. However I am not sure what I am doing incorrectly in this PR. Could I get your help?

**Comment by cyanglaz** [comment]
@MrWinbush Which PR do you mean?

**Comment by MrWinbush** [comment]
@cyanglaz https://github.com/flutter/plugins/pull/3368

**Comment by cyanglaz** [comment]
@MrWinbush Looks like the diff in this PR doesn't reflect the actual change proposed. Did you check in the correct commits?

**Comment by stuartmorgan** [comment]
Closing due to lack of response to the question above about the content of the PR. If you're still interested in contributing a change here, please open a new PR with the correct changes. Thanks!

**Pull request closed without merging**
