### PR TITLE
Make package:e2e a relative reference

### PR DESCRIPTION
**Pull request by dnfield**
Make sure that we pick up the package as it exists in this repo, rather than whatever happens to be published on pub.

This also meant updating some outdated/deprecated references (FlutterRunner -> FlutterTestRunner) in older usages.

/cc @caref @digiter

### CODE REVIEW

**Comment by CareF** [comment]
I'm not sure but will this affect when those packages (not those files in `example`) are used in a user project, where the package is actually in somewhere like `~/.pub-cache/hosted/pub.dartlang.org/e2e-0.6.1/lib/e2e.dart`? In which case, e.g. `~/.pub-cache/hosted/pub.dartlang.org/battery/pubspec.yaml`'s relative path `../../e2e` may not be valid.

**Comment by dnfield** [comment]
Yes, this would mean you cannot run tests in your pub cache, but you shouldn't do that anyway

**Comment by ditman** [comment]
`publishable` is broken because of this issue: https://github.com/flutter/flutter/issues/61747

**Comment by dnfield** [comment]
@cyanglaz - I've re-enabled the test and fixed the issue with `setSurfaceSize` in the e2e binding in this PR.

/cc @CareF who might be interested in that.

**Comment by blasten** [comment]
what about if someone tries to run the example app without forking the repo though?

**Comment by dnfield** [comment]
@blasten - how would they do that (short of trying to run it from their local .pub-cache, which I don't think we should worry about supporting)?

There's no straightforward way of getting _just_ the example app for these projects. And anyone who is willing to do that should be able to just comment out the relative reference to e2e.

The bigger value here is that we'll actually know if a change to e2e is breaking (and/or if it's working as expected).  We'll also have a clearer path to keeping the plugins up to date with the latest e2e stuff rather than reading several migration guides/changelogs to figure out what actually happened.

**Comment by blasten** [comment]
> The bigger value here is that we'll actually know if a change to e2e is breaking (and/or if it's working as expected). We'll also have a clearer path to keeping the plugins up to date with the latest e2e stuff rather than reading several migration guides/changelogs to figure out what actually happened.

Wouldn't that be the case for 3P plugins? e.g. how would the firebase plugins handle this?

**Comment by dnfield** [comment]
Third party plugins cannot do this - if they want to test against master, they'd have to use a git reference. That's probably not desireable.

**Comment by dnfield** [comment]
To be clear - this is not because we want to recommend this method for other repositories, but because we want to catch regressions in e2e in this repository, and make sure that plugins in this repo are on the latest version of e2e.

**Comment by blasten** [comment]
It sounds like the issue is test coverage of the e2e plugin itself. Is that correct? :)

**Comment by dnfield** [comment]
It's both getting more coverage of e2e, as well as making sure that the plugin makes repository are using the latest version.

**Comment by dnfield** [comment]
Have to figure out why linux is timing out.

**Comment by ditman** [comment]
@dnfield maybe related to the latest push to the repo? I've pinged in the merged PR.

**Pull request merged**
