### PR TITLE
[url_launcher] suppress a `uses or overrides a deprecated API` warning in WebViewActivity

### PR DESCRIPTION
**Pull request by valconetti**
## Description

The url_launcher overrides the deprecated `shouldOverrideUrlLoading(WebView view, String url)` method to be backwards compatible with versions before Android API 24. This however currently displays the warning `WebViewActivity.java uses or overrides a deprecated API.` when building for Android. This is causing some problems for developers who treat these warnings as errors as part of their build configuration.

This PR addresses this issue by annotating the `shouldOverrideUrlLoading(WebView view, String url)` method with the @SuppressWarnings("deprecation") attribute.

## Related Issues

[Issue 60986](https://github.com/flutter/flutter/issues/60986)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by amirh — APPROVED** [review]
LGTM

**Review by amirh — CHANGES_REQUESTED** [review]
Make sure to bump the version in pubspec as well

**Comment by mnjaya** [comment]
image
Deprecation Warning on build apk. It seems a revisit on the issue by the developer.

**Comment by valconetti** [comment]
I changed the version in the pubspec.

However I think @mnjaya might be wrong saying that my fix doesn't work. I just checked it and I don't get the warning. So maybe he/she just checked the package instead of my branch.

**Comment by shinriyo** [comment]
Why google can't fix own deprecated bug?
```
WebViewActivity.java uses or overrides a deprecated API.
```

**Review by amirh — APPROVED** [review]
LGTM

**Comment by valconetti** [comment]
> Why google can't fix own deprecated bug?
> 
> ```
> WebViewActivity.java uses or overrides a deprecated API.
> ```

Hi @shinriyo, 
It's because it isn't really a bug. The function `shouldOverrideUrlLoading` [is deprecated from API 24 and up](https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20java.lang.String)). To make this plugin compatible with older versions, the deprecated version of `shouldOverrideUrlLoading` is used as well as the new one. Google can't remove this older deprecated function, because older OS aren't able to use the new one.

**Pull request merged**
