### PR TITLE
[url_launcher] Add a uses-permission for mailto urls

### PR DESCRIPTION
**Pull request by igaponov**
Without this the next exception rises: 
PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { mailto:smith@example.com }, null, null)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by stuartmorgan** [comment]
This seems like excessive permission for just sending email. Can you point to docs indicating that this (vs the query that's already demonstrated for email below what you've added) is necessary?

**Comment by igaponov** [comment]
@stuartmorgan as I mentioned in the description, without this permission I get a PlatformException, so the docs without it are useless. That was the only solution I could find, If you have another one, please provide it.

**Comment by stuartmorgan** [comment]
> @stuartmorgan as I mentioned in the description, without this permission I get a PlatformException

Your one-line description is missing critical information, like exactly what your manifest looks like, what version you are running on when you get this, etc. Please file a bug that describes your detail in issue, so that it can be discussed further.

> That was the only solution I could find, If you have another one, please provide it.

I don't know off-hand why the existing solution didn't work for you (as I don't what what you tried, per the above). That doesn't mean that this PR is correct, however, and we're not going to add a recommendation to the readme that requests a very broad permission without a clear justification. "It works for me" isn't a sufficient justification—the same could be said of, e.g., adding every possible permission, but that doesn't mean doing so is a good idea.

**Comment by hBurt** [comment]
Are you using an emulator? The device you are using might not have and email application which will cause this error to be thrown. 

Try using the `mailto` functionality on physical phone instead of an emulator if that is the case

**Comment by igaponov** [comment]
@hBurt I've tried both emulator and real device.

@stuartmorgan here you go:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.app">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>
   <application
        android:label="app"
        android:icon="@mipmap/ic_launcher">
       <meta-data
           android:name="com.facebook.sdk.ApplicationId"
           android:value="@string/facebook_app_id" />
       <activity
           android:name="com.facebook.FacebookActivity"
           android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
           android:label="@string/app_name" />
       <activity
           android:name="com.facebook.CustomTabActivity"
           android:exported="true">
           <intent-filter>
               <action android:name="android.intent.action.VIEW" />

               <category android:name="android.intent.category.DEFAULT" />
               <category android:name="android.intent.category.BROWSABLE" />

               <data android:scheme="@string/fb_login_protocol_scheme" />
           </intent-filter>
       </activity>
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <!-- Displays an Android View that continues showing the launch screen
                 Drawable until Flutter paints its first frame, then this splash
                 screen fades out. A splash screen is useful to avoid any visual
                 gap between the end of Android's launch screen and the painting of
                 Flutter's first frame. -->
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <meta-data
                android:name="flutter_deeplinking_enabled"
                android:value="true"
            />
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="http" android:host="***.com" />
                <data android:scheme="https" />
            </intent-filter>
        </activity>
       <activity android:name="com.linusu.flutter_web_auth.CallbackActivity" >
           <intent-filter android:label="flutter_web_auth">
               <action android:name="android.intent.action.VIEW" />
               <category android:name="android.intent.category.DEFAULT" />
               <category android:name="android.intent.category.BROWSABLE" />
               <data android:scheme="com.app" />
           </intent-filter>
       </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

       <meta-data android:name="com.google.android.geo.API_KEY"
           android:value="${API_KEY}"/>

       <meta-data
           android:name="com.google.android.gms.ads.APPLICATION_ID"
           android:value="${APPLICATION_ID}"/>
    </application>
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="https" />
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="http" />
        </intent>
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="*/*" />
        </intent>
    </queries>
</manifest>
```

**Comment by stuartmorgan** [comment]
> @stuartmorgan here you go

Again, please file an issue. An issue is the right place to investigate root causes of issues, not a PR.

**Comment by igaponov** [comment]
@stuartmorgan when I press a mailto link in app, I get the next error in console:
```
E/flutter (11956): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ACTIVITY_NOT_FOUND, No Activity found to handle intent { mailto:smith@example.com }, null, null)
E/flutter (11956): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (11956): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (11956): <asynchronous suspension>
E/flutter (11956): #2      launch (package:url_launcher/url_launcher.dart:99:23)
E/flutter (11956): <asynchronous suspension>
E/flutter (11956): #3      MainScreen.build.<anonymous closure> (package:app/screens/main_screen/main_screen.dart:38:13)
E/flutter (11956): <asynchronous suspension>
```

**Comment by stuartmorgan** [comment]
It turns out that this violates [an explicit store policy](https://support.google.com/googleplay/android-developer/answer/10158779), so is definitely not something we will be suggesting in the README.

I still encourage you to file an issue where the problem you are having can be investigated, and solved in a viable way.

**Pull request closed without merging**
