### PR TITLE
[video_player]Added HTTP headers setting to video_player plugin

### PR DESCRIPTION
**Pull request by Yarikk26**
Not the best solution for https://github.com/flutter/flutter/issues/16466 especially for iOS.
It seems that there is the only one way to set headers for iOS player, but it isn't public (https://stackoverflow.com/a/23713028).

### CODE REVIEW

**Comment by JohnGalt1717** [comment]
Please commit this. Desperately needed and the iOS isn't an issue. Many people online report that apps don't get rejected for it.

**Comment by JohnGalt1717** [comment]
@Yarikk26 how would one reference this pull request as a dependency in flutter so that I can try it? I'm blocked right now until this is merged so I need to use it if at all possible.

Thanks!

**Comment by Yarikk26** [comment]
@JohnGalt1717 You can add something like this into your **pubspec.yaml**: 
```
video_player:
  git:
    url: https://github.com/tvip/flutter-plugins.git
    ref: videoplayer_http_headers #branch or commit hash here
    path: packages/video_player
```
You can also specify branch **tvip** in ref field. There are some more additions from me in that branch, but it's a bit outdated(feb 2019). There is the one more way: you can fork this repo and merge my changes into yours copy and use it. :)

**Comment by JohnGalt1717** [comment]
@Yarikk26 Thanks! Here's hoping that @amirh 's tagging means that this is going to go mainstream soon.

Now if we could just get widevine and fairplay enabled we'd really be rocking.

**Comment by JohnGalt1717** [comment]
Bump again, can we please get this merged? This is blocking us going to production with Flutter.

**Comment by JohnGalt1717** [comment]
Bump again.

**Comment by AdamNSmith** [comment]
I'm also very interested in getting widevine and fairplay working. Any updates on when this might get merged?

**Comment by dvirgiln** [comment]
I really need this functionality as well. Any idea when this will be merged?

**Comment by JohnGalt1717** [comment]
@dvirgiln It probably won't be merged because it has issues on ios that will probably get your app rejected from the store. It has to be rewritten to intercept the requests and add the headers similar to how UWP works.   I have semi-working code in Xamarin. If I ever get the time I may do a pull request to write the same code in swift and make this work.

**Comment by vishnukvmd** [comment]
FWIW, [react-native-video](https://github.com/react-native-community/react-native-video/) ran into a [similar issue](https://github.com/react-native-community/react-native-video/issues/2012#issuecomment-630749086), and decided to go ahead with an implementation using the `AVURLAssetHTTPHeaderFieldsKey`, similar to what's proposed here: https://github.com/react-native-community/react-native-video/pull/2014

I'd say that this is a pragmatic way to solve this problem.

**Comment by stuartmorgan** [comment]
We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

We’re currently working through a large backlog of PRs. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are the primary way we’re prioritizing non-trivial reviews; this addresses a fairly highly-voted issue, so is something we can work on moving forward. In order for that to happen, the PR will need:
- Updating to changes in plugin structure on master (e.g., federation)
- Tests (at least unit tests of the app-facing->plugin interface portion of the change)

@Yarikk26 If you're still interested in moving forward with this, once you've done the above please comment and I'll route this to a reviewer. If not, perhaps someone else will be interested in taking over in a new PR.

**Comment by stuartmorgan** [comment]
Given the lack of response to the last comment, and the new PR, I'm going to close this in favor of the new PR.

**Pull request closed without merging**
