### PR TITLE
[camera] fix camera example

### PR DESCRIPTION
**Pull request by nt4f04uNd**
fixes https://github.com/flutter/flutter/issues/79475

* fixed video initialization/disposal that was throwing
* removed scaffold key in favor of ScaffoldMessanger
* close current snackbar when new is shown, so they won't stack up
* changed layout a bit + padded it from bottom so snackbars mostly wouldn't prevent taps on buttons
* updated formatting

original PR https://github.com/bottlepay/plugins/pull/1

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by cyanglaz** [comment]
@nt4f04uNd try `flutter format`

**Comment by nt4f04uNd** [comment]
i'm not asking how to auto format the code

why is this there?

> - [ ] I read and followed the Flutter Style Guide and the C++, Objective-C, Java style guides."

these rules explicitly say not to use an auto formatter

can you please clarify on why plugins do not line up with the style guide of the flutter reporsitory and recommend using it at the same time?

**Comment by cyanglaz** [comment]
@nt4f04uNd Good point! This was an under-sight. We do use dart format for Plugin repo. We need to update the `Pre-launch Checklist` or update the style guide, I created an issue to track this: https://github.com/flutter/flutter/issues/80081

**Comment by cyanglaz** [comment]
@nt4f04uNd The template is updated :)
Also, do you mind formatting the code.

**Comment by nt4f04uNd** [comment]
I will close this as it's quite stale at this point

**Pull request closed without merging**
