### PR TITLE
[file_selector] Annotate all parameters of XTypeGroup with // ignore: prefer_const_literals_to_create_immutables

### PR DESCRIPTION
**Pull request by eugerossetto**
Annotate all parameters of XTypeGroup with // ignore: prefer_const_literals_to_create_immutables to prepare this implementation for the const constructor of XTypeGroup. On files that have more than two occurrences, an ignore_for_file was added at the top of the file.

Issue:
[#111906 [file_selector] `XTypeGroup` should be immutable](https://github.com/flutter/flutter/issues/111906)

Related PR:
[[file_selector] Convert XTypeGroup to const](https://github.com/flutter/plugins/pull/6476#issuecomment-1259562629)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
I hadn't looked at the details of what was still failing. These don't need an ignore, you can just add the consts now since everything that generates this lint warning has a const constructor already.

**Comment by eugerossetto** [comment]
> I hadn't looked at the details of what was still failing. These don't need an ignore, you can just add the consts now since everything that generates this lint warning has a const constructor already.

Hi Stuart, do you think it would be a better approach to use const parameters instead of ignoring the warnings? Then, the desired change it's going to look like this:
```dart
final XTypeGroup typeGroup = XTypeGroup(
      label: 'images',
      extensions: const <String>['jpg', 'jpeg'],
      mimeTypes: const <String>['image/png'],
      webWildCards: const <String>['image/*'],
);
```
Since the [PR](https://github.com/flutter/plugins/pull/6476#issuecomment-1259562629) that updates the constructor hasn't been merged yet, it won't be OK to use a const constructor at this moment. 
I am missing something? 
Thanks.

**Review by stuartmorgan — APPROVED** [review]
I was thinking we should just do it that way since we'd need to make that change regardless, but I guess once we make `XTypeGroup`'s construction `const` we won't need the sub-consts. So that would be more churn, not less; sorry about that.

LGTM with the temporary ignores.

**Comment by stuartmorgan** [comment]
@ditman Can you do the secondary approval here?

**Review by jmagman — APPROVED** [review]

**Pull request merged**
