### PR TITLE
[google_maps_flutter] fix crash and remove listeners

### PR DESCRIPTION
**Pull request by cyanglaz**
## Description

Map plugins crashes when exiting app while using the `FragmentActivity`. 
We are calling `MapView.onDestroy` at an inappropriate location which caused sone undefined behavior. `MapView.onDestroy` should only be called in the corresponding `onDestroy` method in from the activity or fragment. According to https://developers.google.com/android/reference/com/google/android/gms/maps/MapView#onDestroy%28%29 "You must call this method from the parent Activity/Fragment's corresponding method."

Also added some house keeping code to remove all the listeners when disposing. 

## Related Issues

Fixes https://github.com/flutter/flutter/issues/55406

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by xster** [comment]
LGTM, thanks

**Comment by cyanglaz** [comment]
the crash seems to be something new related to google map sdk 
https://stackoverflow.com/questions/61397027/androidruntime-fatal-exception-androidmapsapi-zoomtablemanager-java-lang-arra

**Comment by xster** [comment]
ummm do we need a specific maps version constraint in our gradle in the meantime for our plugin?

**Comment by cyanglaz** [comment]
@xster It seems to pass now (at least for my other gmap PR) Will see how this one goes.

**Comment by xster** [comment]
Still LGTM

**Pull request merged**
