### PR TITLE
[image_picker] add forceFullMetadata for iOS

### PR DESCRIPTION
**Pull request by cpboyd**
## Description

Originally #3090

Make iOS 11+ permissions requests optional per https://developer.apple.com/forums/thread/653414.
PHAssets aren't actually required and there was already some fallback code in place.

To keep this as a non-breaking change, I added an optional parameter of `forceFullMetaData` with a default of `true`.
Setting this to false will disable any permissions checking on iOS and simply display the image picker.

I still need to update the tests.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/65995

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by cpboyd** [comment]
@cyanglaz I was unable to make any changes to the old PR.
I've made the requested changes and tried to simplify/reduce the description for conciseness.

Please let me know if you'd like me to make any additional changes.

**Review by cyanglaz — COMMENTED** [review]
Thanks for the PR, can we add an XCUITest to make sure the permission popup didn't show if `forceFullMetaData` is false

**Comment by cpboyd** [comment]
@cyanglaz Should I add a new FAB to the example with `{forceFullMetaData: false}`?

Also, I suppose I need to create a separate `XCTestCase` since the current has the `UIInterruptionMonitor` to automatically accept the permissions, correct? I'm new to XCUITests.

**Comment by cyanglaz** [comment]
@cpboyd 
This is what I have in mind. 
1. Create a new fab to the example with {forceFullMetaData: false}.
2. Update the existing test to use the new fab instead.
3. In the existing test, add an assertion that the `UIInterruptionMonitor` is never trigger.

**Comment by cyanglaz** [comment]
@cpboyd It's been a while since I last commented, were you able to keep working on this? :)

**Comment by cpboyd** [comment]
@cyanglaz I hadn't had time for this over the holidays. I'll try to make sure it's up-to-date with master and proceed

**Comment by cyanglaz** [comment]
@cpboyd good to hear! just FYI that we are going to migrate image picker to nnbd soon.

**Comment by cpboyd** [comment]
@cyanglaz Great! I've been attempting to do the same with my projects

**Comment by cyanglaz** [comment]
@cpboyd the NNBD migration is done, you can safely rebase your PR. Then I'll review this and let's get this landed :)

**Comment by cyanglaz** [comment]
@cpboyd Looks like you need another rebase master to fix CI. Please ping me when it's done and I'll do another review. Let's try to land it soon :)

**Comment by cpboyd** [comment]
@cyanglaz I've rebased, fixed failing tests, and added a checkbox to the example for toggling the `forceFullMetadata` value.

Please advise next steps.

**Comment by cpboyd** [comment]
I had corrected the casing to `forceFullMetadata`, should I revert to `forceFullMetaData` for consistency per @stuartmorgan's comment on PR  https://github.com/flutter/plugins/pull/4215#issuecomment-891953852 ?

**Comment by stuartmorgan** [comment]
> I had corrected the casing to `forceFullMetadata`, should I revert to `forceFullMetaData` for consistency per @stuartmorgan's comment on PR [#4215 (comment)](https://github.com/flutter/plugins/pull/4215#issuecomment-891953852) ?

Are there other cases where it's wrong in the public API? I was looking at the ObjC code when I made that comment; I don't remember if it extended beyond there.

**Comment by cpboyd** [comment]
> Are there other cases where it's wrong in the public API? I was looking at the ObjC code when I made that comment; I don't remember if it extended beyond there.

From searching `etaData`, it appears to be solely limited to the `image_picker` ObjC code.

**Comment by stuartmorgan** [comment]
Then a new public API should definitely use the correct capitalization.

**Comment by cpboyd** [comment]
@cyanglaz I've split the interface portion into #4288

**Review by cyanglaz — COMMENTED** [review]
Now that the platform_interface is updated, I think we need to update the version dependency in pubspec.yaml?

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
This cannot land without first fixing the interface change, which needs to be reverted.

**Comment by cpboyd** [comment]
@stuartmorgan I'm sorry, I just don't have the time to dedicate to this PR.

In all honesty, I'm not fully certain about the rebases that I did previously. I stopped using this optional approach in my own app months ago in favor of simply stripping out the permissions elevation code: https://github.com/cpboyd/plugins/tree/ios-no-permissions

**Pull request closed without merging**
