### PR TITLE
[in_app_purchase] fix "autoConsume" param in "buyConsumable"

### PR DESCRIPTION
**Pull request by qwert2603**
Fix ignoring "autoConsume" param in "InAppPurchase.instance.buyConsumable".

Fixes https://github.com/flutter/flutter/issues/83035

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by qwert2603** [comment]
Hello! Do I need to update CHANGELOG.md or version in pubspec.yaml for these changes?

**Comment by mvanbeusekom** [comment]
> Hello! Do I need to update CHANGELOG.md or version in pubspec.yaml for these changes?

Hi @qwert2603, thank you for the pull-request. The changes look good, but yes please also update the CHANGELOG.md and the pubspec.yaml. You can update to version `1.0.1`.

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]
There seems to be a small merge conflict on the `pubspec.yaml`.  Could you please rebase your branch with the `master` branch and update the PR?

Otherwise the PR looks good and I can merge it when the conflict is resolved. And thank you for contributing.

**Comment by qwert2603** [comment]
@mvanbeusekom merge conflict resolved. Thanks for review :)

**Review by mvanbeusekom — APPROVED** [review]
LGTM

**Comment by mvanbeusekom** [comment]
Thank you @qwert2603. I have approved the PR and added the `wait for tree to go green` label. This should merge your PR automatically if all CI tasks are ran successfully.

**Comment by stuartmorgan** [comment]
I've filed an infra bug about the Windows issue, which is unrelated to this PR. I'll update here once it's resolved.

**Comment by stuartmorgan** [comment]
Apologies, but another change that updated the version to 1.0.1 landed in the meantime. Could you update this to 1.0.2 in the pubspec and CHANGELOG? Once that's done I can land this.

**Comment by ditman** [comment]
@googlebot I consent.

**Comment by ditman** [comment]
I've rebased this PR, I should be able to land + publish in a few hours.

**Pull request merged**
