### PR TITLE
Fix strict language checks

### PR DESCRIPTION
**Pull request by kevmoo**
The strict- values are meant to be used via the language key

See https://dart.dev/guides/language/analysis-options

### CODE REVIEW

**Comment by kevmoo** [comment]
VERY weird things got into this state!

**Review by stuartmorgan — APPROVED** [review]
LGTM !

It's not that strange: I messed up when updating this because I didn't notice the different key. Thanks for catching it!

**Comment by stuartmorgan** [comment]
Oh, analyze is failing now. I'll take a look later this morning.

**Comment by stuartmorgan** [comment]
Adding overrides for google_sign_in_web since the check doesn't detect comment-only changes.

**Pull request merged**
