### PR TITLE
[google_maps_flutter] Map marker to obey consume tap events configuration

### PR DESCRIPTION
**Pull request by JamesMcIntosh**
## Description

Stop markers from receiving onClick events if consumeTapEvents is set to false

## Related Issues

flutter/flutter#39868

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [-] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by JamesMcIntosh** [comment]
Hi @iskakaushik, any chance of getting this reviewed?

**Comment by JamesMcIntosh** [comment]
@mklim I see that you are merging things into google_maps_flutter, is there any chance you can review this, there has been no response from @iskakaushik in 2 weeks, Many thanks!

**Comment by stuartmorgan** [comment]
Thanks for the submission! We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

Per repo policy, this would need tests validating the change as part of the PR. If you can add tests, we can find a reviewer, as this looks like a relatively straightforward change.

**Comment by stuartmorgan** [comment]
It looks like you submitted a newer version of this as https://github.com/flutter/plugins/pull/2652; closing in favor of that.

**Pull request closed without merging**
