### PR TITLE
Add Android Firebase phone number authentication

### PR DESCRIPTION
**Pull request by alibitek**
Half fix issue https://github.com/flutter/flutter/issues/10404 by adding support for Firebase phone number authentication on the Android platform in the [firebase_auth plugin](https://github.com/flutter/plugins/tree/master/packages/firebase_auth).

For usage example and testing purposes I've implemented a widget - [PhoneNumberSignInPage](https://github.com/alibitek/plugins/blob/b5df6939b0303f9473e58149eb289ace9dbdf7b1/packages/firebase_auth/example/lib/main.dart#L131) in the example application where the user can enter the phone number and verification code (see screenshot bellow).

This showcases how to use the [Dart API for Firebase phone number authentication](https://github.com/alibitek/plugins/blob/b5df6939b0303f9473e58149eb289ace9dbdf7b1/packages/firebase_auth/lib/firebase_auth.dart#L263-L390), which consists of the following three methods on the FirebaseAuth class: 

1. [signInWithPhoneNumber: Signs in a user by sending a verification code to the user's [phoneNumber]](https://github.com/alibitek/plugins/blob/b5df6939b0303f9473e58149eb289ace9dbdf7b1/packages/firebase_auth/lib/firebase_auth.dart#L263:L356)
2. [verifyPhoneNumber: Verify the authenticity of the phone number using the provided [code]](https://github.com/alibitek/plugins/blob/b5df6939b0303f9473e58149eb289ace9dbdf7b1/packages/firebase_auth/lib/firebase_auth.dart#L358:L372)
3. [resendVerificationCode: Resend the verification code for the provided [phoneNumber]](https://github.com/alibitek/plugins/blob/b5df6939b0303f9473e58149eb289ace9dbdf7b1/packages/firebase_auth/lib/firebase_auth.dart#L374:L390)

The implementation is based on the documentation available at:
- [Authenticate with Firebase on Android using a Phone Number](https://firebase.google.com/docs/auth/android/phone-auth)
- [PhoneAuthActivity.java](https://github.com/firebase/quickstart-android/blob/master/auth/app/src/main/java/com/google/firebase/quickstart/auth/PhoneAuthActivity.java)
- [com.google.firebase.auth.PhoneAuthProvider](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/PhoneAuthProvider)

For a description of the usage I've provided documentation to the [`signInWithPhoneNumber` method](https://github.com/alibitek/plugins/blob/b5df6939b0303f9473e58149eb289ace9dbdf7b1/packages/firebase_auth/lib/firebase_auth.dart#L263:L340).

To test you need to generate your own `firebase_auth/example/android/app/google-services.json` file from the Settings page of the project created in the [Firebase Console](https://firebase.google.com/docs/auth/android/phone-auth#before-you-begin).

Feel free to provide any feedback regarding the design and implementation.

Possible improvements:
- Store the Result object as a data member in the FirebaseAuthPlugin class and use it in PhoneVerificationStateChangedCallbacks instead of PhoneSignInStreamHandler?
- Throw custom exceptions with error codes indicating cause of exception?

<a href="https://user-images.githubusercontent.com/528448/34523503-77df7bf8-f0a0-11e7-94e7-83d75a59d2b7.jpg" target="_blank"></a>

### CODE REVIEW

**Comment by CrazyStaff** [comment]
Is there a way to get the phone number automatically? Why should the user type his phone number in the text field if the phone already knows its own number.

**Comment by alibitek** [comment]
@CrazyStaff There is no reliable API to get the phone number automatically, on both platforms (Android, iOS). Due to various reasons, including privacy. The only viable alternative is requiring the user to type it.

**Comment by long1eu** [comment]
@CrazyStaff  you can take a look at FirebaseUI they implement that in Android

**Comment by alibitek** [comment]
@long1eu 

I've looked at [the sample Firebase UI app](https://github.com/firebase/FirebaseUI-Android#sample-app) and [the phone auth source code](https://github.com/firebase/FirebaseUI-Android/tree/master/auth/src/main/java/com/firebase/ui/auth/ui/phone) and I can see the user is required to enter the phone number and they try to provide autocompletion by using the [CredentialsApi](https://developers.google.com/android/reference/com/google/android/gms/auth/api/credentials/CredentialsApi) via the [Smart Lock for Passwords and Connected Accounts API](https://developers.google.com/android/reference/com/google/android/gms/auth/api/credentials/package-summary) from [Smart Lock for Passwords on Android](https://developers.google.com/identity/smartlock-passwords/android/).

From https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/ui/phone/VerifyPhoneNumberFragment.java#L234:
```java
private void showPhoneAutoCompleteHint() {
        try {
            startIntentSenderForResult(getPhoneHintIntent().getIntentSender(), RC_PHONE_HINT);
        } catch (IntentSender.SendIntentException e) {
            Log.e(TAG, "Unable to start hint intent", e);
        }
    }

    private PendingIntent getPhoneHintIntent() {
        GoogleApiClient client = new GoogleApiClient.Builder(getContext())
                .addApi(Auth.CREDENTIALS_API)
                .enableAutoManage(
                        getActivity(),
                        GoogleApiHelper.getSafeAutoManageId(),
                        new GoogleApiClient.OnConnectionFailedListener() {
                            @Override
                            public void onConnectionFailed(@NonNull ConnectionResult connectionResult) {
                                Log.e(TAG,
                                      "Client connection failed: " + connectionResult.getErrorMessage());
                            }
                        })
                .build();


        HintRequest hintRequest = new HintRequest.Builder()
                .setHintPickerConfig(
                        new CredentialPickerConfig.Builder().setShowCancelButton(true).build())
                .setPhoneNumberIdentifierSupported(true)
                .setEmailAddressIdentifierSupported(false)
                .build();

        return Auth.CredentialsApi.getHintPickerIntent(client, hintRequest);
}
```

From https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/ui/phone/VerifyPhoneNumberFragment.java#L166:
```java
 @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == RC_PHONE_HINT) {
            if (data != null) {
                Credential cred = data.getParcelableExtra(Credential.EXTRA_KEY);
                if (cred != null) {
                    // Hint selector does not always return phone numbers in e164 format.
                    // To accommodate either case, we normalize to e164 with best effort
                    final String unformattedPhone = cred.getId();
                    final String formattedPhone =
                            PhoneNumberUtils.formatUsingCurrentCountry(unformattedPhone,
                                    mAppContext);
                    if (formattedPhone == null) {
                        Log.e(TAG, "Unable to normalize phone number from hint selector:"
                                + unformattedPhone);
                        return;
                    }
                    final PhoneNumber phoneNumberObj =
                            PhoneNumberUtils.getPhoneNumber(formattedPhone);
                    setPhoneNumber(phoneNumberObj);
                    setCountryCode(phoneNumberObj);
                    onNext();
                }
            }
        }
}
```

This only works if the user:
- has enabled Smart Lock via Settings > Google > Smart Lock for Passwords and previosuly [stored a phone number](https://developers.google.com/identity/smartlock-passwords/android/store-credentials) there.
[Can I store a phone number in Smart Lock?](https://stackoverflow.com/a/36138730/313113)
- has a SIM card whose phone number is readable, i.e. phone number appears in Settings -> About -> Status -> SIM status
- has a phone number associated with Google Account? (not sure how this works, as there is a phone number in the Google account on the device I tested, but I get a null Credential from the `intent.getParcelableExtra(Credential.EXTRA_KEY)` )
Source: https://stackoverflow.com/a/34537329/313113

Another potential improvement is to use the [SmsRetriever API](https://developers.google.com/android/reference/com/google/android/gms/auth/api/phone/package-summary) to [automatically read the verification](https://developers.google.com/identity/sms-retriever/request).

firebase-ui-screenshot_20180104-171020

**Comment by long1eu** [comment]
@alibitek good answer 🥇

**Comment by alibitek** [comment]
@collinjackson Would it be better to store the Result object as a data member in the FirebaseAuthPlugin class like [this](https://github.com/alibitek/plugins/commit/0b00311ceb1435241bb47ca1033259df4e846a7e#diff-24450cd30718eaedff320c60aa64b0c5R90) and call it from the PhoneVerificationStateChangedCallbacks inner class callback methods like [this](https://github.com/alibitek/plugins/commit/0b00311ceb1435241bb47ca1033259df4e846a7e#diff-24450cd30718eaedff320c60aa64b0c5R457) ? Instead of the current design using a Stream.

**Comment by gaara87** [comment]
I should have looked at this PR before I started my own implementation :) if theres anything I could help with please let me know. Really hoping this gets merged in real quick!

also good job @alibitek !

**Comment by pauldemarco** [comment]
I'm getting an NPE when trying to signInWithPhoneNumber:

```
E/AndroidRuntime(29231): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(29231): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$PhoneVerificationStateChangedCallbacks.onCodeSent(FirebaseAuthPlugin.java:556)
E/AndroidRuntime(29231): 	at com.google.android.gms.internal.zzdyb.zza(Unknown Source)
E/AndroidRuntime(29231): 	at com.google.android.gms.internal.zzdyf.run(Unknown Source)
E/AndroidRuntime(29231): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(29231): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(29231): 	at android.os.Looper.loop(Looper.java:158)
E/AndroidRuntime(29231): 	at android.app.ActivityThread.main(ActivityThread.java:7225)
E/AndroidRuntime(29231): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29231): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/AndroidRuntime(29231): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by alibitek** [comment]
@pauldemarco Yes, the event stream is currently mandatory. I will rewrite the implementation without it, as I think it's a better approach to use the Result object instead.

**Comment by pranjalsatija** [comment]
@alibitek I'm working on an iOS version of this, and I have a question about your usage of `EventChannel`. From what I could tell by looking at your commits, it seems like you're using `EventChannel` for phone number autofill and automatic text reading, but neither of these things is supported on iOS, so do you think it's fine if the iOS implementation I'm writing only responds to `MethodChannel` requests?

**Comment by collinjackson** [comment]
Thanks so much for working this. It looks like it's not ready for merging yet, but let us know when it's ready for the final review and I'll help you get it landed.

**Comment by collinjackson** [comment]
@pranjalsatija can you give an update on the status of your iOS implementation? are you still working on this?

**Comment by pranjalsatija** [comment]
@collinjackson It's half done. I haven't had much time to work on it in the last 2 weeks because of exams. I'm still unsure about what to do concerning phone number autofill and automatic SMS parsing / recognition that can fill the verification code automatically. That doesn't exist on iOS so should I just leave out the code related to it?

**Comment by collinjackson** [comment]
@pranjalsatija  You can leave out features that don't exist on iOS. Thank you so much.

**Comment by pranjalsatija** [comment]
@collinjackson Got it, will try to open a PR today.

**Comment by reeteshkumar39** [comment]
how can implement firebase phone number authentication in flutter ? Is firebase phone authentication with flutter work in progress?

**Comment by collinjackson** [comment]
@pranjalsatija, what's the current status of your iOS implementation?

**Comment by pranjalsatija** [comment]
@collinjackson I will have a PR tomorrow. I'm so sorry for the delay, I've just been bogged down with school.

**Comment by Asoseil** [comment]
what's the current status?

**Comment by pranjalsatija** [comment]
@Asoseil Not sure. As I mentioned in #484, we should probably agree on a unified Dart interface for this, and then build iOS and Android implementations that match up. Currently, I'm pretty sure that the implementations aren't 100% compatible, and I know @alibitek mentioned rewriting his implementation, so it would be beneficial if we could create a PR that has a unified interface, and then have corresponding PRs for iOS and Android.

**Comment by kroikie** [comment]
Hi @alibitek thank you for working on this feature with @pranjalsatija.

Given that the options of the phone auth are different for each side of this plugin let us work with the interface used by the [Unity plugin](https://firebase.google.com/docs/auth/unity/phone-auth#send-a-verification-code-to-the-users-phone).

The Dart interface would look like:
```
verifyPhoneNumber(phoneNumber, timeout,
    verificationCompleted: (credential) => {},
    verificationFailed: (error) => {},
    codeSent: (id, token) => {},
    codeAutoRetrievalTimeout: (id) => {}
)
```

**Comment by mohith7548** [comment]
Hey please help me. I couldn't find the method named 'signInWithPhoneNumber' method in FirebaseAuth. Please see this screenshot

screenshot from 2018-05-05 09-34-07

**Comment by pranjalsatija** [comment]
@kroikie Got it, will submit a PR soon. Finals are almost over. 🙏🏽

**Comment by pranjalsatija** [comment]
@mohith7548 The function isn't available because we haven't merged a PR that implements phone number auth on iOS and Android yet. It's a WIP and I will have the Dart interface and corresponding iOS implementation in a PR soon.

**Comment by alibitek** [comment]
@pranjalsatija I will start implementing the interface mentioned in #484 on Android

**Comment by alibitek** [comment]
@kroikie Do you have any idea how can I send from Java to Dart and back again an instance of  [com.google.firebase.auth.PhoneAuthProvider.ForceResendingToken](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/PhoneAuthProvider.ForceResendingToken) , which implements the Parcelable interface.

I get IllegalArgumentException while doing:
```
@Override
    public void onCodeSent(
        String verificationId, PhoneAuthProvider.ForceResendingToken resendToken) {
      Log.d(TAG, "onCodeSent: " + verificationId);

      ImmutableMap.Builder<String, Object> builder = ImmutableMap.<String, Object>builder();
      builder.put("status", PHONE_SIGN_IN_CODE_SENT_STATUS);
      builder.put("verificationId", verificationId);
      builder.put("resendToken", resendToken);

      result.success(builder.build());
    }
```

Stacktrace:
```
E/AndroidRuntime( 6935): FATAL EXCEPTION: main
E/AndroidRuntime( 6935): Process: io.flutter.plugins.firebaseauthexample, PID: 6935
E/AndroidRuntime( 6935): java.lang.IllegalArgumentException: Unsupported value: com.google.firebase.auth.PhoneAuthProvider$ForceResendingToken@cb230b0
E/AndroidRuntime( 6935): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:293)
E/AndroidRuntime( 6935): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:290)
E/AndroidRuntime( 6935): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:57)
E/AndroidRuntime( 6935): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime( 6935): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$PhoneVerificationStateChangedCallbacks.onCodeSent(FirebaseAuthPlugin.java:602)
E/AndroidRuntime( 6935): 	at com.google.firebase.auth.api.internal.zzdc.zza(Unknown Source)
E/AndroidRuntime( 6935): 	at com.google.firebase.auth.api.internal.zzdg.run(Unknown Source)
E/AndroidRuntime( 6935): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 6935): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6935): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 6935): 	at android.app.ActivityThread.main(ActivityThread.java:6334)
E/AndroidRuntime( 6935): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6935): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime( 6935): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

To be able to implement the `codeSent` callback I need a way to pass it to Dart.
That's why in the implementation currently in the branch I store the resendToken inside Java.

**Comment by alibitek** [comment]
@mravn-google Thanks for your suggestions. I tried the marshall/unmarshall to/from byte[] to Dart's Uint8List and works fine.

@kroikie I will try what you suggest.
Currently, my interface looks like:
```
class PhoneAuthCredential {
  final Map<String, dynamic> _data;

  PhoneAuthCredential._(this._data);

  String get provider => _data['provider'];

  String get signInMethod => _data['signInMethod'];

  String get smsCode => _data['smsCode'];

  FirebaseUser get user => _data['user'];
}
Future<Null> verifyPhoneNumber(
      {@required String phoneNumber,
      @required void verificationCompleted(PhoneAuthCredential credential),
      @required void verificationFailed(final PlatformException error),
      @required void codeSent(final String verificationId, final Uint8List resendToken),
      @required void codeAutoRetrievalTimeout(final String verificationId),
      int timeout = 60}) async { }

Future<FirebaseUser> signInWithCredential(
      {@required String verificationId,
      @required String verificationCode}) async { }
```

**Comment by alibitek** [comment]
@mravn-google You mentioned [here](https://github.com/flutter/plugins/pull/484#discussion_r180673900) that using an event stream is a bit heavy. However, I there is a problem with using a Result object.
There is a need to multiple results from Java to the Dart's API method call.
For example when Firebase can auto verify the phone number, it does this:
- when the verification code is received by the user it calls PhoneVerificationStateChangedCallbacks::onCodeSent which sends back a response to Dart via `result.success(builder.build());`
- it auto verifies the phone number and then it calls PhoneVerificationStateChangedCallbacks::onVerificationCompleted, which also calls `result.success(builder.build());`, but because the response/reply has been already sent via onCodeSent, we get:
```
I/FirebaseAuth( 9722): [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth( 9722): [FirebaseAuth:] Preparing to create service connection to gms implementation
D/FirebaseAuthPlugin( 9722): onCodeSent: AM5PThDUh9jb6gxKlSZkHGltM3hQUxb1C2OdCuTKJek5AAPcz1QWixlpyLifw0iOBW4Sn2qiyo3P0wUc9jHIqtnZ551mpNAGov9Ukx0o5qwrjFhqngdnljb6_jyfbqIeIFHRPch_uPja7XuusiZH4bIPAzZntbNxR6cJxUPSiz8H0V2M_6xMD29eURyENxgP9l5MJlgIikEGtrbbSKX6KUa_b1DCCrFRPg
I/flutter ( 9722): [UI] Code sent event - Display view to let the user enter it null, [69, 79, 255, 255, 0, 0, 0, 0]
D/FirebaseAuthPlugin( 9722): onVerificationCompleted - Provider: phone , SignInMethod: phone , SmsCode: 924796
D/AndroidRuntime( 9722): Shutting down VM
E/AndroidRuntime( 9722): FATAL EXCEPTION: main
E/AndroidRuntime( 9722): Process: io.flutter.plugins.firebaseauthexample, PID: 9722
E/AndroidRuntime( 9722): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 9722): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:162)
E/AndroidRuntime( 9722): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime( 9722): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$PhoneVerificationStateChangedCallbacks.onVerificationCompleted(FirebaseAuthPlugin.java:582)
E/AndroidRuntime( 9722): 	at com.google.firebase.auth.api.internal.zzdd.zza(Unknown Source)
E/AndroidRuntime( 9722): 	at com.google.firebase.auth.api.internal.zzdg.run(Unknown Source)
E/AndroidRuntime( 9722): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime( 9722): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 9722): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 9722): 	at android.app.ActivityThread.main(ActivityThread.java:6334)
E/AndroidRuntime( 9722): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9722): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/AndroidRuntime( 9722): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/AppTracker( 9722): App Event: crash
I/Process ( 9722): Sending signal. PID: 9722 SIG: 9
Application finished.
```

I could add a boolean to know if onCodeSent has replied back, but onVerificationCompleted also needs to send a reply back... otherwise we don't know what happend with the code, was auto verified or not...
For this reason, an event stream is necessary.

I suggest using the above mentioned API interface and have an event stream behind the scenes (not exposed to the client) that receives the replies from Java and calls the coresponding callbacks (as per the PhoneVerificationStateChangedCallbacks methods)

**Comment by kroikie** [comment]
@alibitek Could you try making calls back onto the Dart side using a key to identify which particular call to verify is being completed. When the call to verify is made on the Dart side you can generate the key and pass it to the native side then the native side can use it when invoking the corresponding Dart side method.

See an [example of this](https://github.com/flutter/plugins/blob/master/packages/firebase_database/lib/src/database_reference.dart#L156) in the transaction implementation for firebase_database where a transactionKey was used.

**Comment by mohith7548** [comment]
Can phone Authentication be used now? OR else still it is in development mode.
please answer

**Comment by matejthetree** [comment]
@mohith7548 Still in development

**Comment by kroikie** [comment]
Hi @alibitek I have combined both the Android and iOS version of this feature into a [single PR](https://github.com/flutter/plugins/pull/606). I will close this PR and welcome your feedback in the combined PR.

**Comment by mohith7548** [comment]
Any improvements? I have been waiting for this phone authentication for 3 months. Please come up with a solution. We love #Flutter

**Comment by mohith7548** [comment]
Any improvements? I have been waiting for this phone authentication for 3 months. Please come up with a solution. We love #Flutter

**Comment by mmcc007** [comment]
@mohith7548 phone auth feature is pending review (see #606). The code works and you can try it out prior to release if interested (see [this comment](https://github.com/flutter/plugins/pull/606#issuecomment-402878854) for my attempt at instructions) 😃

**Comment by shlokk9763** [comment]
my app is not sending any otp to given phone number , it is verifying with phone number provided in "Phone numbers for testing (optional) " option in Sign-in method tab.`
String phoneNo;
    String smsCode;
    String verificationId;
    signIn() {
      FirebaseAuth.instance
          .signInWithPhoneNumber(verificationId: verificationId, smsCode: smsCode)
          .then((user) {
        print('/homepage');
      }).catchError((e) {
        print(e);
      });
    }
    Future<bool> smsCodeDialog(BuildContext context) {
      return showDialog(
          context: context,
          barrierDismissible: false,
          builder: (BuildContext context) {
            return new AlertDialog(
              title: Text('Enter sms Code'),
              content: TextField(
                onChanged: (value) {
                  smsCode = value;
                },
              ),
              contentPadding: EdgeInsets.all(10.0),
              actions: <Widget>[
                new FlatButton(
                  child: Text('Done'),
                  onPressed: () {
                    FirebaseAuth.instance.currentUser().then((user) {
                      if (user != null) {
                        print('homepage');
                      } else {
                        print('calling signIn()');
                        signIn();
                      }
                    });
                  },
                )
              ],
            );
          });
    }
    Future<void> verifyPhone() async {
      final PhoneCodeAutoRetrievalTimeout autoRetrieve = (String verId) {
        verificationId = verId;
      };

      final PhoneCodeSent smsCodeSent = (String verId, [int forceCodeResend]) {
        verificationId = verId;
        print("going into smsCodeDialog()");
        smsCodeDialog(context).then((value) {
          print('Signed in');
        });
        //print('Signed in');
      };

      final PhoneVerificationCompleted verifiedSuccess = (FirebaseUser user) {
        print('verified');
      };

      final PhoneVerificationFailed veriFailed = (AuthException exception) {
        print('${exception.message}');
      };
      await FirebaseAuth.instance.verifyPhoneNumber(
          phoneNumber:phoneNo,
          codeAutoRetrievalTimeout: autoRetrieve,
          codeSent: smsCodeSent,
          timeout: const Duration(seconds: 5),
          verificationCompleted: verifiedSuccess,
          verificationFailed: veriFailed);
    }
`
if i enter other phone number it gives "This app is not authorized to use Firebase Authentication. Please verifythat the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed. Is app running on a physical device? ]" this message

**Comment by collinjackson** [comment]
@shlokk9763 could you please open a new GitHub issue if you think there's an error in the implementation or documentation? It seems likely to me that this is a configuration issue.

**Comment by shlokk9763** [comment]
please help me to solve is issue https://github.com/flutter/flutter/issues/30684#issue-430377702

**Pull request closed without merging**
