### PR TITLE
[device_info] Migration to platform interface in device_info

### PR DESCRIPTION
**Pull request by yash1200**
## Description

This pull request migrates the device_info plugin to use platform interface.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by crowded-geek** [comment]
I was trying to migrate it but seems that someone did it already, nice pr :100: Could you try and add support for linux too please? @yash1200

**Comment by yash1200** [comment]
> I was trying to migrate it but seems that someone did it already, nice pr  Could you try and add support for linux too please? @yash1200

I have implemeted the support for linux as well, will make a pr after this gets published.

**Comment by ditman** [comment]
For this to be easier to review and merge, I'd recommend you to split this into smaller pull requests:

1) Moving everything from device_info to device_info/device_info (*in this PR)
2) Creating (and publishing) the platform_interface package (*in this PR)
3) Using the platform_interface package from the device_info core plugin
4) ... Add more platforms!

It is useful to have one big PR like this so people can just clone this and go, but the tooling is not very good (for example the tooling won't let you do step 3 until you've done step 2)

**Comment by yash1200** [comment]
@ditman In this pr, I have only addressed step 1 and 2, step 3 and 4 will be implemeted after this gets published. Let me know if I understood you correctly.

**Pull request closed without merging**
