### PR TITLE
[image_picker]On iOS13 device, pickVideo does not work. (#41046)

### PR DESCRIPTION
**Pull request by NiKoTron**
Precache file to a temp directory for ios13, to prevent unvalidated URL into the response.

## Description

Since URL could be invalidated if image picker delegate is deallocated. It's copied a picked file to the temporary directory and returns it.

## Related Issues

*[On iOS13 device, pickVideo does not work](https://github.com/flutter/flutter/issues/41046).

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by NiKoTron** [comment]
@googlebot I signed it!

**Comment by ailic88** [comment]
@NiKoTron @cyanglaz  please be aware that this fix create a new issue when source is camera(not gallery).

**Comment by cyanglaz** [comment]
@NiKoTron https://github.com/flutter/plugins/pull/2083 seems solving the same issue in a similar way? Do you mind take a review on https://github.com/flutter/plugins/pull/2083 and we can close this PR?

**Comment by NiKoTron** [comment]
@cyanglaz Yep, #2083 uses a similar way. I don't mind if you close my PR.

**Comment by cyanglaz** [comment]
@NiKoTron Thank you. Closing.

**Pull request closed without merging**
