### PR TITLE
[camera]Camera: Optional audio permission on android

### PR DESCRIPTION
**Pull request by lschmierer**
Audio permission is not required if sb. want to take pictures only. This change introduces a parameter in CameraController to enable/disable video support.

On iOS, no changes were needed since iOS asks for permission only once video is actually recorded.

### CODE REVIEW

**Comment by lschmierer** [comment]
I signed it!

**Comment by matin** [comment]
What's the status of this issue?

**Comment by matin** [comment]
@amirh would you be able to review this PR? At the moment, Android users have to authorize microphone permissions just to take photos. It's a confusing experience.

**Comment by bparrishMines** [comment]
Hi @lschmierer 

Thanks for the contribution and sorry for the delay! This feature is now implemented with https://github.com/flutter/plugins/pull/837 in version `0.5.2`

**Pull request closed without merging**
