### PR TITLE
[camera] Limit camera preview size to take high quality picture with startImageStream

### PR DESCRIPTION
**Pull request by comlhj1114**
This is related to the issue, https://github.com/flutter/flutter/issues/46082.
This is an important issue to enable real-time image analysis and take a picture in a Flutter app. 

In iOS, I tried to apply head pose estimation and taking a picture in a proper pose automatically, however, when I tried CameraController.startImageStream with ResolutionPreset.max for capture high quality picture, the app crashed unexpectedly. To resolve the problem, I should limit the resolution to ResolutionPreset.high, but in this case, generated pictures also have low resolution (which is 1280x720). 

In Android, the preview resolution is limited to 1280x720 (resolutionPreset.high) in the function computeBestPreviewSize in CameraUtils.java. Like this, I can resolve the problem by limiting _previewSize in iOS. So, I propose this PR. 

In the future, I recommend to set different resolution for preview and taking a picture by getting some arguments for flexibilities of the camera package.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by comlhj1114** [comment]
@googlebot I fixed it.

**Comment by stuartmorgan** [comment]
Thanks for the contribution!

> - [x] All existing and new tests are passing.

This does not appear to be the case; please ensure that all tests pass. This will also need tests covering the change, per Flutter policy.

Based on discussion at https://github.com/flutter/plugins/pull/1952#discussion_r311785855 it appears that the Android limit you are referring to is controversial, so it seems likely that some users would consider this change a regression. Is there a reason not to go directly to providing preview resolution control?

**Comment by comlhj1114** [comment]
@stuartmorgan Thank you for your comment. I didn't know that discussion. I totally agree with them that someone might need high resolution preset. So, like your opinion, I agree that it is better to go directly to providing preview resolution control.
I will make new PR in near future

**Comment by comlhj1114** [comment]
And I just found that this modification control the shape of the preview not  the resolution of the preview.
So this PR is wrong.

**Comment by comlhj1114** [comment]
And I just found that this modification changes the shape of the preview not actual resolution of the preview.
So, this PR is wrong.

**Pull request closed without merging**
