### PR TITLE
Add async getCurrentUser method.

### PR DESCRIPTION
**Pull request by mogol**
Hey,
I found no way to get state of firebase auth right after app launch. Cached `_currentUser` is always null until we invoke one of sign-in methods. 
I added new asynchronous method `getCurrentUser`, it invokes recommended native implementations [addAuthStateDidChangeListener](https://firebase.google.com/docs/auth/ios/manage-users#get_the_currently_signed-in_user) and caches result to `_currentUser`

### CODE REVIEW

**Comment by mit-mit** [comment]
cc @collinjackson @goderbauer can you review please?

@mogol thanks for contributing! Sorry about the slowness here; we have lots of folks on vacation right now.

**Comment by sethladd** [comment]
cc @goderbauer

**Comment by sethladd** [comment]
cc @kroikie for review

**Comment by sethladd** [comment]
Hi @mogol this PR has a conflict, and can't be merged. Is this something you're still working on? Thanks!

**Comment by mogol** [comment]
Hey, conflicts are solved, should I squash commits? 
Also, ideally synchronous getter `currentUser` should be removed - one source of truth. But it's breaking change if someone relies on it.

**Comment by sethladd** [comment]
I'm fine with removing sync currentUser. Please make a clear note about that in the CHANGELOG. Thanks!

No need to squash on your end, we'll use the "squash and merge" button here. You can squash if you want, though :)

**Comment by mit-mit** [comment]
Please also update the version number in `pubspec.yaml`

**Comment by collinjackson** [comment]
Looks reasonable to me, @mit-mit what do you think? It's possible to have currentUser be a getter instead of a method, but I'm not sure which is more idiomatic Dart.

**Comment by mit-mit** [comment]
I'm OK with doing the breaking change now.

Regarding method vs getter, I believe we usually only use getters for retrieving fairly simple values, and not when there is complex computation or side effects. Since we are doing an interop hop here, and it's async, I think the current method is a good choice.

**Comment by mogol** [comment]
Is it possible to start Travis again without push? Failed without output.

**Comment by mit-mit** [comment]
Yup; I restarted it!

**Comment by mogol** [comment]
CI is green. Do I need anything else to merge this PR?

**Comment by collinjackson** [comment]
merged it, I'll deploy to pub as well

**Comment by collinjackson** [comment]
it's uploaded

**Comment by mogol** [comment]
🎉 thanks

**Comment by sethladd** [comment]
Thanks!!

**Comment by ashish0910** [comment]
Thanks issue solved .

**Comment by ronytesler** [comment]
On the web I get null from 'currentUser' after refreshing the browser.

**Comment by collinjackson** [comment]
> On the web I get null from 'currentUser' after refreshing the browser.

Please open a new issue. Thanks!

**Pull request merged**
