### PR TITLE
[Video_player] Upgraded to exoPlayer 2.17.0

### PR DESCRIPTION
**Pull request by zezo357**
note: onPlayerError in listener override had to be removed so i think its not working
and the details that i found from release notes has been added as a comment to help in that matter

updating the exoPlayer in video player android 
from 2.14.1 to 2.17.0

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
no i didnt change any tests

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Thanks for the contribution! You haven’t checked off the items in the PR checklist above, so I’m assuming this is a work in progress and am marking it as a Draft. Please review the checklist, updating the PR as appropriate, and when that’s complete please feel free to mark the PR as ready for review.

**Comment by zezo357** [comment]
> Thanks for the contribution! You haven’t checked off the items in the PR checklist above, so I’m assuming this is a work in progress and am marking it as a Draft. Please review the checklist, updating the PR as appropriate, and when that’s complete please feel free to mark the PR as ready for review.

i am sorry i cant do the tests requred and dart format does not format java code

i tested the updated code in my applicaiton and it works as expected

hope my contribution helps in future updates in case i couldnt make the rest of the checklist

**Comment by stuartmorgan** [comment]
> i am sorry i cant do the tests requred

If there are not intended to be any functional changes, tests are generally not required; this should quality for a test exemption.

There are many other items on the list that you haven't completed though.

> and dart format does not format java code

That's true, but the tool linked to from the checklist item about formatting does.

**Comment by stuartmorgan** [comment]
@blasten Could you review or delegate this review?

It would be good for whoever reviews to do some manual testing with the example app, since our automated test coverage for video_player wouldn't catch some categories of serious issues.

**Comment by stuartmorgan** [comment]
@blasten Ping on this review?

(This would let us remove some internal forking, which would be nice.)

**Review by blasten — APPROVED** [review]
LGTM

**Comment by Hixie** [comment]
test-exempt: rolls dependency

**Review by stuartmorgan — APPROVED** [review]

**Pull request merged**
