### PR TITLE
Add ability to scale images with ImagePicker plugin

### PR DESCRIPTION
**Pull request by roughike**
[flutter/flutter/#10149](https://github.com/flutter/flutter/issues/10149)

This makes it possible to specificy a `maxWidth` and `maxHeight` for the `pickImage` method, like so:

```dart
Future<File> imageFile = ImagePicker.pickImage(maxWidth: 400.0, maxHeight: 700.0);
```

The picked image will then be scaled accordingly, while **preserving aspect ratio**.

Let me know if there's something that could be improved on. [This is me doing Objective C](https://cdn-images-1.medium.com/max/455/1*snTXFElFuQLSFDnvZKJ6IA.png), so I'm pretty sure it's not the most idiomatic code possible.

### CODE REVIEW

**Comment by sethladd** [comment]
cc @collinjackson 

Thanks @roughike !

**Comment by roughike** [comment]
I'm thinking that maybe `maxWidth` and `maxHeight` would be a better API for this. Thoughts?

**Comment by Alexays** [comment]
it would be perfect if we could just specify width or height and preserve aspect ratio ;)

**Comment by mit-mit** [comment]
Thanks for contributing @roughike! Looks like there are a few formatting issues, would you mind to push a fix for those? See: https://travis-ci.org/flutter/plugins/jobs/291120213

**Comment by roughike** [comment]
@mit-mit I fixed the formatting issues just now!

**Comment by mit-mit** [comment]
Thanks!

**Pull request merged**
