### PR TITLE
[google_sign_in_web] Renamed generated folder to js_interop

### PR DESCRIPTION
**Pull request by balvinderz**
Renamed generated folder to js_interop

Fixes https://github.com/flutter/flutter/issues/101855

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [X] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by ditman — CHANGES_REQUESTED** [review]
Should be: `js_interop` (js_interlop is a typo)

**Comment by balvinderz** [comment]
> Should be: `js_interop` (js_interlop is a typo)

Fixed it. I always thought it was interlop 😛

**Comment by ditman** [comment]
@balvinderz thanks for the fix!

To wrap this up completely, can you try to remove the `ignore_for_file` comments for both the js_interop files, and fix whatever problems the analyzer has with them "so they don't receive special treatment" (as described on [the issue](https://github.com/flutter/flutter/issues/101855)?)

**Comment by stuartmorgan** [comment]
@balvinderz Are you still planning on updating this per the comments above?

**Comment by balvinderz** [comment]
@stuartmorgan not getting enough time to work on this. I will close this PR for now.

**Pull request closed without merging**
