### PR TITLE
[google_maps_flutter] Adds support for BuildingsEnabled property

### PR DESCRIPTION
**Pull request by scottmcarthur**
## Description

- Adds missing property `buildingsEnabled` to the Google Maps Flutter plugin.

[iOS SDK Reference](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view.html#a0167011861fb75c6e8103afe15ac9a37)
> (BOOL) buildingsEnabled [read, write, assign]
> If set, 3D buildings will be shown where available.
>
> Defaults to YES.
> This may be useful when adding a custom tile layer to the map, in order to make it clearer at high > zoom levels. Changing this value will cause all tiles to be briefly invalidated.

## Related Issues

None

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by scottmcarthur** [comment]
@googlebot I fixed it.

**Comment by scottmcarthur** [comment]
@iskakaushik The checks are failing because the version number in the `pubspec.yaml` in my PR is `0.5.21+11` but the commit from #2242 forgot to update their entry to `0.5.21+10` so the CI is expecting `+10`.

**Comment by jmagman** [comment]
> @iskakaushik The checks are failing because the version number in the `pubspec.yaml` in my PR is `0.5.21+11` but the commit from #2242 forgot to update their entry to `0.5.21+10` so the CI is expecting `+10`.

Fixing with a bump to +10 with https://github.com/flutter/plugins/pull/2267.
Once it merges, you can rebase on that commit.

**Comment by ened** [comment]
hi @scottmcarthur thank you for the PR! Could you please rebase? I think some test_driver files have been renamed. Thank you once again

**Comment by scottmcarthur** [comment]
@ened I have rebased.

**Comment by ened** [comment]
hi @scottmcarthur, almost there! Could you please double check that the new method is called during the e2e test? You have added the e2e method for `isBuildingsEnabled`, but it needs to be called within a new test within the `google_maps.dart` file.

**Comment by scottmcarthur** [comment]
@ened I updated [`packages/google_maps_flutter/example/test_driver/google_maps_e2e.dart`](https://github.com/flutter/plugins/pull/2264/commits/cb67abb8c897c7fffbdbc5b5a064ef50cc2d6dc5) which did not have test. I couldn't find a `google_maps.dart` file. Is this the right one?

**Comment by ened** [comment]
@scottmcarthur yes, is correct. Thank you or updating the test!

**Comment by scottmcarthur** [comment]
@ened Great. Thanks for your help.

**Comment by ened** [comment]
@scottmcarthur - please take a look at the failed tests. :)

**Comment by scottmcarthur** [comment]
@ened I am not sure why the 'testScreenCoordinate' would fail. The functionality I have added is a simple value not related to screen location. It should work in the same way as toggling traffic on/off. I am not sure how to resolve this.

**Pull request merged**
