### PR TITLE
[url_launcher] Mark Link as an invisible factory

### PR DESCRIPTION
**Pull request by hterkelsen**
This improves performance, as the Flutter engine is given a signal that it doesn't need to create an overlay to render links.

This optimization requires https://github.com/flutter/engine/pull/30003

Fixes https://github.com/flutter/flutter/issues/94640

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
> This optimization requires [flutter/engine#30003](https://github.com/flutter/engine/pull/30003)

Looks like the PR will need to stay open until 2.9 or later reaches stable.

**Comment by yjbanov** [comment]
Is it time to submit this?

**Comment by stuartmorgan** [comment]
> Is it time to submit this?

Was it cherry-picked to 2.8? If not, we need to wait for the next stable release.

**Comment by ditman** [comment]
This and https://github.com/flutter/packages/pull/529 are waiting for 2.10 to roll into `stable`.

**Comment by ditman** [comment]
Waiting for this benchmark to land:

https://github.com/flutter/flutter/pull/94638

**Comment by ditman** [comment]
Updating PR

**Review by ditman — APPROVED** [review]
Let's go! 2.10 is already stable!

**Comment by stuartmorgan** [comment]
Actually,  I forgot about the new retraction feature. I retracted 2.0.7, and we can just rev the min in a 2.0.8. I'll send a PR now.

**Pull request merged**
