### PR TITLE
[google_maps_flutter] Markers to respond based on consumeTapEvents parameter

### PR DESCRIPTION
**Pull request by JamesMcIntosh**
## Description

Markers when tapped are showing the info window even if the consumeTapEvents parameter has been set to false

## Related Issues

Fixes https://github.com/flutter/flutter/issues/39868

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [-] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by TahaTesser** [comment]
@stuartmorgan 
Do we need to reland this? If yes, I'm happy to help

**Comment by stuartmorgan** [comment]
Thanks for the submission! We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

Per repo policy, this would need tests validating the change as part of the PR. If you can add tests, we can find a reviewer, as this looks like a relatively straightforward change.

**Comment by stuartmorgan** [comment]
> @stuartmorgan
> Do we need to reland this? If yes, I'm happy to help

I'm not sure what you mean. When was this previously landed?

**Comment by TahaTesser** [comment]
@stuartmorgan 
I meant if we need to recreate this PR for a newer version

https://github.com/flutter/plugins/pull/2652#issuecomment-840630342 answered my question

Thanks

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
