### PR TITLE
[firebase_auth] Expose AdditionalUserInfo to Firebase User 

### PR DESCRIPTION
**Pull request by Nash0x7E2**
## Description

This PR exposes the user's [additional information](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/AdditionalUserInfo). Useful for retrieving whether the user is new to your app, their  IDP-specific user data and username (if the provider is Github or Twitter) .

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by CosmicPangolin** [comment]
@Nash0x7E2 @collinjackson 

Hey guys - I see some checks failed here that look pretty easy to solve.  Really hoping this makes it in, exposing the new user flag is quite helpful for me.

**Comment by collinjackson** [comment]
Thanks for this PR. The integration test I added is currently failing on iOS because there's no iOS implementation. Would you be open to adding one?

**Comment by Nash0x7E2** [comment]
Hi, 
Unfortunately I do not have a Mac so I am unable to implement this on iOS

**Comment by Nash0x7E2** [comment]
Is it possible for you to add this implementation? @collinjackson

**Comment by collinjackson** [comment]
I'm looking at this change more carefully and I think a different approach is needed. The `additionalUserInfo` object is a return value for an authentication attempt rather than a signed-in user. The authentication methods (`signInAnonymously` etc) and `onAuthStateChanged ` should return an instance of a new class (perhaps we can call this `AuthResult` like Android, `AuthDataResult` like iOS, or `UserCredential` like React Native Firebase) rather than a `FirebaseUser`. The new return value class should include properties `user` and optionally `additionalUserInfo` to mirror the native SDKs.

Unfortunately changing the return value of the sign-in methods is a breaking change that will affect every developer using this plugin. I'll try to get some feedback on naming internally so we don't have to do this more than once.

FYI @Ehesp

**Comment by jeroen-meijer** [comment]
I'd be willing to work on the iOS implementation once the naming issue has been resolved and breaking changes are made clear. 👋🏻

**Comment by Ehesp** [comment]
Hey - We took the `UserCredential` naming from the [Web SDK](https://firebase.google.com/docs/reference/js/firebase.auth.html?authuser=0#usercredential). This is do-able for Flutter but as Collin mentioned, the credential class needs to be returned from the authentication methods.

**Comment by collinjackson** [comment]
I got some feedback internally and we're going to call the result class `AuthResult`.

I went ahead and implemented the changes we've discussed in #1911. @jeroen-meijer I appreciate your generous offer to help; if you could take a quick look at #1911 and let me know if you have any feedback I'd appreciate it.

**Pull request closed without merging**
