### PR TITLE
[google_maps_flutter_web] Make google_maps_flutter_web work with latest plugins 

### PR DESCRIPTION
**Pull request by stuartmorgan**
google_maps_flutter_web NNBD migration is currently blocked, but this is an attempt to make a non-NNBD version that's uses the NNBD version of all dependencies for compatibility with the latest versions of other plugins.

## Testing

* Tested manually in google_maps_flutter example app, with `// @dart=2.9` in its main.dart file.
* All tests pass:

<details>

<summary>Output</summary>

```
plugins/packages/google_maps_flutter/google_maps_flutter_web/test$ ./run_test

chromedriver is running.
No target specified, running all tests...
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
flutter drive -d web-server '--web-port=7357' '--browser-name=chrome' '--target=test_driver/marker_integration.dart'
Running "flutter pub get" in test...                               773ms
Launching test_driver/marker_integration.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         18.7s
test_driver/marker_integration.dart is being served at http://localhost:7357
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
Application finished.
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +0: MarkerController onTap gets called"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +1: MarkerController onDragEnd gets called"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +2: MarkerController update"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +3: MarkerController infoWindow null, showInfoWindow."
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +4: MarkerController showInfoWindow"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +5: MarkerController hideInfoWindow"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +6: (tearDownAll)"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "Warning: integration_test test plugin was not detected."
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +7: All tests passed!"
All tests passed.
flutter drive -d web-server '--web-port=7357' '--browser-name=chrome' '--target=test_driver/markers_integration.dart'
Running "flutter pub get" in test...                               822ms
Launching test_driver/markers_integration.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         18.6s
test_driver/markers_integration.dart is being served at http://localhost:7357
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
Application finished.
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +0: MarkersController addMarkers"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +1: MarkersController changeMarkers"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +2: MarkersController removeMarkers"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +3: MarkersController InfoWindow show/hide"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +4: MarkersController only single InfoWindow is visible"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +5: MarkersController markers with icon:null work"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +6: MarkersController markers with custom bitmap icon work"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +7: MarkersController InfoWindow snippet can have links"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +8: MarkersController InfoWindow content is clickable"
All tests passed.
flutter drive -d web-server '--web-port=7357' '--browser-name=chrome' '--target=test_driver/shape_integration.dart'
Running "flutter pub get" in test...                               794ms
Launching test_driver/shape_integration.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         18.3s
test_driver/shape_integration.dart is being served at http://localhost:7357
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
Application finished.
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +0: CircleController onTap gets called"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +1: CircleController update"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +2: PolygonController onTap gets called"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +3: PolygonController update"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +4: PolylineController onTap gets called"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +5: PolylineController update"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +6: (tearDownAll)"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "Warning: integration_test test plugin was not detected."
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +7: All tests passed!"
All tests passed.
flutter drive -d web-server '--web-port=7357' '--browser-name=chrome' '--target=test_driver/shapes_integration.dart'
Running "flutter pub get" in test...                               729ms
Launching test_driver/shapes_integration.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         18.7s
test_driver/shapes_integration.dart is being served at http://localhost:7357
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
Application finished.
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +0: CirclesController addCircles"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +1: CirclesController changeCircles"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +2: CirclesController removeCircles"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +3: CirclesController Converts colors to CSS"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +4: PolygonsController addPolygons"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +5: PolygonsController changePolygons"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +6: PolygonsController removePolygons"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +7: PolygonsController Converts colors to CSS"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +8: PolygonsController Handle Polygons with holes"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +9: PolygonsController Polygon with hole has a hole"
All tests passed.
flutter drive -d web-server '--web-port=7357' '--browser-name=chrome' '--target=test_driver/google_maps_plugin_integration.dart'
Running "flutter pub get" in test...                               817ms
Launching test_driver/google_maps_plugin_integration.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         19.0s
test_driver/google_maps_plugin_integration.dart is being served at http://localhost:7357
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
Application finished.
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +0: GoogleMapsPlugin init/dispose before buildWidget init throws assertion"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +1: GoogleMapsPlugin init/dispose after buildWidget init initializes controller"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +2: GoogleMapsPlugin init/dispose after buildWidget cannot call methods after dispose"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +3: GoogleMapsPlugin buildView throws without _webOnlyMapCreationId"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +4: GoogleMapsPlugin buildView returns an HtmlElementView and caches the controller for later"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +5: GoogleMapsPlugin buildView returns cached instance if it already exists"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +6: GoogleMapsPlugin setMapStyles translates styles for controller"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +7: GoogleMapsPlugin Noop methods: updateTileOverlays"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +8: GoogleMapsPlugin Noop methods: updateTileOverlays"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +9: GoogleMapsPlugin Pass-through methods: updateMapOptions"
All tests passed.
flutter drive -d web-server '--web-port=7357' '--browser-name=chrome' '--target=test_driver/google_maps_controller_integration.dart'
Running "flutter pub get" in test...                               816ms
Launching test_driver/google_maps_controller_integration.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...         18.4s
test_driver/google_maps_controller_integration.dart is being served at http://localhost:7357
The web-server device requires the Dart Debug Chrome extension for debugging. Consider using the Chrome or Edge devices for an improved development workflow.
Application finished.
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +0: GoogleMapController construct/dispose constructor creates widget"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +1: GoogleMapController construct/dispose widget is cached when reused"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +2: GoogleMapController construct/dispose dispose closes the stream and removes the widget"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +3: GoogleMapController init listens to map events"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +4: GoogleMapController init binds geometry controllers to map's"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +5: GoogleMapController init renders initial geometry"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +6: GoogleMapController init empty infoWindow does not create InfoWindow instance."
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +7: GoogleMapController init Initialization options translates initial options"
[INFO]: http://localhost:7357/dart_sdk.js 28041:14 "00:00 +8: GoogleMapController init Initialization options disables gestureHandling with scrollGesturesEnabled false"
All tests passed.

```

</details>

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by stuartmorgan** [comment]
We should update scripts/nnbd.sh to remove this from the conflict list (and fix the fact that I forgot to move extension_google_sign_in_as_googleapis_auth up to the NNBD list)

**Comment by ditman** [comment]
@googlebot I consent. Jeez.

**Comment by ditman** [comment]
`And because every version of extension_google_sign_in_as_googleapis_auth from path depends on googleapis_auth ^1.0.0 which depends on crypto ^3.0.0, integration_test from path is incompatible with extension_google_sign_in_as_googleapis_auth from path.` Womp womp, reverting...

**Review by stuartmorgan — COMMENTED** [review]
Your changes LGTM

**Review by ditman — APPROVED** [review]
LGTM! Let's merge!

**Comment by ditman** [comment]
Published https://pub.dev/packages/google_maps_flutter_web/versions/0.2.0

**Pull request merged**
