### PR TITLE
Give the labeler access to PRs

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
RSLGTM (in that it seems to work; I didn't see any docs about this in a quick look).

flutter/packages will need this as well.

**Comment by Hixie** [comment]
A whole bunch of tests failed with `Unable to start WebDriver Session for Flutter for Web testing.`, any ideas? cc @yjbanov

**Comment by Hixie** [comment]
> RSLGTM (in that it seems to work; I didn't see any docs about this in a quick look).

Yeah me either. It's quite concerning how underdocumented the security aspects of GitHub actions are.

> flutter/packages will need this as well.

https://github.com/flutter/packages/pull/467

**Comment by stuartmorgan** [comment]
> A whole bunch of tests failed with `Unable to start WebDriver Session for Flutter for Web testing.`, any ideas? cc @yjbanov

That's a Cirrus issue; see https://github.com/flutter/plugins/pull/4349

**Comment by stuartmorgan** [comment]
The tree is green, so I'm going to land this to fix PRs. (I'm pretty sure this PR doesn't have a web regression hiding behind that failure 🙂)

**Pull request merged**
