### PR TITLE
Silent supported check + silent auth android

### PR DESCRIPTION
**Pull request by jeroentrappers**
Allow a silent check in the background to verify if the function is available, before prompting the user.

Added showDialog flag to allow to do the local authentication silently on android.

### CODE REVIEW

**Comment by kf6gpe** [comment]
@mehmetf, can you help us find someone to review this? Thanks!

**Comment by mehmetf** [comment]
Thanks for the contribution!

- Support checks are already added, please sync your client and revert that part of the checks.
- Silent auth is an interesting idea but without a prompt, how will the user know about the expected fingerprint check? Do you intend to show something via Flutter?

**Comment by jeroentrappers** [comment]
On Android this is the preferred way of working. No need to show an intrusive dialog. I built a screen that shows the fingerprint icon, as well as a keypad to enter a pincode. The user can choose to scan the fingerprint, or enter pincode manually.

**Comment by mehmetf** [comment]
Actually, on Android, you are expected to show a dialog. Otherwise the user cannot see partial status such as "Finger moved too fast". We don't current return these statuses back to Flutter and in the code you modified you are only returning "failure" state which is not enough.

Also, [see the shiny new API](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt) that Android provides now which we will migrate this plugin to (well; to the [compat version](https://developer.android.com/reference/androidx/biometrics/BiometricPrompt) anyway). This gives you no control over the dialog other than messaging. You have to have a prompt.

https://github.com/flutter/flutter/issues/18690

Given this, I will close this PR. As I mentioned the "supportedBiometrics" is a valid use case and is already in the plugin.

**Pull request closed without merging**
