### PR TITLE
[path_provider] Add missing pluginClass: none to path_provider_windows

### PR DESCRIPTION
**Pull request by stuartmorgan**
## Description

Older versions of Flutter (still supported by path_provider) need a
'pluginClass: none' to avoid "Invalid plugin specification" errors
when parsing a Dart-only desktop plugin like this one.

## Related Issues

Fixes https://github.com/flutter/flutter/issues/66158

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Adding a bunch of reviewers so whoever can get to it first can approve.

I don't understand how CI on the endorsement PR passed if stable still requires the `pluginClass: none` workaround.

**Comment by stuartmorgan** [comment]
Ah, I think this only happens for people who haven't updated to the current stable. 1.20 shouldn't need this. However, path_provider doesn't require 1.20+ currently, so this should still be added (so that the last version that claims to support older versions isn't broken on those versions).

**Comment by cyanglaz** [comment]
I think we can just make path_provider to require 1.20+ .

**Review by timsneath — APPROVED** [review]

**Comment by stuartmorgan** [comment]
> I think we can just make path_provider to require 1.20+ .

We could do that later, but if we don't push this first then the last published path_provider that supports 1.17 will be broken for 1.17, which is not a good situation to permanently leave the ecosystem in.

**Pull request merged**
