### PR TITLE
[camera] Adds autofocus support

### PR DESCRIPTION
**Pull request by josh-burton**
## Description

Adds the ability to change autofocus modes when using the camera.

A note on tests: I don't see any existing unit tests covering similar functionality. I'm happy to add some tests but would like some pointers on where to start.

## Related Issues

flutter/flutter#24575
https://github.com/flutter/plugins/pull/709/commits/b25fe889d8fb66776a5d6116648c1da0e87d7c04

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by iNima** [comment]
Please merge this pull request if it is possible!

**Comment by gummie4444** [comment]
https://github.com/gummie4444/flutter-better-camera

I took the most of the major pull requests and added support for flash/zoom/exposure and more in this fork. Meanwhile this is not merged in you can check it out.

**Comment by malikdoksoz** [comment]
How many months will we wait until the flash is added?

**Comment by whiteboypls** [comment]
Any updates on this? Not being able to focus a camera is pretty lousy UX

**Comment by myriky** [comment]
any updates?

**Comment by bparrishMines** [comment]
@athornz Thanks for the contribution!

Unfortunately this PR isn't trivial and our team is focused on other areas within the ecosystem right now. I'm labeling it with "backlog" and we will prioritize according to the issue's [priority](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process).

Relevant issue:

https://github.com/flutter/flutter/issues/24575

**Comment by mvanbeusekom** [comment]
Closing as duplicate of #3370

**Pull request closed without merging**
