### PR TITLE
[camera] setFlash function added camera plugin

### PR DESCRIPTION
**Pull request by altanod**
## Description

*Flashlight on and off feature added camera plugin*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by altanod** [comment]
@googlebot I signed it!

**Comment by malikdoksoz** [comment]
Flutter is doing his best not to add this feature.

**Comment by gummie4444** [comment]
https://github.com/gummie4444/flutter-better-camera

I took the most of the major pull requests and added support for flash/zoom/exposure and more in this fork. Meanwhile this is not merged in you can check it out.

**Comment by JSBmanD** [comment]
Any updates on flash feature?

**Comment by mvanbeusekom** [comment]
Closing this PR in favor of #3314

**Pull request closed without merging**
