### PR TITLE
fix message structure from intent

### PR DESCRIPTION
**Pull request by pepegich**
Fixes https://github.com/flutter/flutter/issues/23148

### CODE REVIEW

**Comment by collinjackson** [comment]
@pepegich Thanks you for your contribution. I'd like to merge it, but first I need you to agree to the Contributor License Agreement (CLA). Could you please do that? Thanks!

**Comment by pepegich** [comment]
I signed it!

**Comment by pepegich** [comment]
> @pepegich Thanks you for your contribution. I'd like to merge it, but first I need you to agree to the Contributor License Agreement (CLA). Could you please do that? Thanks!

@collinjackson I do it!

**Comment by grundid** [comment]
By reading the changelog of this breaking change, I though that the message structure of the onMessage map has changes but by looking at the code it is the other way round. 

> Breaking Change Update message structure for onMessage to match onLaunch and onResume

This was a little bit misleading since we only use the onMessage callback and we didn't see any change after updating to this release. Could you please check if the changelog is correct?

**Comment by pepegich** [comment]
@grundid seems need change log to: 

> Breaking Change Update message structure for onResume and onLaunch to match onMessage

**Comment by josejbarneto** [comment]
I'm still having [#23148](https://github.com/flutter/flutter/issues/23148) problem, isnt fixed yet?

**Comment by collinjackson** [comment]
This PR was merged awhile ago -- please file a new issue with steps to reproduce if you're seeing problems.

**Pull request merged**
