### PR TITLE
[flutter_webview] Raise min Flutter SDK to stable

### PR DESCRIPTION
**Pull request by mklim**
## Description

v2 embedding apps no longer need to special case their Flutter SDK
requirement like they have since v0.3.15+3.

## Related Issues

flutter/flutter#47153
flutter/flutter#42348
flutter/flutter#42694

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by ened** [comment]
@mklim Do you think major SDK bumps warrant a major version bump (e.g. `0.4.0`)

**Comment by xster** [comment]
A few more things we should probably do https://github.com/flutter/flutter/issues/47153#issuecomment-566696399

**Comment by mklim** [comment]
@ened I was wondering that too. The [semver spec](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api) says no:

> Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. I would usually expect additional code for the latter instance, in which case it’s obviously a minor level increment.

Since pub should be resolving Flutter SDK dependencies normally I think it makes sense to follow semver here.

All the actual changes in this amount to internal refactoring so I kept it as a patch bump.

@xster good catch, marking this as a WIP until I resolve those other steps.

**Comment by mklim** [comment]
OK, this should be ready for review now.

**Comment by xster** [comment]
FWIW, Emmanuel makes a valid point in https://github.com/flutter/plugins/pull/2400. If you merge this now, people on 1.9 stable will break.

**Comment by mklim** [comment]
> FWIW, Emmanuel makes a valid point in #2400. If you merge this now, people on 1.9 stable will break.

Sorry, I can't find a comment about this there. @blasten or @xster do you mind copy pasting it?

I don't think this should break anyone on 1.9, because it's bumping the minimum Flutter SDK version in the `pubspec.yaml` to `1.12`. Anyone on 1.9 shouldn't be able to get this version of the plugin because pub will be able to tell that their Flutter SDK version is too low.

**Comment by xster** [comment]
ya I deleted the comment and hoped it's forever erased from everyone's memory after typing it and realizing that it's no long valid since we moved the sdk restriction up :)

**Comment by mklim** [comment]
Lol all good, thanks. :)

**Pull request merged**
