### PR TITLE
[local_auth] Catching crashing exception when result was already previously returned in Android

### PR DESCRIPTION
**Pull request by cspensky**
## Description

When a user without a biometric enrolled attempts to authenticate, the `result` is currently returned twice: first when the biometric fails, and again when the user selects `Cancel` or `Goto Settings`.  This catches the second exception to make sure the app doesn't crash

## Related Issues

Not sure of any

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ x] All existing and new tests are passing.
- [x ] I updated/added relevant documentation (doc comments with `///`).
- [ x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ x] I read and followed the [Flutter Style Guide].
- [ x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ x] I updated CHANGELOG.md to add a description of the change.
- [ x] I signed the [CLA].
- [ x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by cyanglaz** [comment]
I'm going to close the PR because the CLA is not signed. Feel free to ping me when the CLA is signed and I'll re-open the PR. Or you can open a new PR after signing the CLA.

**Comment by cspensky** [comment]
Thanks for pointing that out, I thought I already signed it. Signed and
ready to go. Please reopen the merge request.

**Comment by cyanglaz** [comment]
@cspensky thanks for the quick turnaround ;)

**Comment by cyanglaz** [comment]
@cspensky The CLA bot is still not happy. Could you add a comment like this:
```
@googlebot I fixed it.
```

**Comment by cspensky** [comment]
@googlebot I fixed it.

**Comment by stuartmorgan** [comment]
Thanks for the contribution!

> When a user without a biometric enrolled attempts to authenticate, the `result` is currently returned twice: first when the biometric fails, and again when the user selects `Cancel` or `Goto Settings`.

Thanks, that's very helpful! I've added this to https://github.com/flutter/flutter/issues/76299

> This catches the second exception to make sure the app doesn't crash

Returning a result twice is a programming error; it's a violation of the API contract. The fix needs to be to not do that, rather than to mask the problem. Given that, I'm going to close this PR. I plan to look into fixing this shortly, but if you are interested in working on a complete fix before then, please feel free to submit a new PR. (If you do, please be sure to follow the checklist; you checked every box here, but didn't actually do the steps.)

**Comment by cspensky** [comment]
Thank you for the comment!  Unfortunately, I won't have time in the near future, as this quick fix was sufficient for the time being.  I am unsure which item in the checklist I didn't do, but I will try to be more rigorous in the future.  Are you suggesting there should be a test case to reproduce the bug?

**Comment by stuartmorgan** [comment]
Specifically, I was referring to:
> [x ] My PR includes unit or integration tests for all changed/updated/fixed behaviors (See Contributor Guide).
> ...
> [ x] I updated pubspec.yaml with an appropriate new version according to the pub versioning philosophy.
> [ x] I updated CHANGELOG.md to add a description of the change.

**Pull request closed without merging**
