### PR TITLE
[camera_web] Update camera_web to support Dart's new async requestFullscreen API

### PR DESCRIPTION
**Pull request by jason-simmons**
No version change: No change to plugin functionality

### CODE REVIEW

**Review by gaaclarke — APPROVED** [review]

**Comment by gaaclarke** [comment]
fyi the `publishable` step won't pick up the change in a commit message without pushing to the branch

**Comment by Hixie** [comment]
test-exempt: refactor with no semantic change

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
Please do add a changelog entry since you are changing code; it makes it easier to pinpoint issues if there's some unintended behavioral change.

**Comment by jason-simmons** [comment]
Updated `packages/camera/camera_web/CHANGELOG.md`

**Pull request merged**
