### PR TITLE
Custom Cursor for [mac] and [web]

### PR DESCRIPTION
**Pull request by rodydavis**
Example:

```dart
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'package:custom_cursor/custom_cursor.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Center(
          child: Container(
            width: 400,
            child: _buildBody(),
          ),
        ),
      ),
    );
  }

  Widget _buildBody() {
    if (kIsWeb) {
      return _buildWebBody();
    }
    if (Platform.isMacOS) {
      return _buildMacOSBody();
    }
    return Wrap(
      children: CursorType.values.map((t) {
        return Padding(
          padding: const EdgeInsets.all(8.0),
          child: MouseRegion(
            onEnter: (_) => CustomCursorPlugin().setCursor(t),
            onExit: (_) => CustomCursorPlugin().resetCursor(),
            child: Text(describeEnum(t)),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildWebBody() {
    return Wrap(
      children: WebCursor.values.map((t) {
        return Padding(
          padding: const EdgeInsets.all(8.0),
          child: MouseRegion(
            onEnter: (_) =>
                CustomCursorPlugin().setWebCursor(WebCursor.custom(t)),
            onExit: (_) => CustomCursorPlugin().resetCursor(),
            child: Text(t),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildMacOSBody() {
    return Wrap(
      children: MacOSCursor.values.map((t) {
        return Padding(
          padding: const EdgeInsets.all(8.0),
          child: MouseRegion(
            onEnter: (_) =>
                CustomCursorPlugin().setMacOSCursor(MacOSCursor.custom(t)),
            onExit: (_) => CustomCursorPlugin().resetCursor(),
            child: Text(t),
          ),
        );
      }).toList(),
    );
  }
}

```

Supports all web cursors: 

```
       'all-scroll',
        'auto',
        'cell',
        'context-menu',
        'col-resize',
        'copy',
        'crosshair',
        'default',
        'e-resize',
        'ew-resize',
        'grab',
        'grabbing',
        'help',
        'move',
        'n-resize',
        'ne-resize',
        'nesw-resize',
        'ns-resize',
        'nw-resize',
        'nwse-resize',
        'no-drop',
        'none',
        'not-allowed',
        'pointer',
        'progress',
        'row-resize',
        's-resize',
        'se-resize',
        'sw-resize',
        'text',
        'w-resize',
        'wait',
        'zoom-in',
        'zoom-out',
```

Support all MacOS system cursors:

```
       'arrow',
        'beam-vertical',
        'cross-hair',
        'closed-hand',
        'open-hand',
        'pointing-hand',
        'resize-left',
        'resize-right',
        'resize-down',
        'resize-up',
        'resize-left-right',
        'resize-up-down',
        'beam-horizontial',
        'disappearing-item',
        'not-allowed',
        'drag-link',
        'drag-copy',
        'context-menu',
```

And includes an enum with all shared cursors across platforms:

```dart
enum CursorType {
  arrow,
  cross,
  hand,
  resizeLeft,
  resizeRight,
  resizeDown,
  resizeUp,
  resizeLeftRight,
  resizeUpDown,
  custom,
}
```

In the example I include how to do a mouse region and set and unset the cursor.

### CODE REVIEW

**Comment by rodydavis** [comment]
@googlebot I fixed it

**Comment by rodydavis** [comment]
@googlebot I fixed it.

**Comment by stuartmorgan** [comment]
Custom cursor support is being built into the framework; it doesn't make sense to make a new plugin that we would remove again in the near future. If you want to contribute to the implementation the way forward would be to coordinate with @dkwingsmt on the design and/or implementation of the framework feature.

**Comment by rodydavis** [comment]
I needs platform channels though? Where would it live? The engine, or material?

**Comment by stuartmorgan** [comment]
I'm not sure what you're asking exactly. It would use a system channel presumably, like the other framework features that require native embedding code.

**Comment by rodydavis** [comment]
One nice thing about it being a plugin is that it can be customized, easily extended and also the source separate from the engine so that others can add custom cursors that are beyond the system ones.

**Comment by rodydavis** [comment]
@googlebot I fixed it.

**Comment by stuartmorgan** [comment]
> One nice thing about it being a plugin is that it can be customized, easily extended

Since plugins allow extending the capabilities of the engine+framework, I'm not understanding why building the functionality into Flutter would prevent that. Can you provide concrete examples of things that would be possible if it's a plugin, but not if it's built in?

> and also the source separate from the engine so that others can add custom cursors that are beyond the system ones.

Again, I'm not clear on how these things are coupled. Why do you believe it will be impossible to add non-system cursors if it's not a plugin?

**Comment by rodydavis** [comment]
I don't think it is impossible to add if it is in the engine, just if it is a plugin you can have the calls in the same place. Otherwise if you do a custom cursor you will have to set up the platform channel anyway. 

One example of something you can do if it is a plugin:

- Cursor Loaded from Image or SVG

But I think if it is apart of the framework that is correct too. Also it could prevent conflicts of different plugins updating the cursor at the same time.

I just think if someone wants to update a cursor with their own branding or images then they will need a plugin regardless. Maybe if it is in the engine it could just expose loading it from an asset then you are right there would be no need for a plugin.

**Comment by orestesgaolin** [comment]
Just to let everybody know - there's a new PR in flutter repo that adds custom cursor support https://github.com/flutter/flutter/pull/54171

**Comment by cyanglaz** [comment]
I'm going to close the PR because the CLA is not signed. Feel free to ping me when the CLA is signed and I'll re-open the PR. Or you can open a new PR after signing the CLA.

**Pull request closed without merging**
