### PR TITLE
[video_player] Implement support for RTSP on Android

### PR DESCRIPTION
**Pull request by kjeremy**
Adds RTSP streaming support for Android.

*List which issues are fixed by this PR. You must list at least one issue.*

https://github.com/flutter/flutter/issues/82567

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by kjeremy** [comment]
@googlebot I signed it!

**Comment by kjeremy** [comment]
The formatter crashes on my windows machine. I'm 100% fine with someone else running it and pushing it to this branch.

**Comment by kjeremy** [comment]
Tests pass. This is ready for review.

**Comment by kjeremy** [comment]
@stuartmorgan I'm not sure if you're a reviewer or not but I'd like one.

**Review by blasten — APPROVED** [review]
Java side LGTM

**Review by stuartmorgan — CHANGES_REQUESTED** [review]
This PR has no tests, so cannot land as is. See the repository's contributing guide for more details.

**Comment by blasten** [comment]
Ah. I missed the test part

**Comment by stuartmorgan** [comment]
I'm not sure if this was intended to be ready for review again (I see you pushed another change, but since you didn't comment I'm not sure if it's still a WIP), but it'll need coverage of the native changes as well. E.g., extracting `buildMediaSource` to a unit-testable utility to test the mappings.

**Comment by kjeremy** [comment]
It is not (since it's missing tests). I'm not sure if I have the time to
write them anytime soon.

**Comment by stuartmorgan** [comment]
FYI for when you do have time to come back to this—or when someone else has time to add the missing test—I'm extracting the ExoPlayer-update-related changes you made here to https://github.com/flutter/plugins/pull/4141 since we're having build issues caused by the server hosting the older version of ExoPlayer (which is why I was looking at this PR again). So this will end up with conflicts, but they should be trivial to resolve with a rebase.

(I cherry-picked the commit and then reverted the feature change portions, so your authorship is retained. Thank you for the contribution!)

**Comment by stuartmorgan** [comment]
@kjeremy I see you pushed an update here at some point; is this ready for review?

**Comment by kjeremy** [comment]
I haven't looked at this in a while and do not have the time to pursue. If
I recall some tests were wanted. Feel free to take it over.

**Comment by stuartmorgan** [comment]
I noticed that the last push was "Add test"; I wasn't sure if that was a WIP (since you hadn't commented about it being ready for review), or addressed the previous comments.

**Comment by kjeremy** [comment]
Maybe it's good to go then.

**Comment by stuartmorgan** [comment]
I took a look at the current diff; there's a Dart test that the string is passed to the method channel, but it also needs either an integration test or Java unit test since currently the actual functionality of the change doesn't have any test coverage.

I'll leave this open to adopt since it's nearly done though. Anyone in the community is welcome to contribute a test to get this landed sooner, otherwise someone on the team will add tests when we get to this point in the backlog.

**Comment by NaarGes** [comment]
hi, I need this feature and I couldn't find any other player that plays RTSP stream properly.
Is there any estimation on when this feature will be implemented?

**Comment by stuartmorgan** [comment]
> Is there any estimation on when this feature will be implemented?

Please see my comment directly above.

**Comment by stuartmorgan** [comment]
@blasten If you could allocate eng resources to getting this over the line (adding the necessary testing), that would be great; it should be relatively straightforward.

**Comment by stuartmorgan** [comment]
This isn't currently a priority for the team, as this isn't a high-requested feature, so we're not going to be able to take over the PR. I'm going to close this, but I encourage anyone interested in this feature to open a new PR based on this one, but including tests that address https://github.com/flutter/plugins/pull/3933#issuecomment-923245081.

**Pull request closed without merging**
