### PR TITLE
[draft] accessing a pubspec version at runtime

### PR DESCRIPTION
**Pull request by Salakar**
## Description

This PR is for example purposes (requested by @collinjackson) and is not intended to be merged.

This PR demos retrieving the `pubspec` version at runtime in Android & iOS - to be used for things like the Firebase plugin registrar.

### Notes

 - Only added this to one package, `cloud_firestore` - just as a demo
 - Android gradle code can be moved into a single gradle plugin - then it becomes a 1/2 line change for each package (we do this on RNFirebase)
 - iOS Bunde & version code could be moved into a shared package and exposed as a utility (e.g. on Firebase Core)
 - The `podspec` changes on its own might be a good one to apply already as is for all Flutter plugins - saves duplicating versions, descriptions, authors etc.

### Screenshots

Added some screenshots to show each platform works as expected.

#### Pod install

image

#### iOS via `NSBundle`

image

#### Android via `BuildConfig`

image

## Related Issues

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by kroikie** [comment]
@Salakar we did something similar in https://github.com/flutter/plugins/pull/1733 your comments are welcome.

**Comment by Salakar** [comment]
@kroikie left some reviews on the other PR but it looks like it's got merged soon after 🙈

The `new File()` at least needs fixing for Windows

**Comment by kroikie** [comment]
@Salakar Yeah I just merged it :). I will have a look at the comments thanks! I'll make the updates in a follow up PR.

**Comment by Salakar** [comment]
Looks like 2 new PRs have popped up to fix the incorrect pathing on the other PR: #1740 #1741

**Comment by collinjackson** [comment]
Thanks @Salakar.

I've rolled back the other release (#1742) for now while we review this approach.

**Comment by kroikie** [comment]
I'm going to apply this to the `firebase_remote_config` plugin. If all goes well there I'll move it to other plugins.

**Comment by kroikie** [comment]
@Salakar on the iOS side was there any additional configuration required to use `[[NSBundle mainBundle] pathForResource:@"cloud_firestore" ofType:@"bundle"];`?

**Comment by kroikie** [comment]
Giving this another go :)

Here is the implementation of accessing the pubspec version for the FRC plugin:
https://github.com/flutter/plugins/pull/1748

**Comment by collinjackson** [comment]
> @Salakar on the iOS side was there any additional configuration required to use `[[NSBundle mainBundle] pathForResource:@"cloud_firestore" ofType:@"bundle"];`?

Short answer is yes, I've added the missing line here: aedbe20

**Comment by kroikie** [comment]
@collinjackson I may be doing something wrong but for me the `CFBundleShortVersionString` is truncated to `x.y.z` any additional version parts are dropped. Eg: `0.2.0+3` is retrieved as `0.2.0`. Are you seeing something different?

**Comment by collinjackson** [comment]
I'm seeing the same thing; it looks like Apple doesn't allow additional characters in the version name.

https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring

We could either just live with the extra version info being dropped or go ahead with the header version. I guess I'm ok with the header version given this limitation on `NSBundle`.

**Comment by kroikie** [comment]
I would prefer the header version approach since:
- we get the full version reported
- it ensures both Android and iOS to report the same version (the one defined in the pubspec)

**Comment by collinjackson** [comment]
closing this since we've now landed #1748

**Pull request closed without merging**
