### PR TITLE
[google_maps_flutter] Improve google maps readme example

### PR DESCRIPTION
**Pull request by michalsrutek**
Improved google maps example in readme - used const where appropriate, removed unnecessary new keyword, etc.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by cyanglaz — CHANGES_REQUESTED** [review]
Thanks for this PR! These are all great updates.
Do you mind to add a version updates for this PR. The README change won't be picked up by pub unless a new version is released. It should be a patch version change.

**Comment by stuartmorgan** [comment]
I'm working on rolling out `code-excerpter` in this repository, which will allow maintaining README code in a much less error-prone way. I'd like to hold off on this PR until early next week, as we can likely implement these changes in a more robust way at that point.

**Comment by stuartmorgan** [comment]
The new `code-excerpt` system is in place now, so the fix here would be to switch this code block to an excerpt-based example. See https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#readme-code for instructions on that process.

I'll mark this as a Draft for now; once you've done that please mark it as ready for review. Thanks!

**Comment by stuartmorgan** [comment]
Since this is marked as a draft and hasn't been updated in several months I'm going to close it to clean out our review queue. Please don't hesitate to submit a new PR if you decide to revisit this. Thanks!

**Pull request closed without merging**
