### PR TITLE
Revert "[e2e] Replaces the check for ActivityTestRule"

### PR DESCRIPTION
**Pull request by cyanglaz**
Reverts flutter/plugins#2633

Post submit fails after this. Log
```
./script/incremental_build.sh analyze
Running for all packages
Verifying analysis settings...
Activating tuneup package...
Resolving dependencies...
+ analysis_server_lib 0.1.9
+ args 1.6.0
+ charcode 1.1.3
+ cli_util 0.1.3+2
+ collection 1.14.12
+ intl 0.15.8 (0.16.1 available)
+ logging 0.11.4
+ meta 1.1.8
+ path 1.7.0
+ source_span 1.7.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ tuneup 0.3.6+1
+ yaml 2.2.0
Downloading tuneup 0.3.6+1...
Downloading cli_util 0.1.3+2...
Downloading analysis_server_lib 0.1.9...
Precompiling executables...
Precompiled tuneup:tuneup.
Installed executable tuneup.
Activated tuneup 0.3.6+1.
Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):
  export PATH="$PATH":"$HOME/.pub-cache/bin"
Downloading package sky_engine...                                   0.4s
Downloading flutter_patched_sdk tools...                            0.8s
Downloading flutter_patched_sdk_product tools...                    0.6s
Downloading linux-x64 tools...                                      0.9s
Downloading linux-x64/font-subset tools...                          0.1s
Running "flutter pub get" in android_alarm_manager...               1.0s
Running "flutter pub get" in example...                             1.6s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in android_intent...                      1.6s
Running "flutter pub get" in example...                             1.3s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in battery...                             1.5s
Running "flutter pub get" in example...                             1.2s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in camera...                              2.2s
Running "flutter pub get" in example...                             1.3s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in connectivity...                        1.7s
Running "flutter pub get" in example...                             1.7s
Running "flutter pub get" in example...                             1.0s
Running "flutter pub get" in connectivity_macos...                  0.7s
Running "flutter pub get" in example...                             1.8s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in connectivity_platform_interface...         0.9s
Running "flutter pub get" in device_info...                         1.5s
Running "flutter pub get" in example...                             1.1s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in e2e...                                 1.1s
Running "flutter pub get" in example...                             1.7s
Running "flutter pub get" in e2e_macos...                           0.6s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in espresso...                            0.9s
Running "flutter pub get" in example...                             1.2s
Running "flutter pub get" in example...                             0.6s
Running "flutter pub get" in flutter_plugin_android_lifecycle...         0.9s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in example...                             0.5s
Running "flutter pub get" in google_maps_flutter...                 1.7s
Running "flutter pub get" in example...                             1.6s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in google_sign_in...                      1.3s
Running "flutter pub get" in example...                             1.3s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in google_sign_in_platform_interface...         0.9s
Running "flutter pub get" in google_sign_in_web...                  1.2s
Running "flutter pub get" in image_picker...                        1.0s
Running "flutter pub get" in example...                             1.3s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in in_app_purchase...                     2.2s
Running "flutter pub get" in example...                             1.7s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in ios_platform_images...                 0.9s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in example...                             0.5s
Running "flutter pub get" in local_auth...                          1.3s
Running "flutter pub get" in example...                             1.2s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in package_info...                        1.6s
Running "flutter pub get" in example...                             1.6s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in path_provider...                       1.7s
Running "flutter pub get" in example...                             1.6s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in path_provider_macos...                 0.6s
Running "flutter pub get" in example...                             1.7s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in path_provider_platform_interface...         1.5s
Resolving dependencies...
+ _fe_analyzer_shared 2.1.0
+ analyzer 0.39.6
+ args 1.6.0
+ async 2.4.1
+ boolean_selector 2.0.0
+ charcode 1.1.3
+ collection 1.14.12
+ convert 2.1.1
+ coverage 0.13.9
+ crypto 2.1.4
+ csslib 0.16.1
+ glob 1.2.0
+ html 0.14.0+3
+ http 0.12.0+4
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ io 0.3.4
+ js 0.6.1+1
+ logging 0.11.4
+ matcher 0.12.6
+ meta 1.1.8
+ mime 0.9.6+3
+ mockito 4.1.1
+ multi_server_socket 1.0.2
+ node_interop 1.0.3
+ node_io 1.0.1+2
+ node_preamble 1.4.8
+ package_config 1.9.3
+ path 1.7.0
+ pedantic 1.9.0
+ pool 1.4.0
+ pub_semver 1.4.4
+ shelf 0.7.5
+ shelf_packages_handler 2.0.0
+ shelf_static 0.2.8
+ shelf_web_socket 0.2.3
+ source_map_stack_trace 2.0.0
+ source_maps 0.10.9
+ source_span 1.7.0
+ stack_trace 1.9.3
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ test 1.14.2
+ test_api 0.2.15
+ test_core 0.3.3
+ typed_data 1.1.6
+ vm_service 4.0.1
+ watcher 0.9.7+14
+ web_socket_channel 1.1.0
+ webkit_inspection_protocol 0.5.0+1
+ yaml 2.2.0
Changed 52 dependencies!
Running "flutter pub get" in quick_actions...                       1.5s
Running "flutter pub get" in example...                             1.2s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in sensors...                             1.5s
Running "flutter pub get" in example...                             1.2s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in share...                               1.5s
Running "flutter pub get" in example...                             1.2s
Running "flutter pub get" in example...                             0.6s
Running "flutter pub get" in shared_preferences...                  1.6s
Running "flutter pub get" in example...                             1.7s
Running "flutter pub get" in example...                             1.0s
Running "flutter pub get" in shared_preferences_macos...            0.7s
Running "flutter pub get" in example...                             1.7s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in shared_preferences_platform_interface...         0.9s
Running "flutter pub get" in shared_preferences_web...              0.9s
Running "flutter pub get" in url_launcher...                        1.6s
Running "flutter pub get" in example...                             1.3s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in url_launcher_macos...                  0.6s
Running "flutter pub get" in example...                             1.4s
Running "flutter pub get" in example...                             0.7s
Running "flutter pub get" in url_launcher_platform_interface...         0.9s
Running "flutter pub get" in url_launcher_web...                    1.1s
Running "flutter pub get" in video_player...                        0.9s
Running "flutter pub get" in example...                             1.7s
Running "flutter pub get" in example...                             0.9s
Running "flutter pub get" in video_player_platform_interface...         0.9s
Running "flutter pub get" in video_player_web...                    1.0s
Running "flutter pub get" in webview_flutter...                     1.2s
Running "flutter pub get" in example...                             1.2s
Running "flutter pub get" in example...                             0.7s
Checking project android_alarm_manager...
No issues found; analyzed 10 source files in 24.4s.
Checking project android_intent...
No issues found; analyzed 10 source files in 13.5s.
Checking project battery...
No issues found; analyzed 8 source files in 4.9s.
Checking project camera...
No issues found; analyzed 21 source files in 13.9s.
Checking project connectivity...
No issues found; analyzed 10 source files in 5.1s.
Checking project connectivity_macos...
No issues found; analyzed 8 source files in 5.9s.
Checking project connectivity_platform_interface...
No issues found; analyzed 6 source files in 3.9s.
Checking project device_info...
No issues found; analyzed 8 source files in 4.6s.
Checking project e2e...
No issues found; analyzed 22 source files in 14.9s.
Checking project espresso...
No issues found; analyzed 8 source files in 4.2s.
Checking project flutter_plugin_android_lifecycle...
No issues found; analyzed 9 source files in 4.0s.
Checking project google_maps_flutter...
No issues found; analyzed 48 source files in 15.0s.
Checking project google_sign_in...
No issues found; analyzed 14 source files in 7.0s.
Checking project google_sign_in_platform_interface...
No issues found; analyzed 7 source files in 4.3s.
Checking project google_sign_in_web...
No issues found; analyzed 13 source files in 13.8s.
Checking project image_picker...
No issues found; analyzed 9 source files in 5.1s.
Checking project in_app_purchase...
No issues found; analyzed 37 source files in 15.4s.
Checking project ios_platform_images...
No issues found; analyzed 13 source files in 4.4s.
Checking project local_auth...
No issues found; analyzed 10 source files in 5.5s.
Checking project package_info...
No issues found; analyzed 9 source files in 4.6s.
Checking project path_provider...
No issues found; analyzed 10 source files in 5.0s.
Checking project path_provider_macos...
No issues found; analyzed 8 source files in 4.4s.
Checking project path_provider_platform_interface...
No issues found; analyzed 5 source files in 3.9s.
Checking project plugin_platform_interface...
No issues found; analyzed 3 source files in 3.5s.
Checking project quick_actions...
No issues found; analyzed 9 source files in 4.6s.
Checking project sensors...
No issues found; analyzed 10 source files in 4.9s.
Checking project share...
No issues found; analyzed 9 source files in 4.7s.
Checking project shared_preferences...
No issues found; analyzed 9 source files in 4.9s.
Checking project shared_preferences_macos...
No issues found; analyzed 7 source files in 4.4s.
Checking project shared_preferences_platform_interface...
No issues found; analyzed 5 source files in 3.8s.
Checking project shared_preferences_web...
No issues found; analyzed 4 source files in 5.8s.
Checking project url_launcher...
No issues found; analyzed 10 source files in 5.3s.
Checking project url_launcher_macos...
No issues found; analyzed 8 source files in 4.2s.
Checking project url_launcher_platform_interface...
No issues found; analyzed 4 source files in 3.7s.
Checking project url_launcher_web...
No issues found; analyzed 4 source files in 3.8s.
Checking project video_player...
No issues found; analyzed 15 source files in 6.1s.
Checking project video_player_platform_interface...
No issues found; analyzed 4 source files in 4.2s.
Checking project video_player_web...
  error - The name 'webOnlyAssetManager' is being referenced through the prefix 'ui', but it isn't defined in any of the libraries imported using that prefix at lib/video_player_web.dart:81:23 - (undefined_prefixed_name)
  error - The name 'platformViewRegistry' is being referenced through the prefix 'ui', but it isn't defined in any of the libraries imported using that prefix at lib/video_player_web.dart:162:8 - (undefined_prefixed_name)
2 issues found; analyzed 4 source files in 4.3s.
Checking project webview_flutter...
No issues found; analyzed 13 source files in 14.5s.
The following packages have analyzer errors (see above):
 * video_player_web```

### CODE REVIEW

**Comment by cyanglaz** [comment]
Might not be related, closing to further investigate before reopening.

**Comment by cyanglaz** [comment]
The plugin hasn't been published, save to revert.

**Comment by cyanglaz** [comment]
land to fix ci.

**Comment by blasten** [comment]
The warning in the CI is a different issue though. It's still happening upstream: https://cirrus-ci.com/task/4874613897297920

**Comment by cyanglaz** [comment]
@bashtian ok, could be a flutter update?

**Comment by ditman** [comment]
Details about the breakage here: https://github.com/flutter/plugins/pull/2658

**Pull request merged**
