### PR TITLE
Updated Gradle tooling to match Android Studio 3.4

### PR DESCRIPTION
**Pull request by ened**
## Description

As a follow up PR to https://github.com/flutter/flutter/pull/32550, this updates ALL the plugins gradle & gradle plugin versions to the latest.

It's unfortunately quite a beast to review, therefore please let me know if this needs to be split in any way.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by ened** [comment]
@iskakaushik Could I trouble you to chime in on the approach for this PR? The plugins should all be using the latest gradle plugin versions. But the PR is quite huge I think. Should it rather be 1 PR per package?

**Comment by iskakaushik** [comment]
@ened , there are a couple of things to consider while evaluating this change:

1. Any changes to the classes that the plugins depend on during runtime. This would not be caught by our integration tests as they stand because we only test on iOS. Any secondly, I don't think all our plugins have integration tests. So we would have to make this change to only the plugins that have them.

2. Gradle version mismatches between built version of app and plugin. e.g, Testing against are build using an older version of gradle but has plugins depending on a newer version of gradle. We do not have the infrastructure in place to do this currently.

3. Testing against apps that use stable version of flutter framework. We do not have infrastructure in place for this as well.

We are working on addressing a few of these, but we will not be able to merge this changes until we have a reasonable answer for this.

Thanks!

**Comment by collinjackson** [comment]
1. I ran the Android tests locally and observed some pre-existing failures (none of which seem to be affected by this change). Filed issues for them: https://github.com/flutter/flutter/issues/32181 https://github.com/flutter/flutter/issues/32657 https://github.com/flutter/flutter/issues/32659

I think that most issues relating to the gradle update issues are likely to show up as compile failures or runtime failures that won't be exercised by our one-plugin-at-a-time examples.

2. I tried downgrading example apps and they seem to be able to interoperate with the upgraded plugins.

3. I ran the Android integration tests locally against Flutter stable and saw no regressions from the above.

**Comment by amirh** [comment]
As an extra precautionary I'd suggest starting with upgrading just one plugin and then wait 2(?) weeks to see that nothing bad we didn't anticipate happens.
(we've been burned with these kind of changes that I'd rather be safe than sorry)

**Comment by collinjackson** [comment]
> As an extra precautionary I'd suggest starting with upgrading just one plugin and then wait 2(?) weeks to see that nothing bad we didn't anticipate happens.
> (we've been burned with these kind of changes that I'd rather be safe than sorry)

sgtm, I'll open a PR for just one plugin

**Comment by collinjackson** [comment]
I've landed #1653, putting this PR on hold until we've had time to gather feedback on that change.

**Comment by collinjackson** [comment]
I haven't had any negative feedback on #1653 so I think this PR should be ok to merge. 

@ened do you have the bandwidth to address the merge conflicts?

**Comment by ened** [comment]
@collinjackson - yes, to be handled tomorrow.

**Pull request closed without merging**
