### PR TITLE
video_player: Allow audio playback in silent mode

### PR DESCRIPTION
**Pull request by cbenhagen**
This is the default behaviour of video apps on iOS. 
(fixes https://github.com/flutter/flutter/issues/17911)

I considered setting the category back to `AVAudioSessionCategorySoloAmbient` on `dispose` but this led to race conditions when switching between videos.

### CODE REVIEW

**Comment by cbenhagen** [comment]
@mravn-google done ;)

**Comment by mravn-google** [comment]
This branch seems to need a rebase now. Sorry.

**Comment by cbenhagen** [comment]
No worries. Branch has been rebased.

**Comment by mravn-google** [comment]
Thanks. Of course your two PRs are now conflicting...

**Comment by cbenhagen** [comment]
Was to be expected yes. Merged in the master branch again.

**Comment by cbenhagen** [comment]
As the other PR has already been released I bumped the version again. Also fixed a small typo in the changelog.

**Pull request merged**
