### PR TITLE
Fix image picker crash on IOS

### PR DESCRIPTION
**Pull request by cyanglaz**
fix an IOS crash when the image picker got tapped multiple times. flutter/flutter#20214

When the image in the imagePicker was tapped multiple times, the delegate method didFinishPickingMediaWithInfo gets called multiple times. _result is set to nil at the end of the didFinishPickingMediaWithInfo call.
When the second didFinishPickingMediaWithInfo gets triggered, because _result is nil, crash is caused.

We can also fix it by putting the code after selection inside the completion handler, it will cause a little delay in image showing up after completion. So directly checking if _result is nil and stop the process would be more efficient.

### CODE REVIEW

**Comment by amirh** [comment]
Thanks!
Can you add some details in the PR description explaining the problem the solution?

**Comment by remosingh** [comment]
Awesome, thank you so much! I literally had this exact same bug. Will try to see if it works now.

**Comment by remosingh** [comment]
Pardon my naivety....but if I simply upgrade my flutter plugins, will this solution be there too?

**Comment by iKrupp** [comment]
@cyanglaz still reproduce in version 0.6.5+1

2020-04-21 18:10:06.706981+0400 Runner[3369:1008611] CGImageSourceCreateWithData:3273: *** ERROR: CGImageSourceCreateWithData: data is nil
2020-04-21 18:10:06.707022+0400 Runner[3369:1008611] CGImageSourceGetType:3548: *** ERROR: CGImageSourceGetType: source is nil
2020-04-21 18:10:06.707038+0400 Runner[3369:1008611] CGImageDestinationCreateWithData:3086: *** ERROR: CGImageDestinationCreateWithData: type is nil
2020-04-21 18:10:06.707051+0400 Runner[3369:1008611] CGImageDestinationAddImageFromSource:3283: *** ERROR: CGImageDestinationAddImageFromSource: destination is nil
2020-04-21 18:10:06.707067+0400 Runner[3369:1008611] CGImageDestinationFinalize:3394: *** ERROR: CGImageDestinationFinalize: destination is nil

**Comment by kpalania** [comment]
My iOS app crashes when I try to upload a file. It was working just fine before I upgraded image_picker from version ^0.6.6+4 to ^0.7.2+1. Thoughts?


```
[core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
[Runner] CGImageSourceCreateWithData:3459: *** ERROR: CGImageSourceCreateWithData: data is nil
[Runner] CGImageSourceGetType:3753: *** ERROR: CGImageSourceGetType: source is nil
[Runner] CGImageDestinationCreateWithData:3838: *** ERROR: CGImageDestinationCreateWithData: type is nil
[Runner] CGImageDestinationAddImageFromSource:4038: *** ERROR: CGImageDestinationAddImageFromSource: destination is nil
```

**Comment by mratanpara** [comment]
> My iOS app crashes when I try to upload a file. It was working just fine before I upgraded image_picker from version ^0.6.6+4 to ^0.7.2+1. Thoughts?
> 
> ```
> [core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
> [Runner] CGImageSourceCreateWithData:3459: *** ERROR: CGImageSourceCreateWithData: data is nil
> [Runner] CGImageSourceGetType:3753: *** ERROR: CGImageSourceGetType: source is nil
> [Runner] CGImageDestinationCreateWithData:3838: *** ERROR: CGImageDestinationCreateWithData: type is nil
> [Runner] CGImageDestinationAddImageFromSource:4038: *** ERROR: CGImageDestinationAddImageFromSource: destination is nil
> ```

Have you found anything? I'm facing the same issue.

**Comment by mratanpara** [comment]
While uploading images from the gallery in IOS getting this error.
Package version is latest ^0.8.6

```
[core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
[PAAccessLogger] Failed to log access with error: access=<PATCCAccess 0x282f4ce10> accessor:<<PAApplication 0x282f08b40 identifierType:auditToken identifier:{pid:2995, version:8538}>> identifier:1BC34C1E-E012-4B4C-8EB0-B6F3FBE7B1B1 kind:intervalEvent timestampAdjustment:0 visibilityState:0 assetIdentifierCount:0 tccService:kTCCServicePhotos, error=Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.apple.privacyaccountingd" UserInfo={NSDebugDescription=connection to service named com.apple.privacyaccountingd}
```

**Pull request merged**
