### PR TITLE
Update Gradle and AGP in examples to 7.0

### PR DESCRIPTION
**Pull request by stuartmorgan**
Since https://github.com/flutter/plugins/pull/6614 was painless, I wanted to try bringing all of the examples up to 7.0 (both Gradle and AGP) to see if that goes smoothly as well. This gets us to about a year behind current releases (rather than 3+).

This does only examples since we're still investigating issues like https://github.com/flutter/flutter/issues/111304

Also:
- Updates all `espresso` references to the current version (0.2.0), since 0.1.0 uses a `compileSdkVersion` that is too old.
- Updates the tooling to know that example build files are version- and changelog-exempt, so that this doesn't have false-positive version check failures.

Fixes https://github.com/flutter/flutter/issues/112410
Fixes https://github.com/flutter/flutter/issues/111560

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by GaryQian — APPROVED** [review]

**Comment by GaryQian** [comment]
Tests seem red due though. Looks min SDK related.

**Comment by stuartmorgan** [comment]
I have some fixed; at least one is turning into a rat hole and I may revert it.

**Comment by stuartmorgan** [comment]
Before I give up on these two packages for now: @GaryQian or @camsim99 do you have any idea what's going on [here](https://cirrus-ci.com/task/6664471627169792)?

The error is:
```
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > One or more issues found when checking AAR metadata values:
     The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-29).
     Dependency: androidx.window:window-java:1.0.0-beta04.
     AAR metadata file: /root/.gradle/caches/transforms-3/41a83d0cf61e3d2ab42ea706b65148ab/transformed/jetified-window-java-1.0.0-beta04/META-INF/com/android/build/gradle/aar-metadata.properties.
     The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-29).
     Dependency: androidx.window:window:1.0.0-beta04.
     AAR metadata file: /root/.gradle/caches/transforms-3/bb9a53f8c4dc071c681fa071739dc70b/transformed/jetified-window-1.0.0-beta04/META-INF/com/android/build/gradle/aar-metadata.properties.
```

But I don't see us using 29 in google_maps_flutter_android or google_sign_in_android, only 31.

**Comment by camsim99** [comment]
@stuartmorgan Since the error is coming from espresso, it's possible that it's complaining because espresso's `targetSdkVersion` of 29 is conflicting with that dependency's `compileSdkVersion`. Maybe you could try bumping it to 31?

**Comment by stuartmorgan** [comment]
> @stuartmorgan Since the error is coming from espresso, it's possible that it's complaining because espresso's `targetSdkVersion` of 29 is conflicting with that dependency's `compileSdkVersion`. Maybe you could try bumping it to 31?

Ah-ha! This wasn't exactly it (`targetSdkVersion` is only a property of the example app not the espresso library), but while I was looking at that again I found what I had missed before. While the in-tree `espresso` package has `compileSdkVersion` of 31, which made me think it was unrelated, we've done a major version bump of `espresso` as part of updating some of its dependencies. But we hadn't picked that up everywhere (probably we couldn't because of the gradle versions of our examples being so old), so I was pulling a version of the package that still had its compile version set to 29. Just bumping to 0.2.0 in the pubspec fixed it. Thanks!

**Pull request merged**
