### PR TITLE
[url_launcher]Added webOnlyWindowName parameter to launch() 

### PR DESCRIPTION
**Pull request by balvinderz**
## Description

Adds the ability to launch a url in same tab,new tab or launch the url in an iframe using webOnlyWindowName parameter

## Related Issues

https://github.com/flutter/flutter/issues/56867

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by balvinderz** [comment]
@ditman  2nd pr

**Comment by ditman** [comment]
This contains changes both for url_launcher and url_launcher_web, it should contain only url_launcher_web.

**Comment by ditman** [comment]
Merged with most of the checks passed, I'll keep an eye on post-submit tests and merge the new packages ASAP.

**Comment by ditman** [comment]
Both url_launcher and url_launcher_web have been published:
* https://pub.dev/packages/url_launcher/changelog#551
* https://pub.dev/packages/url_launcher_web/changelog#013

**Comment by lazylazyllama** [comment]
I get this exception since updating to url_launcher 5.5.1

```

Running Gradle task 'assembleDebug'...
../../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/url_launcher-5.5.1/lib/url_launcher.dart:100:5: Error: No named parameter with the name 'webOnlyWindowName'.
    webOnlyWindowName: webOnlyWindowName,
    ^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s
Exception: Gradle task assembleDebug failed with exit code 1

```

**Comment by cyanglaz** [comment]
@lazylazyllama Maybe try `flutter clean`?

**Comment by lazylazyllama** [comment]
That did not solve the issue. But the issue makes sense anyways:

I think you have to add `webOnlyWindowName` to the `launch()` method in `url_launcher_platform_interface.dart`

**Comment by lazylazyllama** [comment]
Running `pub upgrade` fixed it. It seems the platform_interface plugin was still on 1.0.7

**Comment by stuartmorgan** [comment]
This is using a parameter added in 1.0.8 of the interface package, but didn't rev the dependency in pubspec, which is still 1.0.4. This PR should have set that to 1.0.8.

**Comment by ditman** [comment]
5.5.2 should address the issue. Thanks @stuartmorgan for letting me know about the flutter issue!

**Pull request merged**
