### PR TITLE
Update Google Maps Plugin README.

### PR DESCRIPTION
**Pull request by amirh**
Adds instructions for iOS and notes that this is a developers preview.

### CODE REVIEW

**Comment by amirh** [comment]
TBR @bparrishMines @cbracken

**Comment by Hixie** [comment]
LGTM

**Comment by zoechi** [comment]
@Hixie do you think https://github.com/dart-lang/sdk/issues/35261#issuecomment-442004235 is worth it for unreleased packages to make it a bit harder for people to publish wip packages.

**Comment by Hixie** [comment]
We should just publish the packages early.

**Pull request merged**
