### PR TITLE
[Firebase messaging] iOS direct data messages

### PR DESCRIPTION
**Pull request by jaumard**
fixes https://github.com/flutter/flutter/issues/25650
fixes https://github.com/flutter/flutter/issues/29714

To use this right now do:
```yaml
firebase_messaging: #^4.0.0+1
    git:
      url: git://github.com/jaumard/plugins
      ref: feature/iosFirebaseMessagingDataMessages
      path: packages/firebase_messaging
```

### CODE REVIEW

**Comment by amervelic** [comment]
Please fix custom notification sound on android oreo+

**Comment by kroikie** [comment]
@jaumard Thanks for the PR! Could you please make this an optional operation on the Dart side?

If a developer is not using direct messages then there is no need to have this channel open. So let's follow the native SDK and give the option to the developer to enable the channel or not.

**Comment by jaumard** [comment]
@kroikie yes I can, but it will change the cross platform behavior. 
Because on Android you get out of the box push notification and direct messages, shouldn't be the same on iOS ? that's why I didn't hide it behind a flag. 

Let me know what you think !

**Comment by collinjackson** [comment]
Thanks, this PR looks great!

Perhaps we should call `shouldEstablishDirectChannel` in response to `configure` since at that point the `onMessage` method will actually do something.

Don't forget to update pubspec.yaml

**Comment by jaumard** [comment]
Hey @collinjackson I've rebase and update pubspec and changelog, let me know if it's all good :)

**Comment by jaumard** [comment]
I also moved the shouldEstablishDirectChannel in configure response

**Pull request merged**
