### PR TITLE
[google_map] Add support for marker from bytes

### PR DESCRIPTION
**Pull request by iskakaushik**
## Description

Adds support for setting marker icon from bytes

## Related Issues

https://github.com/flutter/flutter/issues/24865

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by iskakaushik** [comment]
forking https://github.com/flutter/plugins/pull/815 due to inactivity.

**Comment by miguelpruivo** [comment]
@iskakaushik I'm looking into it right now. Sorry, I've been busy.

**Comment by iskakaushik** [comment]
@miguelpruivo no worries, your change is in high demand 👍 
I've addressed the comments and added an example, please feel free to reuse them.

I'm closing this PR, let's continue discussion on https://github.com/flutter/plugins/pull/815

**Comment by miguelpruivo** [comment]
Right. Thank you. Do you need any further action from my side?

**Comment by iskakaushik** [comment]
@miguelpruivo nope, you are good.

**Pull request closed without merging**
