### PR TITLE
Add in_app_purchase for readme and replace pub.dartlang.org to pub.dev.

### PR DESCRIPTION
**Pull request by kushvatsa**
Add in_app_purchase plugin detail and change domain from pub.dartlang.org to pub.dev

### CODE REVIEW

**Comment by kushvatsa** [comment]
@mklim

**Comment by amirh** [comment]
Seems like the pub.dartlang.org->pub.dev updated already happened in https://github.com/flutter/plugins/pull/1764

**Comment by cyanglaz** [comment]
@kushvatsa Do you mind to rebase?

**Comment by kushvatsa** [comment]
@cyanglaz Done!!

**Pull request merged**
