### PR TITLE
[webview_flutter] Pre-emptively ignore prefer_const_constructor warning.

### PR DESCRIPTION
**Pull request by mvanbeusekom**
This will pre-emptively ignore the `prefer_const_constructor` warning to make it possible to migrate the webview_flutter_platform_interface without breaking changes to the more strict analysis_options.yaml (see issue flutter/flutter#76229).

A cleanup issue also exist as a reminder to remove the temporary ignore statements and can be found here: flutter/flutter#94311

No version change: this is a temporary change and only necessary to land on master not to break the build when merging #4549. These changes will be undone as part of flutter/flutter#94311 as soon as #4549 lands.

No CHANGELOG change: this is a temporary change and only necessary to land on master not to break the build when merging #4549. These changes will be undone as part of flutter/flutter#94311 as soon as #4549 lands.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Comment by stuartmorgan** [comment]
Did you need the "no version change", or was that pre-emptive? This should have passed the version check without that due to the files touched; if it failed that's a bug.

**Comment by mvanbeusekom** [comment]
No I added it preemptively. I did receive the "No CHANGELOG" warning though (which was fixed by added the right description).

**Comment by stuartmorgan** [comment]
Great, sounds like it worked as intended then; the automatic exemptions are just for the version change, not the CHANGLOG (since that's the general policy we're using, at least for now).

**Pull request merged**
