### PR TITLE
[image_picker] Updating documentation to use isEmpty check.

### PR DESCRIPTION
**Pull request by panmari**
## Description

Updating documentation to be in sync with example. The value returned is never null. This is already done correclty in the
example app.

## Related Issues

-

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by panmari** [comment]
@dnfield can you please take a look? Somehow there was no reviewer assigned by default.

**Comment by yash1200** [comment]
@dnfield is it like that even if a PR is failing in just `submit-queue` test, it can't be merged to master.

**Comment by dnfield** [comment]
@yash1200 Correct. Tree has to be green to merge.

**Comment by dnfield** [comment]
Tagged and published. Thanks for catching this!

**Pull request merged**
