### PR TITLE
[video_player] updated ExoPlayer Android to version 2.10.5

### PR DESCRIPTION
**Pull request by BugsBunnyBR**
## Description

Updates ExoPlayer for Android
https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by cyanglaz** [comment]
Thanks for the contribution!

I'm following the [initial PR review policy](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), this PR isn't trivial to review so I'm labeling it with "backlog" and we will prioritize according to the issue's priority.

related issue: https://github.com/flutter/flutter/issues/36375

**Comment by BugsBunnyBR** [comment]
@cyanglaz What tests do we need? I can give it a try if we have a sample in the plugins repository.

**Comment by ened** [comment]
HI @BugsBunnyBR could you please update the PR to include ExoPlayer 2.10.5 ?

**Comment by BugsBunnyBR** [comment]
> HI @BugsBunnyBR could you please update the PR to include ExoPlayer 2.10.5 ?

I will do it latter today.

**Comment by cbenhagen** [comment]
Thank you for your contribution! Unfortunately the structure of the plugin has changed lately to support implementations on more platforms. Mainly the plugin was moved to a new subdirectory and now uses a common platform interface. Adapting your PR to the new structure should be straight forward. If you have questions please ask!

I guess the version could be bumped to 2.10.8.

**Comment by BugsBunnyBR** [comment]
I am closing this pr as it has not been merged until this date even though I kept it updated upon the team request I am no longer doing this.
This behaviour from the developers show a lack of respect with people trying to offer help.

**Comment by cbenhagen** [comment]
@BugsBunnyBR I totally understand your frustration. Things are improving a lot lately as tests have been added to the plugins and PRs are being reviewed and merged way faster than before. Please reconsider your decision and give the team some time to work through the backlog. If you wan't I can take this and open a PR with those changes. Please not that I am not part of the team and am also just trying to help.

**Pull request closed without merging**
