### PR TITLE
[firebase_ml_vision] Rotate images for iOS when image orientation is not set as UP

### PR DESCRIPTION
**Pull request by schmorrison**
Rotate images that were captured on iOS devices, if required, because device orientation is not necessarily reflected in the orientation of the image that is saved, some images are saved in unexpected rotations. Not sure if this behaviour is persistent across all models of iOS devices (or even all devices), but this PR seems to solve the problem I encountered on two of my own devices.

Prior to including this image rotation code, all images I tried to run through the face detector failed, and the base64 encoding of the image always rendered as if the camera was saving left-landscape orientation regardless of device orientation.

### CODE REVIEW

**Comment by schmorrison** [comment]
I signed it!

**Comment by schmorrison** [comment]
I signed it!

**Comment by collinjackson** [comment]
@bparrishMines this looks like a very simple change, let us know if you think this is fine to land or you can land it yourself

**Comment by bparrishMines** [comment]
Closing due to another PR adding this fix into the android one https://github.com/flutter/plugins/pull/1225

**Pull request closed without merging**
