### PR TITLE
[cloud_firestore] add support for cacheSizeBytes

### PR DESCRIPTION
**Pull request by shasaf1986**
## Description

Add cacheSizeBytes parameter to firestore settings
Today the default value is infinity (native SDKs) which can not modifieded.
I think this option can decrease the slowness of firestore (see the related issue).

## Related Issues

*https://github.com/flutter/flutter/issues/18570*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by shasaf1986** [comment]
Added another email to cla

**Comment by shasaf1986** [comment]
@collinjackson or @kroikie did you review the PR ?
Thanks

**Comment by shasaf1986** [comment]
Sorry, I had some issues with my branches.
I have created new PR 
https://github.com/flutter/plugins/pull/1646

**Comment by shasaf1986** [comment]
sorry for the mess, this PR still relevant

**Comment by collinjackson** [comment]
Thanks for the contribution! Could you please include unit and integration tests when adding new APIs? Here's an example: https://github.com/flutter/plugins/pull/1647/commits/35ef3db7dddbe9e1e8b690ce98abde63fe911da8

**Comment by shasaf1986** [comment]
I have added 2 tests, I hope it's good

**Comment by shasaf1986** [comment]
@collinjackson did you check it ?
This option is important, please merge it 
Thanks

**Comment by collinjackson** [comment]
Looks good - thanks for the contribution.

**Pull request merged**
