### PR TITLE
Removed dependency on Firebase for android_alarm_manager example

### PR DESCRIPTION
**Pull request by bkonyi**

### CODE REVIEW

**Comment by ened** [comment]
FWIW, this PR seems to do more than just that. Split it up?

**Comment by bkonyi** [comment]
As far as I know everything in this PR is related to the removal of
Firebase in the example.

**Comment by ened** [comment]
@bkonyi sorry to not be more specific earlier. 

The removal of some of the methods like `printHelloMessage`, `printHello`, `printGoodbye`, `printOneShot` seem unrelated to me & were added to show a more clear example in the first place, I think.

**Comment by bkonyi** [comment]
> @bkonyi sorry to not be more specific earlier.
> 
> The removal of some of the methods like `printHelloMessage`, `printHello`, `printGoodbye`, `printOneShot` seem unrelated to me & were added to show a more clear example in the first place, I think.

`printHelloMessage`, `printHello`, and `printGoodbye` were all relying on Firebase functionality and didn't make sense with Firebase removed from the example. I don't think there's anything to be split out here.

**Comment by collinjackson** [comment]
Great PR, thanks!

**Pull request merged**
