### PR TITLE
[webview_flutter] add `mixedContentMode` option for Android WebView

### LINKED ISSUE #43595: webview_flutter how to load https and http mixed content?
webview_flutter how to load https and http mixed content?

### PR DESCRIPTION
**Pull request by dotcink**
## Description

Add support of `mixedContentMode` for Android WebView.

## Related Issues

Fixes flutter/flutter#43595 and flutter/flutter#24975

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by dotcink** [comment]
@amirh Please Take A Look.
Thank you.

**Comment by dotcink** [comment]
Not sure what's the meaning of `branch-guard — Cirrus CI failure`.
This failing check didn't show at first.
Clicking `Details` shows error message:

```
{
  "message": "If you would like to help us test the Checks API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.",
  "documentation_url": "https://developer.github.com/v3/checks/suites/#get-a-single-check-suite"
}
```

**Comment by edisonywh** [comment]
Thanks for the great work @dotcink! Any update on this, @amirh? Right now my app just looks pretty jarring with unloaded images everywhere.

**Comment by dotcink** [comment]
> Thanks for the great work @dotcink! Any update on this, @amirh? Right now my app just looks pretty jarring with unloaded images everywhere.

Please thumbs up 👍 flutter/flutter#43595, Flutter team use this to guide the issue prioritizing.

**Review by ikkyu0319 — COMMENTED** [review]
nice ~

**Comment by Vasques1995** [comment]
Hi @dotcink any news on the issue this PR is trying to address? The only reason that the PR is not merged is because of the failed checks?

**Comment by dotcink** [comment]
> Hi @dotcink any news on the issue this PR is trying to address? The only reason that the PR is not merged is because of the failed checks?

I just submitted another common solution. This PR might close if possible.

**Comment by stuartmorgan** [comment]
Thanks for the submission! We’re currently working through a large backlog of PRs, and this will require non-trivial review, so it will take some time before we’re able to review it. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are the primary way we’re prioritizing non-trivial reviews, so we encourage anyone interested in this PR to vote for the corresponding issue.

**Comment by ditman** [comment]
> I just submitted another common solution. This PR might close if possible.

Closing in favor of: https://github.com/flutter/plugins/pull/3721

**Comment by dotcink** [comment]
> > I just submitted another common solution. This PR might close if possible.
> 
> Closing in favor of: #3721

So would #3721 be prepared to be reviewed and merged please?

**Comment by stuartmorgan** [comment]
> > I just submitted another common solution. This PR might close if possible.
> 
> Closing in favor of: #3721

There isn't a decision yet that that's the way we want to go, so for now both should stay open.

**Comment by stuartmorgan** [comment]
> So would #3721 be prepared to be reviewed and merged please?

Please see https://github.com/flutter/plugins/pull/3721#issuecomment-800566453

**Comment by stuartmorgan** [comment]
Adding a setting for this makes sense in the new structure we'll be using, but it's blocked on https://github.com/flutter/flutter/issues/94051: we'll want to support platform extensions to `WebSettings` instead of adding this to the main class, and have a way of configuring the web view that doesn't require yet another highly-specific optional parameter.

We can leave this open for now and it can be adjusted to fit the new structure once that work is done.

(/cc @bparrishMines and @mvanbeusekom who will be working on that restructing.)

**Comment by Hixie** [comment]
Latest status is that we're still waiting on https://github.com/flutter/flutter/issues/94051.
Before this can land even after that is fixed, the conflicts will need to be resolved.

**Comment by dotcink** [comment]
> Latest status is that we're still waiting on [flutter/flutter#94051](https://github.com/flutter/flutter/issues/94051). Before this can land even after that is fixed, the conflicts will need to be resolved.

OK, I'll resolve the conflicts according to the new solution.

**Comment by stuartmorgan** [comment]
webview_flutter v4 has finally been completed, which included fixing the platform interface to that we can make additions to it without breaking changes. That means that this is finally unblocked! Thanks for your patience while we worked through the restructuring.

webview_flutter v4 uses a Dart-first implementation, where the platform channel boundary is as close as possible to the underlying host APIs, and plugin logic is written primarily in Dart rather than the host language. That means that this PR will need to be updated to follow that model. Please let us know if you have questions about updating to v4 (and https://github.com/flutter/plugins/pull/6881 may be useful as an example of adding a feature in the v4 structure).

**Comment by stuartmorgan** [comment]
@dotcink Are you still planning on updating this for compatibility with v4?

**Comment by stuartmorgan** [comment]
(Marking this as a Draft pending that update.)

**Comment by dotcink** [comment]
> 

OK, I'll check the new v4 in the weekend.

**Comment by stuartmorgan-g** [comment]
We've just completed the migration of the plugin code to the flutter/packages repository, as described in https://flutter.dev/go/flutter-plugins-repo-migration, and this repository is now being archived. Unfortunately that means that all in-progress PRs here must be moved to flutter/packages.

Please see [our instructions](https://github.com/flutter/flutter/wiki/Migrating-Plugins-repository-PRs-to-Packages) for an explanation of how to move your PR, and if you have any issues moving your PR please don't hesitate to reach out in the #hackers-ecosystem channel in [Discord](https://github.com/flutter/flutter/wiki/Chat).

Our apologies that your PR was caught in this one-time transition. We're aware that it's disruptive in the short term, and appreciate your help in getting us to a better long-term state!

**Pull request closed without merging**
