### PR TITLE
[url_launcher] Add a workaround for Uri encoding

### PR DESCRIPTION
**Pull request by stuartmorgan**
`Uri`'s constructor doesn't handle query parameters correctly for
non-http(s) schemes, so the `mailto` example in the README is
misleading. This updates the README to show using a simple method
to work around that bug, and a warning about the need to use it.

Fixes https://github.com/flutter/flutter/issues/75552
Fixes https://github.com/flutter/flutter/issues/73717

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by patreu22** [comment]
Hey @stuartmorgan , I'm not sure if you are still working on that fix here, but I'm running into an issue that looks like your PR could possibly fix my issue with the encoding of linebreaks: https://stackoverflow.com/questions/67859136/flutter-url-launcher-line-break-doesnt-work-in-ios-mail-program

Maybe you find some time to finalize your PR, I think it could be very helpful!

Best regards
Patrick

**Comment by stuartmorgan** [comment]
A decision on what to do here is pending a decision in https://github.com/dart-lang/sdk/issues/43838

I may just do a README update in the short term.

**Comment by patreu22** [comment]
I see, thx for coming back to me so quickly! Will use the suggested workaround from there and just replace the `+` with a `%20`. Still not fixing my line break issue but I'll look out for other fixes to that.

**Comment by stuartmorgan** [comment]
Based on discussion with Hixie we're not going to put the workaround in the plugin itself, where we'll need to maintain it (or break people) even after the Dart bug is fixed, so I've updated this to just show the workaround in the README. This will avoid the issue of people following the README and getting the wrong behavior.

**Review by gaaclarke — APPROVED** [review]

**Review by ditman — APPROVED** [review]
There's a simpler version where people can call `Uri.toString().replace("+", "%20")`, but this one is more "standard" (especially in JS you'd end up some code like this if you were concatenating your own URLs).

Anyway, ship it! 🚀

**Comment by stuartmorgan** [comment]
> There's a simpler version where people can call `Uri.toString().replace("+", "%20")`

Only in the same sense that there's a simpler version where you write `'mailto:$emailAddress?subject=$subject`. I.e., it's easier to write, but is incorrect and may not actually work.

> but this one is more "standard"

If by "standard" you mean "correct", then yes 🙂  The URI spec allows for `+` to exist unencoded in certain places, and also specifically says that "URIs that differ in the replacement of a reserved character with its corresponding percent-encoded octet are not equivalent.  Percent-encoding a reserved character, or decoding a percent-encoded octet that corresponds to a reserved character, will change how the URI is interpreted by most applications."

Which means that your `replace` has the potential to corrupt a URI. People should not be writing that.

**Comment by stuartmorgan** [comment]
Landing this simple PR on red to force post-submit CI to run, since we believe the last round of post-submit failures was due to an infra migration that was happening that impacted Cirrus jobs.

**Pull request merged**
