### PR TITLE
Add a BLE plugin

### PR DESCRIPTION
**Pull request by namn**
This is an early implementation of a BLE plugin for Flutter. Right now, the plugin can only initiate scan operation and receive advertisement packets. Feature requested in Flutter's issue [#430](https://github.com/flutter/flutter/issues/430).

### CODE REVIEW

**Comment by sethladd** [comment]
Cc @pauldemarco

**Comment by pauldemarco** [comment]
I really like the use of protobuf as a way of sharing data structure between platforms.  I had no idea this was possible. Nicely done!

**Comment by mit-mit** [comment]
Thanks so much for contributing @namn! We typically use this repo for plugins developed and maintained by the core Flutter team. For other community plugins, you can place the source code in a personal github repo, and then from there [publish the plugin](https://flutter.io/developing-packages/#publish) so that all developers in the Flutter ecosystem can use it. If you would like help/reviews, we'd be happy to do that even for plugins in other repos, just let us know!

Also, I just today noticed that @pauldemarco [is also working](https://github.com/pauldemarco/flutter_blue) on a bluetooth plugin. Would it be worth considering for you two to "join forces" on this?

Kind Regards, Michael

**Comment by pauldemarco** [comment]
I would be happy to, just let me know!

**Comment by namn** [comment]
You're welcome, Michael. I briefly chatted with @Hixie and @tvolkert over Hangouts few days ago about Seth's feature request (https://github.com/flutter/flutter/issues/430) and they both suggested me to just send in a PR. Glad that there's now a firmer guideline on contributing.

Paul, let's see how to bring these two implementations together to a Google repository. I see that you've already gone ahead to pull in bits and pieces of this. I'll ping you at work next week.

Thanks for taking a look, folks.

**Comment by pauldemarco** [comment]
Nam,
Your plugin had an excellent demonstration of how to setup Protobuf for a flutter project.
With protobuf I was able to greatly simplify a lot of the boilerplate code needed when transporting data to/from platform.  I definitely want to do a write-up on this when I get some time @sethladd .
I'm not familiar with Google repositories, and what the benefits might be as opposed to a GitHub repo.
I look forward to talking next week and collaborating.

**Comment by tvolkert** [comment]
@mit-mit, @namn is a Googler, so I had suggested he send a PR to add the plugin here.  Is there a good place for non-core-Flutter-team, but Googler-authored plugins to live?

**Comment by mit-mit** [comment]
>  Is there a good place for non-core-Flutter-team, but Googler-authored plugins to live?

There are several options depending on the details code; let me send you some more information internally.

**Pull request closed without merging**
