### PR TITLE
[webview_flutter] Added Support for the viewport meta width

### PR DESCRIPTION
**Pull request by Niggelgame**
## Description

After rendering a website went completly wrong, I found the issue, that on iOS the Viewport Meta WAS rendering, but on Android not.

### CODE REVIEW

**Comment by cyanglaz** [comment]
@Niggelgame Thanks for contributing. Is there a github issue that we can link?

**Comment by Niggelgame** [comment]
No, I don't think so!

**Comment by cyanglaz** [comment]
@Niggelgame Do you mind to create one describing the issue you encountered in detail and link this PR to the issue? This will help us speed up the process of triaging the issue/PR. :)

**Comment by cyanglaz** [comment]
I'm going to close the PR because the CLA is not signed. Feel free to ping me when the CLA is signed and I'll re-open the PR. Or you can open a new PR after signing the CLA.

**Pull request closed without merging**
