### PR TITLE
[google_sign_in] Remove unused variable

### PR DESCRIPTION
**Pull request by jayjun**
## Description

Removed unused variable introduced by #2127.

### CODE REVIEW

**Comment by jayjun** [comment]
@cyanglaz @ditman @mehmetf Sorry, I wasn’t sure who to ping. Can I get a review?

**Comment by mehmetf** [comment]
Could you please also update the version in changelog and pubspec?

**Comment by jayjun** [comment]
@mehmetf Yeap, done and pushed.

**Comment by ditman** [comment]
I've just seen this, thanks for the fix @jayjun and @mehmetf !

**Pull request merged**
