### PR TITLE
Update example pubspecs to match templates

### PR DESCRIPTION
**Pull request by mit-mit**
## Description

Align example pubspecs with new templates, removing unused upper constraint

## Related Issues

https://github.com/flutter/flutter/pull/68437

### CODE REVIEW

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by mit-mit** [comment]
I'm not entirely sure what to do about the Cirrus failure?

**Comment by dnfield** [comment]
It was an infra failure that reran automatically and passed. This is good to land.

**Comment by stuartmorgan** [comment]
> It was an infra failure that reran automatically and passed.

I actually manually re-ran it when I did my review; I don't think we have auto-rerun for jobs in this repo.

**Comment by dnfield** [comment]
Ahh ok.  I saw it running when I checked.  Cirrus does rerun certain types of failures automatically, if it thinks it was infra.

**Pull request merged**
