### PR TITLE
[webview_flutter]  Fix the issue that webview cannot load assets html and local html

### PR DESCRIPTION
**Pull request by asjqkkkk**
Fix flutter/flutter#27086 

Now, flutter webview can load html file in two ways:

#### Assetfiles
```
    WebView(
      onWebViewCreated: (WebViewController controller) {
        final url = 'assets/index.html';
        controller.loadAssetHtmlFile(url);
      },
      javascriptMode: JavascriptMode.unrestricted,
    );
```
#### Localfiles
```
    WebView(
      onWebViewCreated: (WebViewController controller) {
        controller.loadLocalHtmlFile(filePath)
      },
      javascriptMode: JavascriptMode.unrestricted,
    );

  Future<void> downloadFile(String url) async {
    Dio dio = Dio();
    String path = (await getApplicationDocumentsDirectory()).path;
    String fileName=url.substring(url.lastIndexOf("/")+1);
    await Dio().download(url, '$path/$fileName',onReceiveProgress: (rec,total){
      progress = ((rec/total) * 100).floor();
      if(progress >= 100){
        filePath= '$path/$fileName';
      }
      setState(() {});
    });
  }
```

### CODE REVIEW

**Comment by asjqkkkk** [comment]
> I signed it!

@googlebot I signed it!

**Comment by miyakeryo** [comment]
Could you support initialUrl? Because a black background page flickers for a moment.

**Comment by asjqkkkk** [comment]
> Could you support initialUrl? Because a black background page flickers for a moment.

support initialUrl will bring some broken changes, this is not good for maintenance and expansion, so I didn't do that

maybe you can use some other way to load webview?

```
  String _urlPath;

  @override
  void initState() {
    initialUrlDynamic();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: _urlPath == null ? buildLoadingWidget(): buildWebView(),
    );
  }
```

**Comment by miyakeryo** [comment]
@asjqkkkk 
Thanks for your suggestion. I solved this problem by using `about:blank`

**Comment by SetNameHere** [comment]
Hi,
does anyone know when this feature will be available?
It seems to be a great solution for one of my biggest problems.

Thanks for all your work!

**Comment by TheOneWithTheBraid** [comment]
Does anyone know if this will be merged in further releases?

**Comment by eric8words** [comment]
Any ETA for the merged release ?

**Comment by cyanglaz** [comment]
cc @bparrishMines

**Comment by Wian-TMC** [comment]
Possible ETA?

**Comment by Wian-TMC** [comment]
The PR Triage has last been updated on 13 August. Is there a more up to date indication when this will be available on the master branch?

**Comment by jamesdixon** [comment]
@asjqkkkk why did you end up closing this?

**Comment by asjqkkkk** [comment]
> @asjqkkkk why did you end up closing this?

My branch was not updated for too many days, so I think there should be another fresh pr to fix this issue

**Comment by Wian-TMC** [comment]
I take it that's bad news?

**Comment by DineshKachhot** [comment]
Local html file is loading but local assts like image and css are still not loading in Flutter 2.2 stable.

**Pull request closed without merging**
