### PR TITLE
[google_maps_flutter] fix swift example in readme

### PR DESCRIPTION
**Pull request by PiN73**
## Description

This PR replaces `UIApplicationLaunchOptionsKey` with `UIApplication.LaunchOptionsKey` in example for swift because first one doesn't longer work due to https://github.com/flutter/flutter/pull/35763

## Related Issues

Here is a description of compile error which occurs when using `UIApplicationLaunchOptionsKey`:
https://stackoverflow.com/questions/59365426/flutter-google-maps-ios-build-fail

### CODE REVIEW

**Comment by PiN73** [comment]
Please review this small docs fix

**Comment by PiN73** [comment]
If anyone is requested for review -- sorry, I've just pushed commits merged from master by accident

**Comment by PiN73** [comment]
Done. Version was updated in #2042 (wasn't published yet)

**Comment by PiN73** [comment]
@cyanglaz should I do anything else?

**Comment by cyanglaz** [comment]
@PiN73 Thanks. Sorry about the "not publishing". I just published the new version, could you please update your PR again with a new version?

**Comment by PiN73** [comment]
No problem, done.

**Pull request merged**
