### PR TITLE
[camera] Fix a disposed `CameraController` error thrown when changing a camera

### PR DESCRIPTION
**Pull request by bselwe**
Fixes a disposed `CameraController` error thrown when changing the camera in the camera example. 

The error is thrown by the `ValueListenableBuilder` in the `CameraPreview`. Changing a camera disposes the previous `CameraController` before the widget state is updated causing the `ValueListenableBuilder` to listen to the disposed controller. This PR solves the issue by disposing the previous `CameraController` after the new one is initialized.

Error:
```
The following assertion was thrown building CameraPreview:
A CameraController was used after being disposed.
Once you have called dispose() on a CameraController, it can no longer be
used.

The relevant error-causing widget was:
  CameraPreview
  file:///Users/.../Projects/plugins/packages/camera/camera/example/lib/main.dart:188:16
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by bselwe** [comment]
@ditman @BeMacized @felangel

**Comment by ditman** [comment]
The test failure seems like a chrome flake:

```
UnknownException (13): unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}),platform=Linux 5.4.104+ x86_64)
```

I'll restart the test.

**Comment by BeMacized** [comment]
> Why wasn't this needed earlier?
I'm not entirely sure, but I can reproduce the issue and this does look like the appropriate fix to me.

**Review by BeMacized — APPROVED** [review]
LGTM!

**Pull request merged**
