### PR TITLE
Reland "[video_player] Set audio mix options (#2922)"

### PR DESCRIPTION
**Pull request by cyanglaz**
Reverts flutter/plugins#2938

### CODE REVIEW

**Comment by dnfield** [comment]
LGTM

**Comment by steve-rait** [comment]
Hi, this new feature has a side effect : 
In my app, when I upgrade plugin, It can't play multiple videos in the same screen by default (I have a list with many items, one video player by item) (**only on Android**)
Indeed, this affects multiple players in the app itself.
I had to force **VideoPlayerOptions** **mixWithOthers** to true to let them play together again.

So it's a breaking change which need to be detailed somewhere in the doc, don't you think ?

**Comment by cyanglaz** [comment]
@steve-rait This breakage is not intended. Do you mind create a github issue (https://github.com/flutter/flutter/issues/new/choose) describe the failure scenario in details? And preferably, if you could provide a sample code to reproduce the issue, that'd help us to accelerate the debugging process. :) 
Feel free to tag me if you create the github issue.

Let me know if you want me to create the issue, but I'd probably need your help to describe it in more details.

**Comment by steve-rait** [comment]
Hi 
Thanks for the info, let me create it, I'll do that this weekend or next week with a complete sample code to show precisely the problem.

**Pull request merged**
