### PR TITLE
[google_maps_flutter] Support marker clustering

### PR DESCRIPTION
**Pull request by yyoungg0318**
## Description

Added marker clustering basis function for google_maps_flutter (for now only port for android platform). include add, modify and remove a marker of cluster and some click listener. Also, support custom marker icon for marker of cluster. in the meanwhile I added test case in Place marker page (examples).
 
I have modified onMarkerClickListener callback point, I set listener to MarkerManager instead of GoogleMapController because ClusterManager needs to handle whole marker click event. 
based on the reason I also modified addMarker method for handle whole Marker event and so on.

## Related Issues

flutter/flutter#26863

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?
- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by domesticmouse** [comment]
Unless I miss my guess, this is Android only. Would it make sense to port the Android clusterer to Dart code and thus be able to use it for both Android and iOS?

**Comment by yyoungg0318** [comment]
I think this is not android only, we can use it 
for both Android and iOS. 

iOS version is as below.
https://developers.google.com/maps/documentation/ios-sdk/utility/marker-clustering

**Comment by domesticmouse** [comment]
As the ex maintainer of the iOS maps clusterer, I'd rather not link it. It's in need of a rewrite, and we can't tree shake out unused functionality.

**Comment by domesticmouse** [comment]
I didn't mean to close the PR. Sorry!

**Comment by yyoungg0318** [comment]
@domesticmouse I get it,  it's really a bad news. So sad. 
Do you have any good idea about iOS maps clusters?

**Comment by domesticmouse** [comment]
Marker clustering is implemented completely in terms of the public maps API. This means we can port the Java Maps clusterer across to Dart and get marker clustering everywhere. I'd love to put my hand up to do the work, but I'm currently swamped. I can aim to have a look post I/O.

**Comment by yyoungg0318** [comment]
@domesticmouse  It's a pity you're currently swamped. 

I don't know which one Java Maps clusterer API that you mean, it shouldn't be a Google internal use project.  I guess that is Maps JavaScript API, right?
As far as I know, I feel it's the only way to port Maps clusterer to Dart and get marker clustering everywhere (iOS , Android, Web, ans so on).

But, for now I would prefer to use Maps SDK for Android and Maps SDK for iOS because Google change the pricing policy last year. these two API is for free, the Maps JavaScript API will be charge after 28,500 API calls. that's the reason why I didn't use the Maps JavaScript API.

**Comment by domesticmouse** [comment]
The java clusterer that you are linking in this PR is Apache licensed and available at https://github.com/googlemaps/android-maps-utils/tree/master/library/src/com/google/maps/android/clustering

I’ll look at porting it over soon

**Comment by yyoungg0318** [comment]
@domesticmouse 
Sorry, I mistook what you mean. @@ 

It's really exciting. I really appreciate your kind help.

**Comment by domesticmouse** [comment]
All good @yyoungg0318 =)

**Comment by pplparag** [comment]
Will it support Marker with Icon and Text written over marker icon?

**Comment by bogdannedelcu** [comment]
Hello, is this merged in Master? Runs both on iOS and Android?

**Comment by RyanRamchandar** [comment]
@domesticmouse have you had a chance to revisit adding iOS support for clustering?

**Comment by domesticmouse** [comment]
Sorry, no. Lots of higher priority tasks on my plate at the moment.

**Comment by Injazz** [comment]
Any progress?

**Comment by cyanglaz** [comment]
@yyoungg0318 Thank you for providing this PR. I am trying to start actively reviewing this PR and get this merged. However it is difficult for me to review it now as the PR has some conflicts with upstream. Do you mind to rebase the PR?

**Comment by yyoungg0318** [comment]
@cyanglaz Sorry for late reply, last week is Chinese New Year.
I'll try to rebase the PR. but I didn't update the map source code for a long time, maybe it will take some time to rebase. After that, if no one can help to implement iOS part and I am free I will do that.

**Comment by cyanglaz** [comment]
@yyoungg0318 Happy new year! :) I actually have a plan to create a new plugin to support features in the google-maps-utils. So your PR might be best to go to that plugin. Here is a Github issue tracking that effort: https://github.com/flutter/flutter/issues/49566
So we will move this PR to the other plugin when the plugin is ready.

**Comment by yyoungg0318** [comment]
@cyanglaz  I have just rebase the PR, could you help me to start review it? thanks.

**Comment by Nailer** [comment]
Hi! Any progress on this issue lately?

**Comment by r4ptus** [comment]
Can we cluster our markers with google_maps_flutter yet?

**Comment by tieorange** [comment]
Hello guys, 

any updates on clusters in google_maps_flutter?

**Comment by stuartmorgan** [comment]
We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

@cyanglaz is planning on getting back to this once we're done with the null-safety migration that's in progress for all of our plugins.

**Comment by pixeliner** [comment]
Hey all,

I'm busy rehauling my flutter project and as I'm in need of a cluster functionality, I wanted to know if we can expect this to be implemented soon?

**Comment by augustorsouza** [comment]
Hello guys, any news with this PR? This is really important for us :)

**Comment by Navil** [comment]
Any updates on this? :)

**Comment by DesmondFox** [comment]
any updates?

**Comment by hiteshgarg002** [comment]
Its been a long time, will there be any updates regarding this?

**Comment by stuartmorgan** [comment]
The reviewer is currently out of office for a while, so there won't be any updates on the review front for at least several more weeks.

However, this PR is not complete; it doesn't include tests, and thus won't pass review as-is (as explained in our contributor guide, and highlighted in the PR checklist). So the most useful thing that could be done while waiting for review would be to add the necessary tests so the PR is actually ready.

**Comment by Hixie** [comment]
Since this PR is lacking tests, we won't be able to land it. I'm going to close hte PR for now, but please don't hesitate to open a new PR with these changes if you have the time to write tests. Thanks!

**Comment by yyoungg0318** [comment]
Why you guys review this for many years? and now you guys say test not
passed, you guys are really so funny. Oh this is Google style?

Ian Hickson ***@***.***> 於 2021年11月10日 週三 08:23 寫道：

**Comment by yyoungg0318** [comment]
I will not do this again, it is a fucking stupid thing, review for many
years, after that, just said test not passed, wtf, the test passed before
two years, haha, funny Google guys

yangcs ***@***.***> 於 2021年11月10日 週三 12:42 寫道：

**Comment by stuartmorgan** [comment]
> Why you guys review this for many years?

Ideally the lack of tests would have been flagged as a blocker earlier in the process; that was an oversight. (To be clear though, this PR was not actually reviewed, it just received some high-level initial feedback.)

Automation has since been added to help avoid that in the future.

> and now you guys say test not passed

No, we said that it doesn't have tests, which is not the same thing. This repository's contribution guide was probably not clear enough about the fact that this is a requirement for all PRs at the time you opened the PR unfortunately; that's been significantly improved since.

However, the framing that this is something we're only saying now is not correct. You were aware that it was missing tests when you opened the PR:

> * [ ]  My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md)).

And I flagged that this would be a blocker [four months ago](https://github.com/flutter/plugins/pull/1480#issuecomment-883411942):

>> However, this PR is not complete; it doesn't include tests, and thus won't pass review as-is (as explained in our contributor guide, and highlighted in the PR checklist).

Since that comment, no tests have been added.

When we provide actionable feedback on a PR (such as indicating that it needs to have tests added), and we don't hear back from the PR author, our policy is generally to close the PR under the assumption that the PR has been abandoned. As @Hixie said, you can always open a new PR if that's not actually the case.

> Oh this is Google style?

Flutter's engineering practice is to require tests as part of PRs, yes.

**Comment by yyoungg0318** [comment]
Funny

stuartmorgan ***@***.***> 於 2021年11月10日 週三 下午11:02寫道：

**Comment by yyoungg0318** [comment]
You got wrong point, this PR is not creatre for me, many ppl need this
feature, anyway, it's not my business now.
I'm using react native now. thanks.

stuartmorgan ***@***.***> 於 2021年11月10日 週三 下午11:02寫道：

**Pull request closed without merging**
