### PR TITLE
Re-add bin/ to flutter_plugin_tools

### PR DESCRIPTION
**Pull request by stuartmorgan**
This should have been re-added in #3836 but was missed, so it doesn't
work correctly via `pub global`.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [ ] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Anything else I might have missed in restoring this to working as a stand-alone tool? I'm not sure how to test this locally, unfortunately.

**Comment by cyanglaz** [comment]
@stuartmorgan `pub global activate --source path=<path_to_folder>`

Now thinking of it, maybe we should ask our ci to do the same (activate the tool from source instead of `dart run`) so we make sure the activate logic works correctly.

**Review by cyanglaz — APPROVED** [review]
LGTM! I can't think of anything that's missing, a local test will probably be sufficient to figure it out.

**Comment by stuartmorgan** [comment]
> `pub global activate --source path=<path_to_folder>`

Ah, perfect! Thanks :)

Looks like this does indeed work now.

**Pull request merged**
