### PR TITLE
[google_maps_flutter] Out of developers preview, bump to 1.0.0

### PR DESCRIPTION
**Pull request by amirh**
Bumps the minimally required Flutter SDK to 1.22, starting this version platform views are no longer in developers preview, so the plugin also gets out of developers preview as well.

We also bump the version to 1.0.0 as API stability has been reached.

### CODE REVIEW

**Review by cyanglaz — APPROVED** [review]
LGTM!

**Review by blasten — APPROVED** [review]
LGTM

**Comment by amirh** [comment]
Redness is because Flutter 1.22 is not released yet, landing on red.

**Review by blasten — APPROVED** [review]
LGTM

**Review by bparrishMines — APPROVED** [review]
LGTM

**Pull request merged**
