### PR TITLE
[webview_flutter] Add support for `NavigationRequest.type`

### PR DESCRIPTION
**Pull request by daohoangson**
## Description

Add `hasGesture` property for `NavigationRequest` object to assist developer in detecting whether a navigation request is triggered by user.

## Related Issues

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by abimujianto** [comment]
this plug in able for RTMP ?

**Comment by daohoangson** [comment]
> this plug in able for RTMP ?

No, this PR is about the web view plugin.

**Comment by ened** [comment]
Hi @daohoangson thank you for the PR.
The [WKNavigationType documentation](https://developer.apple.com/documentation/webkit/wknavigationtype?language=objc) seems to list other types of navigation types as well, in addition to the gesture. Do you think it's helpful for developers to get access to the fully detailed navigation type? If so, we perhaps could replace the boolean `hasGesture` with `navigationType`?

**Comment by daohoangson** [comment]
> Do you think it's helpful for developers to get access to the fully detailed navigation type? If so, we perhaps could replace the boolean hasGesture with navigationType?

More data is better however Android doesn't provide such detailed information so I had to settled on the `boolean`. 

Maybe we can create a new `enum` to encapsulate the difference between the two platforms?

**Comment by ened** [comment]
For the initial implementation, I’d probably go with a single enum for both and clearly document that android supports only one of the gesture types.
As a flutter front end developer you should only see a single powerful api.

Please ensure to add links to the iOS / Android docs in the enum flag documentation.

**Comment by daohoangson** [comment]
I'll update the PR to use the `enum`.

**Comment by daohoangson** [comment]
I have updated the PR to use a new enum (`NavigationType`), please take a look when you are available @ened. Thank you.

**Comment by daohoangson** [comment]
Sorry for tagging you directly @amirh, what does it take for this PR to be reviewed?

**Comment by stuartmorgan** [comment]
Thanks for the submission! We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

We’re currently working through a large backlog of PRs, and this will require non-trivial review, so it will take some time before we’re able to review it. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are the primary way we’re prioritizing non-trivial reviews, so we encourage you to file an issue and associate it with this PR.

**Comment by stuartmorgan** [comment]
> and this will require non-trivial review

Specifically, there are API design considerations that need to be evaluated here; having a lot of platform-specific entries scales poorly to larger numbers of platforms. Understanding the specific use case that you want to solve would be useful, as we could determine whether there's a way to abstract the information you specifically need to make this more scalable.

**Comment by stuartmorgan** [comment]
@daohoangson Could you file an issue to associate with this PR, where use cases can be gathered and discussed? Given my concern above, I'd like to see what a reasonable set of enum values is that cover use cases and are likely to be supportable across multiple platforms.

It would also be good to understand how the information we can get from iOS and Android map to what we would provide. E.g., iOS has back/forward; does Android consider that as having a gesture?

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
