### PR TITLE
[CAMERA] Solved device auto-rotation issue on android and iOS which caused the preview to be zoomed when auto-rotation is turned off and rotation is locked using SystemChrome.

### PR DESCRIPTION
**Pull request by AbhishekDoshi26**
*This PR solves the issue [#80881](https://github.com/flutter/flutter/issues/80881). Listening to Device Orientation into Camera Plugin is not required because when device is rotated, Flutter Framework will rotate the camera recording widget and thereby recording into landscape mode too*

*Issue resolved: [#80881](https://github.com/flutter/flutter/issues/80881)*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`. See [plugin_tool format](../script/tool/README.md#format-code))
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Comment by AbhishekDoshi26** [comment]
@darshankawar can you please review the PR

**Comment by AbhishekDoshi26** [comment]
@stuartmorgan can you please go through this PR too?

**Comment by AbhishekDoshi26** [comment]
@BeMacized I absolutely agree. However, don't you think if we listened to UI Orientation, and if we locked the UI with SystemChrome, the preview will get stretched as the UI Orientation Listener won't return any changes. I feel so.

**Comment by stuartmorgan** [comment]
Thanks for the submission! The next step here would be to set up tests asserting all the behaviors around rotation that we care about so that we can evaluate whether this change would address them without regressing other functionality.

**Comment by AbhishekDoshi26** [comment]
@stuartmorgan Hello, I don't have much knowledge about Test Cases and hence it will be great if someone can write the Test Cases for this PR.

**Comment by stuartmorgan** [comment]
See [the overview of plugin tests](https://github.com/flutter/flutter/wiki/Plugin-Tests) for information about types of plugin tests.

I'm going to mark this as a draft for now, as it's not ready for review until it includes tests.

**Comment by AbhishekDoshi26** [comment]
@stuartmorgan will someone be able to help on testcases? I am not able to do the same.
Thanks

**Comment by stuartmorgan** [comment]
> @stuartmorgan will someone be able to help on testcases?

Potentially, but that is work that will need to be prioritized against all of the other plugin work.

**Comment by AbhishekDoshi26** [comment]
> > @stuartmorgan will someone be able to help on testcases?
> 
> Potentially, but that is work that will need to be prioritized against all of the other plugin work.

I totally understand. Thanks though!

**Comment by stuartmorgan** [comment]
Looking at the implementation here, you're unconditionally turning off code (that was presumably written for a reason), and leaving a bunch of dead code in the plugin. This is very unlikely to be the correct change here, since it will almost certainly regress other things. So it's not just a matter of writing tests for this change, but of almost certainly needing a totally different implementation once those tests are written (since this would presumably regress some of them).

Given that, I'm going to close this PR. I encourage anyone interested in fixing this issue to start from the standpoint of making sure that there's thorough testing of rotation handling under a variety of scenarios, and then working from there to find a solution to the specific issue that is compatible with all of the other handling that is necessary.

**Pull request closed without merging**
