### PR TITLE
[in_app_purchase] Update README.md

### PR DESCRIPTION
**Pull request by KishanViramgama**
*Updating readme file content*  

> Update `Stream` to `Stream<List<PurchaseDetails>>`  and store data in array.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by KishanViramgama** [comment]
Change title and agree CLI terms and conditions

**Comment by stuartmorgan** [comment]
Thanks for the submission! Since most of the checklist is still blank I'm going to mark this as a draft; please mark it as ready for review once you've worked through the other items.

For this PR you'll need to read https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#readme-code in particular since changes to legacy README code samples need to be done as part of updating them to managed samples.

**Comment by stuartmorgan** [comment]
Please be sure to address my comment above (following all of the steps in the checklist, and updating this README to use the excerpt system) before marking this as ready for review.

**Comment by stuartmorgan** [comment]
Since you have marked this as ready for review twice without addressing the comments that I explained are necessary for that step, I'm going to go ahead and close this. Please feel to file a new PR if you are willing to complete the all of the required steps. Thanks!

**Pull request closed without merging**
