### PR TITLE
Support updateEmail in firebase_auth

### PR DESCRIPTION
**Pull request by thmsdnnr**
Updated firebase_auth plugin to expose updateEmail.
- defines an updateEmail method on FirebaseAuth with a named email parameter
- passes back exceptions, including failure to update if current user has not signed in recently e.g.:
```
PlatformException(Error 17014, FIRAuthErrorDomain, 
This operation is sensitive and requires recent authentication.
Log in again before retrying this request.)
```
 
#### Reference:
https://firebase.google.com/docs/auth/android/manage-users#set_a_users_email_address
https://firebase.google.com/docs/auth/ios/manage-users#set_a_users_email_address

#### Related Issues:
https://github.com/flutter/flutter/issues/18959
https://github.com/flutter/flutter/issues/17343

### CODE REVIEW

**Comment by ashtonthomas** [comment]
> We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that here in the pull request.

👍 

Confirming my commits,  `AUTHORS` addition, and submission of [CLA](https://cla.developers.google.com/clas)

**Comment by kroikie** [comment]
@thmsdnnr There are currently some conflicts on this PR. Rebasing on master should resolve them. Looking forward to getting the PR in. Thanks.

**Comment by thmsdnnr** [comment]
Hi @kroikie — sure thing! I rebased this on master this morning and bumped the patch version in the CHANGELOG and pubspec.

@ashtonthomas gave the OK when we initially submitted, since it's his repo we both worked on. I assume that's a manual confirmation on the CI checks. Please let us know if you need anything else.

**Comment by kroikie** [comment]
@thmsdnnr Thanks for those updates, we had another update to this plugin which is now conflicting. Please resolve those small conflicts. I'll be happy to merge once they are in.

**Comment by thmsdnnr** [comment]
@kroikie No problem! I rebased and bumped the pubspec version up to 0.5.18. It looks like a bunch of CI checks failed though, it looks like all linked to a Gradle issue:

```
* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not resolve com.android.tools.build:gradle-core:3.1.2.
     Required by:
         unspecified:unspecified:unspecified > com.android.tools.build:gradle:3.1.2
      > Could not resolve com.android.tools.build:gradle-core:3.1.2.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle-core/3.1.2/gradle-core-3.1.2.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle-core/3.1.2/gradle-core-3.1.2.pom'.
               > Read timed out
```

How should I proceed?

**Comment by saltpetreca** [comment]
Hi any eta on when 0.5.18 will be available. It is still showing 0.5.15 on flutter plugin

**Comment by saltpetreca** [comment]
Super thanks!

On Aug 10, 2018, at 12:21 PM, Arthur Thompson <notifications@github.com> wrote:

@saltpetreca sorry for the delay, published.

**Pull request merged**
