### PR TITLE
[location_background] Ignore for CI

### PR DESCRIPTION
**Pull request by mklim**
## Description

This pacakge should be removed entirely soon, so remove it from CI so we
don't spend further time on analyzer failures.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by mklim** [comment]
> I think this requires bumping the minimal Flutter version required to the first release where the template parameter was added.

Blacklisted it from our CI checks instead like we discussed offline.

**Comment by amirh** [comment]
CI seems to still be failing, e.g: https://cirrus-ci.com/task/5899696759898112

**Comment by collinjackson** [comment]
I'll fix the location_background issue in https://github.com/flutter/plugins/pull/1884 but this is still worth investigating

**Comment by mklim** [comment]
@amirh @collinjackson figured out the underlying issue. I missed a branch in `incremental_build.sh` where it decides to analyze every single package if it's running on `master`, and not just the `$CHANGED_PACKAGES`. So this PR doesn't do anything to prevent the analyze checks when CI is running on master commits itself. Will fix in a follow up.

**Pull request merged**
