### PR TITLE
[google_maps_flutter]provide builder class for LatLngBounds

### PR DESCRIPTION
**Pull request by RafaO**
Enable the creation of a LatLngBounds object from a list of LatLng instances.

Fixes https://github.com/flutter/flutter/issues/49728

### CODE REVIEW

**Comment by RafaO** [comment]
I signed it!

**Comment by RafaO** [comment]
I signed it!

**Comment by cyanglaz** [comment]
@RafaO The PR looks good, could you share what's the use case of this feature? Or if there is a related GitHub issue, it would be great if you can link us to it?  It seems to be just a convenient method and someone outside the plugin can also implement it if they need it.
I feel like we can leave the plugin users to choose if they want to implement such method in their app's code. WDYT?

**Comment by RafaO** [comment]
@cyanglaz thanks for getting back! You might be right, I was in the need of this method and I thought it could be useful for other people as well, that's why I thought it might be worth to include it as part of the plugin. Nevertheless, I understand your point of letting whoever needs it to implement it if you think it is not that common need.

**Comment by cyanglaz** [comment]
@RafaO I'm sure there are other people need this as well. I'm just not sure how many people need this. If you'd like to create a Github issue describing this feature. We can then prioritize this if we get a lot of thumbs.

**Comment by stuartmorgan** [comment]
Closing per my comment in https://github.com/flutter/flutter/issues/49728, but thanks for the submission!

**Pull request closed without merging**
