### PR TITLE
[local_auth] support localizedFallbackTitle in IOSAuthMessages

### PR DESCRIPTION
**Pull request by kaparray**
## Description

 Add support localizedFallbackTitle in IOSAuthMessages.

## Related Issues

https://github.com/flutter/flutter/issues/53205

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by kaparray** [comment]
@googlebot  I signed it!

**Comment by kaparray** [comment]
@googlebot how request code review?

**Comment by kaparray** [comment]
@googlebot What is this "submit-queue"?

**Comment by kaparray** [comment]
@a14n please approve or give an answer about PR

**Comment by a14n** [comment]
Sorry I'm not the right person to review this PR.

**Comment by kaparray** [comment]
@a14n Sorry 😐 Who review this PR? I need this update in my production app. Thx for help )

**Comment by a14n** [comment]
You can try to reach to someone on discord in hackers-ecosystem channel.

**Comment by kaparray** [comment]
What about the review?

**Comment by stuartmorgan** [comment]
We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

With the addition of https://github.com/flutter/plugins/pull/2489 it seems like this should only be supported in the non-biometric path, so this PR would need to be updated.

I also suspect that in that path we want the default to be `nil` rather than `@""`; deciding how the default behavior should be handled (whether to disable, or use nil) needs discussion, and due to the subtleties there this PR would definitely need a test.

**Comment by stuartmorgan** [comment]
Thank you for your contribution. I'm going to close this PR for now since there are outstanding comments, just to get this off our PR review queue. Please don't hesitate to submit a new PR if you have the time to address the review comments. Thanks!

**Pull request closed without merging**
