### PR TITLE
[in_app_pur] Add screenshots to pubspec.yaml

### PR DESCRIPTION
**Pull request by szakarias**

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Capturing from offline discussion: is there a way we can add this to the package's page but not the search results, since the image isn't really useful in the search context?

**Comment by szakarias** [comment]
> Capturing from offline discussion: is there a way we can add this to the package's page but not the search results, since the image isn't really useful in the search context?

Thanks for adding the comment here. At this point there is not, unfortunately.  

I agree in the consideration that this package does not offer a visual component, and hence might not be the best candidate for including screenshots. However, a screenshot might still give some value in the search context.

In any case, I think we should drop this PR for now, and see how the use of screenshots will evolve.

**Comment by mit-mit** [comment]
@stuartmorgan can you clarify how you find this "not useful"? It seems very useful to me to be able to see the payment UI when searching, as that is a good indication of the functionality of the plugin.

**Comment by mit-mit** [comment]
My understanding from the UX studies we did, visuals were desired as a way of confirming that a certain package is what the developer is looking for. So white the UI may be OS provided, a screenshot of it is a very strong visual clue to a developer that they have found the thing they are looking for.

cc @InMatrix to get his input

**Comment by stuartmorgan** [comment]
That makes sense to me in general, but my assumption is that "for making in-app purchases through the App Store and Google Play" is so unambiguous that a search listing screenshot is just going to be noise in this particular case. But if my mental model on this is wrong we can certainly reopen the PR.

**Comment by InMatrix** [comment]
Let's consider this pub.dev query: https://pub.dev/packages?q=In-App+Purchase. The `in_app_purchase` package is the 6th result. 

- Will providing a screenshot of `in_app_purchase` in the results page help the user distinguish the package from the rest of the search results? 
- What if all top 10 packages on that search results page provided screenshots? Will they look sufficiently different to provide value to the user?

Not knowing enough about the other packages returned from the query, I don't have good answers to these questions. However, others in the thread might have a better idea.

**Comment by stuartmorgan** [comment]
From a quick skim:
- The first one looks like it's probably wrapping the same libraries that `in_app_purchase` is, so my comment above about UI not being a distinguishing factor would almost certainly apply here.
- The second is one of the platform implementations of `in_app_purchase`; it should not be higher in search. An implementation package (one with `implementation` in the pubspec) should never be higher relevance for a generic search than the app-facing package, so that's a search ranking problem more than anything else.
- The third one looks like a UI library, where screenshots would help distinguish.
- I'm not sure what the fourth one is so I'm not sure
- The fifth isn't a real package, it's an ad for a Udemy course. With 7 likes and 26% popularity. Maybe screenshots would help, but as above that seems like a way to try to paper over a significant ranking issue.

**Comment by mit-mit** [comment]
Ranking issues aside (they are orthogonal to the issue), likely the first one on the list and our in purchase package would both use a screenshot of the native payment UI. I think that would be hugely helpful in having those two stand out against the others.

**Comment by stuartmorgan** [comment]
Okay, we can give this a shot then. This will just need to be updated to re-bump the version.

**Comment by mit-mit** [comment]
@szakarias can you help with that update?

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Pull request merged**
