### PR TITLE
[camera] Expand CameraImage DTO with properties for lens aperture, exposure time and ISO.

### PR DESCRIPTION
**Pull request by BeMacized**
This PR adds additional properties to the CameraImage DTO:

- `lensAperture`
- `sensorExposureTime`
- `sensorSensitivity`

Relevant issue:
- flutter/flutter#73250

This PR adds no breaking changes. 

As this PR depends on changes made by the Android refactor (#4059), this PR will remain in draft state until those changes have been merged. 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by BeMacized** [comment]
@googlebot I consent.

**Comment by BeMacized** [comment]
Closing in favour of #4256.

**Comment by alessandrostuppino** [comment]
Hi,
I'm working with version 0.9.4 and the properties `lensAperture`, `sensorExposureTime` and `sensorSensitivity` are no more available in the CameraImage DTO.

I'm using them in the following way:
```
_initializeControllerFuture = _controller.initialize().then((_) async {
        await _controller.startImageStream((image) {
          if (mounted) {
            setState(() {
                 _lensAperture = image.lensAperture ?? 0;
                 _sensorExposureTime = image.sensorExposureTime?.toDouble() ?? 0;
                 _sensorSensitivity = image.sensorSensitivity ?? 0;
            });
        }
    });
});


...

@override
  Widget build(BuildContext context) {
    return Column(
      children: [
        FutureBuilder<void>(
          future: _initializeControllerFuture,

...


```

I also tried to lock the version of the plugin to 0.9.1 or 0.9.2 but it didn't worked.
Any suggestion?

**Comment by AnimeshHestabit** [comment]
Hello, I am using the camera plugin: ^0.9.4+14  for camera in flutter, but I want to explore more advance features of camera for IOS and android both. So please help me out for this.I am not able to use the [camera] ISO, Shutter Speed etc like features.

**Pull request closed without merging**
