### PR TITLE
[camera] Implement interface methods to allow concurrent stream and record

### PR DESCRIPTION
**Pull request by adam-harwood**
_Recreated from https://github.com/flutter/plugins/pull/6290, that PR got messed up with some bad git merge. I tried to reset and force but GitHub closed the PR and I couldn't re-open it._

Implemented method to concurrently stream and record introduced in https://github.com/flutter/plugins/pull/6550. This feature is useful, for example, in applications that use image recognition. The customer will want some immediate feedback as the video is being recorded (where an ML model might be run on the captured images), as well as to upload the video to a server at the end for final server-side processing.

I have added unit tests to the higher-level dart abstractions, added integration tests for the underlying android and iOS implementations, and tested manually on Android and iOS devices. I have updated `camera_web` to throw an exception if the user attempts to enable streaming when recording (given that streaming is not yet supported).

Closes https://github.com/flutter/flutter/issues/83634

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [X] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

### CODE REVIEW

**Comment by adam-harwood** [comment]
Sorry for having to create a new PR and lose the history from https://github.com/flutter/plugins/pull/6290. I couldn't find a way to re-open it after GitHub auto-closed it.

**Comment by adam-harwood** [comment]
Looks like I need to break this into a few other PRs. Moving back to draft.

**Comment by bparrishMines** [comment]
@adam-harwood I reopened https://github.com/flutter/plugins/pull/6290 for you if you would like to keep using it.

**Comment by stuartmorgan** [comment]
Closing since it looks like re-opening https://github.com/flutter/plugins/pull/6290 obsoleted this.

**Comment by adam-harwood** [comment]
It did, yes thank you.

**Pull request closed without merging**
