### PR TITLE
[various] Enable `avoid_dynamic_calls`

### PR DESCRIPTION
**Pull request by stuartmorgan**
Enables the `avoid_dynamic_calls` lint, to bring us into better alignment with flutter/flutter lints.

There are some miscellaneous changes, but the large majority of these are cases where platform channel code was using `dynamic` values directly (usually for method call arguments). Common changes:
- Converting `dynamic` to a `Map` for method call arguments.
- Marking force-unwraps that were not previously flagged because `someDynamicVarible as NonNullableType` compiles, while `someObject?Variable as NonNullableType` doesn't and needs an explicit force-unwrap (due to another lint we already have enabled).

Since these changes aren't mechanical, and can cause runtime exceptions, they should be reviewed carefully (as we may well not have complete test coverage of all touched lines). In particular, please check that any `as List<...>` or `as Map<..., ...>` isn't using any types other than `dynamic` or `Object?`, as anything else is likely to be an exception-causing bug. (The correct construction for better typing is something like `(... as Map<Object?, Object?>).cast<AType, AnotherType>()`.)

In general I preferred using `Object?` for updated code, per modern Dart style, but in some cases where there was already significant explicit use of `dynamic` I kept that style to minimize disruption. We may want to separately clean up areas of code still using `dynamic` at another time. Although ideally, we would replace most of the code here with Pigeon and avoid the need for manual, error-prone casting at all.

Part of https://github.com/flutter/flutter/issues/76229

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I'll reconcile the webview parts of this on my side once webview v4 lands, but I wanted to get this completed and out for review since it touches a bunch of things.

**Review by jmagman — APPROVED** [review]
LGTM!

**Comment by stuartmorgan** [comment]
Oops, forgetting to check the repo tooling locally strikes again...

**Comment by jmagman** [comment]
Though there are still some analyzer errors.
```
   info - lib/src/common/git_version_finder.dart:91:35 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls
   info - lib/src/common/pub_version_finder.dart:48:10 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls
   info - lib/src/create_all_packages_app_command.dart:284:38 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls
   info - lib/src/dependabot_check_command.dart:61:35 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls
   info - lib/src/pubspec_check_command.dart:248:11 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls
   info - lib/src/pubspec_check_command.dart:268:36 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls
   info - lib/src/pubspec_check_command.dart:280:11 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls
   info - lib/src/readme_check_command.dart:237:36 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls
   info - test/common/git_version_finder_test.dart:27:11 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls
   info - test/common/git_version_finder_test.dart:30:18 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls
   info - test/common/package_looping_command_test.dart:114:11 - Avoid method calls or property accesses on a "dynamic" target. - avoid_dynamic_calls

```

**Review by cbracken — APPROVED** [review]

**Review by tarrinneal — APPROVED** [review]
Shared Prefs looks good

**Review by hellohuanlin — APPROVED** [review]

**Review by ditman — APPROVED** [review]
Looking good!

**Comment by stuartmorgan** [comment]
I held off on landing this so as not to disrupt webview v4; I need to update it to include those changes and then it'll be ready to land.

**Pull request merged**
