### PR TITLE
[google_maps_flutter_platform_interface] Added isGesture to onCameraMoveStartedWith Gesture 

### PR DESCRIPTION
**Pull request by tolotrasamuel**
## Description
This is the first part of this PR https://github.com/flutter/plugins/pull/3027

Google Maps Supports provide isGesture when camera starts to move on both iOS and Android but Flutter Google maps doesn't. This PR extends the Flutter Google Map dart code. No Java or Swift code touched because the channel actually provides the data, no idea why it was never implemented. To prevent breaking change, I created a new function. We can deprecate the old function later in the favour of this new function. 

## Related Issues

flutter/flutter#65755
flutter/flutter#50931 ( <- was a workaround )

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by tolotrasam** [comment]
@googlebot I consent.

**Review by tolotrasam — APPROVED** [review]

**Comment by stuartmorgan** [comment]
Thanks for the submission! We’re currently working through a large backlog of PRs, and this will require non-trivial review, so it will take some time before we’re able to review it. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are the primary way we’re prioritizing non-trivial reviews, so we encourage you to file an issue and associate it with this PR.

We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

> [x] My PR includes unit or integration tests for _all_ changed/updated/fixed behaviors (See [Contributor Guide](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md)).

You've indicated that you've added tests as required by our submission policy, but I'm not seeing them; please ensure that you haven't left files out of the push.

**Comment by stuartmorgan** [comment]
@tolotrasam Approving PRs is reserved for contributors, as it says in the Flutter wiki.

**Comment by stuartmorgan** [comment]
I'm going to close this for now; as described in the contributing docs, we hold off on making the platform interface PRs until the main PR has been fully reviewed (this is to avoid cases where a platform interface change could land without the the main PR ever getting to a landable state). Please re-open (or make a new PR, whichever is easier) once that main PR has passed review.

**Pull request closed without merging**
