### PR TITLE
[ci] Complete architecture switch for iOS

### PR DESCRIPTION
**Pull request by stuartmorgan**
Enables the new architecture tests for iOS and turns down the old ones. Platform tests are now run on ARM, and the build-all test is run on Intel for coverage of building on both architectures.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
I'm going to do a few presubmit runs here; the staging results so far are concerning:
Screenshot 2023-01-31 at 9 05 40 AM

The red is a specific maps test failing flakily, which I can look into, but the blue is hangs.

**Comment by stuartmorgan** [comment]
So far the first and second runs of all 5 iOS tests all passed without issue; trying a third run. (Maybe somehow some of the infra issues yesterday were affecting runs?)

**Comment by stuartmorgan** [comment]
Shard 5 hung on the third run. The output seems to end in video_player, but I'm not sure if it's actually video_player or something later (webview being the most likely other candidate) since I don't know how much output we're missing. Or, maybe the tests aren't hanging at all, and this is the meta-problem I've seen in a variety of different forms with LUCI, like https://github.com/flutter/flutter/issues/115937 or https://github.com/flutter/flutter/issues/81297, where something makes LUCI *think* it's still running.

@jmagman 1/3 runs having a hang isn't great, but it's also probably livable for now given that most runs don't run most packages (or won't once I fix https://github.com/flutter/flutter/issues/119330, which I'm hoping my second PR there will do), which will make the flake occurrence much lower than that in practice. I'm tempted to go forward with the switch and push for help from infra finding out what's going on, rather than staying in limbo indefinitely on this transition, especially since there was discussion of trying to free up as much Intel macOS infra as possible. Thoughts?

**Comment by jmagman** [comment]
> 1/3 runs having a hang isn't great, but it's also probably livable for now given that most runs don't run most packages (or won't once I fix [flutter/flutter#119330](https://github.com/flutter/flutter/issues/119330), which I'm hoping my second PR there will do), which will make the flake occurrence much lower than that in practice. I'm tempted to go forward with the switch and push for help from infra finding out what's going on, rather than staying in limbo indefinitely on this transition

Can we keep the arm tests in staging (bringup: true) while it's investigated?  Do you have a link to an example?

> especially since there was discussion of trying to free up as much Intel macOS infra as possible.

I think having it be flaky and closing the tree randomly will be worse. You could remove the x64 shards and leave the arm ones in staging, though of course that may mean legit test failures are missed.

**Comment by stuartmorgan** [comment]
I started filing an issue, and discovered that it's not actually hanging, it's randomly so slow it can't finish in 60 minutes. https://github.com/flutter/flutter/issues/119750 has details; still investigating more.

**Comment by stuartmorgan** [comment]
It looks like the machine issue may be resolved soon; if it drags out we can consider landing this but with longer timeouts so the behavior will be that the tree will sometimes be slow (mostly for rolls and tooling changes, which run all packages), but won't actually fail, and a TODO to lower the timeouts again once the issue is fixed. That way we won't be in limbo on the switch indefinitely.

**Review by jmagman — APPROVED** [review]
Code LGTM, follow your heart about when to land it based on the slow machine investigation.

**Review by jmagman — APPROVED** [review]
😞

**Comment by stuartmorgan** [comment]
> 😞

Hopefully it'll get resolved before too long, but I decided I don't want to copy the half-way limbo state over to flutter/packages, and I want to do the last of the alignment to unblock the merge.

**Comment by stuartmorgan** [comment]
Landing on red since the tree redness is, somehow, one of the tasks that this PR takes out of bringup mode timing out after an hour. I don't understand how that's possible before this PR lands, but that means we really need to land the increased timeouts.

**Pull request merged**
