### PR TITLE
rev all compileSdkVersion to 28

### PR DESCRIPTION
**Pull request by dnfield**
Should fix CI

cc @mklim

### CODE REVIEW

**Comment by dnfield** [comment]
@fkorotkov this is the PR I actually meant to tag you on.  Is this container image linked to the one we make?

**Comment by fkorotkov** [comment]
@dnfield yeah, but there is no tools 27 on this image: https://github.com/cirruslabs/docker-images-android/blob/master/sdk/28/Dockerfile#L6-L8

I wonder where it gets them from. And also why only some plugins are failing and others not.

**Comment by dnfield** [comment]
I suspect it's getting pulled in by some other dependency in the tree that's actually specifying `buildToolsVersion`.  Looks like we took that out at some point in the past - trying to just add it back in.

**Comment by dnfield** [comment]
I'm really not sure what's making some of these guys hold on to Android 27.  They shouldn't be.

@fkorotkov  Do you think it would be a problem to just add SDK 27 and Buildtools 27.0.3 to the Android image for Cirrus?

**Comment by dnfield** [comment]
Closing in favor of #1104

**Pull request closed without merging**
