### PR TITLE
[webview_flutter] local html and baseUrl support

### PR DESCRIPTION
**Pull request by uc-apa**
## Description

*This is an enhancement of the current implementation of flutter webview. This addresses the issue of loading static html in webview, alongwith baseUrl support. This works in both ios and android.*

## Related Issues

*Earlier we used to do it through initialUrl, by converting it to base64 string and so on. React native has a proper support for static html and baseUrl.(https://github.com/fluttercommunity/flutter_webview_plugin/issues/23)*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by AhmedNourJamalElDin** [comment]
Any reason this is not merged yet?

**Comment by TheManuz** [comment]
I really need this feature, what happened?

**Comment by stuartmorgan** [comment]
Thanks for the contribution! We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

Thanks for the submission! We’re currently working through a large backlog of PRs, and this will require non-trivial review, so it will take some time before we’re able to review it. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are a primary way we’re prioritizing non-trivial reviews, so we encourage you to file an issue and associate it with this PR.

**Comment by stuartmorgan** [comment]
@mvanbeusekom This PR is relevant to recent discussion about alternate loading options. We'll need to evaluate everything (URL-based, string-based, local file-based) holistically to ensure we don't end up with a mess of paramaters that are all mutually exclusive, and then factor that into API iteration here.

**Comment by stuartmorgan** [comment]
Closing as obsolete, since #4446, #4486, and to-be-written-soon follow-up PRs add local file handling based on discussion about how we want the suite of load APIs to interact. Thanks again for the submission though!

**Pull request closed without merging**
