### PR TITLE
fix typo google_maps_flutter

### PR DESCRIPTION
**Pull request by DzinVision**
Fixes issue flutter/flutter#20178. 

There was a typo in [GoogleMapController.m](https://github.com/flutter/plugins/blob/master/packages/google_maps_flutter/ios/Classes/GoogleMapController.m). Instead of 
```objc
(void)mapView:(GMSMapView*)mapView didTapInfoWindow:(GMSMarker*)marker
``` 
there should be 
```objc
(void)mapView:(GMSMapView*)mapView didTapInfoWindowOfMarker:(GMSMarker*)marker
```
according to [google maps documentation](https://developers.google.com/maps/documentation/ios-sdk/reference/protocol_g_m_s_map_view_delegate-p.html#ae1614978aef680d671a6a95da8e13bf7).

### CODE REVIEW

**Comment by DzinVision** [comment]
I signed it!

**Comment by bkonyi** [comment]
@DzinVision @zigapk, I see there's commits on this PR that aren't mentioned in the description (and have comments explicitly saying not to submit to Google). Is this intentional?

**Comment by gerryhigh** [comment]
@bkonyi Sure would be nice to get this merged. I'd recommend only merging this commit: https://github.com/flutter/plugins/pull/704/commits/65ef5589f2ce8aff64763d8e989e03278db99554

**Comment by zigapk** [comment]
Hi!

Yes, this was intentional. `65ef558` works fine and should be merged or otherwise fixed. However, latter commits include some ugly 'try-catch' solutions (good enough for our use case), but definitely not suitable for public use.

We'd love to implement this user location feature properly, but are unfortunately running low on time. So yes, merging `65ef558` only is probably the best idea.

**Comment by bkonyi** [comment]
@zigapk, would you mind creating a new PR with just that commit then?

**Comment by jmcdole** [comment]
Looks like I have run into this issue.  Can I encourage merging only this commit: 65ef558 ?

Thank you!

**Comment by Hixie** [comment]
cc @amirh Can you cherry-pick the "good" change from this PR (https://github.com/flutter/plugins/commit/65ef5589f2ce8aff64763d8e989e03278db99554) and submit that separately?

**Comment by mit-mit** [comment]
@amirh did we get this picked?

**Comment by amirh** [comment]
Sorry for the delay here.

I just sent https://github.com/flutter/plugins/pull/934 with an equivalent typo fix.

**Pull request closed without merging**
