### PR TITLE
[shared_preferences]Shared preferences: add default value capability

### PR DESCRIPTION
**Pull request by jaumard**
fix https://github.com/flutter/flutter/issues/22806

### CODE REVIEW

**Comment by jaumard** [comment]
`pub global run flutter_plugin_tools format --plugins shared_preferences` give me this error on my Mac: 
```
Downloading Google Java Format...
Formatting all .dart files...
Unhandled exception:
ProcessException: No such file or directory
  Command: flutter format /Users/jaumard/StudioProjects/plugins/packages/shared_preferences/test/shared_preferences_test.dart /Users/jaumard/StudioProjects/plugins/packages/shared_preferences/example/lib/main.dart /Users/jaumard/StudioProjects/plugins/packages/shared_preferences/lib/shared_preferences.dart
#0      runAndStream (package:flutter_plugin_tools/src/common.dart:171:7)
<asynchronous suspension>
#1      FormatCommand._formatDart (package:flutter_plugin_tools/src/format_command.dart:98:11)
<asynchronous suspension>
#2      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:39:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:194:27)
<asynchronous suspension>
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109:29)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      CommandRunner.run (package:args/command_runner.dart:109:11)
#7      main (package:flutter_plugin_tools/src/main.dart:41:17)
#8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```
what am I doing wrong ?

**Comment by jaumard** [comment]
All good :) I formatted file manually as `pub global run flutter_plugin_tools` doesn't work for me

**Comment by stevenspiel** [comment]
Can this be merged?

**Comment by acherkashyn** [comment]
@mclark4386 Can this be merged now? This is a useful addition to shared preferences plugin, I'd love to use this in my project when it's released. Thanks in advance.

**Comment by mclark4386** [comment]
@acherkashyn It's fine with me, but I don't have merge permissions^^;

**Comment by acherkashyn** [comment]
@collinjackson @cyanglaz Could you please take a look at this PR? It's been open since October, everything is already implemented and ready to merge. This is useful feature that makes the API more developer friendly.

**Comment by cyanglaz** [comment]
Thank you for providing the PR. 
I don't think this is really necessary. People can just use `??` to have the same behavior. E.g.
```
Bool myBool = getBool('myKey') ?? false;
```
Closing the PR now.

**Comment by jaumard** [comment]
I think even if you can use `??` it's still nice to have a clean API that offer you clear way of doing things :)

**Comment by cyanglaz** [comment]
I agree that it's always nice to have a clean API. However, in this case, I don't see the benefit of passing an object in the parameter and to let the method return the same object as default. I understand that you might not want to have `??` all of the places in your code. In that case, you can create your own helper methods to wrap around the original methods that provided in the plugin. Will that help?

**Comment by jaumard** [comment]
I know I can have my own wrapper but when I did the PR I considered that a lot of people will have to do that wrapper, so why not have it integrated to the plugin directly, even more when the android native sharedPreferences have those default values. And I don't see the point of create a third party package just for that =D 

My point is just about readability `getString('myKey', defaultValue: 'ok');` is more readable than just `getBool('myKey') ?? false;` even more when you have new people / junior on the team. 
If you consider that people should do their wrapper or use `??` fine by me :)

**Pull request closed without merging**
