### PR TITLE
[google_maps_flutter] Button UI improvements

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Use raised buttons to make actions look clickable. Use gridView to organize button actions. Abstract button creation code into private helper functions to make build methods more readable.

screenshot_1539195979
screenshot_1539195973
screenshot_1539195966
screenshot_1539195962
screenshot_1539195957

### CODE REVIEW

**Comment by kenzieschmoll** [comment]
@amirh

**Comment by iskakaushik** [comment]
@kenzieschmoll do you still plan on working on this PR?

**Comment by kenzieschmoll** [comment]
No, you can close it out if you want. I threw this PR together to make some quick improvements, but Hans asked me to make it more material, and at that point it didn't make sense for me to spend any more bandwidth on it.

**Comment by iskakaushik** [comment]
@kenzieschmoll thanks!

**Pull request closed without merging**
