### PR TITLE
[webview_flutter] Add setter and getter for cookies

### PR DESCRIPTION
**Pull request by wwwdata**
## Description

This is adding cookie setter/getter methods to set cookies inside the Web View.

## Related Issues

There already is this #1880  where I based my work on. But a lot of other cookie properties for iOS needed to be supported and I also added tests, formatted everything, so this is ready to merge.

Fixes flutter/flutter#27597

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

For iOS I am using a WKProcessPool now which is syncing the cookies between all instances of WebViews. Is that a breaking change? Was anybody relying on the behavior of having some more or less randomized isolated environments?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by wwwdata** [comment]
@amirh Is there any interest in having a cookie set/get feature for this plugin? Also, there is the other older PR still open. When do the maintainers of this plugin decide if and what approach could be accepted? Also if this is not OK from an API perspective or anything, just write me what a good API should look like and I will change the code to adapt to that.

**Comment by ftore** [comment]
When this PR is going to be merged? @wwwdata it seems, it has conflicts.

**Comment by wwwdata** [comment]
@ftore I have no idea when or if this is ever going to be merged because so far there was no official feedback. In the meantime, I also learned a lot more about cookie settings. And I think the cleanest way to do it is to just send the raw cookie header string over to the native side and use the constructor methods that extract the cookie values from that. If I would adapt my PR to this behavior I would make 2 options: Either send over dart Cookie values (which will be transformed to the Header String) or directly send String values over to the native side, where they will be correctly instantiated to and handled. With this approach, it is also very easy to for example write an HTTP request interceptor that extracts all cookies from your Dart API calls and sets them into the web views as well, if for example, both of them authenticate based on cookies. I learned that a cookie is not a cookie, apparently, there are also at least 2 different versions of it, as I learned here in the Apple documentation: https://developer.apple.com/documentation/foundation/httpcookie

@amirh what is the status here? What do you think about the idea that I wrote? I would be willing to follow this up here, clean up everything that is requested to that there can finally be an official cookie set/get support in the official web view plugin.

In the meantime, I was using a different web view implementation because the page of PR reviews is unfortunately very slow in the official flutter plugins repo :(

**Comment by ftore** [comment]
@wwwdata Thanks for suggestion. The thing is I am not trying to set cookies, but I am trying to read them. Sure, currently I can read them by using javascript and document.cookie, but this will not return cookies marked as HttpOnly.

```To help mitigate cross-site scripting (XSS) attacks, HttpOnly cookies are inaccessible to JavaScript's Document.cookie API; they are only sent to the server. For example, cookies that persist server-side sessions don't need to be available to JavaScript, and the HttpOnly flag should be set.```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

As with your PR, I see that there is getCookies method and it is trying to fetch all the cookies native way, that will return HttpOnly cookies too. Is that right?

**Comment by wwwdata** [comment]
That is correct. It will also return http only cookies that cannot be read out by JavaScript.

**Comment by ftore** [comment]
@amirh we need any feedback on this, please.

**Comment by rusyasoft** [comment]
Lets merge and enjoy by eating some cookies.
I think, at leasting reading HttpOnly should be possible !

**Comment by rodruiz** [comment]
Hi @wwwdata,
could you extract this into a Webview Cookie Manager package?

Thanks.

**Comment by stuartmorgan** [comment]
Thanks for the submission! We’re currently working through a large backlog of PRs, and this will require non-trivial review, so it will take some time before we’re able to review it. As explained in [CONTRIBUTING.md](https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#the-review-process), votes for the corresponding issue are the primary way we’re prioritizing non-trivial reviews; this is a fairly highly-voted issue, so we expect to be able to take a look at this soon and discuss how to best support cookie management (per the recent comment).

We apologize for the long delay in triaging this PR. We’re in the process of overhauling our PR triage system to respond much more quickly, as well as working through the backlog.

**Comment by koteesy** [comment]
This pull request opened 2 years ago, and still not merged, when people opening issues and request this feature?

**Comment by stuartmorgan** [comment]
Closing as obsolete, as the linked issue was fixed by https://github.com/flutter/plugins/pull/4561/files

If you're still interested in adding cookie reading, that would be best done as a new PR given that the plugins have been substantially restructured since this was opened, so a new PR for that portion would be easier that updating this one. Note that a significant change to the iOS implementation is still pending, so you'd want to wait until https://github.com/flutter/flutter/issues/93732 is closed.

**Pull request closed without merging**
