### PR TITLE
[in_app_purchase] Fix crash iOS sandboxTesting default value

### PR DESCRIPTION
**Pull request by Vardiak**
## Description

Currently, in_app_purchase crashes when initiating a payment if `sandboxTesting` of `PurchaseParam` is `null`. But it is actually its default value (contrary to the definition which states that default value is false). In this pull request, the default value is fixed & I added an assert to check if the user didn't pass null explicitly which would cause a crash.

## Related Issues

https://github.com/flutter/flutter/issues/65767

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Vardiak** [comment]
@googlebot I signed it!

**Comment by cyanglaz** [comment]
@Vardiak Thanks for the fix! Could you add a test for this? We would also need to bump the minor version of the plugin since the public API has changed.

**Comment by Vardiak** [comment]
> @Vardiak Thanks for the fix! Could you add a test for this?
> 
> In order to make it non-public API change fix, I would recommend to fix it on the OBJC side. We can always allow this value to be null and in the OBJC side, we just take the null value as `false`.

I'm not a OBJC developer, I may be able to help fix it there but I don't know what kind of test you are expecting me to write, since the fix is straightforward.

**Comment by cyanglaz** [comment]
@Vardiak The test can be "if the `sandboxTesting` is nil, there is no crash"

**Comment by Vardiak** [comment]
#3110 handles the issue at platform level, which is a better implementation

**Pull request closed without merging**
