### PR TITLE
[firebase_messaging]: add additional documentation for the data in notifications

### PR DESCRIPTION
**Pull request by ehhc**
## Description

In the documentation of the firebase_messaging plugin could have a more detailed section about accessing the data send alongside the notification. It would help not to waste time debugging and finding the errors if the documentation would explain it a bit better..

## Checklist
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by ehhc** [comment]
I signed it! 
:)

**Comment by ehhc** [comment]
i am the only author of the change. Maybe the problem is that i pushed it using another computer than normal and therefore commited strange author informations..

**Comment by collinjackson** [comment]
Thanks for the contribution.

I'd like to consider making some breaking changes to allow more re-use of code across platforms, but I maybe for now documenting the current behavior is better than having it be confusing.

Can you please fix the analyzer failures?

**Comment by ehhc** [comment]
@collinjackson done

**Pull request merged**
