### PR TITLE
Correcting DateTime timestamp submission

### PR DESCRIPTION
**Pull request by eliothsu**
Fixing issue [#18470](https://github.com/flutter/flutter/issues/18470)

### CODE REVIEW

**Comment by eliothsu** [comment]
I've signed the CLA linked above.

**Comment by kroikie** [comment]
@eliothsu Thanks for the PR, I was not able to reproduce this. If you can assist with that in the [issue](https://github.com/flutter/flutter/issues/18470) then I'd be happy to accept.

**Comment by goderbauer** [comment]
@kroikie @eliothsu Is this PR still relevant or should we close it?

**Comment by kroikie** [comment]
Closing this PR, since this seems to no longer be an issue.

**Comment by nyanmatt** [comment]
@martinvarelaaaa 
I recently ran into what I thought was the same problem. Turns out that my really looooong integers were being truncated on the platform because the iPhone 5c is a 32-bit device. For me personally, that was happening through the `sqflite` plugin.

Check your integers. Long ints don't behave well on 32-bit iPhones.

**Comment by mabinici** [comment]
This error seems to be solved for iPhones, but I am able to generate the same issue on an Ipad for some reason.

**Pull request closed without merging**
