### PR TITLE
[camera] Expose auto exposure and auto focus point of interest functionality (iOS only)

### PR DESCRIPTION
**Pull request by lsmith130**
I'd love to implement this for Android too, but I don't have a device to test with, and I believe the emulator is a no-go for camera testing.

### CODE REVIEW

**Comment by lsmith130** [comment]
I signed it!

**Comment by lsmith130** [comment]
Who needs to look at this to get it merged?

**Comment by lsmith130** [comment]
@kroikie who needs to review this so I can get it merged? I just had to update for a style guide change, I'd rather get this soon to avoid extra maintenance. Thanks!

**Comment by lsmith130** [comment]
@hariprasadiit I would love to get this merged, but I haven't been able to get anyone to review or even comment. What can I do to help this along?

**Comment by TareqElMasri** [comment]
When can this be merged people?

**Comment by edwardhuerta** [comment]
There is no implementation in this PR for Android. Instead of merging, we should look for people to implement the Android part before merging.

**Comment by lsmith130** [comment]
I recently bought an Android device that I can use for building and testing an Android implementation of this PR in the next few weeks if no one gets to it sooner

**Comment by jdeltoft** [comment]
Hi, how is the progress for Android coming along?  Also, is there a way to get auto focus enabled for this plugin?

**Comment by lsmith130** [comment]
@jdeltoft I haven't had a chance to work on it, but I should be able to knock it out sometime in the next few weeks. This PR implements setting the auto focus/point of interest in screen coordinates, but if you want to implement something like Google's camera app for Android with more advanced auto focus, that's beyond the scope of what I'm working on here.

**Comment by Afsalpp** [comment]
@lsmith130 What is the progress of Android auto focus? How can I check the camera is focused or not?

**Comment by ianpark** [comment]
I am wondering if it's gonna be merged soon.

**Comment by Hixie** [comment]
Looking at this PR, I presume the reason it hasn't been merged is that it is lacking tests. I'm not sure if we yet have the technology to write tests for this kind of plug-in, though.

cc @bparrishMines @collinjackson

**Comment by bparrishMines** [comment]
@Hixie 
We prioritize based on customers and the thumbs up found in the issue connected to the PR. In this case, it looks like its this issue: https://github.com/flutter/flutter/issues/24575.

Unfortunately, we don't have anyone who can look at it right now. However, it is missing an Android implementation and tests usually make it easier to review. But, just like flutterfire plugins that require credentials, we could write tests that would only run locally.

cc @mklim

**Comment by morbyosef** [comment]
What is the status of this feature? when will it be merged?

**Comment by iNima** [comment]
Please merge this pull request if it is possible!

**Comment by drosa88** [comment]
Thanks for your work! Could this simply be changed to a "tap to focus" functionality?

**Comment by misaelriojasftf** [comment]
holy what happened I need this feature :/

**Comment by mvanbeusekom** [comment]
Closing as duplicate of #3346 and #3370

**Pull request closed without merging**
