### PR TITLE
[camera_platform_interface] Add web-relevant docs

### PR DESCRIPTION
**Pull request by ditman**
This PR is the platform_interface part of: https://github.com/flutter/plugins/pull/4240.

```
git cherry-pick 52b8608f61f230ba89ef0e4acbfee0e0f6cce47b
git cherry-pick ad5057472e07df63604489ec344c6a47d2de02a5
```

It adds information relevant to the web to the platform interface docs.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by ditman** [comment]
@bselwe do you mind approving this PR? It's asking for your permission because I cherry-picked your commit into a branch on my fork, you just need to comment `@googlebot I consent.`

@mvanbeusekom / @BeMacized do you mind reviewing+landing this? It's a very simple change in the platform_interface docs. In case of any changes required, I think you guys have more "office time" overlap with @bselwe than I do :)

Once this is landed, I'll be able to rebase https://github.com/flutter/plugins/pull/4240 one final time, so only the `camera` example changes need to land!

Thanks everybody!

**Review by mvanbeusekom — APPROVED** [review]
LGTM, once @bselwe gives his consent I will make sure this will land.

**Comment by bselwe** [comment]
LGTM! Could we also update [this line](https://github.com/flutter/plugins/pull/4358/files#diff-fe9810586c23b9d24500081f5328bcfb90315edba7e083d12623eecdbe6ea3a3R21) in `ResolutionPreset` to:
```dart
/// 2160p (3840x2160 on Android and iOS, 4096x2160 on Web)
```
(same as [here](https://github.com/flutter/plugins/pull/4240/files#diff-fe9810586c23b9d24500081f5328bcfb90315edba7e083d12623eecdbe6ea3a3R21))

**Comment by bselwe** [comment]
@googlebot I consent.

**Comment by ditman** [comment]
> LGTM! Could we also cherry-pick this commit to include:

Arrrrgh, I didn't notice that one! I'll cherry-pick and merge! Thanks @mvanbeusekom!

**Comment by mvanbeusekom** [comment]
Anytime @ditman

**Pull request merged**
