### PR TITLE
[in_app_purchase] Replace `errorColor` to land deprecations

### PR DESCRIPTION
**Pull request by guidezpl**
Anticipate deprecations from https://github.com/flutter/flutter/pull/110848

Related https://github.com/flutter/flutter/issues/91772

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [ ] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Review by GaryQian — APPROVED** [review]
Lgtm. You need to bump the version in pubspec and CHANGELOG to pass publishable.

**Comment by guidezpl** [comment]
Is that necessary since this only touches example code?

**Comment by Hixie** [comment]
test-exempt: refactor with no semantic change

**Comment by stuartmorgan** [comment]
> Is that necessary since this only touches example code?

example/lib/main.dart is published on pub.dev, so this should have been published (the repo tooling knows which example file changes require publishing and which don't, so wouldn't have flagged it otherwise). People look at, and copy from, example code on pub.dev, so we don't generally want to leave deprecated code there.

**Comment by guidezpl** [comment]
I see, should I create a separate PR to bump the version and add a changelog entry?

**Comment by stuartmorgan** [comment]
It's not critical in this case, just please don't override the checks in the future without checking with #hackers-ecosystem first (unless you're certain it's a false-positive).

**Comment by guidezpl** [comment]
Gotcha. Please consider updating https://github.com/flutter/plugins/blob/main/script/tool/lib/src/version_check_command.dart#L563-L586

**Comment by stuartmorgan** [comment]
> Gotcha. Please consider updating https://github.com/flutter/plugins/blob/main/script/tool/lib/src/version_check_command.dart#L563-L586

Do you have specific suggestions for updates? It currently says to use the override of it's a false positive, which is correct.

**Comment by stuartmorgan** [comment]
It doesn't have to specifically be the Discord channel, that was just a suggestion for where to ask; asking your reviewer would also work.

I just meant, please don't unilaterally decide that it's a false positive if you don't actually know. If you aren't sure, the right thing to do is to make sure you get an answer before overriding a check.

**Pull request merged**
