### PR TITLE
[camera_platform_interface] Add support for NV21 image format on android (part 1/3)

### PR DESCRIPTION
**Pull request by acoutts**
This is part 1 of [!6985 ](https://github.com/flutter/plugins/pull/6985) which adds support for NV21 image streaming on Android. It adds NV21 as an option in `ImageFormatGroup`.

This should be merged first because the updates to `camera` and `camera_android` in parts 2/3 both require this change.

*List which issues are fixed by this PR. You must list at least one issue.*
* https://github.com/flutter/flutter/issues/118350

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by acoutts** [comment]
cc @camsim99

**Comment by acoutts** [comment]
Can anyone help me understand how to satisfy this PR check?
> �[31m  When bumping the version for release, the NEXT section should be incorporated into the new version's release notes.�[0m

**Comment by acoutts** [comment]
@stuartmorgan do you know how to fix the `submit-queue` failing job for win32?

**Comment by acoutts** [comment]
This is all set for a review now @bparrishMines -- all CI tasks look to have passed.

**Comment by stuartmorgan** [comment]
> @stuartmorgan do you know how to fix the `submit-queue` failing job for win32?

`submit-queue` reflects the current state of the tree, and is unrelated to the PR, so you can always ignore it during development. It shows up here to prevent PRs from landing while the tree is red.

**Comment by jomagsm** [comment]
> This is part 1 of [!6985 ](https://github.com/flutter/plugins/pull/6985) which adds support for NV21 image streaming on Android. It adds NV21 as an option in `ImageFormatGroup`.
> 
> This should be merged first because the updates to `camera` and `camera_android` in parts 2/3 both require this change.
> 
> _List which issues are fixed by this PR. You must list at least one issue._
> 
> * [[camera] Image stream data is corrupt on some Android devices (Vivo, Xiaomi, Motorola) flutter#118350](https://github.com/flutter/flutter/issues/118350)
> 
> ## Pre-launch Checklist
> * [x]  I read the [Contributor Guide](https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
> * [x]  I read the [Tree Hygiene](https://github.com/flutter/flutter/wiki/Tree-hygiene) wiki page, which explains my responsibilities.
> * [x]  I read and followed the [relevant style guides](https://github.com/flutter/plugins/blob/main/CONTRIBUTING.md#style) and ran [the auto-formatter](https://github.com/flutter/plugins/blob/main/script/tool/README.md#format-code). (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
> * [x]  I signed the [CLA](https://cla.developers.google.com/).
> * [x]  The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
> * [x]  I listed at least one issue that this PR fixes in the description above.
> * [x]  I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning), or this PR is [exempt from version changes](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates).
> * [x]  I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style).
> * [x]  I updated/added relevant documentation (doc comments with `///`).
> * [x]  I added new tests to check the change I am making, or this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests).
> * [x]  All existing and new tests are passing.
> 
> If you need help, consider asking for advice on the #hackers-new channel on [Discord](https://github.com/flutter/flutter/wiki/Chat).

Are you working on this bug?

**Comment by acoutts** [comment]
These 3 PRs fix the issue I linked, correct.

**Comment by bparrishMines** [comment]
@acoutts This feature needs to go through the process of updating a federated plugin and get a PR approved that contains the changes for the platform interface and the Android platform implementation https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins

And it looks like you already created a PR that contains the changes: https://github.com/flutter/plugins/pull/6985

I can reopen that PR if you would like to use that one.

**Comment by acoutts** [comment]
@bparrishMines i thought I would need 3 separate PRs to do this, because first we have to publish a new version of `camera_platform_interface` before we can publish the new versions of `camera` and `camera_android` which rely on it. Is that not the case?

**Comment by acoutts** [comment]
I understand now - yes please let's re-open that and we can use that for the review. I'll have to double check the changes and sync things up again but I'll get it cleaned up.

**Comment by stuartmorgan** [comment]
Marking as draft until https://github.com/flutter/plugins/pull/6985 is reviewed.

**Pull request closed without merging**
