### PR TITLE
[webview_flutter] Implement zoom enabled for ios and android

### PR DESCRIPTION
**Pull request by NickalasB**
This PR adds the iOS and Android implementations of the soon-to-be added `zoomEnabled` param on the WebView widget after the `platform_interface` method was merged in https://github.com/flutter/plugins/pull/4404.

If approved and merged, this PR will be followed up with https://github.com/flutter/plugins/pull/3325, adding `zoomEnabled` to the main `flutter_webview` package as outlined in the [instructions on changing Federated Plugins](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changing-federated-plugins). 

*List which issues are fixed by this PR. You must list at least one issue.*
Implements flutter/flutter#70731
Implements flutter/flutter#48283
Relates to flutter/flutter#48245
Relates to flutter/flutter#60921

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
- [x] No this is *not* a breaking change

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Note that unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [X] I signed the [CLA].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I [updated pubspec.yaml](https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates) with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code

### CODE REVIEW

**Comment by NickalasB** [comment]
@stuartmorgan @bparrishMines here's the 2nd PR for this plugin update. Thank you for taking a look!

**Comment by stuartmorgan** [comment]
> @bparrishMines Lol. Knowing where the tests are definitely helps!

This is documented at https://github.com/flutter/flutter/wiki/Plugin-Tests#types-of-tests; suggestions for how to make that easier to find are welcome (although it may just be that since the original PR predates that page, you just never saw the newer version of the contribution guide that links there).

**Comment by NickalasB** [comment]
> @NickalasB That solution looks fine. You could also pass the test `NavigationDelegate` a mock `WkWebView` and use verify to check that `evaluateJavaScript` was called when `didFinishNavigation` was called.
> 
> ```objc
> OCMClassMock(WKWebView.class);
> OCMVerify([_mockWebView evaluateJavaScript:/*check parameters*/]);
> ```

@bparrishMines 

So I am closer with the syntax for this test but I'm coming up short with how exactly to assert on the value of the JavaScript? Below is what I have so far. I have played around with giving the `evaluateJavaScript` a completion handler but still can't seem to get any value to assert on... I think because of the asynchronous nature

I am getting this error ...
`*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0] (NSInvalidArgumentException)` 
for this line...
 `[self.navigationDelegate webView:webview didFinishNavigation: self.navigation];`
but I'm not sure what is nil?

This is my test inside `FLTWKNavigationDelegateTests.m`

```
@interface FLTWKNavigationDelegateTests : XCTestCase

@property(strong, nonatomic) FlutterMethodChannel *mockMethodChannel;
@property(strong, nonatomic) FLTWKNavigationDelegate *navigationDelegate;
@property(strong, nonatomic) WKNavigation *navigation;

@end

@implementation FLTWKNavigationDelegateTests

- (void)setUp {
  self.mockMethodChannel = OCMClassMock(FlutterMethodChannel.class);
  self.navigation = OCMClassMock(WKNavigation.class);

  self.navigationDelegate =
      [[FLTWKNavigationDelegate alloc] initWithChannel:self.mockMethodChannel];
}
...

- (void)testWebViewWebEvaluateJavaScriptSourceIsCorrectWhenShouldEnableZoomIsFalse {
    WKWebView *webview = OCMClassMock(WKWebView.class);
    self.navigationDelegate.shouldEnableZoom = false;
    [self.navigationDelegate webView:webview didFinishNavigation: self.navigation];

    
    NSString *source =
        @"var meta = document.createElement('meta');"
        @"meta.name = 'viewport';"
        @"meta.content = 'width=device-width, initial-scale=1.0, maximum-scale=1.0,"
        @"user-scalable=no';"
        @"var head = document.getElementsByTagName('head')[0];head.appendChild(meta);";
    
    OCMVerify([webview evaluateJavaScript:source completionHandler:nil]);
}
```

Again thank you and hopefully I'm not too far off here

**Comment by NickalasB** [comment]
> @NickalasB That solution looks fine. You could also pass the test `NavigationDelegate` a mock `WkWebView` and use verify to check that `evaluateJavaScript` was called when `didFinishNavigation` was called.
> 
> ```objc
> OCMClassMock(WKWebView.class);
> OCMVerify([_mockWebView evaluateJavaScript:/*check parameters*/]);
> ```

@bparrishMines @stuartmorgan  Finally figured out a way to write the iOS tests. Apologize for the churn. My lack of experience with OC didn't help.

iOS tests added in 74addca

**Pull request merged**
