### PR TITLE
firebase_messaging: changing getToken to rely on platform's getToken

### PR DESCRIPTION
**Pull request by ffeu**
intends to fix flutter/flutter#17699 and fix flutter/flutter#20378

Removing local cache of getToken() in the dart part of the plugin. Now getToken() calls directly its counterparts in the iOS and Android implementations. This enables obtaining its value without calling configure() or having to wait for a new token refresh.

### CODE REVIEW

**Comment by ffeu** [comment]
@kroikie  BTW, there's this one too. it closes two issues! 😀

**Comment by calebisstupid** [comment]
This PR fixes the hanging getToken() call for me in simulator as well.

**Comment by ffeu** [comment]
gentle ping
@bparrishMines @kroikie

**Comment by beardo01** [comment]
Can also confirm that this has fixed the getToken() hanging issue for me. Another respectful ping to @kroikie to accept this.

**Comment by ffeu** [comment]
yeah, i messed up this branch/PR.  :(

sorry about that, I'll have to recreate it in another PR.

**Comment by beardo01** [comment]
@ffeu Please do and make sure you reference it from this Pull Request so I can come and show my support. Cheers!

**Comment by beardo01** [comment]
@ffeu Please do and make sure you reference it from this Pull Request so I can come and show my support. Cheers!

**Comment by beardo01** [comment]
@ffeu Please do and make sure you reference it from this Pull Request so I can come and show my support. Cheers!

**Comment by beardo01** [comment]
@ffeu Please do and make sure you reference it from this Pull Request so I can come and show my support. Cheers!

**Comment by beardo01** [comment]
@ffeu Please do and make sure you reference it from this Pull Request so I can come and show my support. Cheers!

**Comment by Hixie** [comment]
@ffeu Are you planning on submitting a new PR as per your comment above?

**Comment by ffeu** [comment]
@Hixie yes, give me just a few minutes

**Comment by ffeu** [comment]
replaced by #869

**Pull request closed without merging**
