### PR TITLE
[camera_platform_interface] Add support for NV21 image format

### PR DESCRIPTION
**Pull request by acoutts**
This is a companion to https://github.com/flutter/plugins/pull/3651 and adds the option for NV21 image format, used in Android.

## Pre-launch Checklist

- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test exempt.
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning

### CODE REVIEW

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]
Thanks for splitting up the PR. 
 
I think you accidentally included the `camera.java` into this PR which doesn't really belong to the `camera_platform_interface`. Could you remove this file from this PR which otherwise looks good?

**Comment by acoutts** [comment]
Aha - fixed!

**Comment by mvanbeusekom** [comment]
> Aha - fixed!

Thanks, it still shows up though with some indentation changes. Could you also roll these back?

**Comment by acoutts** [comment]
There we go. Annoyingly, that was just from running the formatter from the contributing guide. Once we merge my PR (which used that formatter) it should be cleaner for future PRs submitted from others, as long as they run the same formatting commands.

**Review by mvanbeusekom — APPROVED** [review]
LGTM! Thanks for this, I will merge the PR once the tree goes green and will request it to be published.

**Comment by acoutts** [comment]
Ah wait! found one thing I missed in the image format definition.

**Comment by acoutts** [comment]
Ok that's fixed now. All set.

**Review by mvanbeusekom — APPROVED** [review]

**Comment by acoutts** [comment]
Argh, so i've found that NV21 is actually not a valid format in android. I think we can scratch this PR. Sorry about that.

**Pull request closed without merging**
