### PR TITLE
[url_launcher_linux] Add Linux url_launcher plugin

### PR DESCRIPTION
**Pull request by robert-ancell**
## Description

Add Linux url_launcher plugin.

## Related Issues

https://github.com/flutter/flutter/issues/41721

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by robert-ancell** [comment]
> This should have an example and test, as with all the other plugins in flutter/plugins.

*cough* url_launcher_macos *cough* :eyes:

**Comment by stuartmorgan** [comment]
> > This should have an example and test, as with all the other plugins in flutter/plugins.
> 
> _cough_ url_launcher_macos _cough_ 👀

https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_macos/example/test_driver/

**Comment by stuartmorgan** [comment]
Added tests that should be driven by CI. That found:
- The example didn't compile, because the CMake project name didn't match the plugin name (url_launcher vs url_launcher_linux)
- The return value for `canLaunch` for a bogus URL didn't match the existing mobile test expectations (an error rather than false), so I changed that for consistent behavior with existing code.

**Comment by stuartmorgan** [comment]
Still one test failure, which CI isn't picking up (filed https://github.com/flutter/flutter/issues/60943).

**Comment by stuartmorgan** [comment]
Published; PR to endorse it will follow.

**Pull request merged**
