### PR TITLE
[video-player] fix iOS player to update frames while pause

### PR DESCRIPTION
**Pull request by tafelito**
## Description

If you scrub video on iOS while paused the player does not update the frames. This PR fixes that issue

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by tafelito** [comment]
@googlebot I signed it!

**Comment by cbenhagen** [comment]
Thank you for your contribution! https://github.com/flutter/plugins/pull/2397 would actually be a better fix for this as it will only update the texture when you really seek. The only missing parts to merge the mentioned PR is the test. So if you have time it would be awesome if you could contribute one.

**Comment by dthuering** [comment]
Will this PR or #2397 merge in the near future? Waiting for this to work on iOS.

**Comment by stuartmorgan** [comment]
Thanks for the contribution! I'm closing this in favor of https://github.com/flutter/plugins/pull/2758 per the discussion above just so we have a single PR to track; if you have issues with the approach there, please leave comments there for discussion.

**Pull request closed without merging**
