### PR TITLE
Live preview

### PR DESCRIPTION
**Pull request by dustin-graham**
Fixes #19274. https://github.com/flutter/flutter/issues/19274

Currently this PR has working code but is still pretty raw. I think the shape of the solution is getting close, but there is a lot of uncleaned code and some outstanding defects. 

Android: barcode detector boundaries are wrong
iOS: MLKit detector doesn't work when preview image is not landscape
Android: Live text detection block boundaries are wrong.
iOS: utilizing some iOS 10 APIs, need to find iOS 8 work-arounds

The barcode implementation is left very basic as I'm told that someone else is working on a more full-featured implementation at this time.

@bparrishMines This is a starting point. I'd appreciate any feedback and guidance you can provide.

The implementation was pulled from several sources:
Android Live Preview ML Kit reference: https://github.com/firebase/quickstart-android/tree/master/mlkit
iOS Live Preview ML Kit reference: https://github.com/firebase/quickstart-ios
Android & iOS flutter camera implementation: Flutter camera plugin

Note that there are two implementations on Android with camera2 and the legacy camera API. I need some guidance on which to use for this effort.

Remaining Tasks:
- [ ] Android runtime permission handling (camera)
- [ ] iOS rotation + detector problem. (detector does not work properly unless video preview is in landscape)
- [ ] Unify Android camera implementation(s).
- [ ] Remove capture functionality from iOS camera implementation

### CODE REVIEW

**Comment by dustin-graham** [comment]
working on merging with upstream changes now.

**Comment by dustin-graham** [comment]
@bparrishMines I'm struggling with code formatting. I'm reading that `flutter_plugin_tools` requires clang-format v5. The only version I can get from homebrew is 7 and it formats my code differently than the CI is expecting. I exported the google .clang-format file that is used when the formatter type is set to google and it disagrees with how this CI system formats ObjectiveC code. I have to assume that it's because I'm running v7 and not v5. I don't know how to get v5, can you please advise?

**Comment by goderbauer** [comment]
@dustin-graham Does this comment help you with regards to formatting? https://github.com/flutter/flutter/issues/12864#issuecomment-408605171

**Comment by bhammer88** [comment]
How is this project going along? I'm kinda interested to learn this, and hope it can help me in making a document scanner in flutter

**Comment by bbofrk** [comment]
Hi @dustin-graham thanks for your work. I am one of the many few that is very excited about this, just wondering if there is any update?

**Comment by gimox** [comment]
any news?

**Comment by bparrishMines** [comment]
Hi @dustin-graham, 

I'm going to go ahead and close this PR since we are going a different direction with a Live camera view with ML Kit.

**Pull request closed without merging**
