### PR TITLE
[google_maps_flutter] Update - Android - Getting started instructions

### PR DESCRIPTION
**Pull request by DipanshKhandelwal**
## Description
*Update - Android - Getting started instructions motivated the change.*

## Checklist
Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [ ] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by iskakaushik** [comment]
What error do you get if you don't include this? It might be useful to document the error with this fix. 

Thanks for the contribution!

**Comment by iskakaushik** [comment]
@DipanshKhandelwal do you plan on continuing this?

**Comment by DipanshKhandelwal** [comment]
I'm sorry, I missed the last notification. I need to re-run the app to get the exact error.
Will update here soon.

**Comment by collinjackson** [comment]
Quick ping on this, it would be great to get this change landed.

**Comment by iskakaushik** [comment]
@DipanshKhandelwal , closing this due to inactivity. Please re-open/create a new PR once you have any new changes.

Thanks!

**Pull request closed without merging**
