### PR TITLE
[camera] Add the ability to disable audio for video recording and image streaming

### PR DESCRIPTION
**Pull request by viniciuslrangel**
Option to disable audio
Avoids requesting unnecessary permissions, especially when using the camera only for photos
_Android implementation only_

### CODE REVIEW

**Comment by collinjackson** [comment]
possibly redundant with #904

**Comment by matin** [comment]
What's the status of this PR?

**Comment by viniciuslrangel** [comment]
> What's the status of this PR?

I didn't test on iOS, but I'm using on Android for a while and works great.

**Comment by bparrishMines** [comment]
Hi @viniciuslrangel,

Thanks for the contribution! I'm going to take over the PR and try and get the iOS side working.

**Pull request merged**
