### PR TITLE
enable lint unnecessary_const

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by a14n** [comment]
Updated

I don't understand why some CI tasks fail.

**Comment by a14n** [comment]
@tvolkert no problem with Fuchsia to merge this PR? (Re. https://github.com/flutter/flutter/pull/19592#issuecomment-408313227)

**Comment by tvolkert** [comment]
Let's hold off on merging just yet -- I'm still wrestling with rolling Flutter into Fuchsia.  Thanks!

**Comment by tvolkert** [comment]
Ok, this is good to go with respect to Fuchsia!  thanks 😄

**Pull request merged**
