### PR TITLE
 [google_maps_flutter] Support enable/disable MapToolbar.

### PR DESCRIPTION
**Pull request by kenzieschmoll**
Add support for enabling/disabling the Map Toolbar. Maps api documentation here: https://developers.google.com/android/reference/com/google/android/gms/maps/UiSettings.html#setMapToolbarEnabled(boolean)

### CODE REVIEW

**Comment by amirh** [comment]
This is great, thanks! We would like to wait until we have maps implemented on both iOS and Android before actually further augmenting the API, because we are worried that they'll get out of sync otherwise. Would you be ok with resubmitting this with iOS support in a few weeks once we have the iOS work more fleshed out?

**Comment by kenzieschmoll** [comment]
Yes, will do!

**Comment by kenzieschmoll** [comment]
Actually @amirh, it looks like enableMapsToolbar isn't even an option in the [iOS SDK](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_u_i_settings), whereas it is supported for [Android](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMapOptions). 

So maybe this PR can be submitted without the iOS implementation?

**Comment by KlausJokinen** [comment]
What is the status of this issue?

**Comment by amirh** [comment]
Can you please rebase and add a dart unit test?
I'm not sure whether the `mapToolBarEnabled`  status can be modified without the app asking to do so (e.g can the user tap on something to have the Maps SDK code internally disable the toolbar after the app set it to enabled?) if it the only trigger for changing this state is the app, this should probably be a widget parameter after the rebase.

**Comment by iskakaushik** [comment]
@kenzieschmoll do you still plan on working on this PR?

**Comment by dazza5000** [comment]
maybe you ate some bad gum and didn't make it? do you need any help with this?

**Comment by kenzieschmoll** [comment]
@iskakaushik My apologies for the silence on this PR. I don't currently have the bandwidth to continue working on this. Feel free to patch or close or do with it what you will 👍 Thanks.

**Comment by dazza5000** [comment]
thank you for the initial work and response - I can grab it if no one gets to it - thank you!

**Comment by iskakaushik** [comment]
@kenzieschmoll no worries. @dazza5000 , feel free to create a new PR with this feature. Thanks!

**Comment by dazza5000** [comment]
New PR here: https://github.com/flutter/plugins/pull/1810

**Pull request closed without merging**
