### PR TITLE
[camera] Update README

### PR DESCRIPTION
**Pull request by stuartmorgan**
- Removes some obsolete references to the current state
- Adds an OS support chart
- Minor cleanup

Fixes https://github.com/flutter/flutter/issues/83722
Part of https://github.com/flutter/flutter/issues/84200 and https://github.com/flutter/flutter/issues/34999

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [relevant style guides] and ran [the auto-formatter]. (Unlike the flutter/flutter repo, the flutter/plugins repo does use `dart format`.)
- [x] I signed the [CLA].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. `[shared_preferences]`
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is [exempt from version changes].
- [x] I updated `CHANGELOG.md` to add a description of the change, [following repository CHANGELOG style].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[relevant style guides]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[exempt from version changes]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#version-and-changelog-updates
[following repository CHANGELOG style]: https://github.com/flutter/flutter/wiki/Contributing-to-Plugins-and-Packages#changelog-style
[the auto-formatter]: https://github.com/flutter/plugins/blob/master/script/tool/README.md#format-code
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests

### CODE REVIEW

**Comment by stuartmorgan** [comment]
@blasten @ditman @jmagman What do you think of the OS support chart here? This is a proposal for what to roll out across all of our plugins as part of https://github.com/flutter/flutter/issues/34999 and https://github.com/flutter/flutter/issues/84200 so if we want a different format we should decide now if possible.

(An alternative I considered was to make it a vertical table so there's more room for inline notes, but having the table compact and linking out for notes seemed like the better option.)

**Comment by stuartmorgan** [comment]
@blasten @ditman Thoughts on this table format for Android and Web dependencies?

**Review by ditman — APPROVED** [review]
I like this, thanks for doing it!

In general all the _web plugins (should) have a README with what's supported/not supported by the web with regards to the plugin (or by each browser in particular), so linking to those docs is a good idea.

(I wish we could open the link in a new tab, but users can always center-click to not lose track of what they were reading so far.)

**Comment by stuartmorgan** [comment]
> Also: are we going to have all supported platforms as columns? That might be a lot of columns? :)

That's why I'm trying to keep them very short. I considered it as rows, but having potentially 6 rows seemed much more disruptive to the flow of the README.

**Pull request merged**
