### PR TITLE
[camera] flip/change camera while recording (split out PR for cam_avfoundation and cam_android)

### PR DESCRIPTION
**Pull request by BradenBagby**
This is another split out PR for https://github.com/flutter/plugins/pull/6478. This PR only contains changes under Camera_AVFoundation and Camera_Android, while also pointing them to the merged platform interface changes version 2.4.0

### CODE REVIEW

**Review by bparrishMines — APPROVED** [review]
LGTM

**Comment by bparrishMines** [comment]
Secondary review request for @camsim99 @stuartmorgan or @hellohuanlin  
I verified this is the same approved code from https://github.com/flutter/plugins/pull/6478

**Review by camsim99 — APPROVED** [review]

**Comment by BradenBagby** [comment]
Did not mean to remove you @hellohuanlin and don't seem to be able to add you back

**Review by hellohuanlin — APPROVED** [review]
LGTM on iOS part - looks like it's the same code from https://github.com/flutter/plugins/pull/6478 which I have reviewed.

**Comment by BradenBagby** [comment]
After looking at the logs Im still not sure whats failing here. I guess the build timed out but not sure why. Any ideas or suggestions @bparrishMines @stuartmorgan. Or can we just re-trigger these tests to run?

**Comment by stuartmorgan** [comment]
> After looking at the logs Im still not sure whats failing here. I guess the build timed out but not sure why. Any ideas or suggestions @bparrishMines @stuartmorgan. Or can we just re-trigger these tests to run?

There aren't any failing tests here; it will be landed automatically when the tree is green.

**Comment by BradenBagby** [comment]
Looks like an android test on Testlab is failing for starqlteue_26. Probably due to this here https://github.com/flutter/plugins/pull/6478#discussion_r1009747007

**Comment by BradenBagby** [comment]
> Looks like an android test on Testlab is failing for starqlteue_26. Probably due to this here [#6478 (comment)](https://github.com/flutter/plugins/pull/6478#discussion_r1009747007)

@stuartmorgan What solution do you think we should use: disable switching camera for devices below API 26, Or disable the plugin for older versions?

**Comment by BradenBagby** [comment]
> > Looks like an android test on Testlab is failing for starqlteue_26. Probably due to this here [#6478 (comment)](https://github.com/flutter/plugins/pull/6478#discussion_r1009747007)
> 
> @stuartmorgan What solution do you think we should use: disable switching camera for devices below API 26, Or disable the plugin for older versions?

@bparrishMines

**Comment by stuartmorgan** [comment]
> Looks like an android test on Testlab is failing for starqlteue_26. Probably due to this here [#6478 (comment)](https://github.com/flutter/plugins/pull/6478#discussion_r1009747007)

Looks that way:

```
     FATAL EXCEPTION: Thread-7
Process: io.flutter.plugins.cameraexample, PID: 8633
java.lang.RuntimeException: eglSwapBuffers()EGL_BAD_SURFACE
	at io.flutter.plugins.camera.VideoRenderer.draw(VideoRenderer.java:362)
	at io.flutter.plugins.camera.VideoRenderer$2.run(VideoRenderer.java:295)
```

I'm confused how this passed the `stable` postsubmit test run given that. I'll make a revert PR.

**Comment by stuartmorgan** [comment]
> > Looks like an android test on Testlab is failing for starqlteue_26. Probably due to this here [#6478 (comment)](https://github.com/flutter/plugins/pull/6478#discussion_r1009747007)
> 
> @stuartmorgan What solution do you think we should use: disable switching camera for devices below API 26, Or disable the plugin for older versions?

We should only disable the new feature, not the entire plugin.

**Comment by BradenBagby** [comment]
> > > Looks like an android test on Testlab is failing for starqlteue_26. Probably due to this here [#6478 (comment)](https://github.com/flutter/plugins/pull/6478#discussion_r1009747007)
> > 
> > 
> > @stuartmorgan What solution do you think we should use: disable switching camera for devices below API 26, Or disable the plugin for older versions?
> 
> We should only disable the new feature, not the entire plugin.

Sorry about that. I don't have access to my Android device right now so will do this tomorrow. 

But to be sure. Im thinking the new feature for devices < 26 should throw some sort of unsupported error when user tries to flip camera mid recording and not mess with the recording state (camera keeps recording unflipped). Is that what you're thinking?

**Comment by stuartmorgan** [comment]
That sounds reasonable to me.

So the next step here would be to make a new PR that starts with a revert of the revert (with no changes) as the first commit, then makes changes in follow-up commits, to make it easy to review just the changes. We'll make sure to have a team member push a commit to the PR once it's reviewed so that we can get full presubmit tests.

**Pull request merged**
