### PR TITLE
[firebase_auth]Fixing exception on Android when linking phone number to email/password account

### PR DESCRIPTION
**Pull request by kika**
Fix for https://github.com/flutter/flutter/issues/26477

For completeness this one is also needed: https://github.com/flutter/plugins/pull/980/commits/b26b2722283f072797a13586df91c7d74758d820

### CODE REVIEW

**Comment by cqhchan** [comment]
Hey, I saw this and you need to include the case on android where phone auth takes place without sending an sms. I had had a fix earlier in https://github.com/flutter/plugins/pull/973 to solve that issue as well

**Comment by kika** [comment]
@cqhchan I'd love to, but for that, I believe I need a real Android device with SIM card and active service and I don't have any physical Android device around. Only emulator.

**Comment by davydany** [comment]
Flutter team, please review and merge this code. This is blocking so many folks!

**Comment by dev-mush** [comment]
this is blocking my team as well, why it's not being addressed?

**Comment by davydany** [comment]
If anyone is blocked by this, please use the following in your `pubspec.yaml`, and comment out whatever you have for `firebase_auth`.

```
...

  firebase_auth:
    git:
      url: https://github.com/aeroxis/plugins.git
      path: packages/firebase_auth
      ref: firebase-auth-phone-bug-fix
...
```

This is the work that @kika already did but with the latest version as of `03/18/2019`.

The pull request shows the changes I made: https://github.com/flutter/plugins/pull/1358

**Comment by collinjackson** [comment]
It looks like this was fixed in flutter/plugins#1333, but if I'm mistaken please let me know.

**Pull request closed without merging**
