### PR TITLE
[google_maps_flutter] ios build fix

### PR DESCRIPTION
**Pull request by OreOreDa**
## Description

Create a new Flutter project with "flutter create"
Add the latest google maps flutter plugin in pubspec.yaml
build for iOS fails with latest version of XCode / Flutter SDK with error "GoogleMapsBase not found", because of GoogleMaps.framework headers:
#if __has_feature(modules)
@import GoogleMapsBase; <--- this is taken by default with a non-modified Flutter project
#else
#import <GoogleMapsBase/GoogleMapsBase.h>
#endif

This is a known issue, it has been solved for React Native : https://github.com/googlemaps/google-maps-ios-utils/pull/20/files

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [X] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [X] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/plugins/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by OreOreDa** [comment]
Some checks failed due to github timeouts (?), I re created this PR to have the checks run again, and have the green mark

**Comment by iskakaushik** [comment]
@OreOreDa could you please edit the pubspec.yaml change version to `0.5.18` and also add a new changelog entry, not edit the current one?

**Comment by OreOreDa** [comment]
Sure, Iska 👍 Done

**Comment by iskakaushik** [comment]
LGTM. This fixes https://github.com/flutter/flutter/issues/34042

**Pull request merged**
