### PR TITLE
Adding ability to detect biometric availability and face id for iOS

### PR DESCRIPTION
**Pull request by jpeiffer**
Apple's guidelines (available here: https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/authentication/) state:

"Reference authentication methods accurately. Don't reference Touch ID on a device that supports Face ID. Conversely, don't reference Face ID on a device that supports Touch ID. Check the device's capabilities and use the appropriate terminology"

This plugin currently does not support knowing which is available.  My PR is intended to address that so that UI developers can follow Apple's guidelines for biometric auth to avoid potential Apple rejections.

### CODE REVIEW

**Comment by jpeiffer** [comment]
I signed it!

**Comment by diegoveloper** [comment]
Thanks for the contribution, I was looking for this update :)

**Comment by sjmcdowall** [comment]
So it's now Sept -- what's the status of this PR or the capability? I am looking for this as well

**Comment by jpeiffer** [comment]
Fixed merge conflicts.

**Comment by jpeiffer** [comment]
Fixed next set of merge conflicts... hoping this can be merged before I have to do a round 3, please.  :)

If there's something that I need to do to get this merged, please comment so I can get any concerns resolved.

**Comment by jeroentrappers** [comment]
The "Google open source way" of working seems to be developing a big next release behind closed doors, and then dropping it on github once it is "done". This is very annoying to get important bugfixes and features in the plugins. The fact that all these plugins are stored in the same repository only makes things 10 times worse. Google should really look into this process, as it is clearly not sustainable.

**Comment by YAPPDEF** [comment]
Also interested in this feature! Thanks @jpeiffer

**Comment by jpeiffer** [comment]
Closing PR.  Looks like the concept involved with this PR was merged to master and that is the cause of the most recent conflicts.

**Comment by sjmcdowall** [comment]
@jpeiffer -- can you explain your statement a bit more -- what has been merged into Master? Where? Where is there any information about the outcome of what is now available ??

**Pull request closed without merging**
