### PR TITLE
[image_picker] remove unnecessary file path for video.

### PR DESCRIPTION
**Pull request by cyanglaz**
Simplified version of https://github.com/flutter/plugins/pull/1245 fix. 
When pick videos, we used to create an unnecessary extra file. This PR removes the extra temp file logic.

### CODE REVIEW

**Comment by pepegich** [comment]
seems related https://github.com/flutter/plugins/pull/1288

**Comment by cyanglaz** [comment]
> seems related #1288

Actually this PR is for iOS and https://github.com/flutter/plugins/pull/1288 is for Android. So although both are trying to solve similar problems but they are separate fixes.

**Comment by amirh** [comment]
The tmp path logic was added in https://github.com/flutter/image_picker/commit/5409baccb75680547b1a799f6853da423e5fd9cb

@collinjackson do you know whether we still need it?

**Comment by cyanglaz** [comment]
The original videoURL is already a tmpPath. I thought adding another tmpPath did not make sense. I guess it could be a copy paste error (copy pasted from the picking image logic) when we introduced the video capability in the plugin.

**Comment by collinjackson** [comment]
lgtm

**Pull request merged**
